### ISSUE TITLE
[Bug] Context menu in Linux doesn't select e.target before showing menu

### ISSUE THREAD

**Issue by Informatic** [jaedb/Iris#101]
When any list item is selected, using context menu options on any other item will issue action on selected item, rather than the one on which context menu has been opened, which is slightly misleading.

**Comment by jaedb** [comment]
Can you please provide some working examples? Or better still a screen recording?

**Comment by Informatic** [comment]
Yep, here's what I'm talking about:
https://hackerspace.pl/~informatic/dropbox/e8a24307671c4c9cfbe9116e912661a4.webm

**Comment by jaedb** [comment]
Awesome, thanks for that. What version of Iris are you running? Also, what browser and OS are you using? It looks like you're running Chrome on Linux?

I had changed the selection toggle binding to `mouse_down` instead of `click` which fixed this same behavior some time ago.

**Comment by Informatic** [comment]
Sorry, forgot about that:
Ubuntu 16.04, AwesomeWM 4, Chrome 56.

**Comment by jaedb** [comment]
Seems to be an issue isolated to Chrome on Linux. Can you please try another OS or browser to confirm?

**Comment by Informatic** [comment]
Tested it on Firefox 52.0.2 right now... The behaviour is... Strange.

https://hackerspace.pl/~informatic/dropbox/a8714ee5cd9f6e5c05b7b01a7ba48f87.webm

First (and last) click in the screencast was actually right mouse click. Seems like sometimes right mouse button is triggered together with left one (this sometimes causes both selection and display of context menu), sometimes right mouse button is registered as left mouse button only... And when it is only registered (properly) as right mouse button, I still get context without actual context (well, options in context menu operate on currently selected list item, not the one from which context menu is opened - this looks like a bad internal design, or just a bug...)

Sadly I haven't really touched React/modern javascript myself much, so I have no idea how to help you with this one.

**Comment by Alladinsane** [comment]
I'm having this issue on a Raspberry Pi running Jessie, accessing the interface through Firefox. For me, it would be better if right-clicking a track caused selection and display of context menu. As is, I spent a lot of time thinking my queue was broken, because I would right-click a track, the context menu would open, I would choose "Add To Queue", and nothing would happen. Obviously, this is because the context menu had no context.

**Comment by Alladinsane** [comment]
I looked into this a little. It looks to me like a right-click is treated as a context menu event, not a mouse down event. So, the fix could be as simple as adding "var target = $(e.target)" to the handleContextMenu event in the Track component.

**Comment by Alladinsane** [comment]
I forked the repo, pulled the source down and tinkered with it, and got this working the way I wanted. It wound up being as a simple as removing the check for right-click from handleMouseDown in the TrackList component. That way, all click types select the track on mouse down, before the context menu is triggered.

**Comment by jaedb** [comment]
Try it on a touch device ;-)

**Comment by Alladinsane** [comment]
Ah, yes. I see.
