### ISSUE TITLE
Can't access Iris from anywhere other than 'localhost'

### ISSUE THREAD

**Issue by ll931217** [jaedb/Iris#104]
I have Iris and Mopidy installed on my Raspberry Pi 3 Model B, running Jessie. I can access the interface from within Raspberry Pi but I can't do so from another computer in the LAN. I searched both open and closed issues but can't seem to find a way to get this to work. Am I missing something?

**Comment by jaedb** [comment]
1. Read [before you log an issue](https://github.com/jaedb/Iris/wiki/Support#before-you-log-an-issue)
2. Read [Mopidy-HTTP](https://docs.mopidy.com/en/latest/ext/http/) where it states:
> As a simple security measure, the web server is by default only available from localhost. To make it available from other computers, change the http/hostname config value. Before you do so, note that the HTTP extension does not feature any form of user authentication or authorization. Anyone able to access the web server can use the full core API of Mopidy. Thus, you probably only want to make the web server available from your local network or place it behind a web proxy which takes care or user authentication. You have been warned.
