### ISSUE TITLE
Volume control status does not work on Alsamixer mixer

### ISSUE THREAD

**Issue by Informatic** [jaedb/Iris#108]
Volume bar value does not change when changing volume. Switching back to default "software" mixer makes it work again.

**Comment by Informatic** [comment]
Looks like it might be caused by events missing from Alsamixer module. Haven't dug into that yet.

**Comment by jaedb** [comment]
Does it work as expected using another Mopidy client? I find [ncmpcpp](https://rybczak.net/ncmpcpp/) great for debugging Iris issues vs server issues.

**Comment by jaedb** [comment]
@Informatic have you managed to explore this further?

**Comment by MarcinWieczorek** [comment]
Alsamixer isn't supposed to change volume in this case. I mean it is, but it's a separate volume range. As mopidy implements MPD you can change the volume with mpc or ncmpcpp or any other client, but if you have a global volume bar in the DE you can control it with alsamixer or similar software.

**Comment by jaedb** [comment]
Iris doesn't have system-level control of volumes; it can only access the volume control of the Mopidy API. As such, this sounds like an issue with Mopidy/MPD/Alsamixer rather than Iris.

Please feel free to re-open this issue if you feel otherwise.

**Comment by mczerski** [comment]
i had the same issue, when clicked on the volume bar, the bar didn't change but the actual volume changed. I could replicate this behaviour with alsamixer, in one terminal I opened alsamixer and in other terminal changed volume from commandline, and the volume bar in alsamixer didn't change. So I assume this is the problem with the alsa driver for particular sound card (I have this problem only on nanopi M1 board, on rpi and nano pi neo with pcm5102 hat all works as expected).
