### ISSUE TITLE
[Feature request] Discover using recommendations engine

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#110]
Using the Spotify `/recommendations` endpoint we could look to create an interactive view that allows you to add genres, artists and tracks as seeds to find similar music. This is the same endpoint that _Radio_ uses.

The frontend would be more of a filtering engine and could replace the current 'Edit radio' modal.

As we only get `tracks` objects returned on this endpoint we would need extract the the relevant artists and albums for a more user-friendly experience.

**Comment by Hugomm** [comment]
Right now the Discover tab is supposed to show something?

**Comment by jaedb** [comment]
Yes, currently we get a number of the user's favorite artists, and the build recommendations for each. You need to be authenticated to access this page.

**Comment by Hugomm** [comment]
I'm authenticated, on Settings, on top page says conected to Mopidy, Pusher and Spotify but I'm not getting anything on the discover tab, just a blank page.
How to provide logs or something?

![image](https://cloud.githubusercontent.com/assets/14215939/25971936/4e568b08-369e-11e7-847a-0c7714ba7904.png)

**Comment by jaedb** [comment]
Nah, it should look like:

![image](https://cloud.githubusercontent.com/assets/1711444/25973073/ae4a6eaa-36f6-11e7-8db6-2cd9aa917a49.png)

But I'm not worried about it as this will be replaced by something much more user-friendly and engaging. It should be released in the next 1-2 weeks as the major release.

**Comment by Hugomm** [comment]
I see, so will report when you release it
