### ISSUE TITLE
Track selection and context menu on touch devices

### ISSUE THREAD

**Issue by torj** [jaedb/Iris#111]
Thanks for a great app!

There is an issue with context menus on ios devices. It seems like that the onContextMenu event is unsupported on ios. This make it impossible to enter edit mode in playlists. It works perfectly on android devices but not on my iphone 7.
http://stackoverflow.com/questions/29228999/jquery-contextmenu-event-not-working-in-ios-8-2

**Comment by jaedb** [comment]
Thanks for posting this issue - I've managed to replicate the issue. I think it prompts re-addressing the use of context menu, and perhaps we use something a little more native (eg checkbox always shown on touch devices and we can ditch the `edit_mode` function).

**Comment by jaedb** [comment]
I've revisited how this works, and how it could work better. I've concluded the current approach is quite flawed and introduces stacks of browser- and device-specific issues.

To this end, I'm looking to use a similar approach as many native mobile apps. Tracks have checkboxes and will only respond to taps/clicks in this zone. 

You can have a look at how it's working on the `feature/touch` branch. Are you able to test this on your device to make sure it fixes the issue you've highlighted?

**Comment by jaedb** [comment]
@torj The latest release has incorporated these changes. Can you please re-test and verify this is no longer an issue on your device? If so, please close this issue.

**Comment by torj** [comment]
Works perfectly! Love the new volume setting for mobile devices as well.
