### ISSUE TITLE
[Feature Request] Play next queuing

### ISSUE THREAD

**Issue by aschwab** [jaedb/Iris#113]
Hello,

we're using Iris at our workplace and we proved it as the best Webclient for Mopidy, so thanks for that (Y).

We would like to queue the play-next songs in the order they were added, as often the "Queue" is about 100+ tracks long. Adding the songs to the queue would take too long. If everyone would say 'Play next' the order would be malformed.

Probably a "Add to play next" button or something like this.

**Comment by aschwab** [comment]
Additionally it would be nice if the "play next" functionality would also work when having shuffle enabled.

**Comment by jaedb** [comment]
Glad to hear you're finding a good use for _Iris_!

The logic behind adding tracks to the queue is quite complex. The _Adding x tracks to queue_ process was introduced as adding a large number of tracks locked the Mopidy server (and on lower-powered devices, crashed). As you can imagine, this made for a rather horrid user experience.

The obvious downside to this is that if another user adds tracks to the queue while your list is still processing, they'll 'jump the queue'. Unfortunately I don't see any way around this, and it's certainly the lesser of the two evils.

**Comment by aschwab** [comment]
Thanks for you reply. I guess we stuck here. ;)
