### ISSUE TITLE
[Feature request] Add global broadcasting

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#114]
Add ability to notify all users of features or updates. This would involve the creation of an endpoint that Iris would lookup during low load.

**Comment by Hugomm** [comment]
That feature would be really cool.

Can you send that updates to mobile browsers?

**Comment by jaedb** [comment]
These will be system broadcasts than client broadcasts.

To broadcast client-to-client, have a play under _Settings_ > _Debug_ > _Pusher_.
