### ISSUE TITLE
[Feature Request] Cover Art as video output

### ISSUE THREAD

**Issue by Hugomm** [jaedb/Iris#115]
Is there anyway to implement a video signal output with the cover art of the song currently playing and maybe the hour or some info?

Is there any extension that does that?

**Comment by jaedb** [comment]
Try _Fullscreen mode_ feature, hit `ctrl + /`. See [Keyboard shortcuts](https://github.com/jaedb/Iris/wiki/Features#keyboard-shortcuts).

**Comment by Hugomm** [comment]
But I mean to get an output from raspberry to a Screen showing the song currently playing, album, artist...

**Comment by jaedb** [comment]
Yep, this is what _Fullscreen mode_ would do. You would need to have Linux installed with a desktop manager (Google PIXEL or LightDM for more info). Then just open a browser with Iris on _Fullscreen mode_. This is what we do in our office and it works great.

**Comment by Hugomm** [comment]
So I have to connect with the desktop manager to the raspberry and open a browser with Iris on fullscreen mode? I tried to activate fullscreen mode on the computer but It didn't do anything.

**Comment by jaedb** [comment]
Hitting `ctrl + /` will activate _Fullscreen mode_. This is what it looks like (obviously depending on your currently playing track):
![fullscreen-mode](https://cloud.githubusercontent.com/assets/1711444/26604446/885a3e36-45de-11e7-8cf5-bf4555fea464.jpg)
