### ISSUE TITLE
[Feature request] Sortable tracks on mobile

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#116]
Further investigation required to explore if this is possible, but currently one cannot change the order of tracks on touch or mobile devices. Perhaps enter a `sort_mode` or similar, only saving on completion rather than after every drag. 

The challenge will be handling touch drag events. I know this can be tricky, especially when working within a browser as opposed to a native app.

**Comment by MarcinWieczorek** [comment]
I'd add two options to that three-squares-circle menu such as "Move up/down the queue". Drag and drop will never work on **every** device.

**Comment by MarcinWieczorek** [comment]
I suggest tracks to be draggable only with left click on the desktop.

**Comment by jaedb** [comment]
Part of me wants to say "challenge accepted!" however I think you're right. I'm thinking of creating a `Modal` that will have faux-drag functionality by using scrolling:
1. Select tracks to move
2. Hit context menu trigger
3. Hit _Reorder tracks_
4. Show modal to handle sorting
5. Save

**Comment by jaedb** [comment]
Up and running at c46af013464a9e5dfa64cbf837509249e7b33278 but some devices lag in rendering the updated queue order. Tapping or scrolling anywhere seems to bring in the change.

**Comment by jaedb** [comment]
Released in `3.1.0`
