### ISSUE TITLE
[Feature request] Support for Mopidy-Dirble

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#12]
_From @mczerski on September 25, 2016 15:44_

dirble plugin search results have empty descriptions. the results are correct and can be played, chust they does not have any description nor logo.

_Copied from original issue: jaedb/spotmop#148_

**Comment by jaedb** [comment]
@mczerski After further investigation, Mopidy-Dirble doesn't provide this information for us to use. So at this stage we will require the backend plugin to provide this for us to display it.

Can you see this information using any other Mopidy clients?

**Comment by mczerski** [comment]
What information are You talking about ? I was talking about any sort of track description like station name. I believe that the dirble backend support that since using mopped the radio station name is showing correctly. Now I'm using Iris and I believe that this issue is resolved in Iris already.

**Comment by jaedb** [comment]
Ah, yes I think that would have been resolved when fixing the similar issue for _Mopidy-Youtube_. Unfortunately FontAwesome doesn't have a Dirble logo, which is why nothing shows. Because these logos carry significant meaning I don't want to use something generic as this will quickly become confusing.

To this end, we won't be able to show the Dirble logo until it's provided by FontAwesome.

If you're happy with this solution for the meantime, please close this issue.

**Comment by mczerski** [comment]
yeah, sure it's perfectly fine for me :)
