### ISSUE TITLE
[Feature request] Support for mopidy-emby

### ISSUE THREAD

**Issue by vrs01** [jaedb/Iris#120]
Hi! 

First of all, thank you for this really nice looking piece of software! I have one request: I would like to use mopidy-emby from within Iris. Mopidy-emby works nicely with the musicbox-webclient. Do you think it is a lot of work to ingegrate it? And do you already have a wishlist for supported backends somewhere here, where I can just add this?

Best, vrs

**Comment by jaedb** [comment]
Hello,

In theory, backends using the standard `lookup` and `browse` endpoints should work fine on Iris. Try browsing under _Your Music_ > _Local_ > _Directories_. You should be able to find your Emby library material this way.

The search engine will also search your Emby library. You can manage the backends searched under _Search_ > _Sources_.
