### ISSUE TITLE
[Feature Request] Allow Change Of Default Click Behavior

### ISSUE THREAD

**Issue by Alladinsane** [jaedb/Iris#121]
Great web interface! I have just one suggestion that would make it perfect: It would be great if the default click behavior could be altered in the mopidy.conf file. I'm planning to use this as collaborative jukebox on our office LAN, and it would be great if double-clicking a track added it to the queue instead of playing it immediately. My end-users are inevitably going to double-click their search results, and the result will be that songs are going to be constantly interrupted. 

That said, this is currently the only frontend I have found who's Spotify search has not been broken by the recent API change, so big thanks for that!

**Comment by jaedb** [comment]
I understand your use case, however it's not really what the end user would expect to happen. The default result from a double-click action is to open/run/activate/play the item. This is the case in almost every UI you can imagine, so it's a pretty universal UX.

Personally I'd suggest education of using the interface with your users as a better approach.

**Comment by Alladinsane** [comment]
I appreciate that. Education of the office staff on the interface is an idea, but I decided that educating myself on how to install reactjs from source on an rpi, and then forking your repo and making whatever customization I needed for my particular use case was easier. Thanks again for a fantastic and well-maintained mopidy frontend, and more importantly, thanks for writing well commented code that was really easy to read, understand, and manipulate. ;)
