### ISSUE TITLE
Spotify authentification with Opera

### ISSUE THREAD

**Issue by vrs01** [jaedb/Iris#122]
Hi!

I have an issue with the web authentification for Spotify in Opera. The pop-up opens and I can put in my account details and click ok but at the end the pop-up doesn't close and spotify doesn't get activated. 
Do you have an idea would could be causing this?
When I use the 'Share authentification' from Firefox, I can activate Spotify in Opera. 

Best, vrs

**Comment by jaedb** [comment]
Thanks for your post, this has been merged with #112
