### ISSUE TITLE
Iris (wrongly?) uses port 80 for wss://-connection.

### ISSUE THREAD

**Issue by stekern** [jaedb/Iris#123]
**Current setup**
![screenshot from 2017-06-07 17-53-11](https://user-images.githubusercontent.com/10640491/26888090-3b7b589e-4baa-11e7-92f3-508dde8ed070.png)

The Raspberry Pi is hidden behind CloudFlare's flexible SSL and a tunneling service called PageKite (similar to ngrok etc.).

**Problem**
When accessing through the CloudFlare-protected https://mydomain.com/, I get the following error:
`WebSocket connection to 'wss://mydomain.pagekite.me:80/iris/ws/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

However, when accessing directly through the unencrypted http://mydomain.pagekite.me it works.

**Possible solution**
I believe my setup would work if the port was excluded from the wss://-connection. The same setup works on [Mopidy-MusicBox-Webclient](https://github.com/pimusicbox/mopidy-musicbox-webclient), where the wss://-connection is setup without any explicit port.

**Comment by jaedb** [comment]
Can't you set _Settings_ > _Mopidy_ > _Port_ to `443`?
