### ISSUE TITLE
Alphabetical sorting with 'The' in the title

### ISSUE THREAD

**Issue by KingDaveRa** [jaedb/Iris#127]
I've noticed when sorting artists alphabetically, all those starting with 'The' are down in the T section. I think it'd be nice if 'The' could be ignored and sort on the first word instead. I.e. The Beatles should be under B,

**Comment by MarcinWieczorek** [comment]
Many people following the common sense would still look for The Beatles in the `T` section. I wouldn't change that.

**Comment by jaedb** [comment]
I agree with @MarcinWieczorek. While I think there's merit to accommodating 'the', 'a', etc in sorting I don't think it's expected behavior for the **average** user.
