### ISSUE TITLE
Failed to add some URI(s) 2.14.3

### ISSUE THREAD

**Issue by gaiterjones** [jaedb/Iris#128]
After an upgrade from 2.14.2 to 2.14.3 I get "Failed to add some URI(s)" when trying to play any song.

**Comment by jaedb** [comment]
Please provide more information (read [Before you lodge an issue](https://github.com/jaedb/Iris/wiki/Support#before-you-log-an-issue)).

**Comment by AKoetsier** [comment]
Same here, I get the following log in the javascript console:

```
Mopidy.ServerError
code: 0
data:
  message: "Exactly one of "tracks", "uri" or "uris" must be set"
  traceback: "Traceback (most recent call last):↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/internal/jsonrpc.py", line 133, in _handle_single_request↵    result = self._unwrap_result(result)↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/internal/jsonrpc.py", line 222, in _unwrap_result↵    result = result.get()↵  File "/usr/local/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get↵    compat.reraise(*self._data['exc_info'])↵  File "/usr/local/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise↵    exec('raise tp, value, tb')↵  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop↵    response = self._handle_receive(message)↵  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive↵    return callee(*message['args'], **message['kwargs'])↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/tracklist.py", line 417, in add↵    'Exactly one of "tracks", "uri" or "uris" must be set')↵ValueError: Exactly one of "tracks", "uri" or "uris" must be set↵"
  type: "ValueError"
```

**Comment by KarelCvanderLinden** [comment]
I have the same issue. after upgrade to newest version, I am not able to listen to spotify anymore.
same error occured for me when I provided the wrong account details in `sudo nano /etc/mopidy/mopidy.conf`, but the login details in that file have not changed after the upgrade

I also use the musicbox webclient, but all seem to work fine on that end.

**Comment by AKoetsier** [comment]
Looks like I had to revert to Mopidy-Spotify version 3.0.0 to make it work again.

**Comment by gaiterjones** [comment]
I have everything running in a docker container, so the newest code is installed by pip whenever I rebuild the container. I how can I specify the Mopidy-Spotify version?

**Comment by jaedb** [comment]
This issue is not due to any changes in Iris, instead within Mopidy-Spotify. The latest version of Mopidy-Spotify requires you to provide additional configuration values and fails to start without these. You will have seen an error when starting mopidy similar to:

```
INFO     Disabled extensions: spotify
WARNING  Found spotify configuration errors, the extension has been automatically disabled:
WARNING    spotify/client_secret must be set.
WARNING    spotify/client_id must be set.
WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.
```

You will need to update your `mopidy.conf` file as per (https://github.com/mopidy/mopidy-spotify)[Mopidy-Spotify readme].

**Comment by gaiterjones** [comment]
That fixed it, thanks very much!

**Comment by voold** [comment]
Hello that did'nt fix it because I did'nt see any of the warnings and I still can't play a song. I've added my name, password, client_id, and secret_id and the error message returned is not talking about authentification problem. I've been sorting this out for hours. Can somebody help?

**Comment by jaedb** [comment]
@voold are you able to play Spotify tracks using a different Mopidy Frontend (try ncmpcpp for command-line simplicity)? What some of the URIs you're trying to play, and what part of the world are you in?
