### ISSUE TITLE
"Failed to load some URI(s)" after updating pi

### ISSUE THREAD

**Issue by Aephir** [jaedb/Iris#129]
Hi,

I saw the issue [#137](https://github.com/mopidy/mopidy-spotify/issues/137), but I don't think it's related. I am running mopidy as service on a raspberry pi 2 (Jessie lite).

After I did `sudo apt-get update && sudo apt-get dist-upgrade` I get the error "Failed to load some URI(s)". I have rebooted, signed out from Spotify (in Iris) and back in with no luck. I can browse and search just fine, and it claims to start radio (no error, but no music either), but complains no matter which track I try to play.

I probably forgot/broke something stupid during update, but I can't seem to figure out what. So any help would be appreciated.

Cheers,

UPDATE: 
*Ahem*, running through a bunch of troubleshooting, I found the error. I needed a client ID/secret. I'm not sure if that was not needed until the update, or if that was somehow deleted during the update. 

If anyone runs into the same issue after updating debian, see [this thread](https://github.com/lfcabend/mopidy-spotify-web). I'm not using spotify-web, but the instructions and link also worked for the base mopidy spotify config.

**Comment by Aephir** [comment]
*Ahem*, running through a bunch of troubleshooting, I found the error. I needed a client ID/secret. I'm not sure if that was not needed until the update, or if that was somehow deleted during the update. 

If anyone runs into the same issue after updating debian, see [this thread](https://github.com/lfcabend/mopidy-spotify-web). I'm not using spotify-web, but the instructions and link also worked for the base mopidy spotify config.

**Comment by jaedb** [comment]
This was discussed in #128 which has recently been closed. Before logging an issue it can be helpful to have a quick spin through closed issues as your issue may already have been addressed.

**Comment by Aephir** [comment]
Thanks, I must have missed that one.
