### ISSUE TITLE
[Feature Request] Country and Locale settings from the system

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#133]
It would be nice if Country and Locale settings were pulled from the host system

**Comment by jaedb** [comment]
See [Configuration](https://github.com/jaedb/Iris/wiki/Getting-started#configuration). This is only respected for new clients. Any existing values specified by the client (the browser) will remain untouched.

**Comment by mczerski** [comment]
if my mopidy server changes ip address i have to change the Country and Locale settings prom the default NZ and nz_NZ. The default could be pulled from the system instead of hardcoded one. The other thing is how one should know which values are correct ?
