### ISSUE TITLE
Failed to add some URI(s)

### ISSUE THREAD

**Issue by jhaagmans** [jaedb/Iris#137]
I've been using Iris for 2 months now as a Spotify client. Initially, I had the error mentioned above because mopidy itself wasn't properly authenticating to Spotify, I fixed that and it has worked ever since, until last week, when I started getting those notifications again.

I'm running on Arch, everything is up-to-date and I'm using Firefox. The log message in the console is a very undescriptive `MopidyMiddleware</</</</<`. I'm lost. Where to look?

**Comment by Mengesh** [comment]
Do you have `client_id` and `client_secret` set in `[spotify]` block of your `mopidy.conf`?

**Comment by jhaagmans** [comment]
Nope, that was it! Is that a new requirement? It's always worked without those.

**Comment by Mengesh** [comment]
It's quite new ([2017-06-08](https://github.com/mopidy/mopidy-spotify/blob/develop/CHANGES.rst#v310-2017-06-08)). The thing is it doesn't take effect until your token expires.
