### ISSUE TITLE
Context menu on long press in Opera: disappears after release of finger

### ISSUE THREAD

**Issue by vrs01** [jaedb/Iris#140]
Hi!

The context menu on long press is disappearing right after I release my finger so I cant use it. I'm using Opera on a Samsung Tab S2 in landscape mode. In Firefox it's working fine, so can be low priority.

Best, vrs01

**Comment by jaedb** [comment]
Context menu (long tap) is forceably disabled due to the inconsistencies across devices and browsers. Devices can also override the hold period which further complicates things.

Instead use the tickbox and context menu trigger.
