### ISSUE TITLE
[Feature request] Explicit badges in Now playing

### ISSUE THREAD

**Issue by antons-** [jaedb/Iris#144]
Thanks alot for your prompt work on #135!

Any chance this can be extended to the Now playing page?

**Comment by jaedb** [comment]
Unfortunately not. _Mopidy-Spotify_ doesn't currently provide the `explicit` switch, which is why the current tracklist doesn't display the flag.

Iris uses the Spotify HTTP API, which is how I've been able to implement this in other components.
