### ISSUE TITLE
playlist appears to duplicate songs multiple times each time loaded

### ISSUE THREAD

**Issue by brianclinkenbeard** [jaedb/Iris#145]
the initial time a playlist is loaded for me, the playlist appears accurate. however, each time the playlist is loading following this every song appears to be re-added to the playlist (i.e. the playlist appears to be duplicated with the all the songs appended again).
to reproduce this simply open a playlist, click an artist/album to move away from the playlist, then hit back or go back to the playlist through the sidebar. the playlist will return to normal on a refresh.

**Comment by jaedb** [comment]
Pow! Sorted - have a peep on the latest version. I was under the hood already :-)
