### ISSUE TITLE
How to enable cover art background under right menu? 

### ISSUE THREAD

**Issue by ikciwor** [jaedb/Iris#155]
On mopidy site and on iris github I can see that right menu gets nice background (blurred cover art of currently played track). However on my computer the menu is completely white...
![_screenshot](https://user-images.githubusercontent.com/10672238/28677109-d22dedd8-72ec-11e7-9495-e85bdc753cda.jpg)
How to make it look like below?
![img](https://raw.githubusercontent.com/jaedb/iris/master/Screenshots/overview.jpg)

**Comment by jaedb** [comment]
Those screenshots are of an old version of Iris (`2.14.5` and older, see ffe790a).

**Comment by jaedb** [comment]
PS. Iris will move to a dark interface very shortly, so this will be quite different again. Watch this space :-)
