### ISSUE TITLE
Configuration unclear about mopidy.conf section

### ISSUE THREAD

**Issue by edysli** [jaedb/Iris#157]
The [Configuration](https://github.com/jaedb/Iris/wiki/Getting-started#configuration) section says `country` and `locale` should be set in `mopidy.conf`, but does not say under which section they should go. I've tried putting them in the `spotify` section, but the UI still shows the default country and locale.

**Comment by jaedb** [comment]
Configuration values per-extension need to live under their own heading, eg `[iris]`.

It is also worth noting this is only applied for unconfigured values. Once you've changed it within Iris web client, it won't be overwritten by changes to the config file.

**Comment by edysli** [comment]
Thanks for the added information! :smile:
