### ISSUE TITLE
My Artists only show Followed artists from Spotify

### ISSUE THREAD

**Issue by Icexist** [jaedb/Iris#158]
I am using Mopidy Iris 3.1.2 with only the Spotify library, no local files. 

The My Artists screen only shows the artists I am following on Spotify, not all artists that I have in my library. I'm not sure if this is intended behavior or not, but it would be nice to have my list of artists in my library available.

**Comment by jaedb** [comment]
Spotify's _My Artists_ is essentially a list of your 'followed' artists. However Mopidy's equivalent (eg _Library/Browse/Local Artists/_) lists **all** artists. So I'm wary that the two different data relationships should be kept separate.

I do hear you though - it would be nice to have _My Library_ encompass all music sources.

**Comment by jaedb** [comment]
After re-reading, I think I misunderstood the issue you described.

When you mention your Spotify artist library, I believe this is the same as artists that you follow. Also, Spotify only provide one endpoint to fetch a user's Artists (https://developer.spotify.com/web-api/get-followed-artists/).

**Comment by Icexist** [comment]
Essentially, when I look at my Spotify library (in a Spotify application), I see a list of all the artists for which I have saved music. In looking through the API reference, I didn't see any endpoint for this type of data. I would have expected an endpoint like `GET https://api.spotify.com/v1/me/artists` but I didn't see anything like it.

This may have to be implemented on the Mopidy or Iris side by compiling a list of all artists that the user has saved music from.

**Comment by Icexist** [comment]
Looks like this has been a feature request made to Spotify: https://github.com/spotify/web-api/issues/611

**Comment by jaedb** [comment]
I think the difference is that following an artist adds them to `/me/artists` however the Spotify interface collates these artists AND artist of tracks that you follow.

**Comment by jaedb** [comment]
I'm closing this issue as it's not an issue with Iris, rather than Spotify API. When [if] Spotify create an endpoint to facilitate this functionality we can re-open and implement it into Iris at that time.
