### ISSUE TITLE
No homescreen icon on Android

### ISSUE THREAD

**Issue by lesteenman** [jaedb/Iris#159]
After adding Iris to my homescreen on Android, I don't get an icon for Iris. The [Chrome Lighthouse](https://developers.google.com/web/tools/lighthouse/) extension also reports there is no valid icon that can be used to add to homescreen.

Do others have this same issue, or could this be related to my local setup? If others have this issue as well, I'll test how to solve this, and make a pull request.

**Comment by Hugomm** [comment]
I dont have an icon too on Android. I used to add it manually on Nova Launcher.

**Comment by Parakoopa** [comment]
@jaedb Was about to add this, since it's pretty simple, but I couldn't really figure out what Iris official icon is. There is a favicion and a logo.png in the assets folder. What icon should be used?

**Comment by jaedb** [comment]
The official logo for Iris is still a work in progress. Once it's completed it'll be added as the homescreen icon, and applied to favicon (#180).
