### ISSUE TITLE
Pressing "Enter" Stops current playback

### ISSUE THREAD

**Issue by ldimitroff** [jaedb/Iris#160]
When playing music and try to make a new search and press "Enter" to perform the search. It stops the current playback. Very annoying. 
Any Thoughts?

**Comment by jaedb** [comment]
Please provide more information about your environment. See [Before you lodge an issue](https://github.com/jaedb/Iris/wiki/Support#before-you-log-an-issue).

**Comment by ldimitroff** [comment]
Sure:

Current config is 3.1.2 (was also happening on 3.1.1)
Running on a Raspberry Pi 3.

Steps to Reproduce.
1) Perform a search.
2) Start a radio or a playback of any kind
3) Go to Search again, put any word. Hit enter (trying to search other artist/song) 

Actual result:
Playback stops
Expected result
Playback continues and results are shown to include on queue if wanted

**Comment by jaedb** [comment]
What browser and OS are you experiencing this on?

**Comment by ldimitroff** [comment]
I'm using Chrome Version 60.0.3112.78 on Ubuntu 17.04.

The Mopidy server is Runing on Raspbian

**Comment by jaedb** [comment]
Hmm this is a peculiar issue. I have not been able to replicate the issue (the closest I can get currently is Debian 8 + Chromium 27).

Can you try another browser and also another device to see if the issue is isolated to that browser/OS?

**Comment by ldimitroff** [comment]
Seems that is an isolated issue. On Firefox I cannot reproduce. What other information can I provide to help you with this?

**Comment by kiwikern** [comment]
Can confirm on desktop, iPad and Android phone. Also, space does not pause/play for me.
![iris_playback_bug](https://user-images.githubusercontent.com/2671139/29000097-a46abe90-7a61-11e7-8e78-40dbc6da33d3.gif)
Windows 10: Chrome 59.0.3071 and Firefox 55.0b13
Android: Chrome/Firefox
iPad: Safari

**Comment by alexdelifer** [comment]
I can confirm this issue only seems to happen on my set up when I'm already listening to the radio and then try to search something, when I press enter the radio stop just like in @kiwikern gif.
