### ISSUE TITLE
Spotify account configuration confusion

### ISSUE THREAD

**Issue by lukecyca** [jaedb/Iris#161]
I've been struggling to understand how Spotify credentials are meant to work, vis-a-vis Iris and mopify-spotify...

* What is the difference between the spotify account that is set through Iris' Settings page, and the spotify account set under `[spotify]` in `mopidy.conf`? I assume the former is just for browsing Spotify, and the latter is for actually streaming the audio?

* Do they have to be the same account? Is there a use case for them to be different?

* Could this be integrated such that users can change Spotify accounts through the Iris GUI, and have it take effect for the `mopidy-spotify` backend as well?

Thank you!

**Comment by jaedb** [comment]
I'd suggest reading up on a few previous discussions as this has been covered in depth: #95 and the [Spotify Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/).

To answer your questions though:
* `mopidy.conf` authorization is for playing the Spotify streams (using pyspotify). Iris needs full access to perform user-specific actions like manipulating your playlists.
* No, they can be different accounts
* No, you need to configure this directly in the `mopidy.conf` file

I hope this helps!

**Comment by lukecyca** [comment]
That makes a lot of sense.

Does that mean that when a client accesses Iris and doesn't have the "Authorization Code Flow" credentials they can still search and play music, but not affect any of the private settings on the Spotify account being used for streaming by pyspotify?

If so, that is ideal for my use case! I want casual users to be able to search and play music, but not affect the account.

**Comment by jaedb** [comment]
Yep - precisely.

**Comment by lukecyca** [comment]
Nice. Thanks for your help and also for your work on this project.

Closing this issue. #featurenotabug
