### ISSUE TITLE
[Feature Request] Allow Caching for Faster Startup

### ISSUE THREAD

**Issue by AlbertMokrejs** [jaedb/Iris#162]
# Allow Caching for Faster Startup
## Summary
Depending on the quality of a user's connection, Iris can take a while to populate all of the content for the 'Artist' and 'Album' tabs from connected Spotify accounts. Although Spotify libraries do change, they do not usually change super drastically, and thus caching the user's library (especially Album/Artist Artwork) could boost start-up performance for users on poor connections.

In instances where a cache is used but Spotify itself is unavailable (the system is offline overall), the albums/artists could simply not be displayed at all, or could simply be marked with an icon indicating they're part of the library but currently not accessible.

## Why
In some instances, generally when using Spotify on poor connections, Iris can take a while to properly load all of the user's library content. This is noticeable to the extent that it is often possible to scroll all the way down the 'Artists' tab and then watch as it gets longer as new Artists and images are loaded in. 

On rarer occasions, this process can actually use enough of the poor connection's throughput to interfere with streaming music from Spotify until everything has synced. This is probably the most disruptive version of this behavior.

### General 

Probably the easiest system for storing a cache for Iris would be using some SQL variant (SQLite, for example), to store references to Artists, Albums and Songs, for both Online and Offline libraries. 

***

At startup, the cache can be loaded to populate the library before the Spotify API even verifies the user's credentials (though the music will be unstreamable (see 'Offline Mode'). When Spotify verifies the user, the music will become available to stream, and it'll become possible to access the user's Spotify Library via the Spotify API. 

At this point, it should be trivial to cross-reference the Artist, Album, and Song URLS (URLS are unique, while names often aren't) to find those that are either 1) Missing (and should be downloaded and cached), 2) Excessive (and should be deleted from the cache, and removed from the library), 3) Correct (and should not be touched).

Once identified, all media in cases 2 and 3 requires no interaction with Spotify (except to Stream), and only interacts with the local databases. Media in case 1 still has to be downloaded along with its Album/Artist Art, but won't need to be on future Iris uses. 

Theoretically, this should shift Iris from needing to download 100+ images at every startup (assuming someone listens to around 30 different artists and likes at least 2 albums per artist) to needing to download 2-10 to account for new media added.

***

Below is a table detailing a possible suggested format (somewhat basic, but theoretically sufficient) for the various database entries that could be used in this cache. The basic idea is that Artists and Albums do not keep track of songs tied to them (as these can grow), but songs keep track of the Albums and Artists they belong to. Albums only track which Artist they belong to. 

Populating an Artist or Album only requires searching through the other tables for references to them. 

| Type | Format |
|--------|-----------|
| Artist Spotify | Artist Name(\<text\>); IsOnline(1); Artist Art(\<image\>); Link To Artist(\<URL\>)|
| Artist Offline* | Artist Name(\<text\>); IsOnline(0); HasArtistArt(\<bool\>); Artist Art(\<image\>)| 
| Album Spotify | Album Name(\<text\>); IsOnline(1); Artist(\<text\>); Album Art(\<image\>); Link To Album(\<URL\>)|
| Album Offline* | Album Name(\<text\>); IsOnline(0); Artist(\<text\>); HasAlbumArt(\<bool\>); Album Art(\<image\>)| 
| Song Spotify | Song Name(\<text\>); IsOnline(1); Album(\<text\>); Artist(\<text\>); Link To Song(\<URL\>)|
| Song Offline | Song Name(\<text\>); IsOnline(0); Album(\<text\>); Artist(\<text\>); Path To Song(\<Path\>)|
| Spotify Playlist** | Playlist Name(\<text\>); IsOnline(1); Playlist Artist(\<text\>); HasPlaylistArt(\<bool\>); Playlist Art(\<image\>); SongList(\<List of Songs, by URL\>); |

* A "Untitled" default art should be available for offline Albums and Artists.

** Playlists would still need to be examined individually at every boot, to check for changes.

### Offline Mode

When Spotify is unavailable, there should be some indicator of which media is unavailable. Because art-styles vary, the most universal indicator would probably be a[ simple red crossed-out-circle](http://clipart-work.net/data_gallery/circle-slash-symbol-clipart-best-Ca9raJ-clipart.gif) icon near the name of each piece of media.

## Notes

Although this suggestion may seem better fit for Mopidy-Spotify, given how Iris interacts with Spotify directly (or appears to), it seemed better to go straight to the source.

I have made some suggestions in this document in an effort to be helpful, but I am by no means trying to tell you how to design your software and apologize if it comes off that way.

I really dig Iris's style. Well done.

**Comment by jaedb** [comment]
Thanks for your very thorough feature request!

Under __Why__, to be experiencing these levels of performance, you must be using a particularly slow connection. What kind of connection are we talking about here? Patchy 3G mobile?

Currently the only caching in use is what the browser provides. The bulk of bandwidth usage is around imagery, and caching of these assets is comfortably handled by the browser already.

A full, uncached load of the _Now Playing_ interface is 2.5mb. This may seem quite high, however 1.15mb of this is the Iris application itself (`app.js`). This file would only be fetched on the initial app load, and for subsequent reloads it would be fully cached by the browser.

I do think there are opportunities for performance enhancement within Iris (and in Mopidy in general), and caching can help achieve these. However I think there needs to be a level practicality; where can we make the least effort with the most gain? Instead of building a huge caching engine, I would suggest looking at the 'quick wins' first.

**Comment by AlbertMokrejs** [comment]
> Under Why, to be experiencing these levels of performance, you must be using a particularly slow connection. What kind of connection are we talking about here? Patchy 3G mobile?

Actually just Wifi in Central Europe (Prague, Kramsach). It can be a shocking difference compared to the states.

That being said, I understand your skepticism when comparing this to other potential places to make immediate improvements, and appreciate your consideration anyway.

**Comment by jaedb** [comment]
It sounds like you have a fair bit of experience with asset caching. Do you have a simplified alternative to caching JSON data? I'd like to avoid building an intermediary database as a caching engine.

The coming releases of Iris will use a much heavier loading mechanism for library assets (Playlists, Artists, etc). This frontloading of asset collection is relatively slow, and will be especially noticeable for users with large playlists. So I'd be looking for a way for Mopidy to cache these assets, rather than having to reconstruct them on every reload.

**Comment by AlbertMokrejs** [comment]
> alternative to caching JSON data

I assume you mean to caching every JSON object you get from the Spotify API from individual API calls, which would essentially be like keeping a "log" of all interaction between Iris and the API. 

Without digging into the code too much, based on how Iris behaves during loading I assume that you collect content gradually to populate each of the tabs; Iris begins by getting a list of what's in the artist's library and then begins making calls to get the information and images for each part thereof, gradually generating and inserting them into pages as the API responds. 

Without any sort of caching, the above behavior is desirable: it means that you don't have to wait for everything to access anything. With access to caching, it can in a way become more desirable to aggregate all of the data first (all of the albums, artists, etc) in the form of some standardized structure and then just convert into the appropriate tabs and visual components. This would essentially be the result of 'stitching' all of the JSON from API calls together, since one gives you the list of items in the library and the rest give you the information about individual elements. It's essentially the same difference between streaming a movie and downloading all of it first: wait-times (streaming > downloading) vs. smoothness (downloading > streaming). 

***

> avoid building an intermediary database as a caching engine

To cache without utilizing a database, your best bet is to find the last (chronologically) element Iris has to generate at each startup and that is roughly consistent at subsequent starts. The hypothetical structure consisting of all of the data aggregated from API calls could be one such element (and is one that would be easy to store in a format as simple as a single JSON object in a file somewhere). A single JSON object is easy to traverse through for the purpose of generating all of the elements on the page.

Iris's process for 'building' the page would essentially go from:

> old process psuedo-code

```
def build():
    User = authenticateUser()
    UserLibrary = getUserLibrary(User)
    for Item in UserLibrary:
        ItemData = unpackJSON(getItemData(Item))
        page.addItem(ItemData)
    render()

build()
```

to:

> new process psuedo-code

```
def stitch( list_of_items, **kwargs):
#list_of_items would simply be every item in the library, without any of its data
#**kwargs would be keyword arguments in the format of <unique identifier>={data about that item}
#by replacing items with themselves and their relevant data, this essentially forms a hierarchy of data about the library as a whole. 
    dataDictionary = unpackJSON(list_of_items)
    for ItemName in dataDictionary:
        if ItemName in kwargs:
            dataDictionary[ItemName] = kwargs[ItemName] 
            #copies the item's data over into the space placeheld by its name
        else:
             dataDictionary.remove(ItemName)
             #remove unavailable items, to prevent errors later
    cacheJSON = packJSON(dataDictionary)
    save(cacheJSON)

def loadFromJSON(dataJSON):
     dataDictionary = unpackJSON(dataJSON)
     for item in dataDictionary:
         ItemData = dataDictionary[item]
         page.addItem(ItemData)
     render()

def build():
     User = authenticateUser()
     if hasCacheAvailable():
           loadFromJson(getCache())
           #This loads the cached object, generates the page and does the first render
           UserLibrary = getUserLibrary(User)
           dataList = []
                 for Item in UserLibrary:
                        ItemData = unpackJSON(getItemData(Item))
                        dataList.add(ItemData)
          stitch(userLibrary, dataList)
          #After waiting to download all data, this stitches all of the data together again and replaces the cache
          loadFromJson(getCache())
          #The new "cache" (actually downloaded just prior) is loaded, and the page is re-rendered with updated content
     else:
          #This will happen on first startup, and in case the cache is lost
           UserLibrary = getUserLibrary(User)
           for Item in UserLibrary:
                ItemData = unpackJSON(getItemData(Item))
                page.addItem(ItemData)
           render()
```

(Sorry that it's a bit messy, I'm on vacation with just travel laptop on hand).

The advantage of a transition like this is that it doesn't require much alteration of how the individual elements on the page are generated: they're still getting the same data that the API would provide, except it's been neatly collected and packages. 

There is some overhead, however since for the sake of simplicity this process blindly redownloads all of that data anyway to later make the new cache (this is the exact same overhead as what Iris does now, though). To reduce this, you could actively compare each element in the cached libraryList to its counterpart in the new libraryList (to see which are missing, or excessive) and then only make changes based on that. That's more of step toward a `caching engine` though, which you wanted to avoid. 

If you want to cache more aggressively you can technically go so far as to start caching the HTML that you end up injecting into the page anyway, which could be done using essentially the same style of JSON-caching (*I think*). I think this is trickier though, since it might alter how some interactions with things like settings that alter the layout or style would have to interact with the injected HTML (*Maybe?*). 

***

I've also come up with an alternate caching method, but I don't have the time to write it out right now. If you have major qualms with this suggestion though, I can lay out the alternate one as well.

**Comment by kingosticks** [comment]
Mopidy-Spotify already caches images and certain other API responses. If there are problems using mopidy-spotify for these resources could we work to fix/improve those rather than duplicate the efforts?

**Comment by jaedb** [comment]
This has been resolved by the use of `localForage` as a browser-based database engine. Essentially assets are stored in a simple key-value store, and is then restored to Redux's state as and when needed without requiring calls to APIs (including Mopidy's). This also covers the asset libraries (ie _My Albums_) by using the same structure.
