### ISSUE TITLE
Searchbar input is cut off on iPad

### ISSUE THREAD

**Issue by kiwikern** [jaedb/Iris#165]
I have added Iris to the home screen via Safari. The search input is slightly offset.
![image](https://user-images.githubusercontent.com/2671139/29000185-77ce5d08-7a64-11e7-913b-39d243faac5e.png)
![image](https://user-images.githubusercontent.com/2671139/29000184-72559530-7a64-11e7-89f6-9f5a3d3ba3ad.png)

**Comment by jaedb** [comment]
Is this issue experienced when you haven't added it to your homescreen?

**Comment by kiwikern** [comment]
Yes, also happens with Chrome:
![image](https://user-images.githubusercontent.com/2671139/30512216-7d2040f4-9aea-11e7-88be-e905f77e0b2f.png)

**Comment by lukecyca** [comment]
I'm experiencing this on iPad and desktop Safari as well.

I've reduced this issue to the following test case:
```html
<html>
<head>
  <style>
input {
  display: inline-block;
  font-size: 3rem;
  height: 3rem;
}
  </style>
</head>
<body>
  <input type=text value=testing>
</body>
</html>
```

Setting the font size the same as the element height implies a line height of 1, but Safari doesn't seem to allow a line-height smaller than the default on a text input element. I also doesn't allow negative padding.

On Chrome it interprets it as having a line height of 1, and centers it vertically:
<img width="497" alt="screen shot 2017-09-24 at 8 42 33 pm" src="https://user-images.githubusercontent.com/366484/30791680-f7817d66-a168-11e7-9b8a-fa22e7bb1f62.png">

But on Safari it keeps the default line height, so it appears clipped:
<img width="606" alt="screen shot 2017-09-24 at 8 42 25 pm" src="https://user-images.githubusercontent.com/366484/30791685-fcd6758c-a168-11e7-9744-f33f51b29834.png">

I tried adjusting and resetting `line-height`, changing `vertical-align`, negative `padding` and a few other things, but couldn't make a difference.

[According to this](https://stackoverflow.com/questions/5285735/vertical-positioning-of-text-in-an-input-field) it's not possible to adjust vertical alignment of text within a text input field. He suggests using a `<textarea>` styled to look the same, or trickery involving extra `<div>`s.

**Comment by jaedb** [comment]
@lukecyca Thanks heaps for looking into this.

I've experimented with a few patches, and the easiest and most reliable fix was to increase the input height and employ negative margins. This fix is now on `master` and will be included in the next release.
