### ISSUE TITLE
Save Spotify authentication into config

### ISSUE THREAD

**Issue by GraysonAdams** [jaedb/Iris#167]
Is there a way to not have to log into Spotify every time I open the player in a new browser?

It loses my settings each time I open the player or if I clear my browsing history.

**Comment by jaedb** [comment]
Short answer: nope.

Thanks to the changes in `Mopidy-Spotify`, we can provide more functionality for Spotify users out-of-the-box (watch this space). However for security reasons 'new' clients (browser) will not be pre-populated with a user's Spotify Authentication.
