### ISSUE TITLE
Allow "CMD + A" and "CMD" for selecting (all) tracks

### ISSUE THREAD

**Issue by apsylone** [jaedb/Iris#168]
It would be awesome to select all tracks by the keyboard shortcut "CMD + A" as in all application.
It would help us to delete all tracks at once.

And also selecting multiples tracks with "CMD" pressed.

**Comment by jaedb** [comment]
Just to be sure, you mean the Apple keyboard CMD key? Currently shift and ctrl keys are used to achieve this functionality already.

**Comment by apsylone** [comment]
Yes, because CMD is the CTRL command of Windows :-)
Using CTRL + A with my mac doesn't work actually.

Shift works for me. It is maybe a bug related to mac so.

**Comment by jaedb** [comment]
Correct - `ctrl + a` doesn't work as it doesn't exist currently. See [Keyboard shortcuts](https://github.com/jaedb/Iris/wiki/Features#keyboard-shortcuts) for a list of the current shortcuts.

**Comment by apsylone** [comment]
Should you add it to the shortcuts ? It will be really useful as i'm using it everyday in every app :-) 
That's a common shortcut I think.

**Comment by JayGatsby7** [comment]
I would like to see a way where you could easily select all the tracks at bottom of page when the discover tab is used. Control a would do it or a radio button.

**Comment by noobadmin** [comment]
The thing is, ctrl + mouse click triggers mouse right click, so you can't effectively use it to select tracks unless remapping your keyboard.

**Comment by jaedb** [comment]
Apple doesn't treat modifier keys (_shift_, _ctrl_, _alt_, _cmd_, etc) as such, whereas Windows identifies these and makes them universally detectable with javascript. And even then, each Apple browser provides different keycodes for the same key.

I'm sure someone, somewhere thought this was a great idea :pensive:

So at this time I've implemented _ctrl + a_ to select all tracks, but adding Apple's _cmd_ modifier key will happen at a later date.

**Comment by apsylone** [comment]
I Think that some libs like KeyboardJS > https://github.com/RobertWHurst/KeyboardJS 
Would help you to easily implements this ?
Am I wrong ? :-)

**Comment by jaedb** [comment]
One thing I've come to learn with coding is that nothing is as easy as it sounds...

That library does sound promising, so when time permits I'll have a look.

**Comment by apsylone** [comment]
Sure... that’s never easy ! I’ll have a try to implement it when i’ll have some time and try to make you a PR.

**Comment by jaedb** [comment]
@apsylone rather than introducing another third-party plugin, I believe we should be able to handle the command modifier key with `e.metaKey`. Can you please test and confirm whether this resolves it for you? You'll need to pull the `develop` branch to see this.
