### ISSUE TITLE
[Feature request] Lyrics integration

### ISSUE THREAD

**Issue by choseh** [jaedb/Iris#171]
Since Spotify doesn't offer a proper lyrics display, maybe Iris can do that instead? Since we use iris on an extra screen in the office, it would be cool to have scrolling lyrics.

**Comment by jaedb** [comment]
Technically possible - it'd be interesting to gauge the level of interest in this functionality.

A quick investigation reveals [musiXmatch](https://developer.musixmatch.com/documentation/api-reference/track-lyrics-get) as a good API candidate.

**Comment by apsylone** [comment]
+9M votes ! I was looking for something integrated directly to Iris ! Would be so awesome :-) 
👍

**Comment by choseh** [comment]
https://developer.musixmatch.com/plans - This doesn't look very promising unfortunately. I think those plans were the actual reason why spotify itself parted with musiXmatch in the first place.

**Comment by jaedb** [comment]
Another option would be to use [Genius](https://docs.genius.com/), but this will still require some bypassing as their API doesn't directly expose lyrics. Rather it provides links to pages with lyrics, so we'd need to scrape the markup to extract the lyrics.

On the upside, _Genius_ also provides track-specific history and information which could be cool.

**Comment by johnhamelink** [comment]
ChartLyrics is potentially an option? http://www.chartlyrics.com/api.aspx
I also found Lololyrics but their DB seems quite empty: http://api.lololyrics.com/

**Comment by jaedb** [comment]
@johnhamelink both of those look pretty good, especially ChartLyrics. It seems to have a good collection of mainstream songs, but not much in the way of less popular material. Genius seems to have a much larger library, so while it's a bit more hacky to get the lyrics it'll get a better end result.

**Comment by johnhamelink** [comment]
@jaedb perhaps worth building a library which can look up lyrics, starting with ChartLyrics and falling back to Genius et al

**Comment by jaedb** [comment]
I'd rather not require multiple integrations to achieve one function, at least unless absolutely necessary. More dependencies = more maintenance.

For the most part, Genius seems to provide solid results.

**Comment by choseh** [comment]
genius looks decent, yes. donation goal? ;)

**Comment by jaedb** [comment]
Released to production

**Comment by choseh** [comment]
"Addition of lyrics to Kiosk Mode, which auto-fetches lyrics from Genius for the currently playing track and auto-scrolls based on the play progress. The initial feature was included in a previous release, but has now been more adequately refined." from 3.46.0 is exactly what we imagined, thanks a lot @jaedb, we'll send a few bucks your way ❤️
