### ISSUE TITLE
Artists list view not working 3.2.0

### ISSUE THREAD

**Issue by noobadmin** [jaedb/Iris#172]
What title says, but it might be only me? Safari Version 11.0 (13604.1.34) When I click the button to switch to list view it does nothing..

**Comment by jaedb** [comment]
Try opening your debug console, and running in test mode to identify more information. See [Debugging](https://github.com/jaedb/Iris/wiki/Advanced#test-mode).

**Comment by jaedb** [comment]
Resolved and released in 3.3.0
