### ISSUE TITLE
Spotify saved songs not showing up 3.2.0

### ISSUE THREAD

**Issue by noobadmin** [jaedb/Iris#173]
In the previous version I could find my Spotify saved songs in the right side menu under My Music/Songs

**Comment by jaedb** [comment]
The whole _My Music_ library is having a major overhaul and individual tracks is a particularly large list that is causing a few performance issues. As such I've removed it until I can figure out how to properly handle this.

The next release is will reinstate the _My Music > Tracks_ view but this will be legacy and will have none of the new library functionality (filtering, sorting, etc).
