### ISSUE TITLE
[Feature request] Gamepad Support

### ISSUE THREAD

**Issue by Parakoopa** [jaedb/Iris#177]
This ticket is about integrating the support for navigating using Gamepads into Iris.

This would be a great addition, because it would allow control of Mopidy on a TV, and I think the interface of Iris is already designed in a way that would allow for nice control using a TV and a gamepad.

I was actually thinking about adding this myself, but thought I'd open a issue first to hear your opinions.

**Comment by jaedb** [comment]
I think that's a cool idea - it would require some considerable thought as navigation keys are already bound to native functions (scrolling, some keyboard shortcuts, etc).  What was your game plan?

It'd also be quite involved to implement, so it would be worth gauging people's interest before embarking on this.

**Comment by jaedb** [comment]
Closing because there is no significant demand for this feature.
