### ISSUE TITLE
Iris not installing over SSH

### ISSUE THREAD

**Issue by mizzoudavis** [jaedb/Iris#178]
I used `sudo pip install Mopidy` to install Iris to my RPi (Jessie) using ssh. Started Mopidy as a service and Iris is not found in the list. Is there a limitation to running it as a service?

![screen shot 2017-08-21 at 4 43 04 pm](https://user-images.githubusercontent.com/24829629/29539530-f6243268-868f-11e7-8abb-a5016a488057.png)
![screen shot 2017-08-21 at 4 43 39 pm](https://user-images.githubusercontent.com/24829629/29539531-f6261e20-868f-11e7-85a0-e65755d53787.png)

**Comment by jaedb** [comment]
Have you installed Iris? Iris is not included in Mopidy out-of-the-box, so it needs to be installed individually (eg `sudo pip install Mopidy-Iris`).

**Comment by mizzoudavis** [comment]
Yes, I've installed that as well. Missed 
![screen shot 2017-08-21 at 5 43 24 pm](https://user-images.githubusercontent.com/24829629/29541236-6765c3e4-8698-11e7-9d64-c6a79b27167d.png)
that in my comment.

**Comment by mizzoudavis** [comment]
Also confirmed it doesn't run when I navigate directly to /iris/
![screen shot 2017-08-21 at 5 46 33 pm](https://user-images.githubusercontent.com/24829629/29541299-c22f8012-8698-11e7-9817-78c9c2d8ff54.png)

**Comment by mizzoudavis** [comment]
Hmm... I installed Spotipy and now it works... sorry if I missed that in the docs somewhere.
