### ISSUE TITLE
Alarm clock

### ISSUE THREAD

**Issue by dylono96** [jaedb/Iris#179]
Would there be a change for Iris to use the mopidy-alarmclock extension in the future?
Or maybe something better with repeating alarms?

**Comment by jaedb** [comment]
This is comfortably beyond the scope of Iris at this time. If enough people are interested and there are enough donations towards this functionality then it'll happen :-)

**Comment by mczerski** [comment]
@dylono96 how do You imagine it would work ? mopidy-alarmclock is a separate web interface, it has separate web interface, so how iris would use it ?

**Comment by dylono96** [comment]
true, I tought of someting like an extra button with a shortcut to the webpage. like with mopidy-musicbox_webclient.

**Comment by mczerski** [comment]
adding a section in iris that will just list avaliable web interfaces with links to them would be easy solution, but then if You got to such link there is no nice way back to iris, either hit back button couple of times or just put iris adress into adress bar. and if you put <serveraddress>:6680 into adress bar You already have that section.

**Comment by dylono96** [comment]
thanks.

**Comment by jaedb** [comment]
Thanks @mczerski for explaining a workaround for this. I believe this is the best approach. For Iris to re-create the interface for every Mopidy extension will make it a nightmare for maintenance and general code upkeep.
