### ISSUE TITLE
Artists isn't automatically loading the next page

### ISSUE THREAD

**Issue by aidos** [jaedb/Iris#18]
When you scroll down to the bottom of the artists listing, I'm assuming it should load the next batch of artists like it does on the album page.

**Comment by jaedb** [comment]
Yip, it'll load the next 50 items from your Spotify Artists endpoint. Can you please check:
1. You have authorized Spotify
2. You have `> 50` items in _My Artists_

**Comment by aidos** [comment]
Ahhh - I've just looked at the network log and it's pulling out the list of artists I'm _following_.

That's different from the Artists page within Spotify, which shows all the artists whose tracks you've starred.

I feel like the later is probably better behaviour because it's consistent with Spotify, but no big deal. I tend to use the albums page when browsing my collection anyway.

**Comment by jaedb** [comment]
Ah I see the confusion now. There isn't an endpoint available in the Spotify API to browse in this manner, and it also becomes platform-specific. The end game is for Iris to work similar regardless of the provider (ie Spotify, Google Music, SoundCloud etc).

**Comment by aidos** [comment]
Makes sense. I'll close this then.
