### ISSUE TITLE
Change the Favicon

### ISSUE THREAD

**Issue by eddible** [jaedb/Iris#180]
Is there a simple way to change the Favicon? I can see there is a PSD file available in the repo, but if I just change the .ico file, it is overwritten whenever I do an upgrade. I wondered if perhaps there was a config option I could add so it doesn't get overwritten during upgrades? Thanks!

**Comment by jaedb** [comment]
The favicon will be updated when the logo for Iris is completed. As the favicon and logo represent Iris, I don't plan to make it user-editable. 

If you wish to customise it, you'll need to fork Iris and apply your own favicon that way. Please note that this will mean you won't get updates.

**Comment by eddible** [comment]
Ah, didn't realise it was temporary. No worries!
