### ISSUE TITLE
Cannot queue local tracks with colon character ":" in URI

### ISSUE THREAD

**Issue by zeroware** [jaedb/Iris#183]
### Description

I have a local song with colon character ":" in the album / title and I can't play them.

### Expected behavior

Being able to play songs with any special characters in the title or album

### Actual behavior

When I try to queue such a track I get the error "Failed to add some URI(s)"

### Steps to replicate
My track has the following metadata : 

- title : Jack Sparrow
- artist : Hans Zimmer
- album : Pirates of the Caribbean: Dead Man’s Chest

When I copy the URI for the concerned track this is what I get in Iris : 

local:track:Hans%20Zimmer/Pirates%20of%20the%20Caribbean

Here is the same URI when I copy it from MusicBox : 

local:track:Hans%20Zimmer/Pirates%20of%20the%20Caribbean_%20Dead%20Man%E2%80%99s%20Chest/01%20Jack%20Sparrow.mp3

### What can be the cause ?

I'm not experienced enough with the mopidy protocol / specs but I think the bug is caused by a manipulation of the URI scheme which also has a colon (example : `local:` , `yt:`)

**Comment by jaedb** [comment]
You're right in that it's a conflict of the common URI syntax. The general format is `{provider}:{type}:{id}` so having a `:` character in there is going to throw things out. The URI you've mentioned is a file-based URI, so removing the `:` from your filename will resolve this.

Windows doesn't allow filenames including `:` so this issue would be isolated to unix/mac environments.

**Comment by zeroware** [comment]
This is really a problem because all my music is tagged and organized using beets.
MusicBox doesn't have this problem which means this is fixable.

If you want I can look into the code of MusicBox (https://github.com/pimusicbox/mopidy-musicbox-webclient) to see how they are handling this ?

**Comment by zeroware** [comment]
I looked into the code more closely. Mopidy is not sending the `: ` character in the URI. It is replaced with a `_` character.

If you look at the `digestTracksKeys` function in Iris code I can see that you are splitting a string with `_` which can be a problem if `_` is part of the URI.

**Comment by jaedb** [comment]
Try running the latest code on `master` branch to see if this fixes the issue for you.
