### ISSUE TITLE
Troubles with build.sh

### ISSUE THREAD

**Issue by bglowacki** [jaedb/Iris#185]
Hello, 
I am trying to run `npm run dev` but I am having with the `build.sh` script on a Mac.

This is what I get:
```
Copying assets
rsync: -avrs: unknown option
rsync error: syntax or usage error (code 1) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(1337) [client=2.6.9]
Copying index.html and test.html
./build.sh: line 13: md5sum: command not found
Cachebusting js/css URLs
sed: 1: "mopidy_iris/static/inde ...": invalid command code m
sed: 1: "mopidy_iris/static/inde ...": invalid command code m
sed: 1: "mopidy_iris/static/test ...": invalid command code m
sed: 1: "mopidy_iris/static/test ...": invalid command code m
sed: 1: "mopidy_iris/static/test ...": invalid command code m
Done!
```

Building process would be more stable for all operating systems if it would be entirely handled by Webpack. What do you think?

**Comment by jaedb** [comment]
I would rather not introduce another dependency (well multiple dependencies) to have Webpack process Iris' HTML and moving of assets. Using `build.sh` is a much lighter way to handle this, so a better approach would be to use commands that Mac can handle. I've reverted to using a `BUILD_NAME` as a timestamp, which should enjoy much better support.

**Comment by lukecyca** [comment]
> sed: 1: "mopidy_iris/static/inde ...": invalid command code m

Macs have BSD sed, but the `build.sh` is using syntax for GNU sed. They differ slightly in how they interpret the `-i` switch. The following syntax works consistently on both versions:

```bash
sed -i='' 's/BUILD_HERE/'$BUILD'/g' mopidy_iris/static/index.html
```

**Comment by lukecyca** [comment]
> The following syntax works consistently on both versions

I spoke too soon. While it appears to work, BSD sed interprets it as `'='` and GNU sed interprets it as `''`. So in the former case, it saves the resulting file to `'index.html='`. Sadly, I'm not sure there's any syntax that works consistently for this switch.

What I've done is install GNU sed using `brew install gnu-sed` and then modified my local `build.sh` to call `gsed`.

**Comment by bglowacki** [comment]
Yeah, just tried it to learn that it makes index.html= file.

Maybe using npm based tooling would be better? It would be consistent through all platforms.
@jaedb What you think?

**Comment by jaedb** [comment]
@bglowacki Good idea!
