### ISSUE TITLE
Context menu and track selection on hybrid devices

### ISSUE THREAD

**Issue by hcoohb** [jaedb/Iris#186]
### Description
Hi,

No context menu available on right click and the blue tick appears on the song list (as if it was a phone) except the blue menu at the bottom does not appear. 
As a result, I cannot multi select and play, or right click and add to library.
It was working recently but I have updated to 3.3 recently and it seems not to work anymore...

Google Chrome, on linux Version 60.0.3112.113 (Official Build) (64-bit)
I tried to completely clear the browsing cache but same problem.
Let me know if you need more details
For the same server, another computer on windows seems to display things fine...
### Expected behavior
Context menu on right click

### Actual behavior
See screenshot:
![screenshot_20170831_171828](https://user-images.githubusercontent.com/12975783/29911281-a0612f5a-8e70-11e7-814d-dd728dbb3655.png)
And I have the standard chrome context menu on right click

### Steps to replicate

**Comment by hcoohb** [comment]
I uninstalled 3.3.3 and went back version by version down to 3.1.3 and the context menu is working again for me!
I tested 3.3.3 again, but no go.
Let me know what other information you need !

**Comment by jaedb** [comment]
Is your device a touch device?

**Comment by hcoohb** [comment]
Yes, it is a touchscreen laptop.
Oh, is that why there is this behaviour ?
I can try with the touchscreen on windows if that helps

**Comment by oscarklein** [comment]
Can confirm this issue on chrome mobile android 6.0 but also on chrome for my desktop and laptop computer.

Another problem i have is that i can't start playing individual tracks just the playlists' play button works.

**Comment by runejuhl** [comment]
I didn't dive deep into the code, but https://github.com/runejuhl/Iris/tree/issue/186-bug-when-display-name-null fixes it for me. I'd be happy to make a PR but you should probably test it out first to make sure I'm not breaking it for anyone else.

**Comment by hcoohb** [comment]
Thanks @runejuhl for the explanation investigation.
I would like to test it but cannot find the files to modify in my python directory...
Any chance you could guide for the process to test your changes ?
Thanks a lot!

**Comment by runejuhl** [comment]
@hcoohb
The easiest is probably to just remove the existing Iris installation and install the one from my branch:

```sh
pip uninstall Mopidy-Iris # prefix with sudo if installed that way
git clone git@github.com:jaedb/Iris.git
cd Iris
npm install
./build.sh
./setup.py develop # again, prefix with sudo as needed
```

After that start mopidy. I'm not entirely sure if `pip` purges files when uninstalling, but if you use the [test mode(https://github.com/jaedb/Iris/wiki/Advanced#test-mode) it should work in any case.

If you run into problems there is some more documentation at https://github.com/jaedb/Iris/wiki/Advanced#setting-up-your-development-environment

**Comment by jaedb** [comment]
From what I can see, there are two issues here:
1. the context menu trigger is not appearing (the blue circle with 3x dots)
2. selection behavior isn't quite right as it should _toggle_ track selection rather than unselecting everything else

@runejuhl I don't believe that the `spotify.me` variable would interfere with either of the above. Perhaps it interferes with the actual _rendering_ of the context menu during calculation of context menu options.

**Comment by jaedb** [comment]
@runejuhl Regarding your change to `action.data.display_name`, I'm not sure how you're detecting this as an object. It's a direct output from the Spotify API [`get_me`](https://developer.spotify.com/web-api/get-current-users-profile/) endpoint, which returns a User object. `display_name` is either a string or `null`.

Perhaps try resetting Iris and re-authenticating (_Settings > Advanced > Reset all settings_) as it's possible you have old `localStorage` data structure.

**Comment by runejuhl** [comment]
@jaedb sorry, should probably have included a bit on that. In my case I get the following error without my change:

```
TypeError: Cannot read property 'replace' of null
    at Object.setUsername (app.min.js?cachebuster=5eb333fd60f31a34c77dca8c344f4a58:formatted:2705)
    at app.min.js?cachebuster=5eb333fd60f31a34c77dca8c344f4a58:formatted:28072
    at app.min.js?cachebuster=5eb333fd60f31a34c77dca8c344f4a58:formatted:25388
    at app.min.js?cachebuster=5eb333fd60f31a34c77dca8c344f4a58:formatted:26240
    at app.min.js?cachebuster=5eb333fd60f31a34c77dca8c344f4a58:formatted:25108
    at app.min.js?cachebuster=5eb333fd60f31a34c77dca8c344f4a58:formatted:24970
    at app.min.js?cachebuster=5eb333fd60f31a34c77dca8c344f4a58:formatted:28104
    at app.min.js?cachebuster=5eb333fd60f31a34c77dca8c344f4a58:formatted:24720
    at dispatch (app.min.js?cachebuster=5eb333fd60f31a34c77dca8c344f4a58:formatted:21840)
    at app.min.js?cachebuster=5eb333fd60f31a34c77dca8c344f4a58:formatted:945
```

This is of course from the minified sources, but going back up the call stack, setting a breakpoint at `if (void 0 !== action.data.display_name)` in the Spotify middleware switch statement and reloading reveals that `action` contains the following:

```js
{
  "type": "SPOTIFY_ME_LOADED",
  "data": {
    "country": "DK",
    "display_name": null,
    "external_urls": {
      "spotify": "https://open.spotify.com/user/iamnotyou"
    },
    "followers": {
      "href": null,
      "total": 0
    },
    "href": "https://api.spotify.com/v1/users/iamnotyou",
    "id": "iamnotyou",
    "images": [],
    "product": "premium",
    "type": "user",
    "uri": "spotify:user:iamnotyou"
  }
}
```

That means that we get this:

```js
typeof(action.data.display_name)
// "object"
```

Which in turn means that the condition `(typeof(action.data.display_name) !== 'undefined')` is `true`, as `null` apparently is an object. This means that `name` get set to `null`, and this is what causes the exception later on when the `setUsername` function tries to do `null.replace(....)`.

**Comment by runejuhl** [comment]
@jaedb I've tested on both my usual Firefox 56, in Chromium and in a clean Chromium profile (`chromium --temp-profile`) so I'm certain that nothing in localStorage is interfering. The content of `localStorage.spotify` with a clean browser is

```
"{"access_token":"ACCESS_TOKEN!","token_expiry":1504391307378,"me":false}"
```

I'm not sure that I've ever set a Spotify display name, but IMO that shouldn't be necessary either :)

**Comment by runejuhl** [comment]
I just tried the 3.3.3 release on Firefox Mobile 55.0.2 and it turns out it handles it differently. Instead of throwing a `TypeError: Cannot read property 'replace' of null` it gives a `TypeError: username is null`, which apparently doesn't cause JS evalulation to stop completely with the effect that it actually works.

Here's the stack trace from Firefox Mobile:

```
console.trace(): 
	<anonymous> debugger eval code:1:1
	setUsername http://10.0.0.100:6680/iris/app.min.js:1:74017
	SpotifyMiddleware</</</< http://10.0.0.100:6680/iris/app.min.js:1:851835
	PusherMiddleware</</</< http://10.0.0.100:6680/iris/app.min.js:1:781493
	MopidyMiddleware</</</< http://10.0.0.100:6680/iris/app.min.js:1:804472
	UIMiddleware</</</< http://10.0.0.100:6680/iris/app.min.js:1:773695
	CoreMiddleware</</</< http://10.0.0.100:6680/iris/app.min.js:1:770361
	localstorageMiddleware</</</< http://10.0.0.100:6680/iris/app.min.js:1:852353
	createThunkMiddleware/</</< http://10.0.0.100:6680/iris/app.min.js:1:763023
	dispatch http://10.0.0.100:6680/iris/app.min.js:1:676161
	getMe/</< http://10.0.0.100:6680/iris/app.min.js:1:24980
```
(`console.trace()` is just to get a copy-paste-able stack trace, ignore that)

**Comment by jaedb** [comment]
@runejuhl this needs to be it's own issue as it's not directly related to the initial issue. Can you please move these details into a new issue? Then we can keep track of the issue and fix in isolation.

**Comment by runejuhl** [comment]
@jaedb sure, I can move it into a new issue but I'm not entirely sure why? The title of this issue was originally " no context menu for Chrome/linux" which is exactly what I experienced. https://github.com/jaedb/Iris/issues/186#issue-254241137 describes the problem I had.

I'm not sure the problem that caused @hcoohb to open the issue have anything to do with touch screens?

**Comment by jaedb** [comment]
Maybe I misunderstand the actual issue (which is why the issue template is important).

At what point during the interaction do you receive the error? I'm just trying to wrap my head around the flow of logic that would connect `uiAction.showContextMenu` to `spotify.getMe`. At this stage I can't see any connection.

Debugging tip: use [test mode](https://github.com/jaedb/Iris/wiki/Advanced#test-mode) for full console logging.

The issue initially flagged by @hcoohb is a regression issue where hybrid devices only bind to touch events. Click events were not functioning properly in this scenario.

**Comment by hcoohb** [comment]
Hi guys,

@runejuhl  Thanks for giving me  a rundown on how to test your changes.

So just to confirm a few things. Yesterday,  I had tested 3.3.3 from a win10 client on touchscreen laptop which gave me the same issues as mentioned in the first post (i.e no custom context menu on right click, and when clicking on one song in the list the  blue round does not appear when the screen is too big). Tested the same setup on a win10 non touchscreen laptop where everything works like a charm!
So it would definitely suggest, this issue is due to the touchscreen capability of the laptop.

Also, I applied the changes from @runejuhl repo, and that did not fix my issue on the touchscreen laptop.

If I have a chance, I will try to test the latest @jaedb iris git to confirm it now works on hybrid devices.

Cheers,

**Comment by runejuhl** [comment]
@jaedb I guess I was the one in the wrong here -- sorry about that. The problems @hcoohb described matched mine exactly so I didn't think twice about the possibility of it being separate issues.

Do you want me to create another issue to investigate it more? Now that it's been merged in https://github.com/jaedb/Iris/commit/b9ae8c449d90ecdcb3d4639a9372c7f161d058f9 it shouldn't be a problem any more, but I'm still a bit curious as to why it failed in the first place. The exception would occur when looking at track listings, e.g. the current playlist.

**Comment by hcoohb** [comment]
Yesterday I cloned git and installed, 
I can confirm that now on my touchscreen laptop when I select songs, the menu appears at the bottom (the  3 dots in the blue circle).

While it is useable and probably the expected behaviour for a touchscreen device, I most often use the mouse but that means that now, I cannot use "SHIFT" to select several songs at the same time.
Do you have any idea on how to "hide" the touch capabilities from Iris? (As in, let's not change the Iris code, but is there a chrome parameter to hide the touch?)

Thanks for fixing the issue promptly!
Cheers
