### ISSUE TITLE
Follow artist/playlist missing.

### ISSUE THREAD

**Issue by dannyc543** [jaedb/Iris#187]
Hi there,

Apologies if I'm being an idiot. Reasonably new to this.

I've got Iris working and I love it but when I search for artists or playlists I don't have the option to follow them. The way I understand it is that this is a feature that should be available so I'm guessing that I've missed something, maybe something I need to turn on in the config file. 

Everything else seems to work just fine so I'm a bit stuck as to how to figure out the issue so thought I would post here.

Many thanks in advance!

**Comment by jaedb** [comment]
For full Spotify functionality (ie following artists, playlists and albums) you need to authenticate Iris with your Spotify account. Check out _Settings > Spotify > Login_.

**Comment by dannyc543** [comment]
That's fixed it! Many thanks, I knew it would be something simple!
