### ISSUE TITLE
tablet issue

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#189]
So i launched Iris on my galaxy tab e, and it is displaying as desktop UI. This is very unuseful because some actions require right clicking. The other issue is that spotify authentication is not possible, the authentication popup is displaying correctly in a separate tab but it is not returning to Iris web page after authentication - Iris does not receive any confirmation from the popup. This is happening in chrome and firefox

**Comment by mczerski** [comment]
hmm, i'm using my tablet in landscape position, if i turn it into portrait position it switches to mobile version .. is it suppose to do that ? i portrait position after selecting a track, a small blue icon shows at the bottom where i can select the action, in landscape position there is no blue icon.

**Comment by mczerski** [comment]
it may relate to #186, and I think that the web page is mobile version in both orientations, but in landscape orientation blue icon on the bottom is not showing when tracks are selected.

**Comment by jaedb** [comment]
@mczerski please raise issues using the proper issue template. This ensures I have all the information necessary to replicate and resolve the issue quickly.

**Comment by mczerski** [comment]
## Actual behavior
blue icon with actions to select is not showing up after selecting track

## Steps to replicate
1. launch Iris in galaxy tab e in landscape position 
2. add something to tracklist
3. select a song

## Tested environment(s)
#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ x] Andriod:
- [ ] Other:

#### Browsers affected
- [x ] Chrome: 
- [ x] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ x] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Additional details, debug data, logs, etc

## Before you submit
- [ x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by mczerski** [comment]
just tested with the newest version 3.4.1 and the problem is gone, so I guess it may be closed.
