### ISSUE TITLE
Proxy API requests to avoid CORS errors, enable caching

### ISSUE THREAD

**Issue by runejuhl** [jaedb/Iris#190]
### Description
Currently Iris makes API calls to services (e.g. Last.fm) directly from the browser to the remote endpoint. Firefox 56.0 blocks cross-origin requests that do not have proper CORS headers resulting in some requests being blocked:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ws.audioscrobbler.com/2.0/?format=json&api_key=4320a3ef51c9b3d69de552ac083c55e3&method=artist.getInfo&artist=. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

In addition I think it's bad behavior in general to do it this way; instead Iris should be extended with an endpoint that can proxy any API calls and remote resources. This has a few additional benefits besides making Iris work with Firefox 56:

* it enables caching for presumably static resources (e.g. images from Spotify [1])
* it enables Iris to work in environments where Mopidy is running remotely and the client is firewalled from the general internet

[1]: And now that I look closer at Spotify images it seems their caching is completely broken; for an image requested tonight it replied with the following headers:

```
Expires: Sun, 23 Jul 2017 09:40:36 GMT
Last-Modified: Tue, 26 Jul 2016 01:17:57 GMT
ETag: "093b7f0f21821d7e666c8c5ed304567b"
Cache-Control: max-age=315360000
Content-Length: 187531
Accept-Ranges: bytes
Date: Sat, 02 Sep 2017 18:35:28 GMT
Age: 3574493
Connection: keep-alive
X-Served-By: cache-ord1746-ORD, cache-ams4446-AMS
X-Cache: HIT, HIT
X-Cache-Hits: 1, 4
Content-Type: image/jpeg
Access-Control-Allow-Origin: *
```
Note the `Expires` and `Date` values.

### Expected behavior
Iris should proxy requests for external resources

### Actual behavior
Iris requests remote resources straight from the browser client

### Steps to replicate
Look at the requests from the browser when using Iris.

**Comment by jaedb** [comment]
This does require further investigation, which I plan to do.

In the meantime, there are a few follow-on thoughts to this:
* Introducing a proxy to _Iris_ will place further load on the Mopidy server. Many users (including myself) run _Iris_ on lightweight devices like the RaspberryPi. Mopidy requests are single-threaded, so high-load requests (eg `start_radio`) create a noticeable performance drop as all subsequent requests must wait for previous requests to complete. This will create a much less-snappy feeling UI.
* The issue is with external APIs not including appropriate CORS headers, rather than Iris. 
* Caching has also been discussed in #162

**Comment by jaedb** [comment]
When testing responses from LastFM, I receive the `Access-Control-Allow-Origin: "*"` header, which effectively [allows all domains](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) Cross-Origin Resource Sharing. Therefore I'm confused as to why you're experiencing a CORS blocking error.

Can you please include the full request and response (including headers) to replicate the error you describe?

**Comment by runejuhl** [comment]
Hi!

Huh, did a search but apparently missed #162 -- sorry.

## Regarding Mopidy load

From a cursory look at the [Mopidy HTTP server documentation](https://github.com/mopidy/mopidy/blob/master/docs/api/http-server.rst) it seems like there shouldn't be a problem; tornado scales quite well.
I don't have any low-powered devices running currently, but a quick test with `siege` shows that Mopidy has no trouble with concurrency:

```
$ siege -b -t 10s http://localhost:6680/iris/
** SIEGE 4.0.2
** Preparing 25 concurrent users for battle.
The server is now under siege...
Lifting the server siege...
Transactions:		        2270 hits
Availability:		      100.00 %
Elapsed time:		        9.74 secs
Data transferred:	      868.82 MB
Response time:		        0.10 secs
Transaction rate:	      233.06 trans/sec
Throughput:		       89.20 MB/sec
Concurrency:		       23.46
Successful transactions:        2270
Failed transactions:	           0
Longest transaction:	        1.19
Shortest transaction:	        0.00
 ```

Maybe I misunderstood you, but from the performance shown above I don't think
there should be a performance problem in adding a proxy feature to Mopidy?

## Regarding CORS

I've tried to reproduce it tonight, but have been unable to do so -- it seems
Last.fm has fixed their headers. I'd guess that it is bound to happen again
though, with Last.fm, Spotify or others, so I'd still prefer the ability to
proxy requests to avoid any future problems -- and to allow for caching and
increased privacy protection.

Feel free to close this issue in favor of #162. I hope to find time to take a
stab at implementing a proxy in the near future if you're interested.
