### ISSUE TITLE
Tunein logo in search

### ISSUE THREAD

**Issue by ugrug** [jaedb/Iris#199]
## Expected behavior
It should be nice to have the tunein logo instead of microphone sign to be able easyer indentify the tunein radio stations.

## Actual behavior
Shows microphone sign.

## Steps to replicate
1. Start a search with a radio name
2.

#### Operating systems affected
- [X] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [X] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [X] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [X] Yes, I have tested this issue thoroughly
- [X] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

![image](https://user-images.githubusercontent.com/5822419/30264247-4629e868-96d8-11e7-817b-d95114f6ca30.png)

**Comment by jaedb** [comment]
Totally agree! However the icons used to represent sources is _FontAwesome_. As such we can only use icons from the [_FontAwesome_ icon set](http://fontawesome.io/icons/).

If you have a suggested replacement for the TuneIn icon that is available in _FontAwesome_ I'm all ears :-)

**Comment by ugrug** [comment]
I'm understand now that the limitations with the font. This case I think the current solution is ok. :)
Thank you for the quick reaction.
