### ISSUE TITLE
Detect Mopidy-Spotify timeouts and notify client

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#20]
Hi,
the subject says it all. I select some artist, I click "Start radio" button and nothing happens. I use latest version from PIP, 2.10.13.

**Comment by jaedb** [comment]
Can you please send me the URI of the artist in question?

**Comment by vojtapolasek** [comment]
Hi,
for example this artist:
https://play.spotify.com/artist/6pIRdCtSE5hLFfIfcTAicI
but it didn't work on any other artist I've tried. Can I get any debug
info from Iris to help you?

**Comment by jaedb** [comment]
Under _Settings > Debugger_ you can enable logging of Redux action events. However this issue is a timeout on the server, which won't be recognised in the client.

**Comment by jaedb** [comment]
Have introduced `processes`. These handle long-running processes like adding a lot of `URI`s to the queue. Now released in `2.13.9`.

**Comment by jaedb** [comment]
This should now be remedied by `process`es. If you encounter this issue on a version later than `2.13.9`, please re-open this issue.
