### ISSUE TITLE
Cant play Podcasts

### ISSUE THREAD

**Issue by buggymonkey** [jaedb/Iris#201]
Hi,
unfortunately i'm not able to find / play an episode of a podcast.
For example this one:
https://open.spotify.com/episode/36yg0MfgOFYyy4Hp5llGJG

**Comment by jaedb** [comment]
Firstly, please use the provided issue template. There is a reason this is in place.

Spotify doesn't provide any API endpoints for podcasts, and it [doesn't look like they plan to at this stage](https://github.com/spotify/web-api/issues/551). Until this happens, Iris (and the more essential Mopidy-Spotify) can't understand what a Spotify podcast is, or how to get it.
