### ISSUE TITLE
Youtube search never finish and cannot cancelled

### ISSUE THREAD

**Issue by ugrug** [jaedb/Iris#205]
## Expected behavior
Search should be finish, timeout or at least should be possibility to cancel search.

## Actual behavior
After search finished for another sources, youtube search continue to run forever.

## Steps to replicate
1. Search an artist with spotify, soundcloud, tunein, youtube.
2.

#### Operating systems affected
- [X] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [X] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [X] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [X] Yes, I have tested this issue thoroughly
- [X] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

![image](https://user-images.githubusercontent.com/5822419/30711185-3e7ac4ec-9f08-11e7-9d5d-6b737956740a.png)
![image](https://user-images.githubusercontent.com/5822419/30711201-5164014a-9f08-11e7-840f-3d514d93fc9f.png)

**Comment by jaedb** [comment]
I've experienced this annoying issue myself, however I haven't quite figured out how we can cancel it (yet). I'm looking down the route of applying timeouts to all Mopidy requests, which would handle this on a global scale.

The reason it's isolated to searching YouTube is that the YouTube extension is quite buggy, and often fails lookups.

**Comment by ugrug** [comment]
Actually its worst on mobile as covers the '...' button and prevent playing songs :(
Thank you for your effort!

![screenshot_2017-09-21-21-30-02](https://user-images.githubusercontent.com/5822419/30714743-478d271c-9f14-11e7-9ae6-2239e85beda8.png)
