### ISSUE TITLE
UI for volume is difficult on touchscreens

### ISSUE THREAD

**Issue by lukecyca** [jaedb/Iris#207]
When using Iris on a touchscreen, it is difficult to accurately control the volume, because the control is quite small. If you touch the slider and are off by a millimeter or two, that can translate into quite a different volume than desired, or even make it louder when you meant to make it a bit softer.

Most apps allow you to drag the volume slider, which makes it far easier because you can hear the relative change as you move your finger. Even if you initially touch the slider with a fat finger and the volume jumps too far, it's easy to drag it a little bit to correct, and still get it one try. Without this continuous feedback, you have to keep trying a few times to hit your target.

The best solution would be to support dragging by providing continuous volume adjustments while dragging is occurring (plus visual feedback).

If that's not feasible, then making the volume slider a bit bigger would help in the short term.

**Comment by jaedb** [comment]
@lukecyca at what screen size is this most affecting you? Can you post a screenshot so I can replicate the issue?

**Comment by jaedb** [comment]
This has been resolved via #297
