### ISSUE TITLE
Double tap has no effect

### ISSUE THREAD

**Issue by mckennajones** [jaedb/Iris#210]
## Expected behavior
Double click should play the item. 

## Actual behavior
Nothing happens when I double click an item. Only way to play is to select using the circle on the left of the item and then use the blue selected item menu.

## Steps to replicate
1. Find an item you would like to play.
2. Double click it. 

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: 
- [x] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [x] Firefox: 
- [ ] Internet Explorer:
- [x]  Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [x] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [x] Small (phone)

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [  ] Yes, I have attached screenshots and/or screencast of the issue in action
Not sure if a screencast would really be useful for a simple issue like this.
- [ ] Yes, I have included any relevant debug data and error logs
Would be happy to include other data if needed.

**Comment by jaedb** [comment]
It sounds like you're using a hybrid touch device (eg touchscreen laptop). Is this accurate?

If so, this is a known issue. Currently devices that can both `click` and `touch` default to only allow touch events. Double-tapping (or clicking) in this situation is not enabled.

**Comment by mckennajones** [comment]
@jaedb You are correct. I am also unable to play a track with my touchscreen though.

**Comment by en00x** [comment]
I have the same behavior. It is not working on any device with a touchscreen.

**Comment by mckennajones** [comment]
@jaedb To be clear, the change of the title that you did above is incorrect. I am unable to double _click_, with my _trackpad_.

**Comment by jaedb** [comment]
@mckennajones Absolutely, it does make sense. However it is technically tricky to implement when trying to facilitate this for the plethora of browsers and devices and make it work consistently (and efficiently!) across them all. This is why the current solution is to detect touch capabilities and use that as the definition for touch vs mouse events.
