### ISSUE TITLE
[Feature Request] Like/add tracks for each provider

### ISSUE THREAD

**Issue by ibrokemypie** [jaedb/Iris#215]
Would it be at all possible to add a 'like' button, which would be able to love a song on last.fm, add song to spotify library, etc, or even just quickly add it to a 'Liked' playlist with a single click?
This would be really awesome, especially if it can like the song on both spotify and last.fm a t once, though I understand if this is not possible.
Thansk!

**Comment by jaedb** [comment]
This would only work if we were to integrate the full LastFM authorization API. This would work in a similar way to the Spotify authorization process. As we're making changes to a user's account, we'd need to be authorized using this mechanism to do so first.

This does open a can of worms in how far do we go with a LastFM integration.

**Comment by jaedb** [comment]
As a side-note I wouldn't bundle liking tracks across all connected services (eg Spotify, LastFM, etc) into one action. This would assume this is the intended behavior for every user.

Instead I would look to create a context menu to add the track to each service's library/likes/etc. This would provide the most flexible functionality for the most users.

**Comment by jaedb** [comment]
LastFM integrated as at 3.8.0
