### ISSUE TITLE
Radio mode and api

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#217]
Is there any API that can disable radio mode ? As I understand the radio mode is unique to the Iris so there is nothing like that in mopidy core API.
I want to be able to remotely clear the tracklist, load the specified playlist and be ale to cycle through songs in this playlist, but when radio mode is on funny things happen like some additional songs appear on the tracklist. If there would be a way to remotely disable the radio mode it would solve my problem.

**Comment by jaedb** [comment]
When you hit _Play_ on anything, radio mode is disabled (you will see a blue notification _Stopping radio_). At this point, playback will resume normal behavior.

At any time you can observe (and control) radio mode under _Now Playing > Radio (top right)_.

**Comment by mczerski** [comment]
I'm talking about API not UI.

**Comment by jaedb** [comment]
Yes, all calls via websockets are available via RESTful requests. This is not documented, so you'll need to be savvy with ajax and JSON. Try `http://localhost:6680/iris/http/get_radio` to get started.

**Comment by mczerski** [comment]
ok, thanks.
BTW, if I hit Play on my playlist, the radio mode is turning off as You mentioned.  So shouldn't it also turn off when I make call through the mopidy core API ? for example when clearing the tracklist.

**Comment by jaedb** [comment]
Nope, if another Mopidy client handles a play request, Iris doesn't assume to stop radio mode as it doesn't know the context of the command.

**Comment by mczerski** [comment]
I thought so :)
