### ISSUE TITLE
[Feature Request] ID3-Tag rating

### ISSUE THREAD

**Issue by tatoosh** [jaedb/Iris#219]
It would be nice to read and write out the id3-tag rating .
Is that a mopidy feature or an Iris one?

**Comment by jaedb** [comment]
This is something that would need to be provided by the Mopidy server. You can see what it does provide in the [Mopidy docs](http://mopidy.readthedocs.io/en/latest/api/models/#mopidy.models.Track).

**Comment by tatoosh** [comment]
thx @jaedb - i will post the feature request there.
