### ISSUE TITLE
Saving album into my music

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#22]
Is it possible to save album into my music? I tried right clicking it but no context menu appeared. If you plan to implement this, could you please implement it as a button in list of albums? I like buttonos more than context menus, because context menus are often not accessible for screenreading software. Thanks for your reply.

**Comment by jaedb** [comment]
Within an album you can _Add to library_. Is this not the functionality you're looking for?

**Comment by vojtapolasek** [comment]
Hi,
yes, I am sorry, I have noticed just now. Do you plan to add any context
menus to albums?

**Comment by jaedb** [comment]
Not at the moment, but once other, more standard, functionality is matured I plan to add context menus and draggability to albums, playlists and artists.

**Comment by vojtapolasek** [comment]
Okay, no problem. I don't like context menus because they have usually
problems with accessibility, but I understand that they mimic desktop
applications.

**Comment by jaedb** [comment]
Accessibility issue highlighted here will be addressed in #33.
