### ISSUE TITLE
[Feature request] Streams menu entry

### ISSUE THREAD

**Issue by tgurr** [jaedb/Iris#221]
I've come across this when trying to add some radio streams to a play list, in Iris my only option seem to be to go the the Playlists section and search for it there.

The alternative musicbox_webclient has an additional menu entry called "Streams"  where the available streams are displayed without having to click on a playlist first. Additionally it provides a way to paste URLs into a form field and start playing them right away.

It would be nice to have something alike in Iris as well as it seems like a very convenient way to make a destinction.

**Comment by jaedb** [comment]
If you wish to add a track or stream URI, you can add this directly to the play queue (_Now Playing > Add URI_ at the top-right). Is this what you mean?

**Comment by tgurr** [comment]
Partly yes, but the main concern is that in Iris you've to do multiple steps to reach the streams you've a local m3u file for.

Musicbox:
* click streams
* click stream to play

![streams_musicbox](https://user-images.githubusercontent.com/414984/32029710-94100738-b9f6-11e7-86a6-17fc052ed7a4.png)

Iris:
* click playlists
* if spotify is configured and/or you've a bunch of playlists you may either first have to choose local as a filter or scroll through playlists or use the search function
* click on the playlist
* click stream to play

![streams_iris01](https://user-images.githubusercontent.com/414984/32029722-a20c3028-b9f6-11e7-8f6e-9acef08dc955.png)

![streams_iris02](https://user-images.githubusercontent.com/414984/32029725-a5718d08-b9f6-11e7-9032-00a3946f8418.png)

So having an additonal "Streams" menu entry like the musicbox webclient has would be helpful.

**Comment by tgurr** [comment]
Maybe the feature is somehow connected to the m3u mopidy plugin as musicbox is also able to display the stream name like configured in the m3u while Iris as seen in the screenshots is not (SWR3 vs SWR3-Livestream). Or Iris just cuts the stream name before the minus?

My radiostreams.m3u8

```
#EXTM3U
#EXTINF:-1,SWR3-Livestream
http://swr-swr3-live.cast.addradio.de/swr/swr3/live/mp3/128/stream.mp3
```
My mopidy.conf
```
[m3u]
playlists_dir = /var/lib/mopidy/playlists
```

Iris could maybe display the Stream menu item depending on wether mopidy's m3u plugin https://docs.mopidy.com/en/latest/ext/m3u is loaded or not.

**Comment by jaedb** [comment]
This second issue is due to Mopidy reporting "SWR3" as the track title. See _Settings > Debug > Mopidy_ and run a lookup call:

**Call**: `library.lookup`
**Data**: `{"uri":"http://swr-swr3-live.cast.addradio.de/swr/swr3/live/mp3/128/stream.mp3"}`
**Response**:
```
[
  {
    "comment": "http://www.swr3.de",
    "genre": "Pop Music",
    "__model__": "Track",
    "name": "SWR3",
    "uri": "http://swr-swr3-live.cast.addradio.de/swr/swr3/live/mp3/128/stream.mp3"
  }
]
```

**Comment by jaedb** [comment]
After a bit of investigation, it appears that the Musicbox "Streams" function is just using a playlist as a mechanism for storing your library of streams.

If this was sought-after functionality by other Iris users, I would approach this differently. A playlist is a series of tracks to be played; a library of streams doesn't really fit this model.

Building a _Streams_ library would look like:
- New Mopidy backend handler to store the library of streams
- Extension of Iris frontend to expose and manipulate this library (with CRUD actions)
- Addition of UI to present this interface to the user
So, you can see there's a bit of work involved!

**Comment by cellcortex** [comment]
+1 from me for this feature. Also happy to help/contribute.

**Comment by foxfabi** [comment]
The radio.de extension for mopidy could maybe serve as a basis

**Comment by warllo54** [comment]
I think this would be a great feature as well!

**Comment by Estefanop** [comment]
+1 for live streaming radio section

**Comment by jaedb** [comment]
I've had another thought on how this could be achieved without having to build too much specific functionality: Pinned Playlists.

This would allow users to pin any playlist from any source (ie Spotify, Mopidy, Tidal, etc) into the sidebar for quick access. This would also allow the _Add to playlist_ context menu to have these pinned playlists at the top of the list.

Then users could name these pinned playlists whatever they wish to reflect their use case (eg _Radio streams_).

Thoughts?

**Comment by sqrtroot** [comment]
Should we extend this functionality to be able to pin anything (songs, streams, playlists, albums, etc.)?

**Comment by jaedb** [comment]
@sqrtroot I don't think so, at least not to start with. The more assets that are pinned, the less usable 'Pinned' becomes.

**Comment by sqrtroot** [comment]
I agree with that, but isn't that up to the end user to manage?

**Comment by jaedb** [comment]
It also requires more of my personal time to develop. I would rather not invest my time in expanding feature scope without good reason. It can always be expanded later if the need and availability arise.

**Comment by jaedb** [comment]
Closing this issue as the original problem has been resolved.
