### ISSUE TITLE
[Feature request] Save to your music

### ISSUE THREAD

**Issue by robinvd** [jaedb/Iris#222]
I have not found a way in Iris to add a single song to 'Your music/Songs'. In the spotify web client in the right click context menu there is 'Save to your music'.

![](https://i.imgur.com/HAJhFHo.png)

![](https://i.imgur.com/vM85NBH.png)

Maybe to add to playlist menu could include 'your music/songs'

**Comment by jaedb** [comment]
Duplicate of #215
