### ISSUE TITLE
No Context menu with SoundCloud backend

### ISSUE THREAD

**Issue by en00x** [jaedb/Iris#223]
## Expected behavior
Context menu for SoundCloud
## Actual behavior
No context menu at all in any list. To play all i have to select each individually
## Steps to replicate
1. Use `Browse -> Soundcloud`
2. Open any tracklist

#### Operating systems affected
- [x] Windows:
- [ ] Mac: 
- [x] Linux: 
- [ ] iOS: 
- [x] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [x] Firefox: 
- [ ] Internet Explorer:
- [x] Opera: 
- [x] Other:

#### Screen sizes affected
- [x] Huge (ie desktop)
- [x] Large (ie laptop)
- [x] Medium (ie slim laptop/tablet)
- [x] Small (phone)

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [x] Yes, I have attached screenshots and/or screencast of the issue in action
Expected this behavior from `Browse -> Local Media` e.g.
![working](https://user-images.githubusercontent.com/13997715/32111782-d0a87144-bb3b-11e7-9cab-52b1cf218602.png)
And this is how it looks like
![notworking](https://user-images.githubusercontent.com/13997715/32111801-dc803b8c-bb3b-11e7-9c34-522b7e4de21b.png)

- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
Thanks for the thorough details.

Based on those screenshots, you are using a touch-capable device.

At this time, if you're using a touch device (this includes hybrid devices with both touch and mouse capability) then you will only have touch-based functionality (see #186). This is why you're unable to get a right-click context menu.

To confirm this is the case, can you please test using a different backend (or any other tracklist)? I suspect you'll find that this is not isolated to the Soundcloud backend.

**Comment by en00x** [comment]
Ah i'm sorry, context menu is misleading. Actually i'm missing the Play button for the list, like in the local backend in the first screenshot. The problem is the same on a none touch device, it's just easier to select all with shift and then press play over the context menu you mentioned.

**Comment by jaedb** [comment]
Ah I see what you're saying now.

The difference is that the first screenshot is an _Album_ view, whereas the second is a _Directory_ view. So the request would be to add a _Play_ button to the _Directory_ view?

**Comment by en00x** [comment]
Exactly. Is it possible or to much effort?

**Comment by jaedb** [comment]
The only concern I would have is that if one was to hit play on a really large list of tracks the server could struggle. Also imagine a list of radio stations - _Play all_ wouldn't make much sense as each track is endless so you wouldn't get past the first item.

That being said, anything is possible :-)

**Comment by en00x** [comment]
But couldn't happen that on a large Spotify Playlist too? And i hope users have the foresight what's going to happen playing all in a list of radio stations :D
Maybe show a warning on lists/playlists when you want to play all and the track count is exceeding a given limit?

**Comment by en00x** [comment]
Wow thanks! That was quick 👍 
It's working like a charm but it's missing in the mobile view. Hitting the three-dot-menu nothing happens. Tested on Android and several browsers in an desktop environment.
