### ISSUE TITLE
[Feature request] Play next in Shuffle mode

### ISSUE THREAD

**Issue by en00x** [jaedb/Iris#224]
First of all thanks for the great work, keep it up :+1: 

It would be nice if i could add any track over `Play next` and this one is going to be played next, also in shuffle mode. 
Is this possible to implement?

Regards

**Comment by jaedb** [comment]
Unfortunately not. When _Shuffle mode_ is enabled, there is no way for us to override the next track. This is part of the core MPD server, so we can't change that behavior.

**Comment by en00x** [comment]
Oh, too bad. But i was thinking something like that is the problem.
