### ISSUE TITLE
Selected tracks not flushed when deleted from queue

### ISSUE THREAD

**Issue by depyttr** [jaedb/Iris#230]
## Expected behavior
Menu button disappears, nothing is selected.

## Actual behavior
Menu button stays visible with track selected.

## Steps to replicate
1. Select track in queue
2. Tap blue menu button
3. Tap remove

#### Operating systems affected
- [x] Windows:
- [ ] Mac: 
- [x] Linux: 
- [ ] iOS: 
- [x] Android:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x] Huge (ie desktop)
- [x] Large (ie laptop)
- [x] Medium (ie slim laptop/tablet)
- [x] Small (phone)

## Additional details, debug data, logs, etc
This bug does not appear with small screen size on Mac with Chrome or Safari, but it has another bug (Menu button not showing).

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
Resolved in #226 by moving context trigger into list item.
