### ISSUE TITLE
Menu button not showing

### ISSUE THREAD

**Issue by depyttr** [jaedb/Iris#231]
## Expected behavior
Blue menu button appears.

## Actual behavior
Nothing
## Steps to replicate
1. Select any track.
2. ??

#### Operating systems affected
- [ ] Windows:
- [x] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome:
- [x] Safari: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [x] Small (phone)

## Additional details, debug data, logs, etc
This bug is not present on Android, but it has another bug regarding the menu button.

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
Can you please post a short video of this issue in action? I have not been able to replicate the issue.

**Comment by depyttr** [comment]
Here is the video, sorry it took so long.
[bug_screencap.m4v.zip](https://github.com/jaedb/Iris/files/1492079/bug_screencap.m4v.zip)

**Comment by jaedb** [comment]
Great, thanks for that - really not sure what was causing this.

The latest release changes how the context menus are triggered so this issue may be a thing of the past when you upgrade to 3.8. See [release notes](https://github.com/jaedb/Iris/releases/tag/3.8.0).

Have a crack at upgrading and please re-open this issue if it persists.
