### ISSUE TITLE
[Enhancement] Make data collection opt-out

### ISSUE THREAD

**Issue by renekliment** [jaedb/Iris#232]
Coming from #229 ...

It would be great if there were a config option to opt-out of the Google Analytics data collection. Of course users who do that cannot expect the same level of _user support_ if they encounter issues.

**Comment by tgurr** [comment]
I second that request, and in addition it would be nice to not only have that option on the gui but addtionally a flag somewhere in the code which could be used by distribution packagers to pre-configure the option as that would ease adoption of iris in distributions.

**Comment by jaedb** [comment]
Users can now opt to exclude personal data from Google Analytics collection. This is found under _Settings > Advanced_. This will mean that debugging assistance for those users will be limited, but Iris will otherwise function as normal.
