### ISSUE TITLE
"404 not found" after upgrade 3.8.1

### ISSUE THREAD

**Issue by Alkuimista** [jaedb/Iris#234]
After upgrading to 3.8.1, I can no longer get the iris to work. I receive the 404 error. Seconds before the upgrade it was working.
I upgraded because it informed me that the 3.8.1 version was available. 
I cant no longer see iris in mopidy web clients, but I double checked all the configs.

#### Operating systems affected
- [ ] Windows:
- [x] Mac: 
- [x] Linux: 
- [x] iOS: 
- [ ] Andriod:
- [x] Other:

#### Browsers affected
- [x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [x] Other: Safari

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
A few questions that may help uncover the issue:
1. How did you update to the latest version (ie command line? update button (beta)?)
2. Did you see any errors during upgrading?
3. Do you see any errors during restart of Mopidy?
4. Have you tried re-installing Iris?

**Comment by Alkuimista** [comment]
1 - I upgraded with command line "sudo pip install --upgrade Mopidy-Iris"
2- There were no errors
3- No errors on the startup of the mopidy
4- Yes, I re-installed iris a couple of times

As I already mentioned, iris no longer appears on the mopidy page as a client in 192.168.1.15:6680 (the ip of my pi), but in mopidy.conf all settings are there.
Mopidy is running as a service.
I always updated Iris this way with no problems.

Thanks in advanced, and congrats for this amazing project.

**Comment by Alkuimista** [comment]
When I run:
`sudo mopidyctl config`

I get this:

`[iris]
enabled = false  ; Extension disabled due to config errors.
country = en
locale = en_EN
spotify_authorization_url = https://jamesbarnsley.co.nz/auth_spotify.php
lastfm_authorization_url = https://jamesbarnsley.co.nz/auth_lastfm.php`

**Comment by jaedb** [comment]
Thanks - that indicates that there's something wrong with your `mopidy.conf`. Perhaps delete all `[iris]` configuration values (or comment them out with `#` at the start of each line) and try restarting.

**Comment by Alkuimista** [comment]
I removed everything about iris in mopidy.conf and it started working like a charm :)
Somehow it seems that the iris config lines in mopidy.conf are no longer needed? Because now my mopidy.conf has no information about iris, and it's working.

Thanks again,

All the best

**Comment by jaedb** [comment]
Glad to hear you're back up and running!

When installing plugins, you don't need to copy the config values into your local `mopidy.conf` file. You only need to do this when you're modifying the default values.

At a guess, your `mopidy.conf` included invalid Iris configuration values. You can see the values available to overwrite in the [installation guide](https://github.com/jaedb/Iris/wiki/Getting-started#configuration).
