### ISSUE TITLE
[Feature request] Disable volume at global configuration

### ISSUE THREAD

**Issue by cubabit** [jaedb/Iris#236]
## Expected behavior
I would like to use a global protected config to disable the volume controls so users of the Iris interface cannot change the volume

## Actual behavior
People use the volume control in Iris to turn down the volume and then turn up the speakers using the hardware controls, so we end up with loud music on the lowest volume setting in Iris.

**Comment by mczerski** [comment]
You can do it already in audio section.

**Comment by cubabit** [comment]
So it is, sorry. I am not familiar with mopidy at all. For those interested, the config is:

```
[audio]
mixer = none
```
