### ISSUE TITLE
Spotify integration broken

### ISSUE THREAD

**Issue by zachnedwich** [jaedb/Iris#237]
## Expected behavior
Spotify connects

## Actual behavior
Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at SpotifyAuthenticationFrame.js:28

## Steps to replicate
1. <mopidy host>/iris/#/settings
2. refresh token

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [X] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [X] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

## Additional details, debug data, logs, etc

Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at SpotifyAuthenticationFrame.js:28

https://jamesbarnsley.co.nz/auth_spotify.php?action=refresh&refresh_token=xxxx returns
 valid json
```
{
"access_token": "xxxxxx,
"token_type": "Bearer",
"expires_in": 3600,
"scope": "playlist-read-private playlist-read-collaborative ugc-image-upload user-follow-read playlist-modify-private user-read-email user-follow-modify user-library-read user-library-modify playlist-modify-public user-read-playback-state user-read-currently-playing user-top-read"
}
```

**Comment by jaedb** [comment]
I'm having trouble replicating this. What distro of Linux, and exact version of Chrome are you using? What version of Iris do you have installed?

**Comment by zachnedwich** [comment]
Hey mate,

Voidlinux, Chrome version is 61.0.3163.100. Seems to work correctly in Firefox 57.

I think the json error was something else, I'm getting this as well when I try and log-out and login from Spotify:

middleware.js:28 {type: "SPOTIFY_AUTHORIZATION_GRANTED", data: {…}}
middleware.js:28 {type: "SPOTIFY_FLUSH_LIBRARY"}
middleware.js:28 {type: "SPOTIFY_AUTHORIZATION_GRANTED", data: {…}}
middleware.js:28 {type: "SPOTIFY_FLUSH_LIBRARY"}
middleware.js:28 {type: "SPOTIFY_AUTHORIZATION_GRANTED", data: {…}}
OPTIONS https://api.spotify.com/v1/me net::ERR_BLOCKED_BY_CLIENT

Not sure if that helps.

**Comment by zachnedwich** [comment]
Turns out Privacy Badger chrome extension was blocking api.spotify.com, d'oh. Apologies for the goose chase.

**Comment by jaedb** [comment]
That makes heaps of sense. I was trying all manner of things to trace what would affect your browser, but couldn't replicate anything.

Glad you got it sorted.
