### ISSUE TITLE
[Feature Request] sort local:artist albums by date and local:album by track_no

### ISSUE THREAD

**Issue by dukrat** [jaedb/Iris#240]
Mostly a discussion.  In my opinion this is the correct way to sort things as the information isn't available in the UI.  

Can be done with:

```
diff --git a/src/js/services/mopidy/middleware.js b/src/js/services/mopidy/middleware.js
index 4093ba8..b9e84fb 100755
--- a/src/js/services/mopidy/middleware.js
+++ b/src/js/services/mopidy/middleware.js
@@ -1459,7 +1459,9 @@ const MopidyMiddleware = (function(){
                 instruct(socket, store, 'library.lookup', action.data )
                     .then(response => {
                         if (response.length <= 0) return
+                       response = response.sort(function(a,b){return a.track_no - b.track_no;});
                         var album = Object.assign(
                             {},
                             { images: [] },
@@ -1628,6 +1630,7 @@ const MopidyMiddleware = (function(){
                             }
                         }
                         if (albums){
+                            albums = albums.sort(function(a,b){return a.date - b.date;});
                             store.dispatch({
                                 type: 'ALBUMS_LOADED',
                                 albums: albums
```

**Comment by jaedb** [comment]
The best way to handle this would be to integrate sorting into the UI. 

The index of assets (`core.albums`, `core.artists`, etc) is an object, rather than an array so any sorting you apply before committing records to the index makes no difference to the order displayed.

**Comment by dukrat** [comment]
I totally agree it should be put into the UI long term.  

/iris/#/artist/local:artist and /iris/#/album/local:album are using the order returned from the library.lookup function which seems to be alphanumeric.  Sorting on that return certainly affects those two pages.

**Comment by jaedb** [comment]
Sorting an album's tracks by `track_no` is already the current logic. I believe this is handled by the backend provider.

Sorting an artist's albums is a different issue, and will create a confusing UX when albums are lazy-loaded (as is the case with Spotify). I agree though, it would make the albums grid a lot more use-friendly if you could define the sort order.
