### ISSUE TITLE
Where to disable "Checkbox-Mode"?

### ISSUE THREAD

**Issue by knowthelist** [jaedb/Iris#242]
Where or how can I disable this terrible "Checkbox-Mode" of lists? I don't want this in any resolution or screen size. I'v got this always on my Android 6.0.1 tablet. I need to play the track by clicking, not to select.
<img width="708" alt="checkbox-modus" src="https://user-images.githubusercontent.com/7604693/34111073-ed58a69c-e408-11e7-8267-2f0c835c5b09.png">

**Comment by jaedb** [comment]
@knowthelist I recommend you justify your non-constructive feedback. This is more likely to get a positive result.

For example, why do you find "Checkbox-Mode" so terrible?

**Comment by knowthelist** [comment]
Such a mode is used for editing. Add multiple songs to a list or remove some. But that should not be the default mode. Default should be to start music as easy as possible. I would expect to select a track by clicking on it and I would expect that the playlist starts at this point in playlist, song 3 or 4 or ... Just at the first click like in the official Spotify Webplayer. 
Iris ist the best Mopidy Frontend and almost perfect, but this behaviour is a show stopper for me.

**Comment by jaedb** [comment]
I think you'll find that it isn't a "mode", rather the touch zone for selecting tracks.

The biggest challenge is ensuring interaction works across touch and mouse devices (and more complicated again, hybrid devices as [previously discussed](https://github.com/jaedb/Iris/issues?utf8=%E2%9C%93&q=hybrid)). If you delve into the actual code behind this you will quickly appreciate how tricky this is (1,000+ lines of code just for these interactions).

These interactions are currently being reviewed, and will possibly address your concerns. While I have no intention to play tracks on click (this makes the UI feel overly sensitive), I am exploring removing the need for a touch select zone and inheriting similar functionality to click events (ie the whole track row is a select zone).

I hope this helps ease your frustration. I also hope you find enough value in Iris to justify donating towards the time spent enhancing this type of functionality and implementing user requests such as yours.
