### ISSUE TITLE
SearchResult for albums not shown

### ISSUE THREAD

**Issue by rawdlite** [jaedb/Iris#244]
Hi,

I am developing a Mopidy Backend called Bigbeet (https://github.com/rawdlite/mopidy-bigbeet)
This is pretty much like mopidy local sqlite except it uses beets (http://beets.readthedocs.io/en/latest/) to organize the local collection and provides a more extensive browsing tree.

Now when searching for albums i return this SearchResult:
'{"jsonrpc": "2.0", "id": 40, "result": [{"__model__": "SearchResult", "albums": [{"__model__": "Album", "name": "In the Beginning", "num_tracks": 8, "uri": "bigbeet:album:12:6730c904-1285-4257-b20c-f27b1b52b87a", "artists": [{"__model__": "Artist", "musicbrainz_id": "1e3c9033-7eb3-4543-af92-5e8c9b778318", "name": "14 Iced Bears"}], "date": "2001-08-01", "musicbrainz_id": "6730c904-1285-4257-b20c-f27b1b52b87a", "num_discs": 1}, ..... and so on

Yet no results are displayed in Iris.
The search for tracks works fine, so i assume only Track objects from the SearchResult get parsed. 
Would be great if Album and Artist objects in SearchResult got parsed as well.
 
BTW: This is really a great frontend and i included it in my mopidy docker container:
https://github.com/rawdlite/docker-mopidy.git (development branch)

## Expected behavior
Show Album and Artist objects returned in SearchResult

## Actual behavior
Only Tracks shown

## Steps to replicate
1. git clone  https://github.com/rawdlite/docker-mopidy.git
2. cd docker-mopidy && git checkout develop && docker build -t rawdlite/mopidy-dev .
3. docker run -d --name mopidy-dev --net host --device /dev/snd  -v ~/.config:/root/.config -v /data/music:/data/music rawdlite/mopidy-dev
4. Search for album in Iris

#### Operating systems affected
- [ x] Linux: 
- - Raspberry Pi - Ubuntu 16.04
-- Docker - Ubuntu 14.04
#### Browsers affected
- [x ] Chrome: 
- [x ] Safari: 

#### Screen sizes affected
- [ x] Large (ie laptop)

**Comment by jaedb** [comment]
No matter what your search context is, Mopidy will always return `Track` objects. It's then up to the user/frontend to digest this into the original search context. For example searching for _Moby_ as an artist in Mopidy will return all `Track` objects where `Track.Artists.Name` includes the string _Moby_.

So to achieve your initial issue (very thorough explanation too, thanks), I need to build more maturity around searching by the different search contexts (eg _Artist_, _Track_, _Album_) and then translating the `Track` responses into the appropriate objects. This will require quite a few daisy-chained server requests to get the full `Artist` or `Album` object.

Note _Playlist_ will not be included as this is only relevant for the built-in M3U backend.

**Comment by rawdlite** [comment]
Thanks for your quick response.

> No matter what your search context is, Mopidy will always return Track objects.

Not necessarily. It is actually up to the specific mopidy backend what objects it sends back.
Mopidy Local Sqlite only returns Tracks.
Mopidy Spotify returns Track, Album and Artist.
I opted for Bigbeet to only return Album objects in an album search context.
With a local collection of more than 35.000 tracks it seems pretty redundant and inefficient to return a huge set of Track objects when only the album information is needed. Sending Tracks for Album Information means about 20 times more data needs to be collected, send and parsed. This makes the frontend less responsive.

> I need to build more maturity around searching by the different search contexts (eg Artist, Track, Album) and then translating the Track responses into the appropriate objects.

Not at all. My proposal is you could check whether the SearchResult already contains Album and Artist objects and use these without daisy-chained server requests.
I think the Track vs. Album/Artist objects in SearchResult is a bit of a hen and egg situation.
Some backends only return tracks because some frontends only parse them and the otherway around.
This is not ideal me thinks.

Cheers.

**Comment by jaedb** [comment]
Ah I see what you're saying. It sounds like many backends don't bother to use the other containers (eg _Artists_, _Albums_) which creates the issue.

I agree that Iris should encourage backend developers to use these containers appropriately, rather than digesting `Tracks` results into the requested context. To display these container's contents in the appropriate view should be pretty straightforward.

The only thing missing is artwork. I assume you're using the standard Mopidy `Album` model, which contains artwork? As the Mopidy `Artist` object doesn't facilitate artwork, this will still need to rely on LastFM.

**Comment by rawdlite** [comment]
While i use the standard Mopidy Album model i did not bother with the artwork field.(yet)
What i do provide though is a musicbrainz id. This could be used to get artwork from the Cover Art Archive https://coverartarchive.org/

**Comment by jaedb** [comment]
Items in your local library that have been scanned will have had the artwork embedded into the tags or at least into the folder structure. Correct me if I'm wrong, but when an album is scanned and matched with an MBID, Beets is capable of fetching the artwork and embedding it into the release for you.

Then Mopidy/Bigbeet can provide the artwork in the `images` property. 

This is the preferred approach as it means Iris doesn't need to fetch artwork in different ways for every different backend provider. Instead it can rely on a standardised format (ie `Track.images`) provided by Mopidy/backend.

**Comment by rawdlite** [comment]
Beets provides Plugins to Fetch Art and to embed them in the files.
But that is not much use, is it?

The `images` property is AFAIK only part of the Album object and it only stores URIs. (not uuencoded images)
Also it is deprecated since version 1.2:( Use mopidy.core.LibraryController.get_images() instead.)
Anyway, i will have a look at the FetchArt Plugin and see whether i can get it to store the Art URI in a beets attribute.
Then i can send that URL as `Album.images` and/or via `LibraryController.get_images()`
Would that work for you?

**Comment by rawdlite** [comment]
The FetchArt Plugin is quite a beauty. It can check for Art in:
- CoverArtArchive,
- ITunesStore,
- AlbumArtOrg,
- Amazon,
- Wikipedia,
- GoogleImages,
- FanartTV,

it also checks for the size of the image and a lot more.
What is doesn't do is saving the URL it finds.

This needs only little extra code to store the URL in a flexible attribute art_url.
I also updated Bigbeet to now send a SearchResult like this.

Sent WebSocket message to 192.168.0.104: '{"jsonrpc": "2.0", "id": 13, "result": [{"__model__": "SearchResult", "albums": [{"__model__": "Album", "name": "(Who\'s Afraid Of?) The Art of Noise!", "num_tracks": 9, "uri": "bigbeet:album:217:87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", **"images": ["https://coverartarchive.org/release/87c96ced-d9b2-4b5b-a85f-6d117b9b6a97/front"]**, "artists": [{"__model__": "Artist", "musicbrainz_id": "be899560-1570-402e-9f95-3182898a8b70", "name": "Art of Noise"}], "date": "1984-01-01", "musicbrainz_id": "87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", "num_discs": 1}], "tracks": [{"album": {"__model__": "Album", "musicbrainz_id": "87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", "name": "(Who\'s Afraid Of?) The Art of Noise!", "num_tracks": 9}, "comment": "British; London (Songs-DB_Custom3)", "__model__": "Track", "name": "A Time for Fear (Who\'s Afraid)", "disc_no": 1, "uri": "bigbeet:track:1093:/data/music/music_data/beets/A/Art_of_Noise/1984_The_Art_of_Noise/01-01_-_Art_of_Noise_-_The_Art_of_Noise_-_A_Time_for_Fear_.flac", "date": "1984-01-01", "length": 284000, "last_modified": 1437718675000, "track_no": 1, "artists": [{"__model__": "Artist", "musicbrainz_id": "be899560-1570-402e-9f95-3182898a8b70", "name": "Art of Noise"}], "genre": "Electronic", "musicbrainz_id": "3c01c79f-c98a-4b40-8902-04db9baeef48", "bitrate": 731352}, {"album": {"__model__": "Album", "musicbrainz_id": "87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", "name": "(Who\'s Afraid Of?) The Art of Noise!", "num_tracks": 9}, "comment": "British; London (Songs-DB_Custom3)", "__model__": "Track", "name": "Beat Box (Diversion One)", "disc_no": 1, "uri": "bigbeet:track:1094:/data/music/music_data/beets/A/Art_of_Noise/1984_The_Art_of_Noise/01-02_-_Art_of_Noise_-_The_Art_of_Noise_-_Beat_Box_.flac", "date": "1984-01-01", "length": 512000, "last_modified": 1437718675000, "track_no": 2, "artists": [{"__model__": "Artist", "musicbrainz_id": "be899560-1570-402e-9f95-3182898a8b70", "name": "Art of Noise"}], "genre": "Electronic", "musicbrainz_id": "a8c3588f-9aaf-4512-91dc-02f11d2b512e", "bitrate": 766774}, {"album": {"__model__": "Album", "musicbrainz_id": "87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", "name": "(Who\'s Afraid Of?) The Art of Noise!", "num_tracks": 9}, "comment": "British; London (Songs-DB_Custom3)", "__model__": "Track", "name": "Snapshot", "disc_no": 1, "uri": "bigbeet:track:1095:/data/music/music_data/beets/A/Art_of_Noise/1984_The_Art_of_Noise/01-03_-_Art_of_Noise_-_The_Art_of_Noise_-_Snapshot.flac", "date": "1984-01-01", "length": 62000, "last_modified": 1437718676000, "track_no": 3, "artists": [{"__model__": "Artist", "musicbrainz_id": "be899560-1570-402e-9f95-3182898a8b70", "name": "Art of Noise"}], "genre": "Electronic", "musicbrainz_id": "bcf42ff8-3e20-439b-87b5-97632dbb94c3", "bitrate": 751197}, {"album": {"__model__": "Album", "musicbrainz_id": "87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", "name": "(Who\'s Afraid Of?) The Art of Noise!", "num_tracks": 9}, "comment": "British; London (Songs-DB_Custom3)", "__model__": "Track", "name": "Close (to the Edit)", "disc_no": 1, "uri": "bigbeet:track:1096:/data/music/music_data/beets/A/Art_of_Noise/1984_The_Art_of_Noise/01-04_-_Art_of_Noise_-_The_Art_of_Noise_-_Close_.flac", "date": "1984-01-01", "length": 336000, "last_modified": 1437718675000, "track_no": 4, "artists": [{"__model__": "Artist", "musicbrainz_id": "be899560-1570-402e-9f95-3182898a8b70", "name": "Art of Noise"}], "genre": "Electronic", "musicbrainz_id": "71f97f6d-fe53-4594-b465-c9d7e6e72f8d", "bitrate": 824300}, {"album": {"__model__": "Album", "musicbrainz_id": "87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", "name": "(Who\'s Afraid Of?) The Art of Noise!", "num_tracks": 9}, "comment": "British; London (Songs-DB_Custom3)", "__model__": "Track", "name": "Who\'s Afraid (of the Art of Noise)", "disc_no": 1, "uri": "bigbeet:track:1097:/data/music/music_data/beets/A/Art_of_Noise/1984_The_Art_of_Noise/01-05_-_Art_of_Noise_-_The_Art_of_Noise_-_Whos_Afraid_.flac", "date": "1984-01-01", "length": 260000, "last_modified": 1437718675000, "track_no": 5, "artists": [{"__model__": "Artist", "musicbrainz_id": "be899560-1570-402e-9f95-3182898a8b70", "name": "Art of Noise"}], "genre": "Electronic", "musicbrainz_id": "091fe005-cf76-4079-98a7-e43b862d445c", "bitrate": 860219}, {"album": {"__model__": "Album", "musicbrainz_id": "87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", "name": "(Who\'s Afraid Of?) The Art of Noise!", "num_tracks": 9}, "comment": "British; London (Songs-DB_Custom3)", "__model__": "Track", "name": "Moments in Love", "disc_no": 1, "uri": "bigbeet:track:1098:/data/music/music_data/beets/A/Art_of_Noise/1984_The_Art_of_Noise/01-06_-_Art_of_Noise_-_The_Art_of_Noise_-_Moments_in_Love.flac", "date": "1984-01-01", "length": 615000, "last_modified": 1437718675000, "track_no": 6, "artists": [{"__model__": "Artist", "musicbrainz_id": "be899560-1570-402e-9f95-3182898a8b70", "name": "Art of Noise"}], "genre": "Electronic", "musicbrainz_id": "cfab1e7c-62c8-4167-b040-84ceca7df5b1", "bitrate": 824610}, {"album": {"__model__": "Album", "musicbrainz_id": "87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", "name": "(Who\'s Afraid Of?) The Art of Noise!", "num_tracks": 9}, "comment": "British; London (Songs-DB_Custom3)", "__model__": "Track", "name": "Momento", "disc_no": 1, "uri": "bigbeet:track:1099:/data/music/music_data/beets/A/Art_of_Noise/1984_The_Art_of_Noise/01-07_-_Art_of_Noise_-_The_Art_of_Noise_-_Momento.flac", "date": "1984-01-01", "length": 131000, "last_modified": 1437718676000, "track_no": 7, "artists": [{"__model__": "Artist", "musicbrainz_id": "be899560-1570-402e-9f95-3182898a8b70", "name": "Art of Noise"}], "genre": "Electronic", "musicbrainz_id": "88c787f5-0dc5-4b18-bedb-6f12951b1925", "bitrate": 614660}, {"album": {"__model__": "Album", "musicbrainz_id": "87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", "name": "(Who\'s Afraid Of?) The Art of Noise!", "num_tracks": 9}, "comment": "British; London (Songs-DB_Custom3)", "__model__": "Track", "name": "How to Kill", "disc_no": 1, "uri": "bigbeet:track:1100:/data/music/music_data/beets/A/Art_of_Noise/1984_The_Art_of_Noise/01-08_-_Art_of_Noise_-_The_Art_of_Noise_-_How_to_Kill.flac", "date": "1984-01-01", "length": 163000, "last_modified": 1437718675000, "track_no": 8, "artists": [{"__model__": "Artist", "musicbrainz_id": "be899560-1570-402e-9f95-3182898a8b70", "name": "Art of Noise"}], "genre": "Electronic", "musicbrainz_id": "b0febd20-0853-49c8-867f-a4e71a615d87", "bitrate": 642300}, {"album": {"__model__": "Album", "musicbrainz_id": "87c96ced-d9b2-4b5b-a85f-6d117b9b6a97", "name": "(Who\'s Afraid Of?) The Art of Noise!", "num_tracks": 9}, "comment": "British; London (Songs-DB_Custom3)", "__model__": "Track", "name": "Realization", "disc_no": 1, "uri": "bigbeet:track:1101:/data/music/music_data/beets/A/Art_of_Noise/1984_The_Art_of_Noise/01-09_-_Art_of_Noise_-_The_Art_of_Noise_-_Realization.flac", "date": "1984-01-01", "length": 105000, "last_modified": 1437718675000, "track_no": 9, "artists": [{"__model__": "Artist", "musicbrainz_id": "be899560-1570-402e-9f95-3182898a8b70", "name": "Art of Noise"}], "genre": "Electronic", "musicbrainz_id": "cb3fcf14-4104-4e1f-860f-fb119be5f528", "bitrate": 836436}], "uri": "bigbeet:search?album=Art%20of%20Noise"}]}'
