### ISSUE TITLE
Please mention analytics on the frontpage

### ISSUE THREAD

**Issue by gerroon** [jaedb/Iris#247]
Hi

I started using this but I had no idea that there was analytics implemented in it. I found out by chance. If I knew that this app has analytics implemented in it I would have never installed it on my server.

Please be honest and at least mention this "minor" feature on the front page. I am sure you just use it to improve the app but watchign what I do or what I listen is plain creepy.

**Comment by StarPicard** [comment]
+1

**Comment by StarPicard** [comment]
Isn't it possible to include a switch in the mopidy config file, to fully disable analytics?

**Comment by herrwusel** [comment]
Holy... thanks for the information @gerroon.

**Comment by jaedb** [comment]
The use of Analytics is clearly stated both in-app (under Settings) and in the documentation in GitHub.
