### ISSUE TITLE
This page isn’t working after 10 or 20 minutes

### ISSUE THREAD

**Issue by wt9bind** [jaedb/Iris#249]
Hi,
I am running Iris on a RPI 3b and love it. What is weird is that the Pi boots, everything is working great, then after say 10 or 20 minutes, I reload the page and get:
This page isn’t working
192.168.1.195 didn’t send any data.
ERR_EMPTY_RESPONSE

I have checked the mopidy.conf and it looks ok:
[http]
enabled = true
hostname = ::
port = 6680
#static_dir =
#zeroconf = Mopidy HTTP server on $hostname

If I reboot the Pi, I get Iris back for a little while until it stops again.

Thanks for any help.

**Comment by mczerski** [comment]
Did You check that if that happens everything other in the pi is working ? is mopidy still alive ? Did you check the mopidy logs ?

**Comment by wt9bind** [comment]
Pi is still responding, Mopidy is still playing. Just the web page isn't.
Can you please advise the location of the log file? Thanks.

**Comment by mczerski** [comment]
I assume You are running mopidy as a system service ? then the logs are in /var/log/mopidy/mopidy.log. You may need to set the log level in /etc/mopidy/logging.conf to INFO or even DEBUG.

**Comment by mczerski** [comment]
It will be helpful also to install other web interface (e.g. moped) to check if the problem is only with iris or also other web interfaces.

**Comment by wt9bind** [comment]
Fantastic! Thank you for your help, I will troubleshoot this tomorrow.

Thanks once again.

**Comment by jaedb** [comment]
@wt9bind how did you get on? Is the issue isolated to Iris?

**Comment by wt9bind** [comment]
Hi, I'm far too embarrassed to comment on the issue... It had absolutely
nothing to do with iris or the pi.

It errr was an IP address conflict with a cctv camera.

**Comment by jaedb** [comment]
Hehe no worries. Glad you managed to get things running as expected :-)
