### ISSUE TITLE
Feature Request: Play Icecast2 Stream support

### ISSUE THREAD

**Issue by gbuisson** [jaedb/Iris#251]
Congrats for this amazing frontend, I've been toying with it since yesterday I find it very creative and amazing. 

One low hanging fruit would be to add the ability to play an Icecast2 stream from the frontend app.

When you run mopidy from a server, there's no audio output, anyway the server is located on some data center, so you have to configure mopidy to push the audio to an Icecast2 mountpoint.

This mountpoint is nothing more than a `.ogg` or `.mp3` file available at a given url endlessly building, aka a stream.

The issue is that you need 2 apps to control/play mopidy/Iris (a browser and another tab or an audio player to play the stream) else you control mopidy but you get no audio feedback, where if Iris could also play the stream, everything would happen on a single tab.

One could integrate that feature adding a dedicated configuration setting (the stream URL). and maybe an autoplay boolean.
if one is set and autoplay is done, then Iris would attempt to play the file located at the specified URL.

**Comment by jaedb** [comment]
I think this is a great idea, and *should* be relatively straightforward. In theory we can have a hidden HTML5 audio player that can be activated when:
1. Icecast2 is installed and enabled
2. Checkbox *Stream to this browser* is selected

One thing that would be worth considering is the other streaming providers currently in discussion (#248). I would prefer to pick the most popular one (and with the most active development) to integrate with to avoid maintenance headaches going forward.

**Comment by jaedb** [comment]
Deployed to production in 3.12.1.

I'd still like to explore a more mature option to prevent buffering and latentency issues. I'll keep an eye out for other ways to achieve this, but it's sorted for now :-)
