### ISSUE TITLE
Upgrade to latest version results in '404 not found' query

### ISSUE THREAD

**Issue by Suz2905** [jaedb/Iris#252]
I've just used 'sudo pip install --upgrade Mopidy-Iris' to upgrade to 3.12.1 
I then restarted mopidy, opened Iris, went to settings as I wasn't signed in, signed in to Spotify and ticked the boxes for personal analytics and other box next to it. 
Clicked to go to Discover and nothing.
Rebooted, tried again and got 404 not found.
Ran 'sudo pip install --upgrade Mopidy-Iris' again still same result.
Going to the default Mopidy page (http://192.168.0.10:6680/mopidy/) it's not listed as available web clients either.
Upgraded loads of time before with no problem - any idea what I've done wrong this time?

## Steps to replicate
1.
2.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ ] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [ ] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaredledvina** [comment]
I believe I hit the same thing, noticed this in the logs:
```
INFO     Starting Mopidy 2.1.0
ERROR    Failed to load extension iris: EOL while scanning string literal (__init__.py, line 16)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/ext.py", line 202, in load_extensions
    extension_class = entry_point.load(require=False)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/__init__.py", line 16
    __version__ = '3.12.2
```

I think the only reason your interface partially worked as that it was cached. 
Locally, I edited `/usr/local/lib/python2.7/dist-packages/mopidy_iris/__init__.py` and changed Line's 16/17 from:
```
__version__ = '3.12.2
'^M
```

to 
```
__version__ = '3.12.2'
```

I think the issue is just a weird Windows newline character, after editing that file and restarting it worked for me.

**Comment by tatoosh** [comment]
Same here:

```
ERROR    Failed to load extension iris: EOL while scanning string literal (__init__.py, line 16)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/ext.py", line 202, in load_extensions
    extension_class = entry_point.load(require=False)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/__init__.py", line 16
    __version__ = '3.12.2
                        ^
SyntaxError: EOL while scanning string literal
```

**Comment by Suz2905** [comment]
Thanks, that sorted it out!

**Comment by jaedb** [comment]
@jaredledvina Thanks for tracing that! It turns out it's an issue with the build scripts not stripping out new lines from the `VERSION.md` file. Editing via command line seem to add a new line at the end of the file. Go figure!

I've implemented a patch to prevent this from happening next time, and pushed to 3.12.3.
