### ISSUE TITLE
[Feature Request] Toggle mute HTTP stream

### ISSUE THREAD

**Issue by Draesia** [jaedb/Iris#254]
I love the new 'Stream audio to this browser' function in 3.12.3, however using this option to toggle the playback takes time to take effect and load the stream and additionally it requires going into the 'Settings' menu each time.

It would be nice if there was a mute button that was displayed (by current control buttons) when HTTP streaming is enabled.

**Comment by jaedb** [comment]
Released in 3.12.4. You can now toggle your stream in the player bar (see streaming icon, when streaming enabled under settings).
