### ISSUE TITLE
Websocket connection error when running as service (Raspbian)

### ISSUE THREAD

**Issue by patrick-glover** [jaedb/Iris#257]
## Expected behavior
I usually start mopidy from SSH as the user pi, and never had any issues playing songs from my spotify. When I run as a service, with all the same config files, I should be able to view and play songs.

## Actual behavior
When starting mopidy as a service, I access the ip:port/iris and see a normal front end. All my playlists are present, and I can view/search for songs. When I try and play anything from Spotify, I get a "WebSocket connection refused", I'm signed out of Spotify, and then the rest of the spotify content won't load through Iris.

## Steps to replicate
1. Run mopidy as service on Raspbian
2. Attempt to play song/playlist from Spotify

#### Operating systems affected

Raspbian Stretch

#### Browsers affected

Chrome

## Additional details, debug data, logs, etc
From the Chrome console:

WebSocket connection to 'ws://10.0.0.96:6680/iris/ws/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

[Chrome Console: 10.0.0.96-1518818418244.txt](https://github.com/jaedb/Iris/files/1732952/10.0.0.96-1518818418244.txt)

## Before you submit
- [ X] Yes, I have tested this issue thoroughly
- [ X] Yes, I have attached screenshots and/or screencast of the issue in action
- [ X] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
Thanks for the thorough details. 

What is your method of installing Mopidy as a service? Given you cannot connect to the Mopidy websocket, the issue sounds like it is to do with Mopidy server rather than Iris (which is just the frontend).

**Comment by jaedb** [comment]
Content (album art, tracks, etc) for Spotify material is loaded using the Spotify HTTP API. So it doesn't need Mopidy to fetch this data. The fact you can't play any tracks confirms that it's an issue with your Mopidy configuration, rather than Iris.

You'll need to open a ticket on the [Mopidy repository](https://github.com/mopidy/mopidy/issues).

**Comment by jindrahelcl** [comment]
Hi @patrick-glover, I have the same issue. Did you solve this? Could you provide a reference to the mopidy repo issue (if there is one)? Thanks

**Comment by 5AMsan** [comment]
This can be issued from using 'SSL' without proper certificate on Settings page.
![image](https://user-images.githubusercontent.com/3309793/42167814-73402596-7e0f-11e8-86e8-89134a223186.png)
