### ISSUE TITLE
[Feature Request] Local artist artwork for "My Artists" view

### ISSUE THREAD

**Issue by domsch1988** [jaedb/Iris#258]
## Expected behavior
Artist images should load on first entering the section

## Actual behavior
Images are load when an Artist is selected for the first time. After that, in the overview, the image is really low resolution
![screenshot_20180217_175416](https://user-images.githubusercontent.com/1961154/36343365-9e7044e4-140b-11e8-8d38-d6faca885306.png)

#### Operating systems affected
Antergos Linux
mopidy 2.1.0
mopidy-iris
mopidy-spotify
mopidy-spotify-web
mopidy-local-sqlite
mopidy-local-images

#### Browsers affected
Tested Firefox

#### Screen sizes affected
Tested 1920 and 2560 Dektop

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [x] Yes, I have attached screenshots and/or screencast of the issue in action
- [x] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
This is a consequence of Mopidy-Images not storing artist artwork (Spotify artists are not subjected to this issue). As a fix (to the artist view) I fetch artist artwork from LastFM, which is then available to the grid view.

For particularly large libraries, users would hit the LastFM API limits very quickly if Iris were to fetch all artists in one go.

I agree that it would be nice to have all artwork come through. The next step is to see if this is on the road map for the Mopidy-Images developers, or if this will need to be handled by Iris (and LastFM).

**Comment by domsch1988** [comment]
Thanks, i appreciate the explanation!
Can i store artist images locally somewhere to have them preload from a folder or such and have them in higher resolution (closer to the album artwork)?

**Comment by jaedb** [comment]
The resolution of artwork is a problem with LastFM. It's super frustrating that their API doesn't provide images that are as high-resolution as their own web interface. To the point where I'm considering an alternative artwork/info provider.

**Comment by jaedb** [comment]
Resolved by batching LastFM requests on render of each album tile. Released at `3.13.1`.

**Comment by domsch1988** [comment]
Man this was fast. Just upgraded and it's working beautifully! Thanky you so much.

**Comment by tmuellerchen** [comment]
Is there a way to kick the artist image download by command line?
I have a very large local MP3 base (2,5TB) and the most artist do not have any picture right now. 
when I click on artist, pictures are loaded (and I think then it is saved locally?)
