### ISSUE TITLE
Not showing Spotify artwork in My Playlists (non-authorized)

### ISSUE THREAD

**Issue by bargru** [jaedb/Iris#26]
The playlist view didn't shows the covers of playlists.

**Comment by jaedb** [comment]
I'm not sure what you're saying here. That images aren't showing? I need more information to identify what the issue is. For example, is a particular playlist affected? Local playlists vs Spotify playlists? etc...

**Comment by bargru** [comment]
![grafik](https://cloud.githubusercontent.com/assets/13362393/21805203/429f3046-d733-11e6-89b7-280adcaae780.png)

The left playlist is a local one and has not an cover. The right one is a spotify playlist witch has a cover.
When I click the spotify playlist the content of the playlist is shown with the cover.

![grafik](https://cloud.githubusercontent.com/assets/13362393/21805370/226e1df4-d734-11e6-92a1-4d00f4c32188.png)

In playlist view the images are linked to <div class="image" style="background-image: url(&quot;undefined&quot;);"></div>

**Comment by henkkah** [comment]
I also have this problem. This is what Chrome's console says:
`GET http://music.local/iris/undefined 404 (Not Found)        DOMLazyTree.js:64`

**Comment by jaedb** [comment]
Resolved in v2.11.2
