### ISSUE TITLE
Clearing 'now playing' queue seems broken on recent releases

### ISSUE THREAD

**Issue by grgcnnr** [jaedb/Iris#262]
I'm seeing this on two separate instances across a number of devices /os's ranging from v3.12.1 to 3.14.2 

## Expected behavior
Clearing the now playing queue should remove all queued tracks from the now playing section
## Actual behavior
Nothing appears to happen
## Steps to replicate
1. Click clear on now playing page or play an album with Clear tracklist on play of URI(s) setting enabled
2. Observe play queue still contains old songs

**Comment by en00x** [comment]
+1

**Comment by jaedb** [comment]
Resolved at `3.15.0`
