### ISSUE TITLE
[Feature Request] Remember scroll position on history back

### ISSUE THREAD

**Issue by JustinHop** [jaedb/Iris#263]
## Expected behavior
When browsing any page that has a list, like now playing, or a search, or playlist, when you click to get more information about anything and you navigate to another page with the info, you expect when hitting back to return to where you were on that page. 

## Actual behavior
On back, you are brought to the top of the page, and if it lazy loaded a bunch of content, you must load it again. 

## Steps to replicate
1. Click a link on a page after scrolling down
2. Hit back in your browser

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ x] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ x] Huge (ie desktop)
- [ x] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [x ] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

If you need any more information, let me know.

**Comment by jaedb** [comment]
Also worth reading: https://reacttraining.com/react-router/web/guides/scroll-restoration

**Comment by jupe76** [comment]
I'd like to second that feature request.
I'm using a big local library and it would be very helpful to get back to the entry in a list from where you have gone deeper.

**Comment by jaedb** [comment]
The tricky part is handling lazy-loaded pages as these make the page dynamic in height. I think we'll need to record each page's state (ie how far we had lazy-loaded) _before_ any page navigation events. My only concern with this is if it introduces a navigation lag.

**Comment by jupe76** [comment]
Thank you very much for implementing this feature. It gives me a totally new view on my around 1400 local albums. Working like a charm, no performance issues so far.
