### ISSUE TITLE
Nginx reversed proxy

### ISSUE THREAD

**Issue by leScepter** [jaedb/Iris#264]
I know this has been asked but I can't get it to work. I was trying to make my ip to redirect directly to Iris but it loads blank page with an error: `http://192.168.1.58/iris/app.min.js?v=1519931300 net::ERR_ABORTED`

Here's my server block:

    location / {
        proxy_pass  http://localhost:6680/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        rewrite /mopidy/(.*) /mopidy/$1 break;
        rewrite /(.*) /iris/$1 break;
        proxy_redirect off;
    }

Thank you.

**Comment by jaedb** [comment]
Duplicate post. Please see @Informatic's post on https://github.com/jaedb/Iris/issues/260#issuecomment-373878067 as this likely to answer your question.
