### ISSUE TITLE
UI Not Updating after action

### ISSUE THREAD

**Issue by ldimitroff** [jaedb/Iris#265]
## Expected behavior
Start playing playlist/album/radio, enable/disable consume or shuffle, 

## Actual behavior
"now playing" tab not displaying the current song
Clicking on consume or shuffle is not updating the button, only refreshing the web

## Steps to replicate
1. Start playing song
2. Click Shuffle

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [x] Other: Electron

#### Screen sizes affected
- [x] Huge (ie desktop)
- [x] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by mikos** [comment]
I'm experiencing the same, seeing a lot of this in the output when running mopidy in the foreground:

```
ERROR    WebSocket request error:
```

**Comment by aeux** [comment]
Reverting _tornado_ from _5.0_ to _4.5.3_ seems to fix this issue for me.

**Comment by mikos** [comment]
@aeux This has fixed the issue for me too.

**Comment by ldimitroff** [comment]
Any help on how to do this?

Thanks

**Comment by mikos** [comment]
For anyone else, here's what I did:

```
> pip2.7 uninstall tornado
> pip2.7 install tornado==4.5.3
```

**Comment by jaedb** [comment]
The latest release (`3.15.0`) limits tornado to below 5.0 to resolve this.

Mopidy needs to be upgraded to Python3 in order to reliably support Tornado 5.0+. This appears to be a work in progress (see [open ticket](https://github.com/mopidy/mopidy/issues/779)), but looks to be a while off.
