### ISSUE TITLE
[Feature Request] Separate Albums from Singles and Compilations in Artist View 

### ISSUE THREAD

**Issue by fbrcc** [jaedb/Iris#269]
Currently, on the Artist Detail view, there is an "Albums" section that encompasses Full Length Albums, Singles/EPs and Compilations the artist appears on. It would be nice to separate this into three distinct sections. I'm not sure if the spotify API gives this information, if I can give a hand please let me know :)

Thanks!

**Comment by jaedb** [comment]
Could be handled with another drop-down beside _Sort_ to filter by these arguments. Spotify does differentiate between albums, singles, etc but it's rather basic.
