### ISSUE TITLE
Clicking "back" button in player does not play last song

### ISSUE THREAD

**Issue by acochran50** [jaedb/Iris#271]
## Expected behavior

Clicking back/last track button should play the previous track. 

## Actual behavior

Animation pops up (with the "last track" symbol) but nothing actually happens.

## Steps to replicate
1. Use `ctrl + back arrow` or
2. Click back button in player

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [x] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [x] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
Do you happen to have either consume or random modes enabled?
