### ISSUE TITLE
Scrolling over snapclient list spams server with volume change requests

### ISSUE THREAD

**Issue by Suz2905** [jaedb/Iris#272]
## Expected behavior
When rebooting a snapclient the stream to other clients should remain constant
## Actual behavior
When rebooting a snapclient the stream stops to all clients, numerous red messages appear on Webui stating 'can't connect to snapcast'. Sound stops to all clients, however it looks as though the music is still playing (the progress bar in webui still moves) after a few minutes sound comes back on.
## Steps to replicate
1. Stop or reboot a connected snapclient.
2.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [x ] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
This sounds like an issue with Snapcast, rather than Iris. I would recommend opening the issue on the Snapcast repository instead.

**Comment by Suz2905** [comment]
No, I think it's related to the Snapcast part of Iris as I haven't had a similar problem over the past 18 months of using snapcast.
Since stopping using Iris snapcast the problem has once again gone away.
Since opening this post I think the reasons may not be as I first thought.
I have a feeling it's connected to the way Iris handles the scroll wheel on the mouse, if you are using the scroll wheel to scroll through the list of snapcast clients, it can sometimes, inadvertently trigger multiple volume increases, each notch on the scroll is another increase in volume. It's easy to run up 30 increases before you realise what is happening, then multiple message flash up and the system grinds to a halt. 
I'll leave it with you, happy to work with you to try and find a solution, but not too bothered if you don't feel it's worth working on.

**Comment by jaedb** [comment]
Ah that makes more sense to me. I guess we must be hitting a server load limit with the quantity of volume control changes. Can you please describe the exact process I can follow to replicate the issue? Make sure you include specifics, like:
- version of snapserver
- version of snapclient
- number of clients
- etc

**Comment by Suz2905** [comment]
As you'll see i'm using Hassbian, however if you would like me to load Snapserver on a Jessie or Stretch system let me know.

Using Mopidy Iris 3.16.2
Snapserver 13.0
Snapclient 13.0
Running on a Rpi 3 but using [Hassbian](https://www.home-assistant.io/docs/installation/hassbian/)
Same RPI is running Mopidy, Home Assistant and Snapserver & Client.
4 other Snapclients, 2 x Pi0 (Wifi) 1 x Rpi 2 (Cable) 1 x Orange Pi 1 (Cable) All these run Mopidy and a Snapclient either on Jessie or Stretch lite.
Wait 5 mins for everything to load properly, start to play using Iris, click with mouse to change volume on individual clients seems fine. Using mouse scroll wheel to change volume works, but if you dodge around trying to change volume on each client quickly - it breaks down after a few changes.
Get messages 'Pusher can't connect' 'Could not load connections' 'Failed to receive Snapcast response'

Also this message 
Message from syslogd@hassbian at Apr 17 21:47:05 ...
 snapserver[544]: ControlSession stop

Broadcast message from systemd-journald@hassbian (Tue 2018-04-17 21:47:05 UTC):

snapserver[544]: ControlSession stop
 
This is Mopidy status
sudo systemctl status mopidy
● mopidy.service - Mopidy music server
   Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-04-17 21:43:31 UTC; 16min ago
  Process: 536 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 527 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
 Main PID: 540 (mopidy)
   CGroup: /system.slice/mopidy.service
           └─540 /usr/bin/python /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Apr 17 21:59:43 hassbian mopidy[540]: ERROR    Iris failed to receive Snapcast response: timed out
Apr 17 21:59:43 hassbian mopidy[540]: ERROR    Uncaught exception in /iris/ws/
Apr 17 21:59:43 hassbian mopidy[540]: Traceback (most recent call last):
Apr 17 21:59:43 hassbian mopidy[540]:   File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 494, in _run_callback
Apr 17 21:59:43 hassbian mopidy[540]:     result = callback(*args, **kwargs)
Apr 17 21:59:43 hassbian mopidy[540]:   File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/handlers.py", line 92, in on_message
Apr 17 21:59:43 hassbian mopidy[540]:     getattr(mem.iris, message['method'])(data=params, callback=lambda response, error=False: self.handle_result(id=id, method=message[
Apr 17 21:59:43 hassbian mopidy[540]:   File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/core.py", line 169, in snapcast_instruct
Apr 17 21:59:43 hassbian mopidy[540]:     if not len(response):
Apr 17 21:59:43 hassbian mopidy[540]: UnboundLocalError: local variable 'response' referenced before assignment

 Snapserver Status
pi@hassbian:~ $ sudo systemctl status snapserver
● snapserver.service - Snapcast server
   Loaded: loaded (/lib/systemd/system/snapserver.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-04-17 21:43:31 UTC; 18min ago
  Process: 521 ExecStart=/usr/bin/snapserver -d $USER_OPTS $SNAPSERVER_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 544 (snapserver)
   CGroup: /system.slice/snapserver.service
           └─544 /usr/bin/snapserver -d

Apr 17 22:01:07 hassbian snapserver[544]: sion::stop
Apr 17 22:01:07 hassbian snapserver[544]: op
                                          Error in socket shutdown:
Apr 17 22:01:07 hassbian snapserver[544]:
Apr 17 22:01:07 hassbian snapserver[544]:
Apr 17 22:01:07 hassbian snapserver[544]: ed
                                          onMessageReceived: {"params": {}, "jsonrpc": "2.0", "id": "qlcssjbqsnub", "method": "Server.Get
Apr 17 22:01:07 hassbian snapserver[544]: ControlSession::stop
Apr 17 22:01:07 hassbian snapserver[544]: ssion stopped
Apr 17 22:01:07 hassbian snapserver[544]:
Apr 17 22:01:08 hassbian snapserver[544]: Exception in ControlSession::reader(): read_until: End of file
Apr 17 22:01:27 hassbian snapserver[544]: Session inactive. Removing
