### ISSUE TITLE
pip install and tornado<5.0,>=3.2

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#275]
## Expected behavior
running "pip install -U mopidy mopidy-iris" should install tornado dependency in version between 3.2 and 5.0

## Actual behavior
running "pip install -U mopidy mopidy-iris" installs tornado dependency in latest available version

## Steps to replicate
1. run "pip install -U mopidy mopidy-iris"
2.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ x] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ ] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Additional details, debug data, logs, etc
running pip install -U mopidy mopidy-iris gives this output:
Collecting tornado>=3.2 (from Mopidy===2.1.0)
  Downloading tornado-5.0.2.tar.gz (506kB)
running pip install -U mopidy-iris gives this:
Collecting tornado<5.0,>=3.2 (from Mopidy-Iris)
  Downloading tornado-4.5.3.tar.gz (484kB)

## Before you submit
- [ x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ x] Yes, I have included any relevant debug data and error logs

**Comment by IVData** [comment]
Having the same issue here. Results in tornado 5.0.2 being installed, and Iris being disabled as it requires <5.0

**Comment by jokerigno** [comment]
I encountered the same issue.

I uninstalled tornado with pip uninstall tornado and then run pip install tornado==4.5.3. 

VOILA!

**Comment by mczerski** [comment]
@jaedb mopidy requirement for tornado <5 was added just 17 days ago. I don't have much knowledge about pip so I cannot help much :( Maybe using the newest version of mopidy which also requires tornado < 5 it will be no longer a problem ?

**Comment by tgurr** [comment]
https://github.com/mopidy/mopidy/commit/86e5e7d34729e0cb644e46d68af5c18348c94585 states mopidy *should* also work with tornado > 5. It it the same reasoning for iris or are there any technical reasons for not supporting tornado >= 5?

**Comment by jaedb** [comment]
@tgurr Tornado 5 overhauls how websockets work, and it renders Iris unstable. Some functionality works, but websocket-related requests break. 

I don't intend to work on upgrading Iris to support Tornado 5 yet. I understand work is under way to upgrade Mopidy to run on Python 3+. My effort is best spent at that point, rather than double-handling the upgrade.

**Comment by jaedb** [comment]
You're most welcome to start investigating. Python is not my native tongue so I'm happy to have assistance with this.

Given the decreasing use of Python 2.7, it would be practical to upgrade Iris to be compatible with Python 3.5+ (with backwards compatibility to 2.7) during this piece of work.

**Comment by kingosticks** [comment]
FYI the upcoming 2.3.0 Mopidy release will include our fixed support for Tornado 5 and we'll therefore remove the version restriction on our pip package. Our Debian package has never had this restriction so on latest stable Debian (buster) you'll find Tornado 5 is already being used.

**Comment by jaedb** [comment]
This should have been resolved now with the recent upgrade to Mopidy 2.3. Please re-open if this is still being experienced.

**Comment by kingosticks** [comment]
I was looking at this in regards to [Python 3 support](https://github.com/jaedb/Iris/issues/356) and it looks like [these methods](https://github.com/jaedb/Iris/blob/master/mopidy_iris/frontend.py#L25-L29) will be a problem. They call into `IrisCore.broadcast` which tries to write the connections from a thread which doesn't have a Tornado IOLoop running. Is that the intention? 

It's similar to what we had in https://github.com/mopidy/mopidy/pull/1796 but I'm not sure if the fix is as simple since Mopidy's HTTPServer event loop is not as easily exposed to this code. And I'm also not sure if Tornado 6 (with it's change to an asyncio IOLoop) makes any difference.

**Comment by jaedb** [comment]
I'm still wrapping my grey matter around threading and IOLoops, but does the [Iris websocket](https://github.com/jaedb/Iris/blob/master/mopidy_iris/handlers.py#L10) not run on it's own thread?

It has a separate URL endpoint of `.../iris/ws`. Or am I misunderstanding threading here?

**Comment by kingosticks** [comment]
The handlers are run from Mopidy's HTTPServer thread. I don't think the endpoint matters. If you prepend `%(threadName)s` to Mopidy's logging format config setting it helps to see what's going on.

**Comment by kingosticks** [comment]
I also found [this](https://www.tornadoweb.org/en/stable/httpclient.html#http-client-interfaces)

> Changed in version 5.0: Due to limitations in asyncio, it is no longer possible to use the synchronous HTTPClient while an IOLoop is running. Use AsyncHTTPClient instead.

Which might explain why `refresh_spotify_token()` (and others) doesn't do anything.

**Comment by jaedb** [comment]
> I was looking at this in regards to [Python 3 support](https://github.com/jaedb/Iris/issues/356) and it looks like [these methods](https://github.com/jaedb/Iris/blob/master/mopidy_iris/frontend.py#L25-L29) will be a problem. They call into `IrisCore.broadcast` which tries to write the connections from a thread which doesn't have a Tornado IOLoop running. Is that the intention?

The more I look at this code, the more confused I become. 

The event listeners in `frontend.py` (`track_playback_ended`, etc) are internal listeners to the Mopidy core, rather than to any websocket. Right? They're only used by Iris to load more tracks when in radio mode and are not exposed to the Iris websocket.

**Comment by kingosticks** [comment]
Yes they are core listeners. But unless I'm mistaken (I might be) one of them has a code path that tries to broadcast some status to the open websockets. I'll try to reproduce that in a test. 

On a related note, why is IrisCore running it's own thread? What code is supposed to be running in that? Is it just the initial command loading or is it the idea that the http handers etc transfer over to it to do their work?

**Comment by jaedb** [comment]
It's not a considered design decision, rather a workaround. From memory it was around having access to Mopidy `core` and `config` objects while not extending `CoreListener`.
I'm running through the code to try and refresh my memory.
What is your opinion on this approach? I'm always keen to understand how the more experienced tackle things.

**Comment by kingosticks** [comment]
I'm by no means an expert on this stuff, and I have next to no experience with asyncio, but I am not a fan of the callback stuff in the handlers. It almost gives the impression that there's some non-blocking execution going on, but there isn't.

To be honest, Mopidy's webclient extension support doesn't cater well for someone expanding beyond a simple javascript client. Ideally, web client extensions would be almost entirely client-side javascript. (And they'd avoid integrating directly with Mopidy's Tornado stuff as there's a non-zero possibility of Mopidy Core swapping Tornado for something else in the future). But obviously that ideal places a lot of restrictions on what you can do and would mean a lot of cool features (like those in Iris) are impossible to achieve. I think we could make it easier for extensions to add custom http/websocket endpoints and avoid having to worry about their threading and Tornado internals e.g. IOLoop.

But right now I'm sure we can tweak the current Iris architecture enough to get things working. I was just trying to figure out how things were supposed to work so I could untangle what's necessary for the Python 3 build and what's a more fundamental Tornado issue.

**Comment by arthurlutz** [comment]
I seem to be bumping into this bug, still. I'm running the python3 version. and my tornado is 6.0.4.

```
2020-07-09 18:22:27,573 ERROR [2249:IrisFrontend-13] mopidy.listener: Triggering event failed: track_playback_ended(tl_track, time_position)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/listener.py", line 40, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_iris/frontend.py", line 26, in track_playback_ended
    iris.ioloop.add_callback(functools.partial(iris.check_for_radio_update))
AttributeError: 'NoneType' object has no attribute 'add_callback'
```

Should I downgrade tornado ? Is this a new issue ?

**Comment by jaedb** [comment]
@arthurlutz this has been created as a new issue as #560 and isn't directly related to the version of Tornado, rather how Iris listens to Mopidy core events.
I also believe this may be related to #554
