### ISSUE TITLE
What is the purpose of the authorization url? 

### ISSUE THREAD

**Issue by samyun** [jaedb/Iris#276]
Maybe I just suck at searching, but what's the purpose of the authorization urls?
 `spotify_authorization_url = https://jamesbarnsley.co.nz/auth_spotify.php`
 `lastfm_authorization_url = https://jamesbarnsley.co.nz/auth_lastfm.php`

The installation instructions indicate that they're authentication proxies, but are they required? Why?

**Comment by jaedb** [comment]
See #161 and #95. You will find the [GitHub search engine](https://help.github.com/articles/searching-issues-and-pull-requests/) for issues very useful.
