### ISSUE TITLE
[Feature request] Skip tickets

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#277]
- All clients start each day with a number of skip tickets
- When skipping a track, they 'spend' a ticket
- Any other user can 'endorse' a skip. When endorsed, the skipper gets their ticket refunded.
- If no endorsement, then skip ticket is not refunded.
- Whether to disable skips when tickets used, or just alert all users?
- Skip tallies stored within `connections` array

**Comment by MarcinWieczorek** [comment]
Doesn't Spotify API require premium version? My information might be incorrect or outdated though, didn't do any research first. Premium accounts can skip however they want, so why implement something like this?
