### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by mathieuhays** [jaedb/Iris#280]
## Expected behavior
Successfully upgrade Mopidy-Iris

## Actual behavior
Mopidy upgrade command fails

## Steps to replicate
1. run `sudo pip install --upgrade Mopidy-Iris`

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: Raspbian 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other: 

## Additional details, debug data, logs, etc
Output:
```
pi@raspberrypi:~ $ sudo pip install --upgrade Mopidy-Iris
Collecting Mopidy-Iris
  Downloading https://files.pythonhosted.org/packages/29/f4/4f19ee9dc984a7838d72216ad83d2242b469f84b6b999bf1ec2cb92d9aa7/Mopidy-Iris-3.16.3.tar.gz (6.5MB)
    100% |████████████████████████████████| 6.5MB 623kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 1
        SPCOcommercial
            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hvbQ9T/Mopidy-Iris/
```

Python version: 2.7.9
Pip version: 10.0.0 (a similar error was also happening with version 9.x.x)

I've had a quick look through the dependencies defined in the package and they all seem to match the requirements.

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [x] Yes, I have included any relevant debug data and error logs

I don't know if it's related to this package in particular. I Googled it quite a bunch and couldn't find anything helpful.

**Comment by jaedb** [comment]
Thanks for the thorough issue reporting!

At a glance I would investigate what exactly `SPCOcommercial` is. What version of `setuptools` do you have installed?

I've run the update command on my Raspbian and all seemed to install smoothly, so I'm unable to replicate the issue at this stage.

**Comment by mathieuhays** [comment]
My setuptools version is 39.0.1

I've just rebooted this morning, tried to upgrade again and it worked.

The weird thing is that I upgraded pip to version 10 yesterday and after reboot I'm back to 9.0.1 for some reason. There's probably something wrong with my python installation.
