### ISSUE TITLE
cant login to spotify (404)

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#282]
## Expected behavior
clinking on the "Login" button in spotify section of settings the login popup shows with login page

## Actual behavior
popup shows with error "404: Not Found"

## Steps to replicate
1. go to spotify settings
2. click on the "login" button

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ x] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [x ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ x] Small (phone)

## Additional details, debug data, logs, etc
nothing related to the issue in the mopidy logs

## Before you submit
- [ x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by mczerski** [comment]
tested on version 17.1

**Comment by mczerski** [comment]
url of the popup window:
http://xxx:6680/iris/undefined?action=authorize&scope=playlist-modify-private%20playlist-modify-public%20playlist-read-private%20playlist-modify-private%20user-library-read%20user-library-modify%20user-follow-modify%20user-follow-read%20user-read-email%20user-top-read%20user-read-currently-playing%20user-read-playback-state%20playlist-read-collaborative%20ugc-image-upload

**Comment by luken8628** [comment]
Also having the same issue.  Using v. 13.17.2

**Comment by depressivum** [comment]
Error is fixed for me / 13.17.2

**Comment by luken8628** [comment]
seems to be working for me now too... just updated to 13.17.4

**Comment by jaedb** [comment]
Resolved at 3.17.3

**Comment by brknkfr** [comment]
Still persists on 13.17.4. Please reopen.

**Comment by depressivum** [comment]
You are right - maybe, it isn't a iris problem but a "mopidy-spotify" issue. I installed 13.16.2 manually without effect.

**Comment by jaedb** [comment]
@brknkfr I believe the issue is resolved, but the 3.17.4 release re-introduced it. Can you please confirm the issue persists on 3.17.5? Make sure you clear your cache and reset all settings for accurate testing.

**Comment by brknkfr** [comment]
Yes, it seems to work now.

**Comment by RensOliemans** [comment]
I tested it on 3.17.5, and it seems to work for me as well (after resetting the settings)!
