### ISSUE TITLE
Genius lyrics query compatibility with accented characters

### ISSUE THREAD

**Issue by anttimc** [jaedb/Iris#284]
I just found out the cool feature of 'track info' finding lyrics using genius API. Removing all non-alphanumeric characters in the query, however, messes up finding some song names with characters like ä, é, î, etc.

I guess this could be circumvented by decomposing these characters by
query=  query.normalize('NFD') 
before removing the non-alphanumerics.

This could help searching for lyrics with non-english names.

**Comment by jaedb** [comment]
This could also be remedied by `encodeURIComponent`, given the query is parsed as URL parameters. Do you have a few example track names that I can use to reproduce the error? The GitHub issue template is there for this reason :-)
