### ISSUE TITLE
MyMusic is not populated with local library

### ISSUE THREAD

**Issue by kdjordjev** [jaedb/Iris#286]
## Expected behavior
Expect Artist/Album/Tracks to be populated with the metadata from the local files

## Actual behavior
All items under My Music empty within the interface. 
I am only able to browse the library through the Browse/Local Media button. 
I can play the media from there without an issue

## Steps to replicate
1.
2.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x ] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [ x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ X] Yes, I have included any relevant debug data and error logs

[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
color = true
console_format = %(levelname)-8s %(message)s
debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
debug_file = /var/log/mopidy/mopidy-debug.log
config_file = /etc/mopidy/logging.conf

[audio]
mixer = software
mixer_volume =
output = lamemp3enc ! shout2send mount=mopidy.mp3 ip=127.0.0.1 port=8000
password=
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[tunein]
enabled = true
timeout = 5000

[scrobbler]
enabled = true
username = 
password = 

[pandora]
enabled = true
api_host = tuner.pandora.com/services/json/
partner_encryption_key = 6#26FRL$ZWD
partner_decryption_key = R=U!LH$O2B#
partner_username = android
partner_password = AC7IBG09A3DTSYM4R41UJWL07VLN8JI7
partner_device = android-generic
username =
password =
preferred_audio_quality = highQuality
sort_order = a-z
auto_setup = true
cache_time_to_live = 86400
event_support_enabled = false
double_click_interval = 2.50
on_pause_resume_click = thumbs_up
on_pause_next_click = thumbs_down
on_pause_previous_click = sleep
on_pause_resume_pause_click = delete_station

[moped]
enabled = true

[local-images]
enabled = true
library = json
base_uri = /images/
image_dir =
album_art_files =
  *.jpg
  *.jpeg
  *.png

[iris]
enabled = true
country = US
locale = en_US
spotify_authorization_url = https://jamesbarnsley.co.nz/auth_spotify.php
lastfm_authorization_url = https://jamesbarnsley.co.nz/auth_lastfm.php
snapcast_enabled = false
snapcast_host = localhost
snapcast_port = 1705

[mpd]
enabled = true
hostname = 0.0.0.0
port = 6600
password =
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist =
  listall
  listallinfo
default_playlist_scheme = m3u

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir = /var/lib/mopidy/playlists

[softwaremixer]
enabled = true

[file]
enabled = true
media_dirs = /mnt/Music
excluded_file_extensions =
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[local]
enabled = true
library = json
media_dir = /mnt/Music
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions =
  .ini
  .itdb
  .itl
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt

[spotify]
enabled = false  ; Extension disabled due to config errors.
username =   ; Must be set.
password =   ; Must be set.
client_id =   ; Must be set.
client_secret =   ; Must be set.
bitrate = 160
volume_normalization = true
private_session = false
timeout = 10
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
toplist_countries =

**Comment by jaedb** [comment]
Do you see any errors in your browser? If you enable _Test mode_ (_Settings > Debug > Test mode_) you'll get more verbose output.

It might sound like a silly question, but have you got _All_ selected in your _Sources_ dropdown?

**Comment by kdjordjev** [comment]
Hello @jaedb 
Thanks for your reply.
Yes i did select "All sources"
I enabled the "Debug" option as you suggested and Overlay the data (see below)
It reports "0" for the Artists, etc.

Sorry i am new to this... What do i need to do to enable it?
I did run "sudo mopidyctl local scan" to scan the files.
anything else i can do?
Appreciate your time


![image](https://user-images.githubusercontent.com/26642112/40667645-82f2dece-6317-11e8-9136-ea7d36e50291.png)

**Comment by burnbabyburn** [comment]
Tested with Iris 3.18 and 3.19 and can confirm this issue

local media is found by mopidy and and iris. Music can be accessed through "browse->local media" only 

But in my case, statistics were running fine.
![s](https://user-images.githubusercontent.com/2515038/40811658-51af5aa0-6532-11e8-96fe-9bc6f49e14b9.png)

**Comment by jaedb** [comment]
The _Debug info_ panel shows the state of the asset indexes (ie how many records are loaded for each), so it isn't an indication of how many records _should_ have been loaded. Open _Discover > New releases_ (if Spotify is enabled) and you'll see the _Albums_ counter will start growing as these are loaded.

Can you please navigate to _My Music > Browse > Local Media > Albums_ and paste the full URL? It may be possible that the URL structure has been changed (either in your local config, or by an updated to Mopidy-Local), breaking this view.

**Comment by kdjordjev** [comment]
i changed the local library from default JASON to SQL-light and everything is functional now
Thanks
