### ISSUE TITLE
HTTPS Everywhere breaks Last.fm scrobbling due to CORS header

### ISSUE THREAD

**Issue by brianclinkenbeard** [jaedb/Iris#287]
## Expected behavior
Last.fm requests are functional
## Actual behavior
COR is blocked due to "missing header"
## Steps to replicate
1. Install HTTPS Everywhere on Firefox 60
2. Authenticate to Last.fm and attempt to scrobble

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ ] Chrome: 
- [x] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

## Additional details, debug data, logs, etc
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ws.audioscrobbler.com/2.0/?format=json&method=user.getInfo&user=xxxxxxx&api_key=xxxxxxx. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`
## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [x] Yes, I have included any relevant debug data and error logs

This issue is particularly strange since it seems that [cross origin requests are allowed everywhere](https://github.com/jaedb/Iris/blob/0fc5a82cf0697817eacb2bd7df47d61a3b780261/build_tools/auth_lastfm.php). I have isolated the browser to only this extension to confirm that nothing is modifying the COR policy and the issue persists.

**Comment by jaedb** [comment]
This sounds like an issue with LastFM, rather than Iris. It's up to the resource you're requesting to provide the appropriate CORS headers.

If you uninstall HTTPS Everywhere, does the issue persist?

I'll investigate further at my end in the meantime.

**Comment by brianclinkenbeard** [comment]
>If you uninstall HTTPS Everywhere, does the issue persist?

Nope. Just disabling the [AudioScrobbler rule](https://www.eff.org/https-everywhere/atlas/domains/audioscrobbler.com.html) in the extension will resolve the issue, as its just a matter of changing the connection to https.
