### ISSUE TITLE
No audio playback in HTML5 player

### ISSUE THREAD

**Issue by burnbabyburn** [jaedb/Iris#288]
- RaspberryPI 3B+ running mopidy, Iris and icecast2 playing spotify
- Clients (Windows & Android) accessing Iris through Browser
## Expected behavior
Iris playing Icecast2 audio stream in client browser. Implemented since [3.12.1](https://github.com/jaedb/Iris/releases/tag/3.12.1)
## Actual behavior
Icecast2 audio stream is not played in client browser. clients need to access icecast2 stream via vlc or mpdroid.

## Steps to replicate
Tested on RPI3B and RPI3B+ using Raspian lite image  (tried 03-2018 & 04-2018 builds)

- Install mopidy using the [documentation](https://docs.mopidy.com/en/develop/installation/debian/), configure [streaming through icecast](https://docs.mopidy.com/en/develop/audio/#streaming-through-icecast) and configure [http] and [mpd] network access (hostname=::)
- Install mopidy-spotify mopidy-local-sqlite mopidy-alsamixer via apt
- Install pip => install iris
- Install & configure icecast2 to: listenurl = http://10.0.0.2:8000/stream.mp3
- Use Iris to control mopidy and start a random track
- Icecast ist streaming the track. Also local audio out on Raspberry [(multiple outputs)](https://docs.mopidy.com/en/develop/audio/)
-MPDroid on Android and VLC can now stream music. Iris remains silent. I've waited till the end of the track, to confirm there isn't any audio lag. There's just no audio at all.
- But mopidy -vvv or iris debug are not showing any errors. Just the youtube plugin getting disabled 

Used Browser: Firefox, Chrome, Iron, IE

Screenshots
Iris: https://picload.org/view/dolwalpr/2018-05-2800_06_11-getwhatyouc.png.html
icecast2: https://picload.org/view/dolwalpa/2018-05-2800_08_47-icecaststre.png.html

So mopidy and icecast seem to be running as configured. Plenty of resources are avaible to the system (load of <0.40, ) But Iris seem to have some problem with this setup. Can someone confirm this?

P.S. Snapcast is working as designed in this setup.

**Comment by jaedb** [comment]
When you open the stream file directly in a browser (ie http://10.0.0.2:8000/stream.mp3), do you get the anticipated audio?

**Comment by burnbabyburn** [comment]
Hi jaedb,
thank you for responding to my issue.

>  do you get the anticipated audio?

Yes audiostream is running and accessible from any device in my LAN as soon as i start playback in iris. But I have to open the mentioned stream-URL in another player e.g. VLC.

Do you need any additional log/output or system configuration? ATM i've got a RPI3 as spare and could provide a testing unit for you.

**Comment by Ismas** [comment]
Same here. Never sounded thru web browser, but icecast2 is installed and working using any player. Tryed in several Debian servers and with several browsers.

---------- mopidy config: ----------------
[audio]
mixer = software
output = lamemp3enc target=quality quality=0 ! shout2send mount=stream ip=0.0.0.0 port=8000 password=hackme

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

------------ mopy deps check: ----------------
Executable: /usr/bin/mopidy
Platform: Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial
Python: CPython 2.7.12 from /usr/lib/python2.7
Mopidy: 2.0.0 from /usr/lib/python2.7/dist-packages
Mopidy-Local-Images: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  uritools>=1.0: 2.2.0 from /usr/local/lib/python2.7/dist-packages
    ipaddress; python_version == "2.7": 1.0.16 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  setuptools: 20.7.0 from /usr/lib/python2.7/dist-packages
  Mopidy>=1.1: 2.0.0 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify: 3.1.0 from /usr/lib/python2.7/dist-packages
  Mopidy>=2.0: 2.0.0 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  pyspotify>=2.0.5: 2.0.5 from /usr/lib/python2.7/dist-packages
    cffi>=1.0.0: 1.11.5 from /usr/local/lib/python2.7/dist-packages
      pycparser: 2.18 from /usr/local/lib/python2.7/dist-packages
  requests>=2.0: 2.9.1 from /usr/lib/python2.7/dist-packages
Mopidy-Iris: 3.19.0 from /usr/local/lib/python2.7/dist-packages
  raven>=6.1.0: 6.8.0 from /usr/local/lib/python2.7/dist-packages
    contextlib2; python_version < "3.2": 0.5.5 from /usr/local/lib/python2.7/dist-packages
  ConfigObj>=5.0.6: 5.0.6 from /usr/lib/python2.7/dist-packages
    six: 1.10.0 from /usr/lib/python2.7/dist-packages
  Mopidy-Local-Images>=1.0: 1.0.0 from /usr/local/lib/python2.7/dist-packages
    uritools>=1.0: 2.2.0 from /usr/local/lib/python2.7/dist-packages
      ipaddress; python_version == "2.7": 1.0.16 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    setuptools: 20.7.0 from /usr/lib/python2.7/dist-packages
    Mopidy>=1.1: 2.0.0 from /usr/lib/python2.7/dist-packages
  setuptools>=3.3: 20.7.0 from /usr/lib/python2.7/dist-packages
  Mopidy>=2.0: 2.0.0 from /usr/lib/python2.7/dist-packages
  tornado<5.0,>=3.2: 4.2.1 from /usr/lib/python2.7/dist-packages
  requests>=2.0.0: 2.9.1 from /usr/lib/python2.7/dist-packages
  pylast>=1.6.0: 2.2.0 from /usr/local/lib/python2.7/dist-packages
    six: 1.10.0 from /usr/lib/python2.7/dist-packages
GStreamer: 1.8.3.0 from /usr/lib/python2.7/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.20.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        flump3dec
        id3demux
        id3v2mux
        lamemp3enc
        mad
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        none

**Comment by Ismas** [comment]
As further info, I sniffed network traffic and it seems the browser is not even trying to connect icecast server.
