### ISSUE TITLE
Autostart Spotify Playlist?

### ISSUE THREAD

**Issue by Pat71** [jaedb/Iris#289]
Is there a way to autostart Iris/Mopidy with a specific spotify playlist?
I'm running a headless server which should automatically run a playlist so I don't have to connect manually via a client.

It would be perfect to specify a playlist via commandline/REST like:
mopidy --start-playlist Pop/Hitradio
or
http://192.168.0.8:6680/iris/#/play/categories/pop/hitradaio

**Comment by Pat71** [comment]
Ok, as I read in some of the issues, mostly all functions of Iris can be called via RESTful api, my question would be would api calls there are and, in my case, what is the api call to play a playlist?
Some calls can be seen (like "playlist", "queue", "settings", ...) but unfortunately not for "play" :-/

**Comment by jaedb** [comment]
This is functionality that shouldn't be baked in to Iris, instead it should be it's own Mopidy extension. Do you have a handle on writing python?

To answer your question, only Iris-specific methods are exposed in RESTful and websocket apis. The actual endpoints are not documented, but see [`core.py`](https://github.com/jaedb/Iris/blob/master/mopidy_iris/core.py) for a starting point. For core methods I rely on the Mopidy websockets library.

**Comment by Pat71** [comment]
Thanks for your reply - well, I searched quite a bit and found none of the endpoints neither Mopidy's nor Iris' :-/ 
It's not that Mopidy or Iris should be changed (baked in), I just wanted to get a hand on the existing REST APi endpoints so I can automate mopidy/iris a bit...

**Comment by jaedb** [comment]
Mopidy provides a great JSON-RPC API, which you can use via any client by using POST requests.

See [JSON-RPC](http://mopidy.readthedocs.io/en/latest/api/http/) to get started, and the [API](http://mopidy.readthedocs.io/en/latest/api/core/) for each component of the Mopidy core.

To make my life easier debugging Mopidy, I built in a simple form to consume the Mopidy API (via websockets, but the JSON-RPC structure is the same) into Iris. See _Settings > Debug > Mopidy_ to wrap your head around what's possible with the Mopidy API.

**Comment by Pat71** [comment]
Thanks again - I managed to "remote control" Mopidy, i.e. to start playing from the commandline/via vron.

What I didn't figure out yet is how to add a specific Spotify playlist...do you have any clues how/whether I can add a playlist like "spotify:user:spotify:playlist:37i9dQZF1DX4jP4eebSWR9" (got this via "copy URI" in Iris)?

**Comment by Pat71** [comment]
No ideas? :-(

**Comment by jaedb** [comment]
Hint: read the documentation of Mopidy, namely [tracklist.add()](http://mopidy.readthedocs.io/en/latest/api/core/#tracklist-controller).
