### ISSUE TITLE
Showing duplicate albums

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#29]
When I open my artist and look at list of albums, I can see that some albums are there multiple times and they have sam content.
For example for this artist:
http://localhost:6680/iris/#/artist/spotify:artist:6pIRdCtSE5hLFfIfcTAicI?_k=9p0ysv
I can see two albums with same name and identical songs:
http://localhost:6680/iris/#/album/spotify:album:10oFicbsgs7qEVJkYjvlwh?_k=4zowme
http://localhost:6680/iris/#/album/spotify:album:6iVYmkmAPFKzK8LVAySQri?_k=bkia1d
And just above them are two albums with a bit different names but same songs:
http://localhost:6680/iris/#/album/spotify:album:1jDd4dtQf0XVIMjDlhWeZG?_k=zesdhw
http://localhost:6680/iris/#/album/spotify:album:7r2LyafbGceqnzbOUz2bWG?_k=e1vltl
But when I look at official Spotify site, I can see only two albums, not four as shown above.  However, I suspect that this might be a Spotipy issue, if you use it, because I experience same problem with mopidy-spotify-web extension.

**Comment by jaedb** [comment]
This is due to not using the `market` parameter in the requests for an artist's albums. I've resolved this in d0d92b807aa627b10e63239886d4f2a180047909 and will be included in the next major release.
