### ISSUE TITLE
installation issue on Raspbian

### ISSUE THREAD

**Issue by aleave** [jaedb/Iris#290]
when installing Iris on Raspbian I get the following error:

sudo echo "mopidy ALL=NOPASSWD: /usr/local/lib/python2.7/dist-packages/mopidy_iris/system.sh" >> /etc/sudoers
bash: /etc/sudoers: Permission denied

must be something related to permissions but cannot figure out what; sudo generally works

**Comment by mathieuhays** [comment]
I had the same issue.

Instead you can do:
`sudo visudo`

and then paste the line:
`mopidy ALL=NOPASSWD: /usr/local/lib/python2.7/dist-packages/mopidy_iris/system.sh`

**Comment by aleave** [comment]
@mathieuhays thanks, your method worked great
