### ISSUE TITLE
How do I list the library using albumartist tag instead of artist?

### ISSUE THREAD

**Issue by fa7ad** [jaedb/Iris#294]
## Expected behavior

When my local music library is displayed its split up by using the artist ID3 tag, I want to change that so that it uses albumartist instead.

## Before you submit
- [x] Yes, I have tested this issue ~thoroughly~
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
You can now configure this under _Settings > Advanced_ :-)

**Comment by fa7ad** [comment]
Thanks a lot for adding that feature :heart: 

For anyone else looking for the artist URI, its:
```
local:directory?type=artist&role=albumartist
```

**Comment by tljohnsn** [comment]
I noticed local:directory?type=artist&role=albumartist is the default now.  Is there a way to change the default back so when a new client connects it just gets local:directory?type=artist
