### ISSUE TITLE
Disable Data Collection

### ISSUE THREAD

**Issue by sidisgood** [jaedb/Iris#295]
Hello. Thank you for excellent open source product! 
Currently I'm testing GUI and functionality of Iris client and when I started to use it first what I saw was 2 startup messages, and one of them was about data collection. The reason why I choose Mopidy, because it's private. I'm not, a big fan of sharing something with Google, I  would like to disable Google Analytics. Is there any way to disable it?

Thank you!

**Comment by jaedb** [comment]
This has been a discussion for a little while (see pull requests and various issues).

Keep your eyes peeled for the next release ;-)
