### ISSUE TITLE
Difficult to change the volume

### ISSUE THREAD

**Issue by tgurr** [jaedb/Iris#297]
## Expected behavior
Being able to work with the volume in a comfortable way

## Actual behavior
A bit difficult to handle, for example it's next to impossible to set the volume (back) to 100%

## Steps to replicate
1. Change volume

## Details
Since right now you don't seem to be able to put the finger or the mouse cursor on the slider to drag it but instead having to tip/click it, it's next to impossible to get the volume to e.g. 100%, especially on small screens, but also on the desktop.

![iris-snapcast](https://user-images.githubusercontent.com/414984/41125760-aaec3e1c-6aa5-11e8-8a2d-5cf88325a032.png)

## Wish/Possible solution
* 1: Maybe add little - and + button next to the volume slider so you can click on them to lower and raise the volume in little steps to overcome the shortness of not being able to drag the slider

* 2: Being able to actually drag the slider, if it's possible to implement it that way

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: 
- [ ] iOS: 
- [x] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x] Huge (ie desktop)
- [ ] Large (ie laptop)
- [x] Medium (ie slim laptop/tablet)
- [x] Small (phone)

## Before you submit
- [x] Yes, I have attached screenshots and/or screencast of the issue in action

## Additional information
Probably what https://github.com/jaedb/Iris/issues/207 is about.

**Comment by jaedb** [comment]
This is a great idea, and something I had experimented with some time ago for all sliders. The thinking was to make all sliders HTML5 slider elements. However this created a bit of a challenge as the change would need to take effect for every incremental change, essentially spamming the server.

I'd definitely prefer to drag than to introduce extra buttons (+ and -), so will need to re-assess how this might work. Perhaps having a 500ms delay between `onChange` and the actual server request would achieve the best of both.

**Comment by lukecyca** [comment]
Yes, this is a big problem for us as we are controlling Iris primarily from an iPad. In #203 I suggested dragging as the ideal solution, which is how most sliders work on mobile platforms. A lesser (but possibly easier to implement) solution would be to just make the volume slider much longer so that at least the target is much bigger and would make it possible to make more precise volume adjustments.

**Comment by mathieuhays** [comment]
Using a [debounce](https://davidwalsh.name/function-debounce) function in this case might be what you're looking for.

In the link above if you set the `immediate` parameter to `false` the callback will only execute once the user has stopped moving the slider around.

You might want to keep triggering the callback from time to time though.

**Comment by jaedb** [comment]
Ready for you guys to test on `develop` branch. 

I've tested this on my RaspberryPi 3b+ and 250ms throttling for seek events and 100ms for volume events seems sufficient. It would be interesting to see how environments cope with this. Let me know your findings.

**Comment by lukecyca** [comment]
Great work! I tried it out and it is a significant improvement. A few minor things I noticed:

* If two clients are connected, moving the volume slider on one doesn't update the other.
* On desktop Safari, clicking anywhere on the slider snaps to that point (as it did before). Similarly, starting a drag from any point on the slider works as expected too — awesome! On iOS it doesn't though — you must start the drag from the current handle position.
* Mute seems to work (it mutes the audio) but nothing in the UI changes to show that its muted (although I'm not sure it did before either).

**Comment by jaedb** [comment]
To achieve this without writing interactive rules (touch, tap, drag, touchdrag, etc), I've simply used an invisible `<input type="range" />` field. As such, any browser behavior on range input fields will be reflected in this new slider. I'm comfortable with iOS having to drag from the handle if that's how the OS handles them!

It sounds like your Iris isn't connected to the server. Updates to volume (including mute) will be broadcast to all connected clients - this hasn't been touched. If it's not broadcasting then I'd suggest running Mopidy in debug mode (ie `mopidy -vvv`) to see if there was something else at play.

**Comment by tgurr** [comment]
Sorry for the bug spam but I just want to say thank you very very much, makes it a breeze to adjust volume(s) now!

**Comment by jaedb** [comment]
@tgurr You're welcome.
