### ISSUE TITLE
[Feature request] Button feedback

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#299]
When clicking buttons, provide visual feedback. For example play/pause/next could blink with a blue background, as per material UI principles.

**Comment by Auroran7** [comment]
Are you maybe looking for something like a "ripple click effect"? 

var links = document.querySelectorAll('.ripplelink');
for (var i = 0, len = links.length; i < len; i++) {
  links[i].addEventListener('click', function(e) {
    var targetEl = e.target;
    var inkEl = targetEl.querySelector('.ink');
    if (inkEl) {
      inkEl.classList.remove('animate');
    }
    else {
      inkEl = document.createElement('span');
      inkEl.classList.add('ink');
      inkEl.style.width = inkEl.style.height = Math.max(targetEl.offsetWidth, targetEl.offsetHeight) + 'px';
      targetEl.appendChild(inkEl);
    }
    inkEl.style.left = (e.offsetX - inkEl.offsetWidth / 2) + 'px';
    inkEl.style.top = (e.offsetY - inkEl.offsetHeight / 2) + 'px';
    inkEl.classList.add('animate');
  }, false);
}

[CodePen working example here](https://codepen.io/thulstrup/pen/OVROEm)   _Credits/Done by: thecodeplayer.com_ 

With that you could just add or adjust the link class, where you want it to blink..

Kind regards,

Auroran

**Comment by jaedb** [comment]
Thanks for the tips @Auroran7, that's totally the type of click feedback I'm looking for but am hoping to make a CSS-only solution to avoid polluting the DOM with too many changes.
