### ISSUE TITLE
Many playlists and API rate limiting

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#3]
_From @sgraca on December 31, 2016 12:28_

I have many playlists (over 200) and this seems to cause some issues when I start Spotmop. It tries to load all of them during startup which takes some time (the application makes over 600 request in total), and before that I cannot use the application. But I also noticed that load calls to load the playlist details fail with HTTP error 429:

```
HTTP/2.0 429 No Reason Phrase
Server: nginx
Date: Sat, 31 Dec 2016 12:21:41 GMT
Retry-After: 3
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 604800
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Content-Encoding: gzip
X-Firefox-Spdy: h2

{
  "error": {
    "status": 429,
    "message": "API rate limit exceeded"
  }
}
```

_Copied from original issue: jaedb/spotmop#167_

**Comment by jaedb** [comment]
Further reading: https://developer.spotify.com/web-api/user-guide/#rate-limiting

**Comment by jaedb** [comment]
@sgraca Does this issue persist? Or is it no longer relevant?

**Comment by sgraca** [comment]
@jaedb I would say both. The issue still persists as the API rate limiting is still in place. However I reorganized my playlists and I'm no longer affected by it.

**Comment by jaedb** [comment]
Issue has been further resolved by loading playlists on demand, rather than on load (along with other requests).
