### ISSUE TITLE
[Feature request] Automatic Airplay on Play status, switch back when not playing.

### ISSUE THREAD

**Issue by Daargajedan** [jaedb/Iris#300]
It would be great if Iris notice that Airplay is used and switch a Group in Snapcast to airplay. And back if airplay is done.

**Comment by jaedb** [comment]
Can you please describe the setup that you're talking about? My initial reaction is that this sounds like it belongs in Snapcast, rather than Iris. Iris' focus is on being a versatile web interface for Mopidy, rather than becoming too specialised in one particular use case.

**Comment by Daargajedan** [comment]
You have made a Snapchat server interface to controle snapcast within Iris. Would love that Iris. 

I can imagion an order on the incontinent streams. And then let Iris manipulatie snapcast. 

Music is playing on my Raspberrypi And Im sitting in front of my mac. Now I wanna AirPlay something to the same player. Nou I need to go to Iris to set it to AirPlay.(other stream). It would be Nice if Iris recignice the other stream is playing so it sets it to that stream. If that stream is done Its going back to Iris.

**Comment by jaedb** [comment]
This type of functionality (ie intelligently switching streams) doesn't belong in Iris. Instead it belongs in, or as an extension of, Snapcast. I'd suggest opening a feature request on the [Snapcast repository](https://github.com/badaix/snapcast/issues).

**Comment by Daargajedan** [comment]
Thnx Jaedb for the good work i posted it on snapcast

[](https://github.com/badaix/snapcast/issues/402)
