### ISSUE TITLE
[Feature request] Youtube Support

### ISSUE THREAD

**Issue by MrJacz** [jaedb/Iris#301]
Add support for youtube (this should be self explanatory)

**Comment by jaedb** [comment]
What exactly do you mean by "YouTube support"?

Iris is just the front-end interface. So for Iris to 'support' a provider, there needs to be a relevant Mopidy backend extension. For Youtube this is [Mopidy-Youtube](https://github.com/mopidy/mopidy-youtube), however this project has become quite stale and has a number of issues.

In order for Iris to better support YouTube, this project needs to be bought up-to-speed. So I suggest you lodge a ticket on that repository asking for a new maintainer.

**Comment by MrJacz** [comment]
Ahh, rip. Maybe I should leave my hate for Python and learn it

**Comment by jaedb** [comment]
I have a love/hate relationship with python too. Sometimes it seems really obtuse, other times simple is good.

I'll mark this as closed as the issue lies with Mopidy-Youtube.
