### ISSUE TITLE
[Feature request] Adding a crossfade option

### ISSUE THREAD

**Issue by Auroran7** [jaedb/Iris#303]
## Expected behavior
Having a smooth change from track to track in a playlist

## Actual behavior
Hard change; one song ends, the other one starts right away

## Steps to replicate
Just add 2 or more songs to a playlist and play them

## Additional details, debug data, logs, etc
_Idea/feature request:_ 
Use html5 <audio> element and javascript to create a crossfade between 2 tracks in a playlist would be awesome!
Maybe with an on/off checkbox in the settings section?

Examples/ideas to make it maybe work/implement it:
-  As described on [html5rocks.com](https://www.html5rocks.com/en/tutorials/webaudio/intro/#toc-xfade-play)
-  Adding the [howler javascript audio library](https://github.com/goldfire/howler.js)

Thank you for the great work on Mopidy-Iris and for consideration,

with kind regards,

Auroran

**Comment by jaedb** [comment]
This belongs in Mopidy as Iris doesn't have anything to do with the actual audio playback. I'd suggest you post this feature request on the [Mopidy repository](https://github.com/mopidy/mopidy/issues).
