### ISSUE TITLE
[Feature request] Play next uses prioritized queue

### ISSUE THREAD

**Issue by NiTr0-at** [jaedb/Iris#304]
If I'm listenting in shuffle mode, the "play next" option should add the song to a prioritized queue and really playing it next, not just adding it to the "Now Playing" list behind the current song.

I would like it to behave like the "add to queue" option in spotify.

**Comment by jaedb** [comment]
To achieve this Iris would need to create an intermediary queue handler, and bypass the built-in Mopidy tracklist functionality. This isn't desirable as it means any other Mopidy clients connected to the same server will get a half-baked experience. I want Iris to _expand_ Mopidy functionality, not _replace_ it.

It also requires a large amount of work to implement, so at this stage is a bit out of scope.

**Comment by PureTryOut** [comment]
I was confused by "play next" not working like this. To remedy I thought I would disable "shuffle", and then play a playlist with the "shuffle play" option. This would (in my mind) add the playlist to the "now playing" list shuffled, which means "play next" would work as expected as it would just put it next to be played in the "now playing" list. However, "shuffle play" seems to be the exact same as just "play" and it plays the playlist in the order it is put together.

Wouldn't this option work like expected if "shuffle play" actually worked?

**Comment by jaedb** [comment]
So is your issue that _Shuffle Play_ is not shuffling tracks when they get added to the queue?

**Comment by PureTryOut** [comment]
That is an issue I'm having yes, I should make a separate issue for that. But having that working would sort of be a solution/workaround for this issue as you would then listen to music shuffled, but since it plays in the order of the "Now playing" list the "Play next" option would work properly.

**Comment by jaedb** [comment]
@puretryout can you please create a new issue for this, including a full bug report? _Shuffle play_ works as expected for me, so I'll need your logs, screencap etc to better understand where things might be going wrong for you.

**Comment by PureTryOut** [comment]
I was going to make an issue for it, then found an [issue already existed for it](https://github.com/jaedb/Iris/issues/391#issuecomment-539946565), then solved it by pulling a newer image.

Anyways, play next works fine if you use shuffle play to start your playlist. Maybe only enable this option when shuffle play is used and explicitely remove the option when shuffle is on?
