### ISSUE TITLE
[Feature request] Shuffle support when starting playlist

### ISSUE THREAD

**Issue by DavisNT** [jaedb/Iris#307]
## Expected behavior
When _Shuffle_ setting is enabled in Mopidy playing a new Playlist starts from a random track. 

It is unclear what would be the best behavior if _Clear tracklist on play of URI(s)_ is **not** enabled. 
In other cases when _Shuffle_ is enabled it would be great to add first 50 (or so) songs from the playlist and go to to next track (that will be a random track from the queue) before starting playback. 

## Actual behavior
When _Shuffle_ setting is enabled in Mopidy playing a new Playlist always starts from the first track.

## Steps to replicate
1. Enable Shuffle option
2. Open a Spotify playlist
3. Click on Play

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux:
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [x] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
When playing a number of tracks or a playlist, Iris now respects the Mopidy Shuffle setting. This isn't possible when playing a `uri` that resolves to multiple tracks (ie an album uri), but regardless it resolves the original issue.

You can see it in action on the `develop` branch.

**Comment by DavisNT** [comment]
Thanks a lot! 
I guess I will wait for the release and then enjoy the new feature. :+1:

**Comment by DavisNT** [comment]
Thank you very much! :+1:  :heavy_check_mark: 
I see the implementation is a bit different (a random track from the playlist is placed on top of the play queue instead of its normal location in playlist), but it reaches the goal (and has advantages on large playlists over the implementation I proposed). 

P.S. I have **not** tested this with _Clear tracklist on play of URI(s)_ disabled.
