### ISSUE TITLE
Suggestion: randomize queue

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#31]
Would it be possible to take current queue and randomize it? I mean the situation when you have some favorite playlist but you don't want to  listen to it always in the same order.

**Comment by jaedb** [comment]
Mopidy has built-in randomise functionality. This is exposed in _Iris_ on the _Now Playing_ view. Is this not what you're after?

**Comment by vojtapolasek** [comment]
Hi,
yes this is it, but unfortunately I can't find this controll. Basically,
all I can find with my screenreader is name of currently playing song,
wo numbers announcing current positin and total lenght of the song and
then list of all songs in the queue. Where is this controll? Could you
try to make it accessible?
This might help:
https://www.w3.org/WAI/intro/aria

**Comment by jaedb** [comment]
Accessibility issue raised above will be addressed in #33
