### ISSUE TITLE
Feature request : bluetooth audio speaker/sink

### ISSUE THREAD

**Issue by daverck** [jaedb/Iris#314]
[mopidy-btmanager](https://github.com/liamw9534/mopidy-btmanager) aimed to do that but it is discontinued for several years.

I ask because Iris is the best mopidy Frontend and It would be awesome to add that feature :)

**Comment by jaedb** [comment]
This would require building a Mopidy _backend_, rather than a frontend (like Iris). I suggest opening a request on the [Mopidy project](https://github.com/mopidy/mopidy) instead.
