### ISSUE TITLE
[Feature request] Play artist top tracks

### ISSUE THREAD

**Issue by bargru** [jaedb/Iris#32]
In the spotify program there is an overview of an artist's top tracks. The play button starts the playback of the top tracks.
![grafik](https://cloud.githubusercontent.com/assets/13362393/21805491/be679d48-d734-11e6-8a0f-1bdfd647927d.png)

In Iris there is the same top tracks list. How about a similar function for Iris? There could be an additional button and / or if you click on one of the top tracks all are added to the play queue.
![grafik](https://cloud.githubusercontent.com/assets/13362393/21805470/a29e544e-d734-11e6-8d58-22f36d34cb89.png)

**Comment by jaedb** [comment]
<b>A funding goal of $50 has been set for this issue.</b>
Donate via CodeFund.io to support this developer and solve this issue.
<a href='https://www.codefund.io/view.php?id=15'><img src='http://www.codefund.io/img/percent/0-percent-funded.png'></a>
<a href='https://www.codefund.io/view.php?id=15'><b>Make a Donation!</b></a>
<i>Why donate? Learn more at <a href='https://www.codefund.io/support-open-source.php'>www.codefund.io/support-open-source.php</a></i>

**Comment by Hugomm** [comment]
How is this feature going?

**Comment by jaedb** [comment]
There haven't been any donations at this point, so it's a bit further down the priority list for the time being.
