### ISSUE TITLE
No Artist Images

### ISSUE THREAD

**Issue by fa7ad** [jaedb/Iris#321]
## Expected behavior
Load artist images like it normally does.
## Actual behavior
As soon as I add the `&role=albumartist` #294 bit artist images stop loading. At first, I thought it might be leading to incorrect URLs for the requests, but it seems like the requests stop altogether.

## Steps to replicate
1. Go to settings ->  advanced -> add `&role=albumartist` to the artist URI
2. Click on the Artist page

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [x] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [ ] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
Two things you could test to help identify the cause:
1. If you reset all settings, does artwork come through as expected (ie is the issue isolated to your custom URL), and
2. Activate testing mode (Settings > Debug > Test mode). Are there any errors in your browser console?

**Comment by jaedb** [comment]
I've had another look into this, and have replicated the issue. When loading as `albumartist`, the result from Mopidy gives us a `directory` object, not an `artist` object.

This will be patched in the next release.
