### ISSUE TITLE
Installation instructions don't tell me how to access Iris

### ISSUE THREAD

**Issue by ciex** [jaedb/Iris#326]
## Expected behavior

I follow the installation instructions and end up in the running Mopidy-Iris web interface.

## Actual behavior

I follow the instructions and don't know how to open Iris. I search for tutorials on the web and find [this](https://learn.pimoroni.com/tutorial/sandyj/streaming-spotify-to-your-pi), which implicates that Iris can be accessed via `http://raspberrypi.local:6680/iris/`. Please add this information to the getting started tutorial. 

## Steps to replicate
1.
2.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ ] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [ ] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
Resolved. See https://github.com/jaedb/Iris/wiki/Getting-started#running
