### ISSUE TITLE
[Feature Request] A "Scan" button to run sudo mopidyctl local scan

### ISSUE THREAD

**Issue by hjbotha** [jaedb/Iris#327]
## Expected behavior
A scan button (in settings?) which runs sudo mopidyctl local scan to update the local library when new music has been copied to the music library

## Actual behavior
No button

## Steps to replicate
1.
2.

## Additional details, debug data, logs, etc
This would be really handy as I use a library on a network share so I can't use inotify, and I don't want to have to schedule something with cron as it would be running unnecessarily 99% of the time or introduce huge delays between copying files and them being picked up by Mopidy.

P.S. I've tried loads of different frontends and Iris is not only the only one that's remotely suited to my use case, but hands down the best one, kudos!

**Comment by jaedb** [comment]
Sounds like a good idea. It'll require the user to have allowed sudo-access to `system.sh`, but is totally achievable.

It'd be nice there was some way to expose the output from this, but I think this would be quite tricky to capture via bash + websocket. At best it would be a 'click and forget' interaction with feedback once the scan is complete.

**Comment by jaedb** [comment]
Deployed to production in `3.30.0`. Button can now be found in _Settings > Advanced_.
