### ISSUE TITLE
Fairly regularly the app goes blank when in "Now Playing"-queue view

### ISSUE THREAD

**Issue by wezzynl** [jaedb/Iris#329]
Fairly regularly the app goes blank (just only showing the background color) in the browser. Music keeps playing and a refresh solves it until the next time it occurs (multiple times an hour). It seems to only occur when I have the "Now Playing"-queue showing. When in search or playlist overview it does not seem to happen.

Today I had the devtools console open and when it happened again I saw an error so I thought I'd screengrab the error as that seemed to cause it:

![image](https://user-images.githubusercontent.com/5656741/45751335-55388200-bc12-11e8-957a-d64177edc360.png)

## Expected behavior

Iris goes on its merry way and keeps on displaying the "Now Playing"-queue without me needing to refresh the browser because the app crashed.

## Actual behavior

App crashes, only showing the dark background color (and an error in the console).

## Steps to replicate
1. Add amount of songs to playlist (say 20)
2. Click "Now Playing"
3. Move on to doing work
4. Observe the view going black after X amount of time

#### Operating systems affected
- [ ] Windows:
- [x] Mac:  macOS High Sierra 10.13.6
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: Version 69.0.3497.100 (Official Build) (64-bit)
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x] Huge (ie desktop) (in portrait mode: 1440x2560px)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [x] Yes, I have attached screenshots and/or screencast of the issue in action
- [x] Yes, I have included any relevant debug data and error logs

Let me know if I can supply more info or can test something.

**Comment by jaedb** [comment]
What version of Iris are you running? I've experienced this issue myself and couldn't make heads or tails of it. It's very intermittent and seems to be when a new track gets loaded from the Mopidy server.

As a patch I built an Error Boundary to capture the issue and prevent it from crashing the app. Instead of a broken app, you should just see "Failed to render" on the broken track. This has been in place since about v2.24.0.

**Comment by wezzynl** [comment]
I'm running `v3.25.1` and it's upgrading to `v3.26.0` as we speak.

**Comment by wezzynl** [comment]
Hay James, just a heads up, I've been running `3.26.0` for a while now and the issue seems to have resolved itself in this version! I'm however upgrading to `3.26.2` now so you never know... :)

**Comment by jaedb** [comment]
@wezzynl is this issue no longer occurring since you upgraded?

**Comment by wezzynl** [comment]
Today I upgraded to `3.28.1` and I saw a black screen with "failed to render" in the top left once. Before upgrading to `3.28.1` I think I have not seen the black screen, not sure if it's just coincidence. Unfortunately I was busy and did not open the devtools console to scan for errors.

It's a minor issue though so feel free to close it and maybe revisit when there's some more info to share?

**Comment by jaedb** [comment]
I've added extra debug info to the `ErrorBoundary`, which will help diagnose the issue should it appear again. Please feel free to re-open if this particular issue persists.
