### ISSUE TITLE
"Add to queue" on playlist

### ISSUE THREAD

**Issue by simmel** [jaedb/Iris#330]
## Expected behavior
When I right-click I want to "Add to queue" or "Play Next".
## Actual behavior
N/A
## Steps to replicate
1.
2.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [X] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ ] Chrome: 
- [X] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [X] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [X] Small (phone)

## Before you submit
- [ ] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by simmel** [comment]
I think this used to work but I'm not sure really. I could be mixing it up with something else.

I can't tag this as a feature request but that's what it is.

**Comment by jaedb** [comment]
Released at `3.34.0`
