### ISSUE TITLE
[Question] Authentication

### ISSUE THREAD

**Issue by JamsheedMistri** [jaedb/Iris#331]
Hey, quick question, hopefully you guys can help out.

I'm hosting Mopidy-Iris on a Raspberry Pi in our school's Robotics workshop, hooked up to large speakers. The Spotify account is mine, and I gave people the IP/URL for the Iris client so they can add songs to the queue as they wish.

The Pi is connected to the school wifi, however, and someone outside of our class got a hold of the IP/port. They've written a script to play inappropriate songs every 5 seconds and we've had to unplug the Pi until we come up with a solution.

Do you have any ideas as to what we can do? Can we place any restrictions on Iris and/or Mopidy itself? We were thinking of either whitelisting MAC, blacklisting MAC, or asking for a password in order to access Iris (but there's no feature in Iris to do this).

Please let me know! Thanks.

**Comment by JamsheedMistri** [comment]
Thanks for the reply! While this would be a step in the right direction, our school network is funky so many of our device IPs would be changing constantly — whitelisting IPs would probably not work.

If we were going to do something along the lines of a whitelist/blacklist, we'd need the proxy to blacklist MAC addresses, and from what I can tell that's not possible.

Is it possible to use proxies to somehow require a username/password to access Iris?

**Comment by jaedb** [comment]
Iris itself is not the place to address this, instead you'd want to manage this in the underlying Mopidy server.

You can use Apache to achieve a username/password combination if you were to use it as a proxy (eg https://stackoverflow.com/questions/5011102/apache-reverse-proxy-with-basic-authentication).

**Comment by JamsheedMistri** [comment]
Thanks so much!

**Comment by JamsheedMistri** [comment]
It works... almost! If you could help me with this issue I'd greatly appreciate it. https://stackoverflow.com/questions/52655579/apache-virtualhost-with-authentication-websockets
