### ISSUE TITLE
[Feature Request] sorting options local files

### ISSUE THREAD

**Issue by MaPoLom** [jaedb/Iris#336]
## Expected behavior
Make different sorting options available for local files e..g

filename, date, artist, title, tracknumber

## Actual behavior
There are none at the moment as far as I can tell

**Comment by MaPoLom** [comment]
Would somebody be so kind and explain to me how currently the sorting of local files is organized. I've tried different commands to emulate the sorting of Iris but it seems random.

Thank you.

**Comment by jaedb** [comment]
The display order is just however Mopidy-File returns it (which I agree seems unusual). I don't apply any sorting within Iris.

If you'd like this functionality, just create a new feature request issue :-)

**Comment by jaedb** [comment]
Looking into this further, we get very little information from _Mopidy-File_, which limits what's possible. 

For now I've set the sort as alphabetical descending by the `name` property (aka track name and folder name). This will be included in the next release.

**Comment by jaedb** [comment]
Deployed to production. There isn't any plan to implement any custom sorting as we're very limited in the data provided by _Mopidy-File_, so I'll mark this as closed.

**Comment by MaPoLom** [comment]
thank you!

**Comment by MaPoLom** [comment]
Hi there!

Using version: 3.31.2
Don't know if I can reopen this but the sorting is in my humble opinion still completely random. Or hasn't it released yet?

To give an example: 
output ls -l:
-rwxrwxrwx 1 root root 18419547 Oct 22  2014 Jean Michel Jarre - 01 - Oxygene Part 1.mp3
-rwxrwxrwx 1 root root 19392347 Oct 22  2014 Jean Michel Jarre - 02 - Oxygene Part 2.mp3
-rwxrwxrwx 1 root root  7160772 Oct 22  2014 Jean Michel Jarre - 03 - Oxygene Part 3.mp3
-rwxrwxrwx 1 root root  9890045 Oct 22  2014 Jean Michel Jarre - 04 - Oxygene Part 4.mp3
-rwxrwxrwx 1 root root 25249000 Oct 22  2014 Jean Michel Jarre - 05 - Oxygene Part 5.mp3
-rwxrwxrwx 1 root root 15164690 Oct 22  2014 Jean Michel Jarre - 06 - Oxygene Part 6.mp3

Output Iris:

![image](https://user-images.githubusercontent.com/11076201/49518459-03150d80-f89f-11e8-8191-10b1e3f5e083.png)


Thank you for your response

**Comment by jaedb** [comment]
The initial sort was using the `uri` component, which is reflective of the filename and would achieve A-Z sorting for most cases. However sorting by `name` is probably a lot more useful as this is what is displayed in the frontend.

I've just pushed this re-patch to `develop` for testing now and it'll be included in the next release.
