### ISSUE TITLE
Log in on Spotify not working

### ISSUE THREAD

**Issue by mellorandsmith** [jaedb/Iris#339]
## Expected behavior
Should load the spotify authorization interface

## Actual behavior
Return an error 524 or 522 from cloudflare

## Steps to replicate
1. logout is logged in with spotify
2. try to log in again

#### Operating systems affected
- [x ] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x ] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Additional details, debug data, logs, etc
![image](https://user-images.githubusercontent.com/8489106/47578362-21532980-d941-11e8-855a-ef737084491f.png)
![image](https://user-images.githubusercontent.com/8489106/47578415-3f208e80-d941-11e8-85cc-b3e1647fa159.png)

## Before you submit
- [ x] Yes, I have tested this issue thoroughly
- [x ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by TilmannBach** [comment]
i'm experiencing the same issue (in germany)

**Comment by mellorandsmith** [comment]
No problem, it's back to normal. Thanks for the great work!
