### ISSUE TITLE
[Feature Request] Updated documentation/wiki

### ISSUE THREAD

**Issue by wbh1** [jaedb/Iris#34]
Feature request to add more information regarding initial setup to either the readme or the wiki.

**Comment by jaedb** [comment]
Good idea. Is there any particular area that you would see improved?

**Comment by wbh1** [comment]
I like the documentation of [mopify](https://github.com/dirkgroenen/mopidy-mopify) as an example. Info on "Getting started", listing the changes that you can/should make to your Mopidy config, customization options, and maybe some basic troubleshooting.

**Comment by jaedb** [comment]
See progress: https://github.com/jaedb/Iris/wiki

**Comment by jaedb** [comment]
Wiki well on it's way, it includes the key info to get started. This will evolve over time but for now should do the trick.
