### ISSUE TITLE
making iris default webui for mopidy

### ISSUE THREAD

**Issue by mecaz** [jaedb/Iris#341]
Hello, 

I am using iris on my raspberry pi zero with justboom digi that running dietpi. 
everything running well i can access mopidy addres: http://192.168.1.9:6680/iris/#
i wonder that is there any way to make it http://192.168.1.9 
i want to access iris interface only my device ip, is it possible? 
what should i do?

Regards

**Comment by jaedb** [comment]
This is totally possible. You'll be looking to setup an ngnix or Apache proxy. An example of this for Apache can be found in the [wiki](https://github.com/jaedb/Iris/wiki/Advanced#encryption-httpswss).

**Comment by mecaz** [comment]
Hello, 

İ have installed apache server to my dietpi system from its packet manager. 
i enabled proxy_wstunnel (sudo a2enmod proxy_wstunnel)
i created iris.conf at "/etc/apache2/sites-available/" and pasted conf lines at shown on wiki
unfortunately nothing happened. 
then i checked sites-available directory and find another file named "000-default.conf" 
i edited that file and pasted same virtualhost lines at wiki page.
after restarting apache2 and mopidy when i go to my device ip adress with browser
it says "Not Found
The requested URL / was not found on this server."

please help.
regards

**Comment by mecaz** [comment]
is is same 
When i go to: http://192.168.1.4/iris/

Not Found
The requested URL /iris/ was not found on this server.

Apache/2.4.25 (Raspbian) Server at 192.168.1.4 Port 80

**Comment by jaedb** [comment]
Did you also enable `mod_proxy`, along with the VirtualHost you created (ie `sudo a2ensite iris && sudo service apache2 restart`)?

Here are some useful resources for setting up Apache reverse proxy:
* http://www.microhowto.info/howto/configure_apache_as_a_reverse_proxy.html
* https://2buntu.com/articles/1574/apache-http-server-as-a-basic-forwardreverse-proxy/

**Comment by erikcvisser** [comment]
If you are open to use Nginx instead of Apache as reverse proxy, you can use the below configuration.
I have configured Mopidy to run with SSL enabled (i.e. https:// ) and redirect from http to https. For completeness, I have also included a http-only configuration.

```
server {
  listen       443 ssl;
  server_name  <your server name, or _ if you want to listen to everything>;

  ssl on;
  ssl_certificate <location of your certificate>;
  ssl_certificate_key <location of your certificate's key>;
  ssl_prefer_server_ciphers on;

  location / {
    proxy_pass         http://127.0.0.1:6680/iris/;
    proxy_redirect     off;
    proxy_set_header   Host             $host;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }

  location /mopidy/ {
    proxy_pass         http://127.0.0.1:6680;
    proxy_redirect     off;
    proxy_set_header   Host             $host;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }

  location /iris/ {
    proxy_pass         http://127.0.0.1:6680/iris/;
    proxy_redirect     off;
    proxy_set_header   Host             $host;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
}

server {
  listen       80;
  server_name  <your server name, or _ if you want to listen to everything>;

  return 301 https://$host$request_uri;
}
```


http-only:


```
server {
  listen       80;
  server_name  <your server name, or _ if you want to listen to everything>;

  location / {
    proxy_pass         http://127.0.0.1:6680/iris/;
    proxy_redirect     off;
    proxy_set_header   Host             $host;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }

  location /mopidy/ {
    proxy_pass         http://127.0.0.1:6680;
    proxy_redirect     off;
    proxy_set_header   Host             $host;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }

  location /iris/ {
    proxy_pass         http://127.0.0.1:6680/iris/;
    proxy_redirect     off;
    proxy_set_header   Host             $host;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
}
```

**Comment by mecaz** [comment]
Thanks a lot @erikcvisser 
I installed nginx instead of apache and
It worked. 

Appreciated a lot. 
Regards

**Comment by jaedb** [comment]
Thanks guys - I've updated the wiki to include the HTTPS example.
