### ISSUE TITLE
Touch screen doesnt open the playlist genres etc.

### ISSUE THREAD

**Issue by Daargajedan** [jaedb/Iris#345]
## Expected behavior
When touching a big blok the next page would open, this doesn't happen anymore on a touch event with the screen, in the browser the click event from mouse or trackpad works. But not the touch event from the screen.

![schermafbeelding 2018-12-11 om 22 59 42](https://user-images.githubusercontent.com/3182483/49832986-7edbf200-fd98-11e8-95a6-342c42959220.png)

#### Operating systems affected
-  Raspbian

#### Browsers affected
- [x] Chrome (Kiosk)

#### Screen sizes affected
- The standaard touch screen.

**Comment by jaedb** [comment]
Can you please advise what version of Chrome you're using? Also it'd be super-helpful if you could open the _Developer Tools_ (F12 shortcut key) and screenshot any error messages that pop up when you try and tap on a tile.

**Comment by Daargajedan** [comment]
Yes np,
On start:
<img width="868" alt="schermafbeelding 2018-12-13 om 20 01 34" src="https://user-images.githubusercontent.com/3182483/49961145-2b8daf00-ff12-11e8-97dd-909862f7d84d.png">

On page open:
<img width="868" alt="schermafbeelding 2018-12-13 om 20 02 03" src="https://user-images.githubusercontent.com/3182483/49961157-33e5ea00-ff12-11e8-9e24-b830ec03e418.png">

On a button touch (With screen touch)
<img width="868" alt="schermafbeelding 2018-12-13 om 20 02 39" src="https://user-images.githubusercontent.com/3182483/49961198-52e47c00-ff12-11e8-8dd7-6d60c32144cc.png">

**Comment by jaedb** [comment]
Great, thanks for those extra screengrabs. This is an issue that I've already patched (it affects Safari also).

The latest release (`3.31.3`) resolves this, so please try upgrading, re-testing and confirming whether the issue is resolved for you.

**Comment by Daargajedan** [comment]
Hi James, 

Thanks for youre response! Fortionally i still have the issue on the buttons:

Installed latest version (3.31.6)
Browser: Version 60.0.3112.89 (Developer Build) Built on Ubuntu 14.04, running on Raspbian 9.4 (32-bit)
![schermafbeelding 2018-12-16 om 00 52 00](https://user-images.githubusercontent.com/3182483/50048461-2759c100-00cd-11e9-9992-ce9f065663d5.png)

**Comment by Daargajedan** [comment]
Just updated everything still the issue is there, (Updated via apt-get all latest versions)

**Comment by jaedb** [comment]
Did you restart Mopidy after updating _Mopidy-Iris_ (ie `sudo service mopidy restart`)?

PS. The first screengrab with the service worker error is due to not running Mopidy via a HTTPS proxy. Iris will still run fine without HTTPS. You can read more in the [wiki](https://github.com/jaedb/Iris/wiki/Advanced#encryption-httpswss)

**Comment by Daargajedan** [comment]
Yes i did a reboot aftar all Updates..

First screenshots where IRIS 3.31.4

Yes im looking for local certificates that auto renew or something, not a error i'm looking to solve right now

**Comment by jaedb** [comment]
I've installed a VirtualBox with the Raspbian + Chromium setup you've got but haven't been able to replicate the issue. Admittedly this doesn't accurately reflect your touch device state, but Chromium's touch emulator should have triggered the same error.

Can you please _View source_ of Iris and confirm the build and version shown there? Should be about line 100.

**Comment by Daargajedan** [comment]
Ive updated to 3.31.7 and the problem disapaired. I can't figure out what the problem was. But it is working. 

Thnx for for youre attantion!!!

**Comment by jaedb** [comment]
@Daargajedan Glad you're now up and running smoothly, and thanks for the support :-)
