### ISSUE TITLE
Iris is not responding when Album/Artis name is null [undefined]

### ISSUE THREAD

**Issue by AndrewGolovey** [jaedb/Iris#35]
**Description:**
Some local files do not have Album name in metadata, as a result, Iris UI throws following warning:

`warning.js:36 Warning: performUpdateIfNecessary: Unexpected batch number (current 182, pending 180)`

After that, UI is not responding to any actions 

**Reproduce steps**
Scan local file without Album/Artist name.

**Affects version**
All version of Iriss project, works well in Spotmop

**Comment by jaedb** [comment]
@AndrewGolovey Firstly, thanks for providing detailed description of the issue - it makes life a lot easier!

I've tried removing the metadata on some local test tracks but it still seems to run (albeit with no titles). Can you please attach one or two files that will help me replicate the issue?

**Comment by AndrewGolovey** [comment]
Hi,
Indeed:

**Comment by AndrewGolovey** [comment]
smb://gt/music/music_warehouse/Nightwish%20(1997-2015)/Singles/2001%20Over%20The%20Hills%20And%20Far%20Away%20%5BUniversal%20UICN-15004%20Japan%5D/Nightwish%20-%20Over%20The%20Hills%20And%20Far%20Away%20(Japan%20Edition).flac

**Comment by AndrewGolovey** [comment]
Hi,
Indeed - [Rammstein, Spring.flac](http://fex.net/#!220024428827) It will be here for 7 days. Sorry for such big file, all my library are in flac ;)

More detailed info:
**Behavior**
1. Start to play track - track is playing
2. Try to move on different tab (**Playlist** or **Local** for example)
3. Iris will not change pages.
**Stacktrace**
`Potentially unhandled rejection [1] render@http://gt:6680/iris/app.js:22891:1
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext/renderedComponent<@http://gt:6680/iris/app.js:49018:17
measureLifeCyclePerf@http://gt:6680/iris/app.js:48299:13
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext@http://gt:6680/iris/app.js:49017:28
ReactCompositeComponentMixin._renderValidatedComponent@http://gt:6680/iris/app.js:49044:30
ReactCompositeComponentMixin._updateRenderedComponent@http://gt:6680/iris/app.js:48968:32
ReactCompositeComponentMixin._performComponentUpdate@http://gt:6680/iris/app.js:48946:6
ReactCompositeComponentMixin.updateComponent@http://gt:6680/iris/app.js:48867:8
ReactCompositeComponentMixin.receiveComponent@http://gt:6680/iris/app.js:48769:6
ReactReconciler.receiveComponent@http://gt:6680/iris/app.js:6918:6
ReactCompositeComponentMixin._updateRenderedComponent@http://gt:6680/iris/app.js:48976:8
ReactCompositeComponentMixin._performComponentUpdate@http://gt:6680/iris/app.js:48946:6
ReactCompositeComponentMixin.updateComponent@http://gt:6680/iris/app.js:48867:8
ReactCompositeComponentMixin.performUpdateIfNecessary@http://gt:6680/iris/app.js:48783:8
ReactReconciler.performUpdateIfNecessary@http://gt:6680/iris/app.js:6950:6
runBatchedUpdates@http://gt:6680/iris/app.js:4455:6
Mixin.perform@http://gt:6680/iris/app.js:8351:14
Mixin.perform@http://gt:6680/iris/app.js:8351:14
.perform@http://gt:6680/iris/app.js:4394:13
flushBatchedUpdates@http://gt:6680/iris/app.js:4477:8
Mixin.closeAll@http://gt:6680/iris/app.js:8417:12
Mixin.perform@http://gt:6680/iris/app.js:8364:12
ReactDefaultBatchingStrategy.batchedUpdates@http://gt:6680/iris/app.js:52265:8
enqueueUpdate@http://gt:6680/iris/app.js:4505:6
enqueueUpdate@http://gt:6680/iris/app.js:12252:4
ReactUpdateQueue.enqueueSetState@http://gt:6680/iris/app.js:12437:6
ReactComponent.prototype.setState@http://gt:6680/iris/app.js:11881:4
handleChange@http://gt:6680/iris/app.js:43754:10
dispatch@http://gt:6680/iris/app.js:20301:8
SpotifyMiddleware</</</<@http://gt:6680/iris/app.js:24469:26
PusherMiddleware</</</<@http://gt:6680/iris/app.js:24278:33
MopidyMiddleware</</</</_ret<@http://gt:6680/iris/app.js:23914:37
MopidyMiddleware</</</<@http://gt:6680/iris/app.js:23468:29
UIMiddleware</</</<@http://gt:6680/iris/app.js:24892:26
localstorageMiddleware</</</<@http://gt:6680/iris/app.js:23182:18
createThunkMiddleware/</</<@http://gt:6680/iris/app.js:56910:17
dispatch@http://gt:6680/iris/app.js:56969:19
instruct/</<@http://gt:6680/iris/app.js:23431:18
tryCatchReject@http://gt:6680/iris/app.js:42551:29
runContinuation1@http://gt:6680/iris/app.js:42510:5
makePromise/Fulfilled.prototype.when@http://gt:6680/iris/app.js:42298:5
makePromise/Pending.prototype.run@http://gt:6680/iris/app.js:42189:6
__WEBPACK_AMD_DEFINE_RESULT__</Scheduler.prototype._drain@http://gt:6680/iris/app.js:40779:5
Scheduler/this.drain@http://gt:6680/iris/app.js:40744:5
run@http://gt:6680/iris/app.js:10491:5`
**Environment**
- OS - Linux Mint 18.1
- Browsers: Google Chrome 55.0.2883.87 (64-bit), Firefox 50.1

**Comment by jaedb** [comment]
I've traced it back to when the `Sidebar` module tries to load the album artwork. I've setup an extra check to make sure the track has an album before proceeding. I've confirmed this has fixed the issue using the provided file (thanks for that too), can you double-check it's working now as expected at your end?

**Comment by AndrewGolovey** [comment]
Hi,
I confirm that now Iris is responding when starts track without Artist/Album. Thanks!!!!
But unfortunately looks like now I am unable to searching in local DB. It shows for me results from Spotify but any in local DB ;( Could you please verify

**Comment by jaedb** [comment]
Sweet! I'll close this issue :-)

Yep, I can confirm searching does not include local media (or other backends like SoundCloud) as I'm working through the rebuild of the asset index. Once this is all done and tested I'll push out a new release.
