### ISSUE TITLE
Inclusive CSS media queries collide at exact breakpoints

### ISSUE THREAD

**Issue by opatut** [jaedb/Iris#352]
Media queries are inclusive (min-width/max-width) on both ends, which leads to visual bugs at the exact breakpoint (1200px, 1900px) etc.

https://github.com/jaedb/Iris/blob/a7c8dc9ec88cefacdc0e2bd07e076256f9e4ebb9/src/scss/global/_variables.scss#L237-L263

## Expected behavior

At 1900px, in the albums list, all items are neatly aligned in a grid.

## Actual behavior

At exactly 1900px, every 5th item has no gap to the previous one:

![image](https://user-images.githubusercontent.com/235784/51465910-3a654e00-1d69-11e9-8631-68b8d74678b3.png)

## Suggested solution

In the `responsive` mixin, replace each `$max-width` with `$max-width - 1`. That might already do the trick (to be tested).

## Steps to replicate
1. Resize browser to exactly 1900px width.
2. Go to album list.

#### Operating systems affected
- [x] Linux
- probably all

#### Browsers affected
- [x] Firefox: 
- probably all

#### Screen sizes affected
- [x] Huge (ie desktop)
- [x] Large (ie laptop)
- exactly in between ;)

#### Version

3.31.6

**Comment by jaedb** [comment]
Good spotting, and thanks for the thorough bug report.

This has been resolved and queued up for for next deployment. Feel free to test/preview on the `develop` branch.
