### ISSUE TITLE
'Play next' button not visible on mobile

### ISSUE THREAD

**Issue by qurben** [jaedb/Iris#353]
## Expected behavior

Show the next button in mobile. 

Previously there was a next button in mobile, since I updated the button is gone (still visible on desktop). I couldn't find anything in the changelogs explicitely mentioning it. 

## Actual behavior

Currently there is no next button on mobile

## Steps to replicate
1. Open Iris on mobile
2. Login
3. Notice that the next button is missing

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [x] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [x] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [x] Small (phone)

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [x] Yes, I have attached screenshots and/or screencast of the issue in action
- [x] Yes, I have included any relevant debug data and error logs

![https://i.imgur.com/T3f2wvD.png](https://i.imgur.com/T3f2wvD.png)

**Comment by qurben** [comment]
I did find https://github.com/jaedb/Iris/commit/ffbf3b8de47155d2817cecd8a9c65975b846f6d4, but this is not documented anywhere.

I also just noticed that Spotify itself also does this. A view with next/previous buttons on mobile would be something I'd really like.

**Comment by mczerski** [comment]
Uuu, i also think that removing next button is a very bad idea... This is not what the user expects.

**Comment by DavisNT** [comment]
I would suggest adding a setting that shows the "next" button in mobile (and maybe adds "previous" button as well). 
Spotify (at least latest Android version available to me) has the "next" and "previous" buttons in the screen that is shown shen tapping on the currently playing track name ([screenshot](https://user-images.githubusercontent.com/4958774/52888120-21db2e80-3183-11e9-93b2-46b5183e38e3.png)).

**Comment by daverck** [comment]
Swiping does not work on neither my galaxy tab s2 nor my galaxy s7.
Switching tracks is a very basic and important feature it is very lacking right now.

**Comment by dionysiusmarquis** [comment]
On mobile I always went to “now playing“ searching and played the next song manually. The swipe isn‘t something that is learned or intuitively done in my experience. There should be a hint on screen to inform about this feature. Or at least next/prev in the panel where you find the volume etc. to still be able to navigate the songs if you missed or can’t use this feature.
