### ISSUE TITLE
[Feature request] snapcast: Show hostID instead of host name

### ISSUE THREAD

**Issue by breiti** [jaedb/Iris#354]
Snapcast allows to set a [unique hostID for every client](https://github.com/badaix/snapcast/blob/master/client/snapClient.cpp#L104). Right now, the list of Snapcast clients in Iris shows the hostname of all clients. It would be nice if it shows the hostID instead.

For one, this would make it easy to make the interface show nice names like 'Kitchen' instead of a host name.

In my case, I have some hosts that run multiple instances of snapclient where each of these instances plays to different rooms. In the interface they all show up under the same name, making it impossible to know which one applies to which room.

**Comment by jaedb** [comment]
If I understand your report correctly, you can already do this. Every client can have it's name customised to whatever you wish (and uniqueness is not enforced by either Iris or Snapcast).

Have a look at _Settings > Snapcast > Expand a client > Name field_. The value will be saved on blur of the field.

Does this resolve your concern?

**Comment by breiti** [comment]
You are right, I missed the settings for Snapcast. The settings you describe solve my problem.

Thank you!
