### ISSUE TITLE
Allow option to disable/enable for playlist search animation

### ISSUE THREAD

**Issue by jareddreyer** [jaedb/Iris#357]
## Description
When searching in a playlist that is extremely long you can somewhat feel lost in the animation of searching for a title. Because the highlight of text has reached the point where the match is (which could be many scrolls away from the current viewport) the animation then moves the scrollbar slowly, which distracts and disorientates the user. This effect is worse if it searches upwards in the playlist.

## Idea Request
Add option (checkbox?) in 'Settings' to disable or enable search animation for those who don't wish to use this feature.

**Comment by jaedb** [comment]
Scheduled for next release. Setting added under _Settings > Interface > Behavior > Enable smooth scrolling_. 

This will toggle smooth scrolling in it's entirety; there is no way to selectively disable it when using the browser search functionality.
