### ISSUE TITLE
Drill down on All results no longer works

### ISSUE THREAD

**Issue by jareddreyer** [jaedb/Iris#358]
## Expected behavior
Clicking "All Artists" or "All Albums" or "All Playlists" should take user to playlist of search results.

## Actual behavior
Returns error. E.g. when clicking "All Albums" it takes user to http://iris.music:6680/iris/search/album/music and reports error "Not found. Oops, that link could not be found"

## Steps to replicate
1. Open Search
2. Enter term
3. Click any of the buttons; "All Artists", "All Albums", "All Playlists"

#### Operating systems affected
- [x] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Additional details, debug data, logs, etc
![image](https://user-images.githubusercontent.com/8870250/52189878-46402c80-28a0-11e9-9b75-8b6c22ce3968.png)

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [x] Yes, I have attached screenshots and/or screencast of the issue in action
- [x] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
Resolved at `3.31.4`
