### ISSUE TITLE
Feature request: YouTube support 

### ISSUE THREAD

**Issue by lukasmrtvy** [jaedb/Iris#360]
**What?**
Add support for youtube.

**Why?**
YT is great 'music' library.

I am aware of https://github.com/jaedb/Iris/issues/301, but it is closed.

mopidy-youtube is now discontinued:
https://github.com/mopidy/mopidy-youtube/issues/87

Can You look at this?
https://github.com/mps-youtube/pafy
https://github.com/mps-youtube/mps-youtube

I think that YouTube support is a future major feature for this great project.

**Comment by jaedb** [comment]
I agree completely - there is a heap of musical content on YouTube that would be great to enjoy through Mopidy. However this is not the purpose of Iris; Iris is just a frontend interface to manage and control Mopidy.

What you're asking for is for a new repository maintainer for `Mopidy-Youtube` or a replacement extension. This has already been asked for: https://github.com/mopidy/mopidy-youtube#maintainer-wanted.
