### ISSUE TITLE
nginx reverse proxy - Tornado shows 404 for /iris/ws/

### ISSUE THREAD

**Issue by alorimer** [jaedb/Iris#361]
I have set up a reverse proxy with nginx, according to https://github.com/jaedb/Iris/wiki/Advanced#nginx. My nginx config is pasted below.

When accessing Iris through http://host.domain:6680/iris, all works well (accessing the Tornado server directly). However, when I go to http://host.domain:80/iris (i.e. through the nginx proxy), the frontend seems to load but I get a notification every few seconds saying "Mopidy disconnected", and none of the functions actually work. I also get notifications saying "Could not load [config|radio|version|queue metadata|connections]".

Looking at `mopidy.log`, the following messages seem to correlate with the frontend notifications:  
`10:51:38,387 WARNING [4013:HttpServer] tornado.access: 404 GET /ws/ (127.0.0.1) 5.42ms`  
`10:51:38,688 INFO [4013:HttpServer] tornado.access: 101 GET /iris/ws/ (127.0.0.1) 7.68ms`

Why is the websockets directory 404ing? Tornado thinks the requests are coming from localhost, so is localhost being denied access despite having `hostname = 0.0.0.0` in the mopidy http config?

I've tested this on several outbound ports, several local ports, with/without SSL, and with several domains (including plain IP). I can't figure it out for the life of me.

Both mopidy and nginx are running as systemd units. This is on mopidy 2.2.2, Iris 3.32.4, nginx 1.14.2, Arch Linux 4.14.97-1.

## Steps to replicate
1. Set up mopidy and Iris with frontend on port 6680
2. Set up nginx proxy as per config below

## nginx config
```
events {
}

http { 
	server {
		listen 80 default_server;
		listen [::]:80 default_server;
		return 301 https://$host$request_uri;
	}
	server {
		listen 443 ssl;
		listen 80;

		server_name gustav.nasci.cc;

		ssl on;
		ssl_certificate /etc/letsencrypt/live/gustav.nasci.cc/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/gustav.nasci.cc/privkey.pem;
		ssl_prefer_server_ciphers on;

		location / {
			proxy_pass         http://127.0.0.1:6680/iris/;
			proxy_redirect     off;
			proxy_set_header   Host              $host;
			proxy_set_header   X-Real-IP         $remote_addr;
			proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
			proxy_set_header   X-Forwarded-Proto $scheme;
			proxy_set_header   Upgrade           $http_upgrade;
			proxy_set_header   Connection "upgrade";
		}

		location /mopidy/ {
			proxy_pass         http://127.0.0.1:6680/;
			proxy_redirect     off;
			proxy_set_header   Host             $host;
			proxy_set_header   X-Real-IP        $remote_addr;
			proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
			proxy_set_header   X-Forwarded-Proto $scheme;
			proxy_set_header   Upgrade $http_upgrade;
			proxy_set_header   Connection "upgrade";
		}

		location /iris/ {
			proxy_pass         http://127.0.0.1:6680/iris/;
			proxy_redirect     off;
			proxy_set_header   Host             $host;
			proxy_set_header   X-Real-IP        $remote_addr;
			proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
			proxy_set_header   X-Forwarded-Proto $scheme;
			proxy_set_header   Upgrade $http_upgrade;
			proxy_set_header   Connection "upgrade";
		}
	}
```

Screenshot of web interface - https://imgur.com/a/A8IAnEu

**Comment by jaedb** [comment]
@erikcvisser can you please provide guidance on this? It looks like the nginx proxy configuration is missing some key endpoints.


PS: as a side-note you can manually set the Mopidy server details (within Iris: _Settings > Server > Host/Port_), which can be helpful for debugging proxy issues.

**Comment by alorimer** [comment]
@jaedb I'm pretty sure `ws://` is not a valid protocol in nginx configurations. I know it's used by Apache but I thought the point of `proxy_set_header  Upgrade $http_upgrade;` was to run websockets over HTTP. More info about this here - https://nginx.org/en/docs/http/websocket.html

Regardless, I tried replacing `ws://` with `http://` in your additions, which produced a valid config, but didn't affect the problem. Hm :/

**Comment by erikcvisser** [comment]
Sorry for the late response.

I cannot reproduce the errors you have @alorimer - the config I submitted works on my machine. I also see no errors in mopidy.log.

Indeed, it is my understanding that websockets are run over HTTP in nginx, through the two upgrade headers. I'm observing two successful GET calls to wss://(..)/iris/ws and /mopidy/ws that return a HTTP 101 status code 'Switching Protocols'. It seems that /iris/ws is working for you, but the second request is going to /ws/ instead of /mopidy/ws. I am not sure what's causing that.

@jaedb I don't think there is a need for explicit specification of the ws endpoints in nginx config. They are subdirectories of a location that is already specified: /iris/ws matches the /iris/ location directive, and, contrary to Apache, we don't need different config for HTTP and ws.

The /images/ location directive was indeed missing on the Wiki. Not all headers may be required to be set here, but cannot test at this moment.

		location /images/ {
			proxy_pass         http://127.0.0.1:6680/images/;
			proxy_redirect     off;
			proxy_set_header   Host             $host;
			proxy_set_header   X-Real-IP        $remote_addr;
			proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
			proxy_set_header   X-Forwarded-Proto $scheme;
			proxy_set_header   Upgrade $http_upgrade;
			proxy_set_header   Connection "upgrade";
		}

**Comment by w1d3m0d3** [comment]
```nginx
server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;

    location /iris/ws {
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;
        proxy_pass         http://127.0.0.1:8080/iris/ws;
    }

    location /mopidy/ws {
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;
        proxy_pass         http://127.0.0.1:8080/mopidy/ws;
    }

    location / {
        proxy_pass         http://127.0.0.1:8080/;
    }
}
```

**Comment by jaedb** [comment]
@w1d3m0d3 the configuration you've provided above, is that tested and fully-functioning? Is there anyone else who can verify that this setup works for them?

If it is working, I will amend the documentation (along with #426).

**Comment by BrainStone** [comment]
I'd recommend using my config, as it does essentially the same in a better way (plus adds the redirect)

**Comment by w1d3m0d3** [comment]
@jaedb Last time I've used it it did work, however I am not in a situation in which I can test it right now.

**Comment by erikcvisser** [comment]
I'd recommend @BrainStone's config as well. WIth the 301 on root location there is no need for the deep proxy_pass-ing, making it a cleaner solution.

**Comment by jaedb** [comment]
Cheers - documentation updated.

**Comment by lblabr** [comment]
where i can find a working nginx config?
