### ISSUE TITLE
Local scan failed

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#365]
Hi,

I am running Iris 3.32.4, mopidy 2.2.1 on a Raspberry PI3 with Rasbian Stretch.

From "Settings" page I tried to run a local scan, but a red pop-up was showing "Local scan failed", with no entry in mopidy log file. I can run a scan from terminal with `sudo mopidyctl local scan`, but I'm not able to do it from Iris.

Am I missing something?

Thanks

**Comment by jaedb** [comment]
Have you followed the setup instructions for adding sudo access to Iris?

**Comment by fmarzocca** [comment]
You're right, of course. I forgot that line. Now I added mopidy to sudoers for iris system.sh and now it is working.

Thanks
