### ISSUE TITLE
Can I edit radio names in playlist?

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#367]
I tried to edit the Radio Station name in the .m3u playlist file, but it doesn't change. I would like to add Radio station location to the name. Is it possible?

**Comment by jaedb** [comment]
You may need to change the file directly. I don't believe Mopidy can manipulate playlist tracks (which is what a stream is).

**Comment by fmarzocca** [comment]
That's what I did: modified the file directly, but the changes are not shown on the Playlist. I suspect that the Radio station name is always refreshed from Internet...

**Comment by jaedb** [comment]
You're right - the `name` of a stream track is pulled from the stream itself by the `http` extension (part of the Mopidy core). This means Iris cannot get the EXTINF data that you define in the `m3u8` file.

**Comment by jaedb** [comment]
For reference: #8
