### ISSUE TITLE
Album artwork in files, but not displayed

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#368]
I have checked my local mp3 files with an ID3 tag inpector, and some of them have cover artwork embedded.
In such a case, I think I don't need mopidy-local-images and Iris should display the album artwork from mp3 files. But it doesn't.

**Comment by jaedb** [comment]
You will require _Mopidy-Local-Images_ in order to display any file's artwork. Once installed, run `mopidyctl local scan` to scan your library and prepare artwork, and restart Mopidy. Then you should see your artwork as intended.

**Comment by fmarzocca** [comment]
installed Mopidy-Local-Images and configured this way:

```
[local-images]
enabled= true
library=sqlite
base_uri=/music/images/
image_dir=
album_art_files = *.jpg, *.jpeg, *.png
```

then I run:

```
sudo mopidyctl local clear
sudo mopidyctl local scan
```

No changes. No Album artwork. Only artists.

**Comment by fmarzocca** [comment]
Ok. Configured and enabled.
Now Cover Images are shown (only from those files with embedded cover art) as expected, thanks.

BTW, do you know if there is any way to gather cover art images from Last.fm? In my Android app MPDroid I have all cover images, included thos file without ID£ image-tag embedded.

**Comment by fmarzocca** [comment]
I have browsed app.js and find this code snippet:

```
    // load artwork from LastFM
                            if (album.images.length <= 0) {
                                var mbid = helpers.getFromUri('mbid', album.uri);
                                if (mbid) {
                                    store.dispatch(lastfmActions.getAlbum(false, false, mbid));
                                } else {
                                    store.dispatch(lastfmActions.getAlbum(album.artists[0].name, album.name));
                                }
                            }
```

Isn't it to load cover album image from LastFM?

**Comment by jaedb** [comment]
Technically yes, however the LastFM API is subject to relatively low request quotas. I've used it sparingly for this reason. Album artwork is feasible by embedding artwork in the albums whereas artists this is not possible, hence using LastFM only for artists.

That snippet is legacy code that is not currently being used, but it is how one could use LastFM for local album artwork.

**Comment by fmarzocca** [comment]
@jaedb , thank you very much for your assistance. When I rip a CD audio of mine, album cover is not embedded so I need to do some more work to edit the ID3 tags and embed the artwork. This is annoying.
In  your opinion, is it a major modification trying to add to Iris the capability to gather albums cover from the Internet?
