### ISSUE TITLE
artist is_loading_tracks forever

### ISSUE THREAD

**Issue by dukrat** [jaedb/Iris#371]
## Expected behavior
All artist load
## Actual behavior
Artist with tracks that are on their albums (they are the album artist) that are not the artist of the track (i.e. track "Lolo (intro)" by "Dr. Dre feat. Xzibit & Tray Deee" on album "2001" by "Dr. Dre") do not load depending on which track returns from mopidy first
## Steps to replicate
1.  Have such a track
2.  Try to load artist

#### Operating systems affected
- [x] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [ ] Firefox: 
- [x] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [ ] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Additional details, debug data, logs, etc
See PR that mentioned this for ugly workaround.  
## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by dukrat** [comment]
Abridged mopidy return for example track:

{"jsonrpc": "2.0", "id": 55, "result": [{"album": {"__model__": "Album", "name": "2001", "num_tracks": 23, "uri": "local:album:mbid:e11b78b7-e2aa-4a40-868c-64212bc77c09", "images": ["/images/0d41bdc7730179b9e17aa57cc37a163f-800x800.png"], "artists": [{"__model__": "Artist", "musicbrainz_id": "5f6ab597-f57a-40da-be9e-adad48708203", "name": "Dr. Dre", "uri": "local:artist:md5:a064f2d25c607f8f672336bc2851e325"}], "date": "1999-11-16", "musicbrainz_id": "e11b78b7-e2aa-4a40-868c-64212bc77c09", "num_discs": 1}, "composers": [{"__model__": "Artist", "name": "Not Applicable", "uri": "local:artist:md5:8349f6a673db7246536a4b3c5a990cd2"}], "__model__": "Track", "name": "Lolo (intro)", "disc_no": 1, "uri": "local:track:library%5CDr.%20Dre%5C2001%5C01-Lolo%20%28intro%29-Dr.%20Dre-2001.ogg", "comment": "Amazon.com Song ID: 204121577", "date": "1999-11-16", "length": 41142, "last_modified": 1550640016123, "track_no": 1, "artists": [{"__model__": "Artist", "musicbrainz_id": "5f6ab597-f57a-40da-be9e-adad48708203", "name": "Dr. Dre feat. Xzibit & Tray Deee", "uri": "local:artist:md5:77c5ae518770cca6a3b8424f13396036"}], "genre": "Rap & Hip-Hop", "musicbrainz_id": "130098f1-caef-4401-b078-bef0ef6e5791"}, 
...

**Comment by jaedb** [comment]
This issue doesn't affect all artists - only those where the track artist's URI does not match that of the album artist's URI. This appears to be mainly an issue where a library has been mapped with md5 values (eg `"local:artist:md5:77c5ae518770cca6a3b8424f13396036`). In some cases these artists have different URIs for some reason. Possibly due to duplicate data in your indexing provider (eg Media Monkey).

I have managed to replicate this with a very small number of artists, but a reliable fix will be tricky to achieve as it will mean we need to overwrite artist URIs which I suspect will introduce more issues than it solves.

**Comment by dukrat** [comment]
Yeah that sounds about right.  

In my case I use beets that labels MUSICBRAINZ_ARTISTID with the first track artist when there are multiple.  Picard will use a pretty offensive artist1/artist2/... setup.  Therefore in my case setting use_artist_mbid_uri = true for Mopidy-local-sqlite would fix a lot of issues, but there are still some tracks on albums where the first (or only) track artist doesn't match (though I'm not sure if any in my library would be the first returned track).  

That would be one way to fix it, but it does seem very tricky.  

I wasn't able to figure out how to test it, but I seem to recall thinking that loading just the album artist would be sufficient.  If so, enriching the mopidy return with the requested artist somehow or maybe separating the artist loading from the track loading might work without requiring messing around with overwrites.
