### ISSUE TITLE
404 on Track Info

### ISSUE THREAD

**Issue by fa7ad** [jaedb/Iris#373]
## Expected behavior
Previously, when I click on a Track's name from Now Playing it would show the lyrics for that track.
## Actual behavior
Since the last couple of updates, I get a blank page. When I refresh, I get a 404 page
## Steps to replicate
1. Play any track
2. Go to now Playing
3. Click on its name or Right click and select Track Info.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: 
- [ ] iOS: 
- [x] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [x] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ ] Huge (ie desktop)
- [x] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [x] Small (phone)

## Before you submit
- [ ] Yes, I have tested this issue thoroughly
- [x] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

![2019-02-23-123628_1920x1080_scrot](https://user-images.githubusercontent.com/7447677/53282839-ad4a5600-3767-11e9-81cf-91f11cc3e93a.png)

**Comment by fa7ad** [comment]
Just in case you need it,

URL in the screenshot is:
```
http://localhost:6680/iris/track/local%3Atrack%3APorcupine%20Tree%2FIn%20Absentia%20%282002%29%2F01.%20Blackest%20Eyes.flac
```

**Comment by jaedb** [comment]
The issue appears to be because Mopidy gives us track URIs with slashes in them. This throws both the Tornado webserver and Iris' URL handling rules.

**Comment by fa7ad** [comment]
@jaedb what changed about the url parsing logic between the last couple of releases and say 3.27.x

**Comment by jaedb** [comment]
`react-router` v4 was the big change that I believe is where this would have stopped working. The way URLs and their components are handled required a major overhaul of the URL scheme in Iris.
