### ISSUE TITLE
[Feature request] ncmpcpp-like shortcuts

### ISSUE THREAD

**Issue by roosemberth** [jaedb/Iris#374]
Pretty much the title. I find myself usually switching to ncmpcpp in my scratchpad to do stuff like `cy` (clear all elements), `l` (check lyrics), `~` (Go to album). I think it'd be nice to provide an opt-in feature to emulate ncmpcpp shortcuts.

**Comment by jaedb** [comment]
It's definitely a "power user" level feature. I think you'll find that the majority of users will end up accidentally clearing elements and navigating the interface without meaning to. To handle this it needs some degree of "undo" (think Gmail's web interface). This is a huge undertaking and would need to benefit a large number of users to warrant the development effort.

In the meantime I have changed the shortcut keys to be hotkeys (more like ncmpcpp) where it is a single-key shortcut. Check them out in [Keyboard shortcuts](https://github.com/jaedb/Iris/wiki/Features#keyboard-shortcuts).

**Comment by jaedb** [comment]
Hotkeys are supported for a select few functions. This is the foundation for future hotkeys, so if you have a specific hotkey request, please open a new ticket.
