### ISSUE TITLE
Weird GUI Misalignment

### ISSUE THREAD

**Issue by luken8628** [jaedb/Iris#375]
## Expected behavior
Normal UI

## Actual behavior
https://imgur.com/a/1EuJYdw

bottom of the screenshot the little icons are all messed up

Additionally, I cannot seem to find local media when I go to browse > local > artist.  All artists show, and Mopidy has scanned successfully but actual tracks do not display.

If I do a local search though, I can find things.

## Steps to replicate
Open Iris

Ive tried to uninstall and reinstall via pip.  Different browsers, incog. Little icons are always messed up.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [ ] Linux: 
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x ] Chrome: 
- [ x] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [ x] Huge (ie desktop)
- [ x] Large (ie laptop)
- [ ?] Medium (ie slim laptop/tablet)
- [ ?] Small (phone)

## Before you submit
- [ x] Yes, I have tested this issue thoroughly
- [ x] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by luken8628** [comment]
edited Imgur album to also include the lack of ability to browse

**Comment by luken8628** [comment]
anyone got any advice here?  Instructions how to completely remove Iris and any leftover folders that pip uninstall doesn't get?

**Comment by jaedb** [comment]
@luken8628 please create a new issue for your library / search bug.

The icon misalignment appears to be due a specific resolution responsive rule. Please help me by answering:
1. what resolution are you running (assuming browser is full-screen)
2. are you magnified in the browser (ie 120%)

**Comment by luken8628** [comment]
Hmm.  I tried adjusting browser window sizes and had the same issue, including going full screen.  

#1.  I am on a 15in Mid 2015 Retina MBP.  Apple does not list my actual resolution, but here are my settings and hopefully relevant helpful info...  https://imgur.com/a/CSaClAz

#2.  No magnification in the browser.
