### ISSUE TITLE
Play All doesn't work...

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#376]
I have seen that this issue has already been reported and closed, but the bug is still there: by pressing "`Play All`" in Browse->Files, nothing happens...

**Comment by jaedb** [comment]
In that case it would be more practical to keep the conversation on that existing issue. I presume you're talking about #333? 

Please comment on #333 and be sure to include more information, including:
* screenshots
* some example track info (a screenshot of these)
* inclusion of any error messages you may encounter.
