### ISSUE TITLE
No tracks show when browsing local media

### ISSUE THREAD

**Issue by luken8628** [jaedb/Iris#377]
## Expected behavior
Being able to see tracks when browsing local media

## Actual behavior
Upon navigating trough the UI & Down the folder structure when browsing local media, I never see any actual tracks despite them being there, since search works fine.

## Steps to replicate
1. Browse > Local Media > Any Artist > Any Album > **missing tracks**
2.

#### Operating systems affected
- [ ] Windows:
- [x ] Mac: browsing on mac
- [ x] Linux: mopidy and iris on RPI
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [x ] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x ] Huge (ie desktop)
- [ x] Large (ie laptop)
- [ ] Medium (ie slim laptop/tablet)
- [ ] Small (phone)

## Additional details, debug data, logs, etc
Let me know how to pull you the relevant logs if needed.  Not too sure how to do it myself

## Before you submit
- [x ] Yes, I have tested this issue thoroughly
- [x ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

I have tried clearing my mopidy library and rescanning, reinstalling Iris.

**Comment by luken8628** [comment]
issue in action

https://www.dropbox.com/s/mptc53g4hmlhmt4/mopidy%20search%20issue.mov?dl=0

**Comment by jaedb** [comment]
Have you got _Mopidy-Local-Sqlite_ installed?

**Comment by luken8628** [comment]
osmc@LRMopidy:~$ sudo pip install Mopidy-Local-Sqlite
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting Mopidy-Local-Sqlite
  Downloading https://files.pythonhosted.org/packages/e0/db/aa4640a6045c0550b872adc0d8f053470d6914ecc21c9b5c8a44aea73710/Mopidy_Local_SQLite-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: Mopidy>=1.1 in /usr/lib/python2.7/dist-packages (from Mopidy-Local-Sqlite) (2.1.0)
Requirement already satisfied: Pykka>=1.1 in /usr/lib/python2.7/dist-packages (from Mopidy-Local-Sqlite) (1.2.1)
Requirement already satisfied: uritools>=1.0 in /usr/local/lib/python2.7/dist-packages (from Mopidy-Local-Sqlite) (2.2.0)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from Mopidy-Local-Sqlite) (33.1.1)
Requirement already satisfied: ipaddress; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from uritools>=1.0->Mopidy-Local-Sqlite) (1.0.22)
Installing collected packages: Mopidy-Local-Sqlite
Successfully installed Mopidy-Local-Sqlite-1.0.0

**Comment by fmarzocca** [comment]
I suggest to clear and rebuild local library.

```
sudo mopidyctl local clear
sudo mopidyctl local scan
```

**Comment by luken8628** [comment]
thanks, running now.  I have a large library... Reporting back in a few hours or tomorrow morning!

**Comment by luken8628** [comment]
ugh, same thing, going to try again, rebooting mopidy before running the new local scan

**Comment by luken8628** [comment]
not sure if this helps, but getting these with verbose logging enabled, also getting a ton of server errors when browsing around in the settings...  Anyone know how to clear out Iris completely, so I can start with a fresh install.  I am looking specifically where I can clean up all leftover files that may remain after a pip uninstall mopidy-iris

`[Violation] 'focus' handler took 3120ms
middleware.js:128 [Violation] 'setTimeout' handler took 401ms
middleware.js:144 [Violation] 'setTimeout' handler took 392ms
[Violation] 'focus' handler took 3057ms`

**Comment by luken8628** [comment]
Did some more investigating this morning.  Clean install of Mopidy + Iris = Issue still present.  

Also installed another web extension and was able to browse local media normally.  Looks like an Iris only issue.

**Comment by juzam** [comment]
I can confirm that this issue is still present in version Iris version `3.34.1`. I use Firefox on OSX, which is different from what @luken8628 was using. I don't have`Mopidy-Local-Sqlite` installed but I have `Mopidy-Local-Images`.

I've tried to rebuild the library from scratch but that doesn't change anything. 
Browsing Local media with another frontend be it web or command line works fine.

**Comment by luken8628** [comment]
glad to see its not just me @juzam, felt like I was taking crazy pills there for a bit

**Comment by jaedb** [comment]
@luken8628 have you run through the [setup instructions](https://github.com/mopidy/mopidy-local-sqlite#configuration) for _Mopidy-Local-SQLite_? 

All will run smoothly once you have this setup, so I think the issue is isolated to the `json` library provider. Are you able to confirm? The key is setting `library = sqlite` under the `[local]` section.

**Comment by luken8628** [comment]
confirmed fixed @jaedb thanks!!

I was missing that flag, funny because I never remember having to set that before.  Oh well!  Sending a beer or two your way.
