### ISSUE TITLE
CD artwork weird issue

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#378]
Hi,

I am using Mopidy-CD plugin. I can browse my CD from IRIS->Browse window but the cover artwork keeps the same even when I change the CD with another one. Tracks are refreshed, but not artwork.

Is there any way I can improve this?

**Comment by jaedb** [comment]
@fmarzocca can you please complete the issue template? This allows me to gather the necessary information to replicate the issue and efficiently develop the fix.

**Comment by fmarzocca** [comment]
Hi James, sorry I forgot to close this. I think it was just a cache problem with the plugin mopidy-cd. Now it working.
