### ISSUE TITLE
Sorting local albums by artist does not work

### ISSUE THREAD

**Issue by haaase** [jaedb/Iris#379]
## Expected behavior
Sorting local albums by artist in the "Albums" view should sort the albums accordingly.

## Actual behavior
The albums are still sorted by album title instead of artist name.

## Steps to replicate
1. Open albums view
2. Select source -> local to only display local albums
3. Select sort -> artist to sort by artist

## Tested environment(s)
Chrome 72.0.3626.96 on Linux
Firefox 65 on Linux
Chromium 72 on Android 7.1

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: 
- [ ] iOS: 
- [x] Android:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [x] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x] Huge (ie desktop)
- [x] Large (ie laptop)
- [x] Medium (ie slim laptop/tablet)
- [x] Small (phone)

## Additional details, debug data, logs, etc

Sorting of Spotify albums seems to work fine.

The screenshots below illustrate the issue:

![Screenshot from 2019-03-17 16-29-14](https://user-images.githubusercontent.com/9250536/54493579-083c1c80-48d2-11e9-91ff-cf0618968771.png)
![Screenshot from 2019-03-17 16-29-31](https://user-images.githubusercontent.com/9250536/54493581-0d00d080-48d2-11e9-87bc-4fcd5daa24af.png)

![Screenshot from 2019-03-17 16-29-43](https://user-images.githubusercontent.com/9250536/54493599-299d0880-48d2-11e9-9dde-4ee931e819b6.png)
![Screenshot from 2019-03-17 16-29-51](https://user-images.githubusercontent.com/9250536/54493601-2c97f900-48d2-11e9-8a87-bc9d36f18dbc.png)

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [x] Yes, I have attached screenshots and/or screencast of the issue in action
- [x] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
This is a frustratingly good bug! I've been playing around with the sorting mechanics but can't find a solid reason for the botched sort.

Can you please switch to list view (_View > List_) and take another screenshot of the issue in action?

**Comment by haaase** [comment]
Sure, here they are.

I just noticed that it interestingly only displays the album artist for a few of my local albums and those seem to be sorted correctly. Could this be a problem with my Mopidy library? However, if I click on one of the albums with missing album artists, it suddenly displays the album artist correctly (see last screenshot).

![Screenshot from 2019-04-09 12-34-39](https://user-images.githubusercontent.com/9250536/55793914-4ccb6a00-5ac4-11e9-90d3-a47710127c7d.png)
![Screenshot from 2019-04-09 12-36-32](https://user-images.githubusercontent.com/9250536/55793938-5785ff00-5ac4-11e9-8279-ab5bda87da50.png)

![Screenshot from 2019-04-09 12-34-16](https://user-images.githubusercontent.com/9250536/55793994-784e5480-5ac4-11e9-930e-07ac2b3a51d8.png)
![Screenshot from 2019-04-09 12-36-11](https://user-images.githubusercontent.com/9250536/55793953-6076d080-5ac4-11e9-87d3-39999ddcaa59.png)

![Screenshot from 2019-04-09 12-37-11](https://user-images.githubusercontent.com/9250536/55794238-0aeef380-5ac5-11e9-9a38-917fca5db340.png)

**Comment by dukrat** [comment]
I have a few artists like this.  In my case it seems to stem from ALBUMARTIST and/or ALBUM ARTIST tag being present but blank on the files.  Which causes the mopidy album object to be missing the artists attributes.
