### ISSUE TITLE
Now playing page shows Unknown error with mopidy-internetarchive

### ISSUE THREAD

**Issue by kartsan** [jaedb/Iris#380]
## Expected behavior

_Now playing_ page shows the list of searched and added tracks when using mopidy-internetarchive.

## Actual behavior

Some searched and added tracks are not visible, instead there is an error message "Unknown error" and a backtrace.

## Steps to replicate

1. Install mopidy-internetarchive backend
2. Go to Search and find some tracks, for example use query "black".
3. Go to an album and start playing a track.
4. Take another track and choose "Play next"
5. Go to Now playing page to see an error

#### Operating systems affected
- [x] Windows:
- [ ] Mac: 
- [x] Linux: 
- [ ] iOS: 
- [x] Andriod:
- [ ] Other:

#### Browsers affected
- [x] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [ ] Other:

#### Screen sizes affected
- [x] Huge (ie desktop)
- [x] Large (ie laptop)
- [x] Medium (ie slim laptop/tablet)
- [x] Small (phone)

## Additional details, debug data, logs, etc

I actually spotted this issue when testing my mopidy extension (https://github.com/kartsan/mopidy-yle/) but since that extension needs a bit more challenging configuration than mopidy-internetarchive, I chose that for error replication environment. The same issue exists in the both of the extensions.

![unknown_error](https://user-images.githubusercontent.com/6375154/54536995-68969100-499a-11e9-96d1-6a6ca9196e70.png)

Chrome developer console error: https://pastebin.com/8zAEeL96

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [x] Yes, I have attached screenshots and/or screencast of the issue in action
- [x] Yes, I have included any relevant debug data and error logs

**Comment by jaedb** [comment]
Are you able to enable Test mode (_Settings > Debug > Test mode_) and look at your browser console (typically F12 keyboard shortcut)? I believe I've solved the issue, but a screenshot of your browser console may help confirm this.

**Comment by kartsan** [comment]
I'm not very familiar with the web stuff so that's why I decided to open this as an issue for discussion. It's of course possible that something is missing in my code or environment. Anyways, I run Test mode and pasted the error from console to https://pastebin.com/AsA3iDxH. Is that helpful or do you need something else?

**Comment by jaedb** [comment]
@kartsan absolutely, that's exactly what I'm after. That error is now resolved, so I expect this issue will be resolved when the next release rolls out :-)

**Comment by kartsan** [comment]
Cool. Thanks @jaedb !

**Comment by jaedb** [comment]
Released at `3.34.0`
