### ISSUE TITLE
space in m3u playlist filename mistranslated

### ISSUE THREAD

**Issue by pepicek1977** [jaedb/Iris#381]
## Expected behavior
Radio stations contained in m3u playlist with filename `[ Radiozenders ].m3u` should display. 

## Actual behavior
Filename `[ Radiozenders ].m3u` shows an error in Mopidy Iris version 3.33.0 (and a couple of versions prior to this latest release): 

`Could not find playlist with URI "m3u%3A%5B%2520Radiozenders%2520%5D.m3u8"`

The space in the filename should translate to %20, but instead translates to %2520. As %25 is the percent sign, it looks like space is correctly translated to %20, then further translated to incorrect %2520.

## Steps to replicate
1. Create m3u playlist by this name.
2. Try to display it.

#### Operating systems affected
- [ ] Windows:
- [ ] Mac: 
- [x] Linux: Raspberry Pi (the server running Mopidy)
- [ ] iOS: 
- [ ] Andriod:
- [ ] Other:

#### Browsers affected
- [ ] Chrome: 
- [ ] Firefox: 
- [ ] Internet Explorer:
- [ ] Opera: 
- [x] Other: Safari (and others; used to access Iris)

## Before you submit
- [x] Yes, I have tested this issue thoroughly
- [ ] Yes, I have attached screenshots and/or screencast of the issue in action
- [ ] Yes, I have included any relevant debug data and error logs

**Comment by fmarzocca** [comment]
I confirm this too on my system

**Comment by jaedb** [comment]
@pepicek1977 it doesn't so much appear to be the space that's the problem, rather the square brackets. Can you confirm that creating the playlist without these works for you (ie "Radiozenders test two")?

**Comment by pepicek1977** [comment]
In the latest release, both spaces and square brackets function fine: neither of them disrupts loading the m3u8 file and the list of radio stations in it. I hope you managed to locate what went wrong rather than the bug now being solved miraculously :-)  

Thanks!

**Comment by jaedb** [comment]
@pepicek1977 correct, this bugfix was released yesterday. Glad it solved the issue for you.
