### ISSUE TITLE
[Support] Adding commands

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#382]
I am wondering which typ eof commands can I add to Iris (Settings->Commands->Add New).

Is it possible to add system commands (i.e.: shutdown, eject, etc.)?

**Comment by fmarzocca** [comment]
I can't find any documentation about this feature.

**Comment by jaedb** [comment]
Hi Fabio, please see tooltips in the interface itself. There is no formal documentation at this time.

Iris is not a commercial project with 24-7 support. Every bug, improvement and upgrade requires hours of my personal (and unpaid) time. So please be patient.

**Comment by fmarzocca** [comment]
Hi James,
I am an old Open Source developer and I have many of my software currently running on Linux, so I am very well aware about support personal efforts. I don't want to bother, but I didn't find any tooltip on that function. Only this suggestion, as an example: `{"url":"https://pab.local/broadlink/sendCommand/power/"}`

I understand it must be called with an Ajax request, but what requests can I do? Do I have to add the code to handle my request? Is there any additional command ready-made?

**Comment by jaedb** [comment]
You can add any jQuery ajax parameters (as documented: http://api.jquery.com/jquery.ajax/). Basically these commands only fire off ajax requests; there is no back-end logic whatsoever. The input field is just accepts a json object.

My use case for this is to send commands to the RESTful API for my [RM Mini](http://www.ibroadlink.com/rmMini3/), allowing Iris to control my AV Receiver and other radio-frequency connected devices.

**Comment by fmarzocca** [comment]
Ok! I got it! 
Thank you very much.

**Comment by fmarzocca** [comment]
I am only getting one issue.

From my REST API handler, I am returning a success code (200) but IRIS always pops up a "Command failed" banner, even if the command is executed successfully.

**Comment by jaedb** [comment]
Ensure you're running in test mode (_Settings > Debug > Test mode_) and have a look at your browser console while sending the command. This should help you debug the issue.

**Comment by fmarzocca** [comment]
Hi James,

weird things happening. If I test my REST API from curl, I get a successful message:

```
curl -v http://localhost:3000/test
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3000 (#0)
> GET /test HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: text/html; charset=utf-8
< Content-Length: 18
< ETag: W/"12-mlJciYyzvl49fsbLFYwKGpa/UL4"
< Date: Sun, 31 Mar 2019 16:52:23 GMT
< Connection: keep-alive
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
Command successful
```

but running the same from IRIS, I get this error message in the javascript console:

```
jquery.js:9600 GET http://localhost:3000/test/ net::ERR_CONNECTION_REFUSED
......
middleware.js:528 Command failed, response was:
{readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}  
```

**Comment by jaedb** [comment]
When testing other requests they work fine, so I suspect the issue is with your server-side code. 

For example, try a command with the following payload:
```
{"url":"https://jsonplaceholder.typicode.com/todos/1"}
```
which functions as expected.

**Comment by fmarzocca** [comment]
Yes, that command is working, but I can assure you that my very simple REST API is working nice if called directly from any browser. So, maybe, IRIS is expecting something in the response that I am not sending.
But what is really weird is this:

`GET http://localhost:3000/test/ net::ERR_CONNECTION_REFUSED`

Anyway, I realize that this is not in the scope of IRIS, so I will not bother you more.
Thanks you for your time.
