### ISSUE TITLE
Remove played tracks in queue

### ISSUE THREAD

**Issue by michaelgierer3** [jaedb/Iris#386]
It would be nice if songs get instantly removed from the queue after being played!
Otherwise you need to scroll down to see the current track, since the focus isn't on the current track.

Suggestion: A checkbox in the settings would be nice!

P.S. i tried to hard-code it on my own, but i don't find the function which will be called after a track ends and a new one starts ... (any help would be great)

;-)

**Comment by jaedb** [comment]
The great news is this already exists! Click the knife and fork icon in the play bar to to toggle Mopidy's built-in _Consume Mode_.
