### ISSUE TITLE
Donate dialog box won't close

### ISSUE THREAD

**Issue by Multipixelone** [jaedb/Iris#388]
**Describe the bug**
The dialog box "2,116 hours of coding" Won't close no matter what I do, and it blocks a significent portion of the screen on my iPhone

**To Reproduce**
Open Iris

**Expected behavior**
When you click the "x" button, it should close

**Environment details:**
On every browser and OS I Tested it on (Ubuntu, Manjaro, iOS, Firefox)
 - Iris version [3.35.0]

**Comment by jaedb** [comment]
Good spotting. Patched and released.
