### ISSUE TITLE
getting 404 when opening iris

### ISSUE THREAD

**Issue by bjo81** [jaedb/Iris#39]
Hi,

I'm getting "404: Not Found" when I open mopidy:6680/iris/, but iris appears in the list of available webinterfaces.

**Comment by jaedb** [comment]
@bjo81 In order to replicate this issue, please provide more information:
- Version of Mopidy
- Version of Iris
- OS and browser versions

At first glance, I would suggest clearing all browser caches and re-starting Mopidy server.

**Comment by bjo81** [comment]
Mopidy: 2.1.0
Iris:  2.10.17
OS is Arch Linux
Browser: Firefox 50.1.0

Browsercache was cleared und mopidy restarted several times, it also appeared on several systems (all Arch Linux, same Mopidy and Iris versions)

**Comment by occulkot** [comment]
i had similar problem in arch - solved by instaling with pip2
I guess problem is with PKGBUILD

**Comment by bjo81** [comment]
OK, so I will report it again at its AUR page.

**Comment by jaedb** [comment]
@occulkot When you experienced this issue, were you also on Arch Linux or another distro?

**Comment by occulkot** [comment]
yes, it was on arch installed from AUR

**Comment by MarcinWieczorek** [comment]
As the maintainer in AUR I fully confirm the issue.
Does anyone have a solution? The installation from pip looks almost identical as mine.
I use `python2 setup.py install --root="${pkgdir}/"` for installation

**Comment by jaedb** [comment]
@MarcinWieczorek My understanding of this installation method is it installs a local build. For example if you have pulled `master` branch, you'll build and install _Iris_ based on `master`, or whatever commit you have in your local folder.

Installing via _PIP_ (rather than from local source) will give you an official release (ie `pip install Mopidy-Iris`).

Does this sound right to you?

**Comment by MarcinWieczorek** [comment]
The AUR package uses tagged (2.10.17) source tarball.

**Comment by MarcinWieczorek** [comment]
These are the files missing when installing with `setup.py`:
http://sprunge.us/JLDQ?diff

**Comment by jaedb** [comment]
I'm not familiar with _AUR_, but it looks like it's creating a release based on the source code of this GitHub repository. The code needs to be compiled from this repo in order to be operational.

Either:
- use [PyPi](https://pypi.python.org/pypi/Mopidy-Iris/2.11.0) as the AUR source
- compile code prior to submitting to AUR (eg `npm run prod`)

**Comment by MarcinWieczorek** [comment]
`source=("${url}/archive/${pkgver}.tar.gz")`
The url points to github and the $pkgver is 2.10.17 so the source is, as I said, tagged source tarball.
It's literally this: `https://github.com/jaedb/Iris/archive/2.11.0.tar.gz`
Your project doesn't seem to rely on git when building, am I wrong?

**Comment by jaedb** [comment]
This GitHub repository is just source code, so the tarball you're using (auto-created by GitHub) is of uncompiled code. 

Building is performed prior to submitting to _PyPi_, so if you're submitting to another provider it will need to be manually built. You can see a list of all compiled releases on _PyPi_ here:  https://pypi.python.org/pypi/Mopidy-Iris/2.11.0/json

Alternatively do you know of any method that enables GitHub to compile code during a release?

**Comment by MarcinWieczorek** [comment]
Guys... It works for me... No idea why tho. I'm tracking down today's package upgrades to find out.

**Comment by MarcinWieczorek** [comment]
I'm okay with having just the source so no worries @jaedb. Everything seems to be good on your side as it works from pip. At the moment I don't know why does it work for me too.

**Comment by bjo81** [comment]
I think you should use https://pypi.python.org/packages/a8/c7/a133e8a9baf12b41d75106ad294e5768ca1119c81690fb39c81ff225a47b/Mopidy-Iris-2.11.0.tar.gz#md5=b93044569b3ce16f3c53db2ad399fd0e instead of the archive from github. Or we need a npm run in the PKGBUILD.

**Comment by MarcinWieczorek** [comment]
Does `npm` do anything besides installing dependencies?

**Comment by jaedb** [comment]
And host the build code, nope.

How come one cannot just use `npm` instead of AUR?

**Comment by MarcinWieczorek** [comment]
I have all dependencies sufficed from AUR

**Comment by bjo81** [comment]
@MarcinWieczorek Why do you not use simply the pypi-archive as the source in the PKGBULD? I replaced the git-archive with the pypi-archive and it works fine. No need to run npm.

**Comment by MarcinWieczorek** [comment]
It works for me as it is, with the source from GitHub. No idea why tho.

**Comment by bjo81** [comment]
Do you have also the missing files you mentioned above?

**Comment by MarcinWieczorek** [comment]
I was unable to track what fixed the package. Might be an update, could you try? I have tried downgrading and checking the packages but I could not break Iris ever again.

**Comment by bjo81** [comment]
I've downgraded back to your version (2.10.17-1) and I get the 404 again.

BTW, my selfcreated PKGBUILD with the the pypi-source is much bigger than yours:

> Packages (1) mopidy-iris-2.11.0-0
> 
> Total Installed Size:  14.62 MiB
> Net Upgrade Size:      14.53 MiB

Did you remove your pip-installation before trying your PKGBUILD?

**Comment by MarcinWieczorek** [comment]
I have never installed any files from pip. I actually tricked the package to use files from pip to get it working. I'll make sure there's nothing left tho. Pacman might have missed some files when removing the package.

**Comment by bjo81** [comment]
But your PKGBUILD still uses the github-archive and is outdated.

**Comment by MarcinWieczorek** [comment]
You were right about pip files left over.
Why does setup.py give us an incomplete install and how possibly is everything ok when build from pip? How does pip build the project?

**Comment by occulkot** [comment]
i guess pip sources have already compiled (via npm) webapp part

**Comment by MarcinWieczorek** [comment]
Let's reproduce that process for the package.

**Comment by jaedb** [comment]
@MarcinWieczorek if any change is required to the source code, please feel free to make a pull request.

**Comment by MarcinWieczorek** [comment]
If only I knew how to fix it...

**Comment by occulkot** [comment]
@jaedb, imo you should consider creating stable branches for version you put on pip with compiled js/html code added. That way @MarcinWieczorek could use this branch as source for installing package.
Problem with running npm on package install process with aur is using "npm", which is another package management system and its not recomended - https://bbs.archlinux.org/viewtopic.php?id=186935

**Comment by MarcinWieczorek** [comment]
The dependencies are easy to get without npm install. I don't know how to get npm-generated files and where to put them. Any advice would be greatly appreciated.

**Comment by jaedb** [comment]
Happy to explore the options to include built code in a release, however it begs the question: why are you not installing with `pip install Mopidy-Iris`? Most other Mopidy extensions are available only using this method, so in most cases users will already have PIP installed.

**Comment by occulkot** [comment]
pacman (which AUR extend) is package management system for arch linux. Same as apt is for debian and ports / package are for freebsd. It is used to maintain (install/uninstall) all software installed in OS so users dont have to remember what way (pip, npm, src, pear, pecl, gem) they installed which library. One tool to control all software. Most of mopidy extensions are already available there - https://aur.archlinux.org/packages/?O=0&K=mopidy

**Comment by MarcinWieczorek** [comment]
Iris has been updated. I used pip. I didn't manage to build it without pip, so the issue is here in the upstream. It would be nice to install the project just with setup.py (assuming I don't need npm for dependencies). Thanks for the support guys.

**Comment by jaedb** [comment]
Including compiled code into a repository makes for cumbersome development (merge conflicts on minified JS). So at this stage I'll include a compiled .tar.gz through GitHub releases as an additional download. See the https://github.com/jaedb/Iris/releases/tag/2.11.3
