### ISSUE TITLE
Snapcast server connection stability

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#390]
**Is your feature request related to a problem? Please describe.**
When the snapcast server connection is interrupted, Mopidy may need to be restarted to re-establish the Iris-Snapcast connection. Currently this is a bit of a blunt instrument.

**Describe the solution you'd like**
Sensible server-side management of the connection within the Iris backend.

**Describe alternatives you've considered**
Leaving it as it is. The issue might not actually inhibit many users.

**Comment by armageddon421** [comment]
I get hundreds of these every 30 seconds:

` mopidy[8132]: ERROR    Malformed Snapcast message:`

I recently had to restart the snap server. Maybe this is related. Also, my mopidy is pinning my CPU at 100% on both cores without anything playing, maybe that's also related?

**Comment by jaedb** [comment]
If you can provide more information then it may be possible to identify the cause.

It's unlikely Iris is causing high CPU as there is no reconnection attempt, so once the server-to-server connection is lost it will require a Mopidy restart. But anything is possible.

**Comment by jaedb** [comment]
Closing as this is no longer relevant. Iris does not connect directly to Snapcast, rather the browser connects to the Snapcast websocket and JSON.
