### ISSUE TITLE
Shuffle Play doesn't shuffle

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#391]
**Describe the bug**
When using context menu on Playlists, _Shuffle play_ plays the tracks but doesn't shuffle them first.

**To Reproduce**
1. Go to a playlist
2. Click context menu ("..." button)
3. Click _Shuffle play_
4. Compare playlist track order with the queue order and they're the same

**Expected behavior**
Shuffle applied at the adding of URIs to the queue.

**Comment by jaedb** [comment]
Released at 3.37.1

**Comment by PureTryOut** [comment]
With the latest Docker image I still have this issue.
