### ISSUE TITLE
Unable to connect to iris (docker installation)

### ISSUE THREAD

**Issue by kthys** [jaedb/Iris#393]
Hi,
I've installed Iris today from [your docker webpage](https://hub.docker.com/r/jaedb/iris) and installed it using docker-compose. There was no install tutorial so I had a look at the dockerfile and tried to make a config.
It looks like the config works, docker has no problem with it but when I try to connect to the port 6680, nothing happens.
Do you have any idea on how to fix that?

Here is the config:
```mopidy:
        image: jaedb/iris
        container_name: mopidy-iris
        volumes:
            - ..../Media/Music:/var/lib/mopidy/media:ro
            - ...../mopidy/metadata:/var/lib/mopidy/local
        ports:
            - 6600:6600
            - 6680:6680
        restart: always
        networks:
            - default

**Comment by jaedb** [comment]
You'll need to setup the actual command and entrypoint (which as you rightly identified, are not documented yet). Iris' Dockerfile is a copy-and-tweak from [wernight/mopidy](https://hub.docker.com/r/wernight/mopidy), so you can use that documentation to get you up and running.

In essence:
- Command: `'/usr/bin/mopidy'`
- Entrypoint: `/entrypoint.sh`

I hope this helps.

**Comment by kthys** [comment]
Thanks for your reply,
Do I have to add these to fields to the config ? I've added the fields ` entrypoint: /entrypoint.sh` and ` command: '/usr/bin/mopidy'` to my config but it looks like the webpage is still not reachable.
Have I done it wrong ?

**Comment by jaedb** [comment]
No they are the configuration values on the _container_. I'm still figuring how Iris should use Docker so this is very much a work in progress.

I recommend following the instructions on [wernight/mopidy](https://hub.docker.com/r/wernight/mopidy) and replacing only the image to at least get you started. Then you'll have enough to create your `docker-compose.json` file.

**Comment by kthys** [comment]
I've tried the commands in the tutorial of [wernight/mopidy](https://hub.docker.com/r/wernight/mopidy) and it works fine on the Iris container, you did a good job ! I'll probably use this version until you've finished setting up Iris on docker.
I've used the command `docker run -d -v "$PWD/media:/var/lib/mopidy/media:ro"     -v "$PWD/local:/var/lib/mopidy/local"     -p 6600:6600 -p 6680:6680     --user $UID:$GID     jaedb/iris     mopidy`

Concerning the _compose_. I'm still confused because it doesn't seem to need a custom entry point as you have previously mentioned, the initial docker command looks very basic so I don't understand why docker-compose should have that kind of details.

**Comment by jaedb** [comment]
@kthys I trust you've managed to get things up and running, now that the required initial settings are in this repository? I'll close this issue for now, but if you feel your issue persist, please feel free to re-open.
