### ISSUE TITLE
Keep search results until next search

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#398]
After searching, search results are lost after switching to different view. For example:
1. Go to search view
2. Type something to search
3. Wait for search to finish
4. Go to "now playing"
5. Go to search view
After that search result is empty. It would be very useful if after step 5 the search view showed last search result.

**Comment by mathew65** [comment]
I second that

**Comment by jaedb** [comment]
@mczerski Please use the provided issue templates.

**Comment by jaedb** [comment]
This is a good idea and makes the interface feel more intuitive.

However I found it cumbersome having my last search results kept for an infinite period of time and then returning to have everything pre-populated. It felt more appropriate to keep the results in the browser history so you can easily go back to your search. When navigating to _Search_ (ie clicking the left menu) the expectation is to start a new search.

To this end, have a look at `develop` to see this in action.
