### ISSUE TITLE
Search results don't show local artist and albums, only from spotify

### ISSUE THREAD

**Issue by occulkot** [jaedb/Iris#40]
Album is visible in track table, and then you can navigate to it.

![search](https://cloud.githubusercontent.com/assets/1793465/22056230/62d59242-dd5f-11e6-999b-802ba676ea80.png)

iris version: 2.10.17 
mopidy: 2.0.1
platform: archlinux x64

**Comment by jaedb** [comment]
Are you experiencing this on a published release of Iris, or the `master` branch?

**Comment by occulkot** [comment]
irsi 2.10.17 installed from pip, so i guess its published release.
you suggest to check again with master branch?

**Comment by jaedb** [comment]
Curses. I've been working on functionality that has caused regression in the search view, but I've since patched it.

As a side-note, if you have installed _Iris_ in develop mode (ie `python ./setup.py develop`), this will overwrite any official install you may have from _PIP_. That is, unless you have uninstalled _Iris_ in develop mode (ie `python ./setup.py develop --uninstall`).

**Comment by occulkot** [comment]
ive checked current git version (2.11) and problem stil appears.

**Comment by jaedb** [comment]
It may seem like a daft question, but have you run a new build (ie `npm run prod`)?

**Comment by occulkot** [comment]
sorry for lag. 
So to install and run current git version i have to:
1. Download/update node libraries - npm install
1. compile webpart  - npm run prod
2. install package - python setup.py install

Is it correct?

**Comment by jaedb** [comment]
There are to installation methods:
1. [Production installation](https://github.com/jaedb/Iris/wiki/Installation) (for most users)
2. [Development installation](https://github.com/jaedb/Iris/wiki/Developing-and-debugging) (for advanced users)

If you have installed a development installation, this will need to be properly removed before installing via production installation.

So, assuming you've been using a development installation, you need to follow steps [4-7](https://github.com/jaedb/Iris/wiki/Developing-and-debugging) to upgrade.

**Comment by jaedb** [comment]
Original issue resolved.

**Comment by occulkot** [comment]
version 2.11.3 should include fixes? Because my instance still dont show artist from local library
