### ISSUE TITLE
Lost Artists images

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#400]
I have just updated to 3.37.1, but all of my artist's images are gone (white star on gray background). Album covers are still there..

**Comment by jaedb** [comment]
Firstly, @fmarzocca if you want to contribute issues to Iris, please refrain from ignoring the issue templates I have created.

The reason artwork is now replaced by a star image is LastFM has removed artwork from their API. This is a massive shame and has affected a lot of other applications, including Iris. See https://www.reddit.com/r/lastfm/comments/bjwcqh/api_announcement_lastfm_support_community/?sort=old

The fix to this will be to use an alternative artwork library. Perhaps MusicBrainz? This will require further investigation.

**Comment by fmarzocca** [comment]
**Describe the bug**
Artists images are missing

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Artists'
2. No artist's image

**Expected behavior**
Show the artist's image

**Screenshots**
![Schermata 2019-06-19 alle 10 49 17](https://user-images.githubusercontent.com/8530030/59751133-4a357f80-9280-11e9-9a94-14145279d2b0.png)

**Environment details:**
 - OS: MacOS 10.14.5 (18F132)
 - Browser Chrome
 - Iris version: 3.38.0

**Additional context**
Consider using musicbrainz for images
