### ISSUE TITLE
"Uncaught Exception in /iris/ws"

### ISSUE THREAD

**Issue by msaied56** [jaedb/Iris#405]
**Describe the bug**
Immediately after successfully launching mopidy-iris significant error messages are printed to the console. eventually these errors cause content to stop playing.

**To Reproduce**
1. launch mopidy
2. check terminal where you launched it

**Expected behavior**
I do not expect the system to crash

**Screenshots**
https://imgur.com/LK3GcgE

**Environment details:**
 - OS: raspbian
 - Browser: not a browser issue
 - Iris version 3.37.1

**Additional context**
The error occurs every 30 seconds. 

`ERROR    Uncaught exception in /iris/ws/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 494, in _run_callback
    result = callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/handlers.py", line 81, in on_message
    getattr(mem.iris, message['method'])(data=params, callback=lambda response, error=False: self.handle_result(id=id, method=message['method'], response=response, error=error))
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/core.py", line 331, in update_connection
    self.connections[connection_id]['client']['username'] = data['username']
KeyError: u'username'
`

**Comment by jaedb** [comment]
This looks like you might have an old version of Iris running in a browser, trying to connect to a new version of the backend. Can you try clearing the cache on your browser of all connected devices to see if this fixes it?

You may need to check if anyone else in the network has been using Iris and get them to do the same.

It's basically looks to be a case of the breaking change in the way websockets are established (release [3.37.0](https://github.com/jaedb/Iris/releases/tag/3.37.0)).

**Comment by msaied56** [comment]
That was probably the cause of the issue, i asked everyone to clear their cache and it seems that specific issue is gone. i had previously believed the error I reported above was causing spotify issues, but that is not the case. even without the error from above I still get this error in the terminal: https://i.imgur.com/IKatVPd.png

This stops content from playing and I have to close mopidy and relaunch to get it working. 
Any thoughts on this issue?
