### ISSUE TITLE
Handle Spotify error when trying to add more than 5 radio seeds

### ISSUE THREAD

**Issue by beaufour** [jaedb/Iris#407]
**Describe the bug**
The radio function does not allow me to add more than 5 tracks as seeds. If I do, it errors out with a `Could not change radio` error message and the radio doesn't start.

**To Reproduce**
1. Click on radio
2. Add 6 tracks as seeds
3. Click Start
4. See error message.

**Expected behavior**
4 should be "Radio starts playing" :)

**Environment details:**
 - OS: Mac OS 10.14.5 (Browser OS)
 - Browser: Chrome 75.0.3770.51
 - Iris: 3.37.0

**Comment by jaedb** [comment]
Unfortunately this is a limitation of Spotify's recommendation endpoint. So there is nothing practical Iris can do to work around this.

_Up to 5 seed values may be provided in any combination of seed_artists, seed_tracks and seed_genres._
From https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/

**Comment by beaufour** [comment]
Bah. Could you block adding more than 5 in the UI then? Because I just wasted a fair amount of time trying to figure out why it was erroring out for me :)

**Comment by jaedb** [comment]
That's totally possible. Ideally the error would come straight from Spotify and is handled through the Iris backend. This would mean when/if they change the limits there will be no change required in Iris.

**Comment by beaufour** [comment]
Ah yes, that would make a ton of sense to do it that way :)

Thanks for a fantastic piece of software btw!
