### ISSUE TITLE
Snapcast Buffer size to small

### ISSUE THREAD

**Issue by asciidisco** [jaedb/Iris#408]
**Describe the bug**
I have a lot clients in my Snapcast installation (over 30) & the buffer size
as described in https://github.com/jaedb/Iris/blob/3c3fad92d5b56ba3aab9872509dc7bd6ed8ec392/mopidy_iris/snapcast.py#L72 & https://github.com/jaedb/Iris/blob/3c3fad92d5b56ba3aab9872509dc7bd6ed8ec392/mopidy_iris/snapcast.py#L138 is to low to handle the amount of data from the `GetStatus` request.

I'd ask (as I don't now what side-effects come with it) to either increase the buffer size (doubling it might help me in my case) or to make it configurable somehow. Would that be possible? Thanks.

**To Reproduce**
1. Create a Snapcast installation with >20 clients
2. Start Mopidy process

**Expected behavior**
Iris can handle large Snapcast responses

**Environment details:**
 - OS: Debian
 - Browser [All]
 - Iris version [latest]

**Comment by asciidisco** [comment]
@jaedb Thank you

**Comment by jaedb** [comment]
@asciidiscoy you're welcome!
