### ISSUE TITLE
Search seems inefficient. Why?

### ISSUE THREAD

**Issue by sbaier1** [jaedb/Iris#409]
*What part of Iris is your question about?*

Search module

**Your question**
I am updating a plugin for using plex with mopidy. I am personally using Iris as frontend but i am running it on a slow machine and have seen that search queries are being handled quite slowly.

While debugging this i found that iris queries the backend three times: once with parameter "any" which returns results matching any artist, album or track in my case. Then it proceeds to query again for specifically artists and albums. Why is that? the "any" query already returns all elements for the query.

Other frontends such as moped for example simply query once for all providers. I can understand that separate queries are used for each source so users can filter their sources but why query each part of the library separately?

**Comment by jaedb** [comment]
The main reason was to keep the search process more granular so it can more easily be controlled by the user and the Iris search process.

To support as many Mopidy backends and external API providers (only Spotify at the moment) the current search will treat each search type (_Artist_, _Album_, etc) as it's own search request. This prevents locking the Mopidy process during searches on slow backends (_YouTube_ is a prime example) and makes it more straightforward to expand support in the future.

I think you'll find that other frontends are not using HTTP APIs as well as Mopidy backends. This is part of what allows Iris to be more engaging.

The `any` query relates to searches for _Tracks_.

I run Iris and Mopidy on a Raspberry PI 2 and 3 without any major performance issues. What type of machine are you running?

**Comment by sbaier1** [comment]
alright, that makes sense. i am running on a raspberry pi 3 as well. The problem is the underlying API used for the plex plugin i am working on is a little slow. I am implementing some rudimentary caching now to speed things up across the different types of query.

I was just curious if there's a bug here that slipped past or something.

>The any query relates to searches for Tracks.

Is the `any` query specified somewhere to only search for tracks? because as of now, my plugin returns any items matching the search query in that case...

**Comment by jaedb** [comment]
Previously I had kept it as `any` to return tracks with any field matches, but I can see how that could result in double-ups and potentially un-necessary lookups. This could be fixed by only searching tracks on `track_title`.

Can you please provide me a link to your Plex-Mopidy plugin so I can see how it's working with Iris?

**Comment by sbaier1** [comment]
[this](https://github.com/sbaier1/mopidy_plex) is the current state of my fork

**Comment by jaedb** [comment]
Unfortunately I'm going to roll back this change. By limiting search fields on Tracks to `track_title` we are missing out on any results for backends that don't use proper Artist / Album models.
