### ISSUE TITLE
settings from distant connexion

### ISSUE THREAD

**Issue by ZargosLord** [jaedb/Iris#41]
Hi,

I have a mopidy server where i installed Iris. The mopidy accept only local connexion (to secure it)

I've used apache to reverse proxy access to mopidy with the following configuration:

```
<VirtualHost *:80>
  ServerAdmin *********
  DocumentRoot /var/www/
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined
  ProxyPreserveHost On
  ProxyPass / http://localhost:6680/
  ProxyPassReverse / http://localhost:6680/
  ServerName myserver
</VirtualHost>

```
But in the Iris setting i can't set up the mopidy server as it doesn t seems to consider server local but client local. Localhost should be the server localhost and not the client?

or is that my proxy apache configuration that need some more?

I'm guerssing that the localhost setting you set up inmopidy server in Iris setting section isn't considered server side.

can someone help me with this?

i'd like to use mopidy as a music server, but i want to secure it so noone would be able to connect to it whithout authentication (through apache) in the network.

i.e.:

Client -> server [ -> apache -> mopidy]

**Comment by jaedb** [comment]
Couldn't you setup your Mopidy server to only accept requests from localhost (ie `127.0.0.1`)? Then only requests from your server or your server's proxy would be accepted by Mopidy.

Secondly, there are essentially two servers that make up Mopidy, with a third for Iris:
1. Mopidy event engine on port `6600`
2. Mopidy webserver on port `6680`
3. Iris event engine (aka _Pusher_) on port `6681`

You will need to setup a proxy to accept and route requests for all of the above ports.
