### ISSUE TITLE
Random play radio station in playlist

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#412]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
I'd like to load playlist with several radio station and let Iris play them randomly, changing one to another with an interval..

**Describe alternatives you've considered**
manually change station

**Additional context**

**Comment by foxfabi** [comment]
i solved this issue on linux with mpc and a cronjob.
something like this... 
```
#!/bin/bash
mpc stop
mpc clear
mpc load "StartUp"
mpc shuffle
mpc play
```
Maybe this will help.

**Comment by fmarzocca** [comment]
Yes, I am doing the same. Thanks!
