### ISSUE TITLE
Spotify uri lookup failed

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#414]
**Describe the bug**
I am using mopidy with Iris since many months, with no issues. Today I tried to use the "Add uri" feature in the "Now Playing" page and I found that I am able to add and play any track except spotify’s playlists.

For any spotify playlist I get this error in log:

`2019-07-12 13:27:26,564 INFO [3731:SpotifyBackend-8] mopidy_spotify.lookup: Failed to lookup "spotify:playlist:37i9dQZF1E4kZJksQ28QcL": Failed to get link from Spotify URI: u'spotify:playlist:37i9dQZF1E4kZJksQ28QcL'`

If I normally click on “Play” on the playlist, it plays fine.

Any hint?

**To Reproduce**
1. Go to 'Now Playing'
2. Click on 'Add uri'
3. Add a spotify playlist uri
4. The playlist is not added to the queue

**Expected behavior**
Spotidy playlist added to queue

**Environment details:**
 - OS: Raspbian
 - Browser [chrome]
 - Iris version 3.39.0

**Comment by jaedb** [comment]
You can't currently add a Playlist URI to the _Now Playing_ queue. This currently supports track URIs only (eg `spotify:track:4GUSd2HIJdZylmc6BzuLjD`) which explains why you're getting that error.

**Comment by fmarzocca** [comment]
Ah, ok. Is that a mopidy limitation as it is not working with JSON-RPC calls either?

**Comment by jaedb** [comment]
Correct. The issue isn't with _Iris_, rather that _Mopidy-Spotify_ doesn't allow the adding of playlist URIs to the queue.

**Comment by fmarzocca** [comment]
thanks
