### ISSUE TITLE
Is there any way to change the image associated with a source under Browse?

### ISSUE THREAD

**Issue by syedrali** [jaedb/Iris#417]
Directly under Browse where it shows available sources, such as Files, Local Media, Spotify, Google Music, etc is there a way of changing what image is used to represent a source?

**Comment by jaedb** [comment]
I've created a set of popular logo tiles to keep the interface feeling consistent, but there isn't anywhere you can manually change these. If you have a particular request, please feel free to open a [Feature Request](https://github.com/jaedb/Iris/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=) or make the code changes and create a [Pull Request](https://github.com/jaedb/Iris/pulls).

**Comment by syedrali** [comment]
Understood. Thank you.
