### ISSUE TITLE
Icecast not working

### ISSUE THREAD

**Issue by nscpro** [jaedb/Iris#421]
Hi

I have installed a icecast2 server, but if i go iris website in localhost and choose icecast and my aadress is set http://192.168.1.106:8000/mopidy and config file set  Audio output set to "lamemp3enc ! shout2send async=true mount=mopidy ip=192.168.1.106 port=8000 password=proov" this does not working my icecast xml file configure password - proov, hostname - 192.168.1.106 and port - 8000. What can i do wrong?

**Comment by jaedb** [comment]
Can you open your stream from a browser? Ie does http://192.168.1.106:8000/mopidy play your audio stream?

**Comment by jaedb** [comment]
Closing this issue due to missing information. Please feel free to re-open when more information is available.
