### ISSUE TITLE
Multi-language interface

### ISSUE THREAD

**Issue by nscpro** [jaedb/Iris#424]
Hi.
Where can i find Iris language file in raspberry pi? i'm using pip to install iris. I wish translate Iris another language.

Thank you :)

**Comment by jaedb** [comment]
Unfortunately there isn't one 😲 

What is the language you wish to translate to? If there is enough interest then I could prioritize the effort to pull all the language elements into a translatable template.

**Comment by fmarzocca** [comment]
If interested, I can provide italian translation.

**Comment by nscpro** [comment]
I wish translate in Estonian language. But where is located Iris website files? index.php and another files?

**Comment by fmarzocca** [comment]
> I wish translate in Estonian language. But where is located Iris website files? index.php and another files?

IRIS is not running on php.

**Comment by nscpro** [comment]
What language IRIS using? Python? or Java?

**Comment by fmarzocca** [comment]
> What language IRIS using? Python? or Java?

Strange question... You have the whole code available here... try just to have a look at it.
https://github.com/jaedb/Iris

**Comment by nscpro** [comment]
Looks like Java. But i don’t understand where is same files located on raspberry pi

**Comment by jaedb** [comment]
Iris is a python backend, ReactJS frontend. So for internationalization we would only be working on the ReactJS side. The exact location depends on your pip environment. Searching for "pip packages location" will help you (also see https://stackoverflow.com/questions/29980798/where-does-pip-install-its-packages/29980912).

**Comment by foxfabi** [comment]
i can provide german translation

**Comment by el97** [comment]
I can provide a Swedish translation.

**Comment by el97** [comment]
Any updates on this?

**Comment by jaedb** [comment]
@el97 not at this stage.
Right now there are only 3-4 users that have expressed interest in this feature. It is a large chunk of work (at least 40 hours work) so it is hard for me to personally justify committing time to at this stage.

**Comment by fmarzocca** [comment]
James,

if you ever need to move to multilanguage, I am available for italian.

**Comment by kobbejager** [comment]
Happy to help with Dutch translation

**Comment by jaedb** [comment]
I have managed to set aside time to tackle this chunk of work (over 20 hours and I'm still not done!) but I am nearly there. I anticipate having an English map file ready for translation in the next week or so.
To confirm the languages that we will initially support and who will be responsible for the translation (please tick to confirm your availability):
[ ] Dutch by @kobbejager 
[ ] Italian by @fmarzocca 
[ ] Swedish by @el97 
[ ] German by @foxfabi 
[ ] Estonian by @nscpro

**Comment by kobbejager** [comment]
Great news!
I remain very much interested in doing the Dutch translation, although I probably won't be able to start before the 2nd week of August.

**Comment by el97** [comment]
I will help to provide a Swedish translation. It might take a while until it's done if I don't get help from others though.

**Comment by jaedb** [comment]
I think we're ready to start translating!🎉 

All you need to do is (where CODE is the language code that you're translating for, eg 'en'):
1. Fork this repository
2. Branch off `develop` (ie `git checkout develop && git pull origin develop && git checkout -b feature/language-CODE`)
3. Copy `src/locale/en.yaml` to `src/locale/CODE.yaml`
4. Work through the file, translating as you go. The YAML file structure loosely reflects where you would encounter the phrases in the interface.
5. Create a pull request with your completed translation.

I have a number of other features and fixes queued up in this next release, so please provide some kind of timeframe for your translations so I know what will be included for release (in the next week or so).

**Comment by foxfabi** [comment]
I followed your instructions but i do not find the file to translate. did i miss something?
```
fabforge@devstack:/opt/DEV/Iris$ find . -name *.yaml
./src/js/locale/en.yaml
./src/js/locale/de.yaml
```

**Comment by jaedb** [comment]
@foxfabi Sorry - I missed the `/js` subfolder.

**Comment by jaedb** [comment]
I'll be releasing the multi-language functionality in the next few days as part of a larger release. Does anyone have a completed translation to be included in this release?

**Comment by el97** [comment]
#573 Just provided the first version for a Swedish translation.

**Comment by foxfabi** [comment]
#575 Just provided german translation.

**Comment by jaedb** [comment]
@el97 and @foxfabi awesome stuff, thanks for the quick turnaround! I have just released Iris 3.51 which includes your translations 🎉 

For anyone else who is interested in providing translations, please follow the following instructions (where CODE is the language code that you're translating for, eg 'en'):
1. Fork this repository
2. Branch off `develop` (ie `git checkout develop && git pull origin develop && git checkout -b feature/language-CODE`)
3. Copy `src/js/locale/en.yaml` to `src/js/locale/CODE.yaml`
4. Work through the file, translating as you go. The YAML file structure loosely reflects where you would encounter the phrases in the interface.
5. Create a pull request (merging back into the `develop` branch) with your completed translation.

**Comment by kingosticks** [comment]
@jaedb, worth adding those useful notes to a section of the wiki?

**Comment by jaedb** [comment]
@kingosticks good point. Done: https://github.com/jaedb/Iris/wiki/Contributing#translations

**Comment by el97** [comment]
It would be nice if we could use a translation platform like Crowdin or Lokalise. I think that it would easier to organize and more structured way for translation.
_I hope it's okay that I use this issue even when it's closed. Open a new issue just for this felt unnecessary._

**Comment by jaedb** [comment]
@el97 I think that's a great idea. However these platforms aren't free, and I simply don't get enough monthly donations to cover those costs.
At my work we have just started using Lokalise, but before that we were using a spreadsheet with a spreadsheet-yaml converter script. Not elegant, but it worked fine offline.
I had a quick look around, but there don't seem to be any free for open source translation platforms. Do you know of any?

**Comment by el97** [comment]
I have never used this but could Zanata be a option? http://zanata.org/

**Comment by foxfabi** [comment]
What's about [Pootle](http://pootle.translatehouse.org/) ?  
An online translation and localization tool written in Python using the Django framework.
https://github.com/translate/pootle

**Comment by el97** [comment]
@jaedb  Any updates regarding a translation platform?

**Comment by jaedb** [comment]
@el97 I have been investigating [Weblate](https://weblate.org/) and it looks great. However for it to be of any use, it needs to be publicly hosted, which costs money.

The best option is AWS at about $10 USD per month (it is too large an app to run on AWS free tier instances), but there aren't enough donations to the Iris project to cover this additional cost at this stage 😞
