### ISSUE TITLE
Custom images

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#425]
*What part of Iris is your question about?*
Images/thumbnails

**Your question**
Is there any way to assign a custom image to those personal playlists without image?

**Did you want to make a donation to support this support?**
Yes.

**Comment by jaedb** [comment]
At the moment all responsibility of asset storage is managed by Mopidy (and Mopidy-Local-Images). It will muddy the waters of what Iris is if it starts becoming responsible for managing asset like this.

Personally I'd like to see Mopidy support this directly, as I believe that's where it belongs. Right now the Playlist object (https://docs.mopidy.com/en/latest/api/models/#mopidy.models.Playlist) doesn't have any reference to image, so it would require significant core development.

I would suggest making a feature request on the Mopidy repository.
