### ISSUE TITLE
nginx SSL configuration in docs not working

### ISSUE THREAD

**Issue by BrainStone** [jaedb/Iris#426]
The current nginx configuration for using SSL in the docs isn't working.

I'm proposing to change it to this

```nginx
server {
        listen 80;

        # Set to "_" to listen to all domains
        server_name  mopidy.localdomain;

        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl;

        # Set to "_" to listen to all domains
        server_name  mopidy.localdomain;

        # Update the following to reflect your certificate and key location
        ssl on;
        ssl_certificate <path to certificate>;
        ssl_certificate_key <path to certificate key>;
        ssl_prefer_server_ciphers on;

        proxy_http_version 1.1;
        proxy_read_timeout 600s;
        location = / {
                return 301 /iris/;
        }

        location / {
                proxy_pass http://127.0.0.1:6680/;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;
        }
}
```

**Comment by BrainStone** [comment]
This is the section I'm talking about: https://github.com/jaedb/Iris/wiki/Advanced#nginx

**Comment by jaedb** [comment]
@BrainStone Thanks for working on this. Are there any other nginx users who can verify that this configuration works for them before I commit it to the documentation?

**Comment by BarrettLowe** [comment]
Hey folks! Is this supposed to work for a non root location? I want to access it at sub.domain.xyz/music. If I use your script as a template I do this:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    # comment according to ha website - listen [::]:443 ssl;

    server_name sub.*;

        location = /music {
                return 301 /music/iris/;
        }

        location /music/ {
                proxy_pass http://127.0.0.1:6680/;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;
        }
```

But when I try to access sub.domain.xyz/music, it seems to send me to sub.domain.xyz/iris which gives ma a 404. 

I'm not really a web guy so I'm wondering if someone will help me figure it out. Once I get it, I'll do a PR for more documentation outlining this if needed. Thanks

**Comment by kingosticks** [comment]
Have you tried the suggestion at https://github.com/jaedb/Iris/issues/542#event-3364632683 ?

**Comment by BarrettLowe** [comment]
First - If this turns into a nginx discussion I'll take it elsewhere.

Yes, if I remove the trailing slash from the proxy_pass statement, it takes me to sub.domain.xyz/music/iris/ which is then a 404 not found.

I was able to get it working with the config in the documentation if I paste it verbatim. It just seems to be adding a subfolder throws things off.
