### ISSUE TITLE
Docker image: /entrypoint.sh: Permission denied

### ISSUE THREAD

**Issue by PureTryOut** [jaedb/Iris#427]
I'm trying to run the Docker image (`jaedb/iris`) but am failing so far.

It just reports `[dumb-init] /entrypoint.sh: Permission denied`. From what I can see from other issues I'm not running the container any different (besides me using docker-compose rather than a straight up Docker command).

**Comment by jaedb** [comment]
This is fixed in the release (moments ago). Have a crack with the latest image on Docker Hub in the next 15 minutes (to allow for build to complete), or build yourself from `master`.
