### ISSUE TITLE
Control bar is white in dark mode

### ISSUE THREAD

**Issue by BrainStone** [jaedb/Iris#433]
**Describe the bug**
The control bar in the bottom of the window has become white in the dark mode since the last release (3.39.0 was working fine)

**To Reproduce**
1. Open the player
2. Use the dark theme (and make sure resources are not cached (<kbd>Ctrl</kbd> + <kbd>F5</kbd>))
3. Check the control bar in the bottom

**Expected behavior**
That the control bar is dark like the rest of the theme

**Screenshots**

![grafik](https://user-images.githubusercontent.com/4106544/64521095-a9db7e00-d2f7-11e9-87d3-f5220a5a39eb.png)

**Environment details:**
 - OS: Windows 10
 - Browser: FireFox, Chrome, Edge (embedded)
 - Iris version: 3.40.0

**Additional context**
Issue started occuring after the update from 3.39.0

**Comment by jaedb** [comment]
This is quite deliberate :-) I know it's controversial, but it's a design decision.

**Comment by BrainStone** [comment]
Then at least make it consitent with the light design (by making that dark).

And I quite frankly disapprove of that decision. If I wanted a light control bar, I'd use the light theme.

**Comment by jaedb** [comment]
As I'm sure you're well aware, design and what feels "right" is very subjective. I appreciate your feedback on this change.

You are most welcome to create a pull request to illustrate how this might work as a new setting that people can configure to their preference.
