### ISSUE TITLE
Show that a given track has been queued by the radio feature

### ISSUE THREAD

**Issue by beaufour** [jaedb/Iris#435]
A group of us use the radio feature a lot, but you cannot see whether a given track has been queued by the radio feature or somebody that hasn't given a username. That makes it a bit hard to clear out the ones the radio has queued up, or put songs requested by people in front of the radio if you want to prioritize those, etc. So just like a song has `beaufour (from search)` if I added it, there could be `added by radio` or something for radio songs?

**Comment by jaedb** [comment]
Just to clarify, when you say _number_ you mean _track_?

**Comment by beaufour** [comment]
Hah. Yes, edited that.

**Comment by beaufour** [comment]
Amazing. Thanks @jaedb !
