### ISSUE TITLE
Pls add a way to upload custom images to mopidy playlists

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#438]
Every mopidy playlist (not potify) will not have an image and it is display the "empty" png. It would
 be nice to have a feature to upload custom images, so that to improve the GUI.
See attached.

![Schermata 2019-09-24 alle 11 43 07](https://user-images.githubusercontent.com/8530030/65501144-c31c2700-dec0-11e9-972a-12fdb604e5e0.png)

**Comment by jaedb** [comment]
@fmarzocca haven't you already requested this? See #425. Have you made a request on the Mopidy repository as suggested?

**Comment by fmarzocca** [comment]
Hi James,
#425 was related to artists and I have made a [request](https://github.com/mopidy/mopidy/issues/1793) to mopidy.

This time a was referring to playlist (don't know if it is the same matter), but looking at my playlists page with all those black squares I imagined 2 options:

1) Upload a custom image for every local playlist

2) Change the template, showing the image for spotify's playlist and removing the black square (leaving just the name) for local playlists.

**Comment by jaedb** [comment]
What it sounds like you're trying to achieve is the same thing: an image for each playlist.

Removing the thumbnail for playlists that have no image is going to be fraught with issues. Removing the thumbnail for some elements but not others does not work in a grid layout. If you want to reduce the impact of missing thumbnails, just change to the list view (_View > List_).
