### ISSUE TITLE
Queue duration

### ISSUE THREAD

**Issue by LittleFox94** [jaedb/Iris#439]
I'm using Mopidy together with friends. They put random songs in the queue, and we hear them in shuffle while having consume mode enabled. We would like to see the duration we still have in the queue.

I poked around in the code a bit and came up with some minor changes to add the queue duration to the 'Now playing' header (like 'Now playing (11:42:23 in queue)'). See attached screenshot. I'm want to make pull request to upstream this, if this is deemed useful.

For discussion:
* where to place that information?
* setting required whether to show this or not?

**Comment by LittleFox94** [comment]
![Screenshot](https://user-images.githubusercontent.com/2444973/65528554-e660c980-def4-11e9-81b7-a322dfbfe7a9.png)

**Comment by jaedb** [comment]
Many versions back this did exist in the interface but it has since been simplified.

There are a few tricky things to consider (duration formatting, how it looks on mobile devices, etc) but what you've done is a great step in the right direction. It'll need a bit more thought and design consideration.

**Comment by LittleFox94** [comment]
Probably better from the design perspective would be to have this information below the header in normal sized font. This would also look good on mobile (where it currenty overflows the "3 dot menu" on my Pixel 2)

Duration formatting is done with the same thing `Track` uses.

A problem I currently have: I sum the duration of all songs in the queue and substract the `time_position` of the currently playing song. This jumps after a song was played since it is removed from the queue but the position is still set.

(oh and I have the code here: https://github.com/LittleFox94/Iris/tree/queue-duration). I can also give a link where this is running with music playing most of the time (but cannot share that link in public).
