### ISSUE TITLE
Spotify "Made for $USER" list

### ISSUE THREAD

**Issue by Ismas** [jaedb/Iris#440]
Hi there
Is there any posibility to add support for that lists? Specially for "Your daily list N" and discoveries.
It would be highly appreciated.

Congratulations for your work. I made Mopidy + Iris my central sound source for years now.

**Comment by jaedb** [comment]
Unfortunately Spotify doesn't make the _Made for you_ assets like _Your daily mix_, etc available on their API. This seems to be a strategic decision as their value-add is around music discovery and it would be in their best interest to have this kept within their own Application.

Further reading: https://github.com/spotify/web-api/issues/324
