### ISSUE TITLE
Please adjust control bar color to the selected theme color

### ISSUE THREAD

**Issue by osc86** [jaedb/Iris#442]
It would be nice if the control bar also uses dark colors, when dark theme is selected.
The little green buttons aren't too easy to see on a bright, white background.

**Comment by jaedb** [comment]
Having a uniform white play bar is a design decision (see https://github.com/jaedb/Iris/issues/433). I do appreciate that some users want a completely dark interface. If there is enough demand then I could develop functionality so users could customise how they want it to appear.

**Comment by krater** [comment]
It's not a good design decision. It pains in the eyes when you want to use the player in a dark environment.

**Comment by jaedb** [comment]
Feel free to create a feature request issue (or better yet, a pull request) with the functionality to allow users to customise the player bar. This will also be an opportunity to gauge support for the feature and its priority. I'm sure you can appreciate that Iris is a product of my personal time and time is precious.

In the meantime I will close this issue.

**Comment by osc86** [comment]
Thank you for implementing the dark control bar in the latest release! It looks great!
