### ISSUE TITLE
Incompatibility with Mopidy 2.3

### ISSUE THREAD

**Issue by DavisNT** [jaedb/Iris#443]
**Describe the bug**
Incompatibility with Mopidy 2.3.

**To Reproduce**
1. `sudo pip install -U Mopidy`
2. `sudo service mopidy restart`
3. Mopidy-Iris is not loaded due to requirement of `tornado >= 3.2, < 5.0` by Mopidy-Iris and conflicting with requirement of `tornado >= 5, < 6` by Mopidy 2.3.

**Expected behavior**
Everything works.

**Environment details:**
 - OS: Linux
 - Iris version: 3.41.1

**Additional context**
Mopidy-Iris has a requirement of `tornado >= 3.2, < 5.0` defined in https://github.com/jaedb/Iris/blob/master/setup.py#L28 

Apart from incompatible tornado version requirements, Mopidy-Iris seems to have some issues with the /iris/ws websocket.

**Comment by jaedb** [comment]
Can you please elaborate (preferably in a new issue) on the issues you're experiencing with the `/iris/ws` websocket?

**Comment by DavisNT** [comment]
Thanks! I see the websocket issue has been fixed (currently in master branch - I hope soon there will be a release). I guess there is no need to register a new issue.

Currently in Iris under _Settings_ - _Server_ - _Status_ status _Connected_ is shown. Also request to `/iris/ws` can be seen in Chrome developer tools.
