### ISSUE TITLE
Loudspeaker button & no sound

### ISSUE THREAD

**Issue by chlowden** [jaedb/Iris#447]
Hello again James,
As I move forward, I cannot find playback via Iris. The loudspeaker button in the iris web  interface states "no output". But when I open an mp3 file directly on the raspberry pi, I have sound out of the headphone socket.
Could you tell me where I am going wrong please? Thank you
Below is my  mopidy config:

admin@pimusic:~ $ sudo mopidyctl config
[sudo] Mot de passe de admin : 
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf config" as user mopidy
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
color = true
console_format = %(levelname)-8s %(message)s
debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
debug_file = /var/log/mopidy/mopidy-debug.log
config_file = /etc/mopidy/logging.conf

[audio]
mixer = software
mixer_volume = 
output = tee name=t ! queue ! audioresample ! autoaudiosink t. ! queue ! lamemp3enc ! shout2send async=false mount=mopidy ip=192.168.0.105 port=8000 password=Lowden1805
buffer_time = 

[proxy]
scheme = 
hostname = 192.168.0.105
port = 6680
username = 
password = 

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
password = 
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist = 
  listall
  listallinfo
default_playlist_scheme = m3u

[http]
enabled = true
hostname = 192.168.0.105
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname
allowed_origins = 
csrf_protection = true

[stream]
enabled = true
protocols = 
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist = 
timeout = 5000

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir = /var/lib/mopidy/playlists

[softwaremixer]
enabled = true

[file]
enabled = true
media_dirs = 
  $XDG_MUSIC_DIR|Music
  ~/|Home
excluded_file_extensions = 
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[local]
enabled = true
library = json
media_dir = /var/lib/mopidy/media
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions = 
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip

[musicbox_webclient]
enabled = true
musicbox = false
websocket_host = 
websocket_port = 
on_track_click = PLAY_ALL

[moped]
enabled = true

[local-images]
enabled = true
library = json
base_uri = /images/
image_dir = 
album_art_files = 
  *.jpg
  *.jpeg
  *.png

[iris]
enabled = true
country = NZ
locale = en_NZ
spotify_authorization_url = https://jamesbarnsley.co.nz/iris/auth_spotify.php
lastfm_authorization_url = https://jamesbarnsley.co.nz/iris/auth_lastfm.php
genius_authorization_url = https://jamesbarnsley.co.nz/iris/auth_genius.php
snapcast_enabled = false
snapcast_host = localhost
snapcast_port = 1705
snapcast_buffer_size = 8192

[spotify]
enabled = false  ; Extension disabled due to config errors.
username =   ; Must be set.
password =   ; Must be set.
client_id =   ; Must be set.
client_secret =   ; Must be set.
bitrate = 160
volume_normalization = true
private_session = false
timeout = 10
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
toplist_countries =

**Comment by chlowden** [comment]
Hello James
I have managed to get icecast2 streaming working on the same PI. Iris sort of controls mopidy, that is broadcast on the web by icecast2. This means I have a page open for Iris and a second web browser page open for mopidy. Is there a way to integrate the mopidy / icecast stream via the iris web page ?
Thank you

**Comment by jaedb** [comment]
The _Outputs_ popup is really only for outputs that provide controls (like Snapcast and Icecast). Out of the box there will be _No outputs_ like you describe as the audio is coming straight from Mopidy.

To control Icecast from Iris, see _Settings > Icecast > Stream audio to this browser_, but do note that it's a bit temperamental due to the nature of how it's integrated in Iris.

**Comment by chlowden** [comment]
Hello James

Thanks for clarification. I cannot see how I did not see the Icecast 
button in the settings, but then, I was not looking for it there either.

Is there an intention to make this workflow more robust? At the moment, 
when it works, it works well, but when i change track, the connection is 
lost. That said, I have exactly the same issue when I have both the the 
iris & mopidy html pages open at the same time. So I presume that maybe 
it is more a mopidy - icecast issue.

Last question, it is possible to see more track metadata in your 
interface, in particular the genre

Many thanks for your time

Christopher

**Comment by jaedb** [comment]
Not right now, there are some more pressing features and upgrades in the pipeline first. Feel free to open a Feature Request ticket and we can gather community feedback and support to decide it's priority.

There isn't any support for genre at this time. Genre structure is too varied between backend providers to make it a straightforward and platform-agnostic feature.
