### ISSUE TITLE
[Feature request] Queue whole album

### ISSUE THREAD

**Issue by sgraca** [jaedb/Iris#45]
It would be nice to be able to easily queue the whole album. Currently clicking play starts playing the album immediately, and to queue it one has to mark all tracks individually and queue them.

**Comment by henkkah** [comment]
Second this, Context clicking an album would feel natural, or just mimic the way Spotify works.

ps. @sgraca shift click works so no need to click all tracks individually, just select the range from first to last...

**Comment by sgraca** [comment]
@henkkah I know about shift click, but how do I do this on smartphone?  :smile:

**Comment by henkkah** [comment]
Oh, no idea.

Come to think of it, guess I've never stumbled upon an effective mobile UX-pattern for selecting a range of items from a list...

Ps. thanks @jaedb for making Iris. I really appreciate the slick UI and the snappiness of React :)

**Comment by jaedb** [comment]
@sgraca When tapping a single track (touch devices), this is the same as `CTRL + Click` on the desktop. This will mean you can select all tracks (albeit one-by-one).

As you mention @henkkah, it is a function that has not been cracked, even by the Googles of this world (yet!).

**Comment by jaedb** [comment]
Resolved in #808ce2d (2.11.3)
