### ISSUE TITLE
Add Snapcast Stream Control to Speaker window

### ISSUE THREAD

**Issue by ncsufan8628** [jaedb/Iris#451]
**Is your feature request related to a problem? Please describe.**
I use Snapcast to play Mopidy thru Iris (and other sources, too).  This means 100% of the time, I need to change the active snapcast stream to Mopidy within the Iris settings when I go to play something.

**Describe the solution you'd like**
It'd be great to also add the stream selection dropdown underneath each zone shown in this window, which would greatly simplify the process of changing Snapcast active sources within Iris.

**Additional context**
Screenshot of area I am referring to

<img width="420" alt="Screen Shot 2019-10-20 at 1 13 13 PM" src="https://user-images.githubusercontent.com/16391568/67164463-bcaa8f00-f348-11e9-8f9f-5eb384d59857.png">

**Comment by jaedb** [comment]
Sounds like a valid suggestion.

It makes me wonder whether the better UI for the _Output Controls_ popup (in your screenshot) is better to control clients or groups. My multi-room setup only has one client per room so it wouldn't affect me, but I would be interested to gauge people's feedback:

What would be most useful for the _Output Controls_ popup in Iris:
1. manage stream, mute and volume on a per-group basis (individual clients wouldn't be shown); or:
2. list all clients (grouped by group), possibly creating a large list of clients and controls.

**Comment by ncsufan8628** [comment]
To elaborate a bit, I currently have 3 available sources that Snapcast can play.  Mopidy, Airplay, MUTE.  The purpose of mute is to allow me to keep sets of speakers deliberately OFF in the case I am playing Mopidy in the Main House but Airplay in the Mancave.  

I'd be just looking to see the active stream controls added.  Grouping doesn't really apply to me, and I currently do not use it (each Zone is its own group).  In my setup the "grouping" of speakers is handled by my hardwiring of my amplifier.  Main House is actually 3 pairs of speakers/stereo channels.  When I was sketching out the system, if each speaker pair was its own client and I used grouping, the soundcard required to have that many unique outputs would have cost a fortune lol.

Hope that helps.

**Comment by jaedb** [comment]
Released at 4.43.0
