### ISSUE TITLE
Search incomplete

### ISSUE THREAD

**Issue by chlowden** [jaedb/Iris#455]
**Describe the bug**
Searching does not give all the possible mopidy results

Attached is a search result using the same mopidy service using Iris and Moped on the same machine.
As you can see, the Iris result is not as complete. This result is very consistent on nearly all the search results.
Any ideas what I am doing wrong ?

**Screenshots**

![moped](https://user-images.githubusercontent.com/6749130/67439917-f6ed8800-f5f7-11e9-9bcc-8a3bfadeaaa7.png)
![iris](https://user-images.githubusercontent.com/6749130/67439923-fce36900-f5f7-11e9-8df3-2313bcbdab10.png)

**Comment by jaedb** [comment]
I believe the issue is a knock-on to #409 which was causing duplicate searches. In summary, the results in Iris are only matching the `track_name`, not it's artist or album.

**Comment by BrainStone** [comment]
I can confirm that the search in the current version is not giving nearly as many results as before.

And for some sources like YouTube and TuneIn you don't get any results anymore at all. Where as a normal MPD search will give you plenty of results.

**Comment by jaedb** [comment]
Sidenote: is Mopidy-YouTube working for you? I've had such mixed success with that extension.

**Comment by BrainStone** [comment]
I use a fork of it that is working great!  
https://github.com/natumbri/mopidy-youtube if anyone is interested!
