### ISSUE TITLE
Volume slider too small for mobile devices

### ISSUE THREAD

**Issue by nilsholle** [jaedb/Iris#459]
**Describe the bug**
The volume slider is quite small on large screens (too small in opinion), but on smaller (mobile) devices it is close to being unusable.
I would highly appreciate a 1.5 - 2 times increase in size.

**To Reproduce**
Try using the slider on your phone.

**Comment by jaedb** [comment]
Can you please provide me with screenshots, and more information about your device(s) and environment (browser, Iris version, etc)?

**Comment by jaedb** [comment]
I'll close this issue for now as I cannot replicate it and there are no supporting screenshots of the issue to help diagnose it. Please feel free to re-open when more information can be provided.
