### ISSUE TITLE
Having the option to search different metadata depending on source

### ISSUE THREAD

**Issue by chlowden** [jaedb/Iris#460]
Following the discovery that the Iris search engine only searches song titles because of the huge amount of source that it can consult, can I suggest that an option be added that offers the option to search title, artist & genre for local files and more reduced search criteria for non local sources.
Currently, I use the musicbox_webclient for title, artist & genre search that I play through Iris & icecast.
Many thanks

**Comment by jaedb** [comment]
As far as the Mopidy architecture is concerned, there is no difference between a 'local' source (ie `local:file:...`) and a 'remote' source (ie `spotify:track:123...`). So I whatever the approach is, it will need to be applied to all sources.

#455 reverts to searching `any` field for tracks, which goes some way to resolving your underlying issue, so I will close this ticket.

I do see the value in allowing different backends to search different fields, but right now it is a bit out of scope. The current mechanism to reduce the impact is the ability to select which sources you want to search (_Search > Sources_).
