### ISSUE TITLE
Iris - questions

### ISSUE THREAD

**Issue by chlowden** [jaedb/Iris#461]
What does the "consume" button do?
Can the titles, albums & Tracks tabs show Local content?
How does the Love button work with local media?
Can the create playlist button work with local media?
I don't use spotify. I have joined Lastfm but I don't understand how or if Iris can feed it?
Many many thanks

**Comment by jaedb** [comment]
I suggest having a peek at the Mopidy documentation which covers a lot of this. And have a play with Iris - see what stuff does! To answer your questions though:
- Consume removes the track from the queue once played
- Local content can be viewed under _My Music > Browse_ or if using Mopidy-Local-Sqlite, _My Music > Artists_, _Albums_, etc.
- Create playlist supports local `m3u` playlist backend, yes
- Iris uses LastFM for the _Love track_ feature, and for fetching album artwork
