### ISSUE TITLE
Various Artists show separately in Artist Page

### ISSUE THREAD

**Issue by tomaspapan** [jaedb/Iris#462]
*What part of Iris is your question about?*
Artist Page

**Your question**
If I add an album which consists of Various Artists the Artist page shows all the artists. I would prefer to have only Various Artists (exactly like it is done in iTunes or Plex) Screenshot attached.

https://imgur.com/a/0mMDtNY

1. In the first screenshot you can see there is a Various Artists in the Artist Page. Underneath is only one album Stranger Things.

2. This album has one song from Bon Jovi in it and as you can see now the Bon Jovi is also shown in Artist Page (screenshot 3). 

3. Itunes nor Plex will display Bon Jovi in their Artist page. (they respect albumartist tag).

4. It's pretty annoying if you have a big collection of classical music.

Can something be done here? Or should I ask in mopidy community.

**Did you want to make a donation to support this support?**
I can help with pull request if this functionality is desired.

**Comment by jaedb** [comment]
If you are using the recommended `Mopidy-Local-SQLite` backend then you can configure the URI used to define your _Local Artist_ library.

To do this, just got to _Settings > Advanced > Artist Library URI_ and set the value to `local:directory?type=artist&role=albumartist`. This will tell the local library to get your artists by `albumartist`.

Hopefully this does the trick for you.

**Comment by tomaspapan** [comment]
> If you are using the recommended `Mopidy-Local-SQLite` backend then you can configure the URI used to define your _Local Artist_ library.
> 
> To do this, just got to _Settings > Advanced > Artist Library URI_ and set the value to `local:directory?type=artist&role=albumartist`. This will tell the local library to get your artists by `albumartist`.
> 
> Hopefully this does the trick for you.

That is perfect, that's exactly what I wanted. Thank you!

**Comment by fmarzocca** [comment]
> To do this, just got to _Settings > Advanced > Artist Library URI_ and set the value to `local:directory?type=artist&role=albumartist`. This will tell the local library to get your artists by `albumartist`.

Hi James,

where could I find a complete list of various settings details (such as above)?
