### ISSUE TITLE
accented characters in local library

### ISSUE THREAD

**Issue by chlowden** [jaedb/Iris#463]
**Describe the bug**
Accented french characters are not being interpreted properly leading to playlist not working. Not sure if it is iris or mopidy that is interpreting the characters.

Raspberry Pi path
/var/lib/mopidy/media/LOWDEN_MUSIC/MUSIC/Compilations/Master_Gold_France__Disc_1_/01_L_été_Indien.mp3

playlist path
local:track:Compilations/Master_Gold_France__Disc_1_/01_L_été_Indien.mp3

Below is the browser address
http://***********:6680/iris/track/local%3Atrack%3ACompilations%2FMaster_Gold_France__Disc_1_%2F01_L_Ã©tÃ©_Indien.mp3

![Screenshot from 2019-11-10 10-47-30](https://user-images.githubusercontent.com/6749130/68542019-8db39600-03a7-11ea-8e30-7f5b6bf77878.png)

Is there a way to add foreign character interpretation?
Thank you

**Comment by jaedb** [comment]
It depends on how Mopidy translates these characters, and making sure that Iris encodes them appropriately for use in a URL. Mopidy encodes _some_ characters but not others, so it's a bit clunky right now.
I suspect that this is an area of improvement, especially with the upcoming Mopidy Python3 revamp.

**Comment by chlowden** [comment]
Let us look forward to the revamp.
Many thanks

⁣Get BlueMail for Android ​

**Comment by jjok** [comment]
I've never seen the issue with the any of the backends or frontends that I've used. I've seen Japanese, Thai and Korean characters displaying correctly.

I would guess that this is a problem with Mopidy-Local, which I've never used.
Maybe [this `fsdecode()`](https://github.com/mopidy/mopidy-local/blob/d65a7902df7d030e1a213c52972b23cd2b34960a/mopidy_local/translator.py#L24). I'm totally guessing though.

**Comment by kingosticks** [comment]
I'd suggest attempting to reproduce this in Mopidy 3, we changed a lot of the unicode handling during the Python 3 port.

**Comment by jaedb** [comment]
@chlowden do you still encounter this issue running the latest Mopidy and Iris releases?

**Comment by chlowden** [comment]
Hello James

I'm sorry I have not replied earlier. For French, it work well now that 
i have upgraded. On top of that, the whole system works so much better 
for me now.

Thank you so much for your work

Christopher

**Comment by jaedb** [comment]
Perfect - glad to hear Iris is working well for you. I'll close this issue now.
