### ISSUE TITLE
Error after updating to 3.42.2

### ISSUE THREAD

**Issue by el97** [jaedb/Iris#465]
Hi! I just updated iris and i got the errors that i pasted in this issue. I updated it with the PIP command though SSH. I can find iris if i manually type in the URL. But i got a warning that says "Pusher not connected" and in the status is stuck at connecting.
```
Nov 19 23:06:10 MagicMirror mopidy[20785]: INFO     Disabled extensions: iris
Nov 19 23:06:10 MagicMirror mopidy[20785]: WARNING  Found iris configuration errors, the extension has been automatically disabled:
Nov 19 23:06:10 MagicMirror mopidy[20785]: WARNING    iris/snapcast_port unknown config key.
Nov 19 23:06:10 MagicMirror mopidy[20785]: WARNING    iris/snapcast_host unknown config key.
Nov 19 23:06:10 MagicMirror mopidy[20785]: WARNING    iris/snapcast_enabled unknown config key.
Nov 19 23:06:10 MagicMirror mopidy[20785]: WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.

```

**Comment by jaedb** [comment]
You will need to remove the configuration lines for the old `snapcast_host`, `snapcast_port` and `snapcast_enabled` values. I've updated the release notes to ensure other users don't experience the same issue.
