### ISSUE TITLE
Removal of snapcast_enabled configuration variable

### ISSUE THREAD

**Issue by tgurr** [jaedb/Iris#466]
First let me thank you very very very much for bringing back Snapcast support in combination with the latest Snapcast release and providing a great experience with Iris!

I have a small question, https://github.com/jaedb/Iris/commit/b75c2a67f8dc7243dfedd5a5492ef6176488c15d removed the `snapcast_enabled` variable so now users browsing Iris first have to go to the settings to enable snapcast functionality manually. Previously it was possible to enable Snapcast support globally via the configure variable which was pretty handy and neat. Is it possible to bring this feature back?

**Comment by jaedb** [comment]
**The short answer**
Not as it once was.

**The long answer**
I'm thinking there may be a way to set 'Server default' configuration. Right now you can share your config (including Spotify, Genius and LastFM authorizations, general UI config, and Snapcast config) with any connected client.
Perhaps there could be a mechanism to set these config values as the server default, so clients will inherit the defaults out-of-the-box. If this is something that would solve your concern, please feel free to open a Feature Request issue.
