### ISSUE TITLE
Feature Request: Add entire local Albums and add multiple local songs to a local playlist

### ISSUE THREAD

**Issue by ncsufan8628** [jaedb/Iris#467]
**Is your feature request related to a problem? Please describe.**
Currently, to create a playlist from local files within Iris, I need to go song by song and individually click the hamburger menu, then add to the appropriate playlist

**Describe the solution you'd like**
I'd like to be able to search for albums and add the entire album to a local playlist and be able to select multiple songs at once from an album and add those to a local playlist with one "add to playlist" click/action

**Describe alternatives you've considered**
Alternative is manually clicking each song within the album and adding them... much more work and tedious.

**Comment by jaedb** [comment]
@ncsufan8628 today is your lucky day. Try clicking the track, holding down `ctrl` (`command` on Mac) and clicking another track to select multiple, or `shift` to select a range.

**Comment by ncsufan8628** [comment]
boom!  thanks!  should have tried that
