### ISSUE TITLE
Iris not working after update from UI

### ISSUE THREAD

**Issue by Alkuimista** [jaedb/Iris#468]
I already tried upgrading from command line with no success:

`pi@raspberrypi:~ $ sudo pip install --upgrade Mopidy-Iris
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: Mopidy-Iris in /usr/local/lib/python2.7/dist-packages (3.42.2)
Requirement already satisfied, skipping upgrade: ConfigObj>=5.0.6 in /usr/local/lib/python2.7/dist-packages (from Mopidy-Iris) (5.0.6)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in /usr/lib/python2.7/dist-packages (from Mopidy-Iris) (2.21.0)
Requirement already satisfied, skipping upgrade: setuptools>=3.3 in /usr/lib/python2.7/dist-packages (from Mopidy-Iris) (40.8.0)
Requirement already satisfied, skipping upgrade: Mopidy-Local-Images>=1.0 in /usr/local/lib/python2.7/dist-packages (from Mopidy-Iris) (1.0.0)
Requirement already satisfied, skipping upgrade: Mopidy>=2.0 in /usr/lib/python2.7/dist-packages (from Mopidy-Iris) (2.3.0)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python2.7/dist-packages (from ConfigObj>=5.0.6->Mopidy-Iris) (1.12.0)
Requirement already satisfied, skipping upgrade: Pykka>=1.1 in /usr/lib/python2.7/dist-packages (from Mopidy-Local-Images>=1.0->Mopidy-Iris) (2.0.0)
Requirement already satisfied, skipping upgrade: uritools>=1.0 in /usr/lib/python2.7/dist-packages (from Mopidy-Local-Images>=1.0->Mopidy-Iris) (2.2.0)
Requirement already satisfied, skipping upgrade: ipaddress in /usr/lib/python2.7/dist-packages (from uritools>=1.0->Mopidy-Local-Images>=1.0->Mopidy-Iris) (1.0.17)
pi@raspberrypi:~ $ `

Any idea?

Thanks in advanced

**Comment by jaedb** [comment]
Looking at your log, you're already on the latest version. What exactly do you mean by "Iris not working"? Please follow the provided issue templates as it makes sure your provide the relevant information first time around.

**Comment by LickABrick** [comment]
From what version are you coming? After 3.42.0 you need to remove some settings from the config:

**Breaking changes**
Configuration values changed, users will need to remove snapcast_host, snapcast_port and snapcast_enabled from their configuration.

_[from the releases page](https://github.com/jaedb/Iris/releases)_

**Comment by jaedb** [comment]
@Alkuimista I'm closing this as it appears to be resolved, but please re-open with additional information if the issue persists.
