### ISSUE TITLE
Shuffle enabled on Iris startup

### ISSUE THREAD

**Issue by triangle-stream** [jaedb/Iris#470]
Hi there! 

Is it possible to enable the shuffle function into Mopidy or Iris config, so it will be able to start with shuffle enabled? 

Thank you.

**Comment by jaedb** [comment]
This is something that is managed by the Mopidy core (see [configuration](https://docs.mopidy.com/en/latest/config/#confval-core/restore_state)).
I recommend you open a feature request on the [Mopidy repository](https://github.com/mopidy/mopidy) to have this feature developed (or help develop it yourself if you can).
