### ISSUE TITLE
Trying to use the Docker instructions on armbian

### ISSUE THREAD

**Issue by depressivum** [jaedb/Iris#475]
I tried the default files for docker-compose.yml on armbian buster and got this message after issuing 
`sudo docker-compose up`
`"ERROR: Named volume "HOST_SNAPCAST_TEMP:/tmp:rw" is used in service "snapserver" but no declaration was found in the volumes section."`

The /tmp directory is existend. Any further advices to run the Docker setup for Iris?

**Comment by jaedb** [comment]
It looks like you haven't yet configured the mapping of the `/tmp` path. Replace `HOST_SNAPCAST_TEMP` with your temporary directory on your host machine (eg `../tmp/snapcast`).
Give that a crack and let us know if it does the trick for you.

**Comment by depressivum** [comment]
Thank you for your help.
The Dockerfiles are in `~/iris` and the regular host machine has an existing folder  `/tmp`.
I created a new `/tmp` folder inside `~/iris` and also tried different paths for `HOST_SNAPCAST_TEMP`.
I have to admit that i´ve no idea what i´m doing because i didn´t use docker this way before. 

I tried this paths without success:
```
    volumes:
      - HOST_SNAPCAST_TEMP:/tmp
```
```
    volumes:
      - HOST_SNAPCAST_TEMP:./tmp
```
```
    volumes:
      - HOST_SNAPCAST_TEMP:../tmp
```
```
    volumes:
      - HOST_SNAPCAST_TEMP:/tmp/snapcast
```

**Comment by jaedb** [comment]
I recommend reading up on what these configuration values actually mean (see [volume configuration reference](https://docs.docker.com/compose/compose-file/#volume-configuration-reference)).
You need to **replace** the text `HOST_SNAPCAST_TEMP` with your path. Leave the right-hand side alone, you only need to change th left-hand side (left of `:`). The syntax for these rules is `HOST_PATH:CONTAINER_PATH`.

**Comment by depressivum** [comment]
Thank you very much, this solved the problem.
I now get
`helios@helios4:~/iris$ sudo docker-compose up
Starting iris_snapserver_1 ... done
Recreating iris_mopidy_1   ... done
Attaching to iris_snapserver_1, iris_mopidy_1
mopidy_1      | standard_init_linux.go:211: exec user process caused "exec format error"
snapserver_1  | standard_init_linux.go:211: exec user process caused "exec format error"
iris_snapserver_1 exited with code 1
iris_mopidy_1 exited with code 1`
but i think it´s a misconfiguration i did again so i will search this and open a new issue if i won´t find it my own.

**Comment by jpbaril** [comment]
> I recommend reading up on what these configuration values actually mean (see [volume configuration reference](https://docs.docker.com/compose/compose-file/#volume-configuration-reference)). You need to **replace** the text `HOST_SNAPCAST_TEMP` with your path. Leave the right-hand side alone, you only need to change th left-hand side (left of `:`). The syntax for these rules is `HOST_PATH:CONTAINER_PATH`.

I think it should be clarified in instructions because I too did not understood that and I have used Docker a lot.
