### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by sterni1971** [jaedb/Iris#491]
In https://github.com/jaedb/Iris/wiki/Getting-started#installing
you find under:
To install using PIP
Run sudo echo "mopidy ALL=NOPASSWD: /usr/local/lib/python2.7/dist-packages/mopidy_iris/system.sh" >> /etc/sudoers 

this should be
/usr/local/lib/python3.7/dist-packages/mopidy_iris/system.sh

best regards!

**Comment by jaedb** [comment]
Wiki updated to reflect new environment.

**Comment by fmarzocca** [comment]
_"Run sudo pip install --upgrade Mopidy-Iris._" 
Shouldn't this be:
`sudo pip3 install --upgrade Mopidy-Iris`
?
