### ISSUE TITLE
iris is not using album artwork provided by mopidy-local

### ISSUE THREAD

**Issue by tomaspapan** [jaedb/Iris#496]
**Describe the bug**
Iris is not using album artwork which is embedded in the media file and correctly processed and generated by mopidy-local

**To Reproduce**
1. Put an album artwork in to the file
2. Run mopidyctl local scan
3. Go to Iris
4. Click on 'Albums'
5. There is different album artwork

**Expected behavior**
Use a album artwork provided by mopidy-local

**Screenshots**
https://imgur.com/a/m3p03v7

**Environment details:**
 - OS: Raspbian
 - Browser Firefox, Safari
 - Iris version [e.g. 3.44.0]

**Additional context**
It was working just fine pre-python3.

**Comment by tomaspapan** [comment]
It was fixed in 3.44.3 but it is back in 3.45.1 :(

**Comment by jaedb** [comment]
Can you please hard refresh your browser and use the _Clear cache_ button under settings? I cannot replicate the resurfacing of this issue at my end.

**Comment by tomaspapan** [comment]
I'm sorry but it's not showing up. It is pulling the images from last.fm. Tested in two browsers (Safari, Firefox and dropped cache :(

**Comment by tomaspapan** [comment]
as you can see lastfm pulling :(
https://imgur.com/a/KTfGPNt

**Comment by tomaspapan** [comment]
I've just tested the develop branch with your latest commit and I'm still not able to see the embedded pictures.

**Comment by shadowking001** [comment]
Hello, I'm facing the same issue.

**Comment by jaedb** [comment]
@tomaspapan can you please try again, making sure you clear all browser caches? This is working perfectly for me (on `develop`).

**Comment by tomaspapan** [comment]
@jaedb can confirm, it's working.
