### ISSUE TITLE
Use getImages for Browse > Local libraries

### ISSUE THREAD

**Issue by spinfoam** [jaedb/Iris#497]
Thanks for the nice work on this webclient.
I am a new user of this mopidy client and I couldn't find if the behavior in  "My music -> Browse -> Files" or "My music -> Browse -> Local media" should include the display of album artwork from local directories that include jpeg files or not.
I don't see any artwork in these two views contrary to "My music -> Album" where the pictures are loaded.

If this is not yet implemented I would support the implementation by donation, additional to my recent one.

Thank you.

**Comment by jaedb** [comment]
It is not currently implemented, but with Mopidy 3 and the more universal `library.getImages`, it should be very doable.

**Comment by spinfoam** [comment]
I have been intermittently trying this new feature (recently on 3.46.0) and I am still not able to see any pictures when browsing via "My music -> Browse -> Files -> 'Artist directory' " (my setup is "mopidy music root directory" -> "artist directory" -> "albums"). I have tried to understand the code of the relevant commit but I have no experience with JS so it was not much enlightening. Is it really so that in the Thumbnail view there should now be tiles with pictures from the album folder? Maybe there are some restrictions on format/naming/uniqueness. Going to localhost:6680/local I see webpage filled with images.

Sorry for bothering with my problem.

**Comment by jaedb** [comment]
Images are only available to the Local backend (ie _My Music > Browse > Local media_, and to Album and Tracks, not Artists.

Use the collated library instead (_My Music > Artists_, etc) which provides additional images and metadata.
