### ISSUE TITLE
Version is not detected

### ISSUE THREAD

**Issue by BrainStone** [jaedb/Iris#499]
**Describe the bug**
The current installed version is not being detected/detected as "unknown version".

**To Reproduce**
1. Install Mopidy-Iris 3.44.3
2. Go to "Settings" and scroll down
3. Check version number

**Expected behavior**
That the version number is being detected properly.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4106544/74646373-03cf5200-517a-11ea-8458-340ddb04344c.png)

**Environment details:**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Iris version: 3.44.3

**Comment by TrollDecker** [comment]
I think this is the same as [this one](https://github.com/jaedb/Iris/issues/489), so it's been ongoing for a little bit. :confused:

**Comment by jaedb** [comment]
@BrainStone are you running in a Docker container? How do you usually perform updates?

**Comment by fmarzocca** [comment]
Same for me. I am not running in a docker container, and I have updated from 3.44.0 to 3.44.3 with 
`sudo pip3 install --upgrade Mopidy-Iris`

**Comment by BrainStone** [comment]
@jaedb no I am not running in a Docker container.  
And I install updates just like the guy above.
