### ISSUE TITLE
Links don't react on pressing ENTER

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#5]
_From @vojtapolasek on December 19, 2016 8:55_

Hi,
I am a blind Linux user and Spotmop looks really like the think I need. But unfortunately  all links in Spotmop (Artists, settings, etc) don't react on pressing Enter on them. I have to click them with a mouse and this is really impractical for me. Could you please fix this?

_Copied from original issue: jaedb/spotmop#162_

**Comment by jaedb** [comment]
Are you able to run Iris to see if this is still an issue? Iris is the new version of Spotmop, and is built on React so will use a different rendering method for links. Hopefully this will remedy this issue.

If not, we may require involvement from the community in order to code this as I'm not familiar with UX design for blind users.

**Comment by vojtapolasek** [comment]
Hi,
it works in Iris.
