### ISSUE TITLE
In-browser playback intended?

### ISSUE THREAD

**Issue by connor4312** [jaedb/Iris#502]
*What part of Iris is your question about?*

General

**Your question**

Apologies if this is a dumb question. I'm just getting started with Mopidy and am working on an little Azure/cloud playback extension. I have it working, running the server on a Linux VM. When I play tracks in the browser, the UI seems to update, but music doesn't play. Is it intended that music plays through the browser, or only on the server on which Mopidy is running?

By the way, great work on Iris--it feels super sleek and professional. Better UI that spotify in my opinion 😄 

**Did you want to make a donation to support this support?**
Answering questions and providing support takes personal time, so please bear this in mind.

**Comment by jaedb** [comment]
I'd suggest having a read-up on the [Mopidy documentation](https://docs.mopidy.com/en/latest/) as this will answer a lot of your questions.

The answer to your immediate question is: yes and no. It depends how you're using it. Mopidy plays audio on the device that Mopidy is installed (eg your VM). However you can set things up so this audio stream is handled however you like.

For example I personally run Mopidy on my home server alongside a [Snapcast](https://github.com/badaix/snapcast) server. Snapcast broadcasts the audio to the Snapcast client process which is running on my 3 RaspberryPi devices throughout the house, which are connected to speakers. This gives me a full multi-room audio setup.

Or you could have Mopidy output to Icecast, and then setup Iris to receive that audio stream in your browser.

Ultimately "Mopidy is just a server" and Iris is just an interface to Mopidy. Once you create the setup that you're after, it is an amazing combination!

**Comment by connor4312** [comment]
Okay, thank you! I'll see what I can do 🙂
