### ISSUE TITLE
Installing Mopidy-Iris-3.45.1 - won't install into python3.7

### ISSUE THREAD

**Issue by chlowden** [jaedb/Iris#504]
**Describe the bug**

**To Reproduce**
log of install

admin@pimusic:~/Desktop/install/Mopidy-Iris-3.45.1 $ sudo python setup.py install
[sudo] password for admin: 
running install
running bdist_egg
running egg_info
writing requirements to Mopidy_Iris.egg-info/requires.txt
writing Mopidy_Iris.egg-info/PKG-INFO
writing top-level names to Mopidy_Iris.egg-info/top_level.txt
writing dependency_links to Mopidy_Iris.egg-info/dependency_links.txt
writing entry points to Mopidy_Iris.egg-info/entry_points.txt
reading manifest file 'Mopidy_Iris.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Mopidy_Iris.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/mopidy_iris
copying build/lib.linux-armv7l-2.7/mopidy_iris/system.py -> build/bdist.linux-armv7l/egg/mopidy_iris
copying build/lib.linux-armv7l-2.7/mopidy_iris/__init__.py -> build/bdist.linux-armv7l/egg/mopidy_iris
copying build/lib.linux-armv7l-2.7/mopidy_iris/ext.conf -> build/bdist.linux-armv7l/egg/mopidy_iris
copying build/lib.linux-armv7l-2.7/mopidy_iris/frontend.py -> build/bdist.linux-armv7l/egg/mopidy_iris
copying build/lib.linux-armv7l-2.7/mopidy_iris/handlers.py -> build/bdist.linux-armv7l/egg/mopidy_iris
creating build/bdist.linux-armv7l/egg/mopidy_iris/static
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/app.css.map -> build/bdist.linux-armv7l/egg/mopidy_iris/static
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/app.css -> build/bdist.linux-armv7l/egg/mopidy_iris/static
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/app.js.map -> build/bdist.linux-armv7l/egg/mopidy_iris/static
creating build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/app-icon_256.png -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/app-icon_512.png -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/favicon.psd -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/favicon_paused.png -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/favicon_error.png -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/radio-overlay.png -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/app-icon_192.png -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/app-icon-standalone.ai -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/app-icon_64.png -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/logo-app.psd -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icon-no-bg-512.png -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
creating build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/chevron-right.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/spotify.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/folder.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/play.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/speaker-group.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/stop.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/leaf.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/list.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/chevron-left.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/broadcast.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/speaker.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/playing.gif -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/connection.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/mic.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/playlist.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/local.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/shuffle.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/soundcloud.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/server.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/back.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/search.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/music.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/close.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/cd.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/star.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/skip.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/pause.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/sections.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/compass.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/filter.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/repeat.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/genius.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/grid.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/consume.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/cog.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/folder-open.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/icons/play-alt.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/icons
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/app-icon.ai -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/logo.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/app-icon.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/favicon.png -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
creating build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-default.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/settings.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-tunein.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-soundcloud.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-folders.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/discover.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-dirble.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-itunes.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-artists.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-spotify.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-albums.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-somafm.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-google.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/backgrounds/browse-tunigo.jpg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/backgrounds
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/favicon.ico -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
creating build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/overpass-bold-webfont.woff2 -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/MaterialIcons-Regular.woff -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/overpass-regular-webfont.woff -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/overpass-italic-webfont.woff -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/overpass-black-webfont.woff -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/FontAwesome.otf -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/overpass-black-webfont.woff2 -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/MaterialIcons-Regular.ttf -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/overpass-extrabold-webfont.woff -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/MaterialIcons-Regular.eot -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/iris.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/overpass-bold-webfont.woff -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/iris.eot -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/iris.ttf -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/iris.woff -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/fontawesome-webfont.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/fontawesome-webfont.woff -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/fontawesome-webfont.ttf -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/MaterialIcons-Regular.woff2 -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/fontawesome-webfont.woff2 -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/overpass-italic-webfont.woff2 -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/overpass-regular-webfont.woff2 -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/fontawesome-webfont.eot -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/fonts/overpass-extrabold-webfont.woff2 -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets/fonts
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/logo.png -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/no-image.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/assets/blur.svg -> build/bdist.linux-armv7l/egg/mopidy_iris/static/assets
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/app.min.css -> build/bdist.linux-armv7l/egg/mopidy_iris/static
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/app.min.js -> build/bdist.linux-armv7l/egg/mopidy_iris/static
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/app.js -> build/bdist.linux-armv7l/egg/mopidy_iris/static
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/index.html -> build/bdist.linux-armv7l/egg/mopidy_iris/static
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/service-worker.js -> build/bdist.linux-armv7l/egg/mopidy_iris/static
copying build/lib.linux-armv7l-2.7/mopidy_iris/static/manifest.json -> build/bdist.linux-armv7l/egg/mopidy_iris/static
copying build/lib.linux-armv7l-2.7/mopidy_iris/mem.py -> build/bdist.linux-armv7l/egg/mopidy_iris
copying build/lib.linux-armv7l-2.7/mopidy_iris/system.sh -> build/bdist.linux-armv7l/egg/mopidy_iris
copying build/lib.linux-armv7l-2.7/mopidy_iris/core.py -> build/bdist.linux-armv7l/egg/mopidy_iris
byte-compiling build/bdist.linux-armv7l/egg/mopidy_iris/system.py to system.pyc
  File "build/bdist.linux-armv7l/egg/mopidy_iris/system.py", line 37
    def get_command(self, action=None, *, non_interactive=False):
                                        ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-armv7l/egg/mopidy_iris/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/mopidy_iris/frontend.py to frontend.pyc
byte-compiling build/bdist.linux-armv7l/egg/mopidy_iris/handlers.py to handlers.pyc
  File "build/bdist.linux-armv7l/egg/mopidy_iris/handlers.py", line 50
    async def on_message(self, message):
            ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-armv7l/egg/mopidy_iris/mem.py to mem.pyc
byte-compiling build/bdist.linux-armv7l/egg/mopidy_iris/core.py to core.pyc
  File "build/bdist.linux-armv7l/egg/mopidy_iris/core.py", line 45
    async def do_fetch(cls, client, request):
        ^
SyntaxError: invalid syntax

creating build/bdist.linux-armv7l/egg/EGG-INFO
copying Mopidy_Iris.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Mopidy_Iris.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Mopidy_Iris.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Mopidy_Iris.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Mopidy_Iris.egg-info/not-zip-safe -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Mopidy_Iris.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Mopidy_Iris.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
creating 'dist/Mopidy_Iris-3.45.1-py2.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing Mopidy_Iris-3.45.1-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/Mopidy_Iris-3.45.1-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/Mopidy_Iris-3.45.1-py2.7.egg
Extracting Mopidy_Iris-3.45.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Iris-3.45.1-py2.7.egg/mopidy_iris/core.py", line 45
    async def do_fetch(cls, client, request):
        ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Iris-3.45.1-py2.7.egg/mopidy_iris/handlers.py", line 50
    async def on_message(self, message):
            ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Iris-3.45.1-py2.7.egg/mopidy_iris/system.py", line 37
    def get_command(self, action=None, *, non_interactive=False):
                                        ^
SyntaxError: invalid syntax

Mopidy-Iris 3.45.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/Mopidy_Iris-3.45.1-py2.7.egg
Processing dependencies for Mopidy-Iris==3.45.1
Searching for setuptools==40.8.0
Best match: setuptools 40.8.0
Adding setuptools 40.8.0 to easy-install.pth file
Installing easy_install script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Searching for Pykka==2.0.1
Best match: Pykka 2.0.1
Adding Pykka 2.0.1 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for Mopidy==3.0.1
Best match: Mopidy 3.0.1
Processing Mopidy-3.0.1-py2.7.egg
Mopidy 3.0.1 is already the active version in easy-install.pth
Installing mopidy script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages/Mopidy-3.0.1-py2.7.egg
Searching for tornado==4.5.3
Best match: tornado 4.5.3
Processing tornado-4.5.3-py2.7-linux-armv7l.egg
tornado 4.5.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg
Searching for requests==2.21.0
Best match: requests 2.21.0
Adding requests 2.21.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for singledispatch==3.4.0.3
Best match: singledispatch 3.4.0.3
Adding singledispatch 3.4.0.3 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for certifi==2018.8.24
Best match: certifi 2018.8.24
Adding certifi 2018.8.24 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for backports-abc==0.5
Best match: backports-abc 0.5
Adding backports-abc 0.5 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for Mopidy-Iris==3.45.1

**Expected behavior**
Following upgrade to Mopidy V3, I am trying to install Iris. Mopidy seems to work. The raspberry pi is running on python V3.7, but it looks like iris keeps installing into 2.7.

**Screenshots**

**Environment details:**
admin@pimusic:~/Desktop/install/Mopidy-Iris-3.45.1 $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
admin@pimusic:~/Desktop/install/Mopidy-Iris-3.45.1 $ cat /etc/debian_version
10.3

**Additional context**
I have tried both the apt and .zip install and I don't see where I am going wrong. I am sure it is something silly
thank you

**Comment by kingosticks** [comment]
sudo python**3** setup.py install

**Comment by kingosticks** [comment]
@jaedb it looks like the install instructions linked from the readme are outdated.

**Comment by chlowden** [comment]
The devil is in the detail.
The new command line worked more than perfectly.
On top of that, the system works a hundred times better than before.
Thank you so much

**Comment by jaedb** [comment]
@kingosticks thanks - I've updated the [wiki](https://github.com/jaedb/Iris/wiki/Getting-started#installing) now.
