### ISSUE TITLE
iris is not using album artwork provided by mopidy-local

### ISSUE THREAD

**Issue by tomaspapan** [jaedb/Iris#508]
**Describe the bug**
It was already fixed in 3.43.3 but it is back in 3.45.1. For all the details see #496 

**To Reproduce**
see #496 

**Expected behavior**
see #496 

**Screenshots**
see #496 

**Environment details:**
see #496

**Comment by jaedb** [comment]
Duplicate of https://github.com/jaedb/Iris/issues/496
