### ISSUE TITLE
sudo echo ... >>/etc/sudoers can't work

### ISSUE THREAD

**Issue by elmicha** [jaedb/Iris#509]
The command 

    sudo echo "mopidy ALL=NOPASSWD: /usr/local/lib/python3.7/dist-packages/mopidy_iris/system.sh" >> /etc/sudoers

on https://github.com/jaedb/Iris/wiki/Getting-started#installing cannot work, because `sudo` is applied to `echo`, but the redirection happens in the shell. We get an error message:

    -bash: /etc/sudoers: Permission denied

The docs should instead have this line:

    echo "mopidy ALL=NOPASSWD: /usr/local/lib/python3.7/dist-packages/mopidy_iris/system.sh" | sudo tee -a /etc/sudoers

or 

    sudo sh -c 'echo "mopidy ALL=NOPASSWD: /usr/local/lib/python3.7/dist-packages/mopidy_iris/system.sh" >> /etc/sudoers'

or tell people to use `sudo visudo` and just add that line if it's not already there.

**Comment by jaedb** [comment]
@elmicha did you want to make a PR to implement this change?

**Comment by jaedb** [comment]
Added to Wiki
