### ISSUE TITLE
Unable to play 'Your top songs' playlist

### ISSUE THREAD

**Issue by sebastianberm** [jaedb/Iris#51]
I've authorized the frontend, and can see the playlist 'your top songs 2016', I can start playing individual songs, however, when attempting to play the entire list, I get a syslog notice with:
Jan 28 19:26:08 raspberrypi mopidy[32246]: INFO     Failed to lookup "spotify:user:spotify:playlist:37i9dQZF1CyO88Y3kSd8Jo": Operation did not complete in 10.000s

I think this playlist probably needs additional auth or something?
Is anyone able to replicate this?

**Comment by jaedb** [comment]
This is due to a 10s timeout by the Mopidy-Spotmop frontend. Unfortunately there's nothing Iris can do about it. I am looking to capture this error so at the very least Iris can notify the user.

**Comment by fekete-robert** [comment]
@sebastianberm You can increase the timeout value in your config file, that helps somewhat. See https://github.com/mopidy/mopidy-spotify

**Comment by jaedb** [comment]
See #20

**Comment by sebastianberm** [comment]
For future reference:
If anyone wants to change the timeout, do note there's a currently active open issue in Mopidy-spotify making it not to honor this config setting.
(More info @ https://github.com/mopidy/mopidy-spotify/issues/129)

**Comment by jaedb** [comment]
Also related #36
