### ISSUE TITLE
Unable to get Iris to connect to snapclients

### ISSUE THREAD

**Issue by hazardlabs** [jaedb/Iris#510]
*What part of Iris is your question about?*
Settings > Snapcast

**Your question**
I have mopidy piping sound into snapserver without issue. Clients have sound as expected
I have the snapcast android app, which can connect to the server, see all clients and control their volume.

In Iris, when I enable snapcast the icon updates to say disconnected.
I've tried all of the port number from the android app with no luck.

![snapcast](https://user-images.githubusercontent.com/10254256/76245918-ae480b80-6234-11ea-8881-4585b24f8265.png)

I suspect I'm missing a simple step or not understanding the system correctly.

**Comment by hazardlabs** [comment]
This was a rather odd issue in the end.

I ended up reinstalling firefox, as I was using firefox-esr that came with debian buster and today it had stopped working with youtube videos. Installed firefox from testing, Iris asked me to log in, and everything worked with the default values.

**Comment by jaedb** [comment]
@hazardlabs glad to hear it's working for you now.
The `host` value should be the hostname or IP address of your Snapcast server. For the value `titan` to work, your browser must be able to connect to it (ie it is a LAN-recognised address).

**Comment by predazzo** [comment]
Hello, I'm unclear how the integration is supposed to work.

Is it defining an audio source for mopidy (similar to icecast integration)?
Or does it provide functionality like snapcast app (independent control of speakers)? The little speakers button near shuffle icon pops up empty for me.

I'm interested in the 2nd functionality and although mopidy->snapserver->snapclient->alsa pipeline is playing sound, I get disconnected status for snapcast integration.

I tried snapserver, IP for host and ports 1704, 1705 and 1780 to no avail. Here's  my docker compose:

version: "3"
services:
  mopidy:
    image: nohcic/mopidy
    build:
      context: ./build_mopidy
    ports:
      - 6600:6600
      - 6680:6680
      - 5555:5555/udp
    depends_on:
      - snapserver
    networks:
      - kenwood
    volumes:
      - ./mopidy.conf:/etc/mopidy/mopidy.conf
      - ./Podcasts.opml:/Podcasts.opml
      - /storage/music:/var/lib/mopidy/media
      - soundshare:/tmp/sharesound

  snapserver:
    image: nohcic/snapserver
    build:
      context: ./build_snapserver
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    networks:
      - kenwood
    volumes:
      - ./snapserver.conf:/etc/snapserver.conf
      - soundshare:/tmp/sharesound
#    command: "-s pipe:///tmp/sharesound/snapfifo?name=default"

**Comment by diabl0w** [comment]
I am also having this issue of the snapcast saying its disconnected... I am running the snapserver on the host machine outside of a docker container. I use the ip address of the host machine (192.168.111.120) and I have tried ports 1704 1705 and 1780. It cannot connect no matter what.
