### ISSUE TITLE
Running in an iframe and/or persisting an existing connection across devices?

### ISSUE THREAD

**Issue by zaneclaes** [jaedb/Iris#516]
**Is your feature request related to a problem? Please describe.**
In a manner of speaking. I cannot seem to use Iris as a multi-room media player kiosk because of the way it handles per-device connections.

**Describe the solution you'd like**
Allow me to share a connection such that multiple kiosks can resume an existing session, given the connection ID. For example, allow me to append `?connection=WEKZPZEWFDH4` to the URL and bypass the setup.

**Describe alternatives you've considered**
I've tried the "prepopulate" solution for the initial setup, but that's not what I'm looking for (it does not bypass setup, nor does it preserve a single user). I would like to essentially have a single session that persists across devices, including i.e. spotify credentials and playlist states.

I've poked about the code and readme but don't see an obvious way to resume the session. I assume it's being set by a cookie, and it may well be the case there's already a query parameter I could use...

**Additional context**
I am attempting to embed Iris as an iframe within a Home Assistant card so that users of Home Assistant may control the audio using your beautiful UI :) 

Thanks for the efforts thusfar.

**Comment by jaedb** [comment]
A connection is an exclusive specific server-client connection to handle the websocket communication. It cannot be shared or restored, and there isn't any direct benefit to doing so as nothing is stored against that specific connection.

It sounds like you wish to effectively restore another client's browser state (authentications, settings, etc) does that sound accurate? This would be all of the data contained in `localStorage`. If you wanted to delve in to this, in your browser console just write `_store.getState()`.

**Comment by zaneclaes** [comment]
Yep — the restoration of state is what I'm looking for. I had thought it could `localStorage` but didn't dig deep enough to be sure. It seems like Iris was built for the use-case where every user interacts via their personal device, and each device has its own configuration... whereas I am trying to take a "kiosk" approach, where guests have access to physical devices (i.e., Raspberry Pi touchscreens) that allow control of the audio system. 

Ideally, they could even open a URL in their browser to get the same exact experience (i.e., Spotify account) without going through a log-in process. The purpose is to make the audio experience friction-free and **identical for everyone** in the house, with the knowledge that the network is already secure. In other words, we're looking for a "server-authoritative" approach to `state`.

Sounds like my best bet may be to use a proxy that supports localStorage (maybe [like this](https://github.com/fixate/web-storage-proxy)) so that I have a single session all browsers can share.

**Comment by jaedb** [comment]
A proxy on its own won't really do anything. What you need is an external data store that lives on your Home Assistant device, rather than the end user's browser. Iris would then need to be configured to accept an option and then support this external store.

I'll be honest, it is a significant piece of work.

It also raises privacy concerns where someone authenticates with Spotify (giving full access to playlists, music libraries, etc) and all other users inherently get this access. Right now this is facilitated on a user-triggered basis with the _Settings > Share Configuration_ function, giving the user the ability to choose what is shared. This issue has previously been discussed in #322 and #490.

What is the minimum viable solution to your concern? Bypassing the initial setup screen?

**Comment by zaneclaes** [comment]
> A proxy on its own won't really do anything.

Well, the proxy would need to inject data into `localStorage` to do something. Which works just fine; I did it in about 5 minutes with Node RED. But I'd prefer to not run behind a proxy...

> Iris would then need to be configured to accept an option and then support this external store.

Sounds like you're describing a solution where changes to the session are mirrored to the other clients. For a MVP, this may be overkill. We just need to restore state.

> It also raises privacy concerns

Certainly. I addressed this in my prior message already, but I appreciate that other users may be operating in different circumstances.

> What is the minimum viable solution to your concern? Bypassing the initial setup screen?

Well, yes, but also ensuring that `snapcast` and `spotify` in particular are configured.

I was able to achieve this with a small addition to the last `<script>` in `index.html`:
```	// Load query param settings
	const configKeys = ['ui', 'spotify', 'pusher', 'snapcast', 'mopidy', 'google', 'lastfm', 'genius']
	const params = new URLSearchParams(window.location.search)
	var urlParams = params.forEach((v, k) => {
		if (!configKeys.includes(k)) return;
		try {
			var config = {...JSON.parse(localStorage.getItem(k) || '{}'), ...JSON.parse(v)}
			localStorage.setItem(k, JSON.stringify(config))
		} catch (error) {
			console.error(error)
		}
	})
```

This solution achieves everything I was looking for (and then some). Assuming I have a valid Spotify token, I can create a URL that instantly configures everything the way I want, including the `light` theme.

I haven't fully thought through the consequences of modifying localStorage in this manner for other users. The only real vector I can easily imagine, though, is a phishing attempt. The client is in control of the browser URL, and such pre-configuration would therefore (likely) only harm the client which did Something Silly.

**Comment by jaedb** [comment]
That looks like a viable solution, nice! I would only suggest moving the importer into the `App.jsx` class.

One possible issue would be if a user inadvertently overwrites your authorization (ie _Spotify > Log out_) with their own user it may invalidate your previous authorization token, making all subsequent Spotify requests invalid. I'll need to check if Iris instructs Spotify of the authorization token invalidation.

Let me know how you get on with this solution, and if you're happy to contribute this as a pull request with supporting documentation/instructions for the integration.

**Comment by zaneclaes** [comment]
Glad that it's viable — and thanks for the offer to contribute! Here's a PR: https://github.com/jaedb/Iris/pull/519

Yeah, I thought briefly about the *logout* case as well. It's not a concern for my use-case, but I'll test that before sending a PR just in case.
