### ISSUE TITLE
Swiftkey duplicates search input when adding a space

### ISSUE THREAD

**Issue by losiu97** [jaedb/Iris#517]
**Describe the bug**
When attempting to search on mobile, the input i have written is duplicated once i click space

**To Reproduce**
1. Open Iris on mobile
2. Go to search
3. Write Test and then click space bar
4. See that word test is duplicated

**Expected behavior**
The input not to be duplicated

**Screenshots**
[Video](https://send.firefox.com/download/d1004489fd343b66/#0cVxj9T5797HWNFZ9mZ9uw)
![image](https://user-images.githubusercontent.com/20441031/77294197-1a6e4900-6ce4-11ea-9155-bfb12e04a09a.png)

**Environment details:**
 - OS: Android 10
 - Browser Firefox
 - Iris version 3.46.0

**Additional context**

**Comment by jaedb** [comment]
I have been unable to replicate this using Google Keyboard and Samsung Keyboard. What Android keyboard application are you using?

**Comment by losiu97** [comment]
Swiftkey. I just tested with GBoard - the problem does not occur

**Comment by jaedb** [comment]
@losiu97 can you please confirm whether the issue persists on the latest version? Search has had a significant change so I'm hoping this issue is resolved as well.

**Comment by losiu97** [comment]
Unfortunately, the error persists. (iris version 3.50).
But since it is a SwiftKey issue, it may not be easily resolvable
