### ISSUE TITLE
Build Docker Image on Tags

### ISSUE THREAD

**Issue by cablespaghetti** [jaedb/Iris#521]
**Is your feature request related to a problem? Please describe.**
I'm using the Docker image as the basis for https://github.com/cablespaghetti/radio-k8s and at the moment I'm using the `latest` tag. However I prefer to use versioned docker tags so I can guarantee the setup will keep working in the future if things change in your repository.

**Describe the solution you'd like**
Docker Hub can be set to run and tag a build when you push a tag to GitHub. I know you've done this for 3.44 but can you set this up for all tags, so I don't have to choose between the latest release and locking in a version?

Thanks for your great work!

**Comment by jaedb** [comment]
In _theory_ this is now setup using Docker Hub auto builds. This is how `latest` is built out, but we'll see how it goes in the next release.

**Comment by jaedb** [comment]
Automated builds are working as expected now. `3.47.0` is building out as I write this.
