### ISSUE TITLE
Sorting local albums by 'added' doesn't seem to work?

### ISSUE THREAD

**Issue by 01tot10** [jaedb/Iris#523]
First of all, thanks a lot for all the effort put into the Iris Front-End!
It is such a beautiful interface to Mopidy, and one of the early motivators for me try out the whole system in the first place!

I'm having some problems with sorting my local Albums via Iris. In detail:

**Describe the bug**
Trying to sort local albums by 'Added' doesn't produce expected results.
The sort order seems to be identical to sort by 'Name' as well as 'As Loaded'.

**To Reproduce**
1. Go to 'Albums'
2. Change sort order to 'Added'

**Expected behavior**
The sort order should be so, that the last added albums appear on top.

**Screenshots**
Sort by name:
![sort-by-name](https://user-images.githubusercontent.com/35490779/79073084-30709780-7ced-11ea-8436-7e49042d4b58.png)

Sort by added:
![sort-by-added](https://user-images.githubusercontent.com/35490779/79073069-1767e680-7ced-11ea-9bbc-b4dca287ba3a.png)

**Environment details:**
 - OS: Server running on Raspbian. Browsing collection on Ubuntu 18.04
 - Browser: Firefox
 - Iris version: Mopidy-Iris==3.46.0

**Comment by jaedb** [comment]
So glad to hear you're finding it useful!

Unfortunately there isn't a field for playlists/tracks in Mopidy for _Added_; this is only available in some providers (predominantly Spotify). As a result, unfortunately, most back ends will ignore this sort option.

_As loaded_ is simply an option to apply no sorting. This came around because Spotify's playlists load in the same order as their App, and some users wanted Iris to respect that rather than force a load order.

The upshot is that I don't know how we can fix this bug, while preserving the sort option for Spotify assets.

**Comment by 01tot10** [comment]
> Unfortunately there isn't a field for playlists/tracks in Mopidy for _Added_; this is only available in some providers (predominantly Spotify). As a result, unfortunately, most back ends will ignore this sort option.
> 
> The upshot is that I don't know how we can fix this bug, while preserving the sort option for Spotify assets.

Hey @jaedb! 

Thanks for the quick reply and for the insight!
Wow, I didn't realize this actually comes down to the fact that Mopidy doesn't support date-added at all! I also checked using 'ncmpcpp' and understood even there there's no option for sort by Added.
Hmm, I have to investigate and think of a work-around. Interesting how such, at least for me, important feature is left out completely from an otherwise awesome protocol!

Thanks again for your time!

**Comment by 01tot10** [comment]
Hey @jaedb!

I discussed with the Mopidy developers at https://discourse.mopidy.com/ and they pointed out, that while Mopidy doesn't support 'Date Added', at least 'Date Modified' is provided by the 'Track' data model!
https://docs.mopidy.com/en/latest/api/models/#mopidy.models.Track

Could this be used as the sorting 'backend' for the Albums view, when looking through local files?
I also realized that when I'm looking through my music files directly from the File Browser, I'm not actually sorting by Date Added but Date Modified instead, so it pretty much results in the same outcome.

I guess even easier would be, if the Data model for albums would support 'Date Modified', but this seems to not be a thing..
https://docs.mopidy.com/en/latest/api/models/#mopidy.models.Album

**Comment by jaedb** [comment]
In my experience, both Albums and Artists are quite simple objects; ultimately the bulk of data is in Track objects. As a result I have had to populate Album information based on the first of its Tracks. This is how I would infer an Album's `last_modified` date.

However looking at the documentation, [`last_modified`](https://docs.mopidy.com/en/latest/api/models/#mopidy.models.Track.last_modified) is the file's last modified date, not the date it was added to the Local database. So it doesn't really indicate when it was added to the library, unfortunately.

This is the continual struggle with multi-source libraries: each source has different information gaps. I think the best course of action is to rename _Added_ to _Modifed_ as a sort label. That allows a bit more flexibility in to what that actually means, cross-service.

**Comment by 01tot10** [comment]
Hey @jaedb! 

Thanks for your time once again!

> In my experience, both Albums and Artists are quite simple objects; ultimately the bulk of data is in Track objects. As a result I have had to populate Album information based on the first of its Tracks. This is how I would infer an Album's `last_modified` date.

Exactly, this is how I thought it would go as well. 

> However looking at the documentation, [`last_modified`](https://docs.mopidy.com/en/latest/api/models/#mopidy.models.Track.last_modified) is the file's last modified date, not the date it was added to the Local database. So it doesn't really indicate when it was added to the library, unfortunately.

Yes, that's what I understood as well. IMHO that's not too bad even, or at least way better than having no sort at all, since when I'm sorting albums directly via the file browser (Nautilus), the 'last modified'-sort gives quite a useful view into my latest music, I'd say. So if you ask me, I think the sort by 'Added', when browsing local files, should result in this, instead of nothing at all!
 
> This is the continual struggle with multi-source libraries: each source has different information gaps. I think the best course of action is to rename _Added_ to _Modifed_ as a sort label. That allows a bit more flexibility in to what that actually means, cross-service.

Sounds reasonable.. And I bet there's plenty of inconsistencies like these between different sources. I feel your pain.
