### ISSUE TITLE
[Feature Request] control multiple mopidy instances with one IRIS frontend

### ISSUE THREAD

**Issue by Mohawi** [jaedb/Iris#524]
I recently discovered snapcast and was amazed, that it is already supported by iris.

Using snapcast, I would love to have multiple mopidy instances on my server to provide different streaming content to different snapcast groups. Looking through github what already exists, I found https://github.com/mariolukas/HydraPlay which seems to supports this functionality.
I really like iris though and don't want to change just for this functionality. So I think it would be really great if Iris would be able to support multiple mopidy instances to enhance support for multiroom audio.

**Comment by jaedb** [comment]
I would be really interested in how you would see this working. This functionality has been bought up before, but I think it has increasing value so I am keen to explore how this might work.

The HydraPlay project looks to take a heavy focus on switching between Mopidy instances (ie it's the first decision you need to make when opening the browser). I suspect that for most Iris users would be a bit confusing, so I would be inclined to find a home for it somewhere in the playback bar or in _Settings_.

How do you see the UI controls for this functionality working with Iris?

**Comment by Mohawi** [comment]
Hi James,

great, that you want to look into it.
I think you're right about the fact, that iris shouldn't break the current user experience in favour of the hydra play gui.

For the playback bar, maybe the already implemented snapcast control with the speaker button can be augmented with the functionality of switching the playback bar to a specific zone. Maybe by just clicking on the name of the zone, the context of the playback bar switches to the selected zone. Then I guess the playback bar also would need some kind of identifier for the connected zone. (maybe as well hidden behind the speaker button)

For the tracklist aka "now playing" I could imagine a kind of "tabbed" view with one tab per zone or maybe a caroussel or something like this to change between zones...

The library and search, I believe, should be the same regardless of the zone/stream. So each searchable uri should be playable on all zones equaly. So all mopidy instances would need to have the same extensions installed. 
From the library or search you could add an URI to specific zone with the context menu. Maybe with an additional drop down menu ala "play with zone ..." or "add to tracklist / queue of zone ..."

And for the creation of new zones, I guess the already implemented functionality in the settings is more than enough. 

If you want, I guess I could create some sketches to add more details to the ideas...

**Comment by Mohawi** [comment]
Great, thank you. This works nicely.

**Comment by jaedb** [comment]
Glad it's working for you. I had a play with some other ways to approach the switching between servers. I think that if it proves itself to be a highly used feature then we could look to add a new control (like _Outputs_) in the play bar to quick-switch between them.
Have a play and let me know how you find it for day-to-day use.

**Comment by Mohawi** [comment]
Yep, I will keep you updated 👍

**Comment by oschade** [comment]
Cool feature! But how do you use it?
I started two mopidy instances at:
http://192.168.178.115:6681
http://192.168.178.115:6682

I can access both separately. But after adding the second server two the first one in settings, iris not connecting. The terminal printing this error:

`HTTP request denied for Origin "http://192.168.178.115:6681"`

**Comment by maledo** [comment]
Thank you for implementing this feature in iris! It is really great that snapcast is integrated that easily with iris!
However, I still have a problem in adding additional servers.
@Mohawi : How did you get it to work? When I try to add another modipy server (I have several instances on one raspberry pi with different ports but the same IP), iris' status says it's _connecting_ to it, but I would get a warning and nothing would happen:
```
WARNING  2020-05-28 xx:xx:xx,xxx [848:HttpServer] mopidy.http.handlers
  HTTP request denied for Origin "http://<ipaddress>:6680"
```
Any idea where it comes from and how to fix it?

**Comment by oschade** [comment]
@maledo 
You have to specify allowed origins in your mopidy config
`
[http]
enabled = true
hostname = 127.0.0.1
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins = 192.168.178.112:6680, 192.168.112:6681, 192.168.112:6682 
`

maybe, you could use 127.0.0.1, but this does not work in my setup:

`
allowed_origins = 127.0.0.1:6680, 127.0.0.1:6681, 127.0.0.1:6682 
`
see:
https://docs.mopidy.com/en/latest/ext/http/

**Comment by maledo** [comment]
@oschade Thank you so much, that worked for me!
