### ISSUE TITLE
Responsive rules for tiny (< 320px) screens

### ISSUE THREAD

**Issue by hans-martijn** [jaedb/Iris#532]
Is there a way to go to the mobile site, even though the browser may not be specifically made for mobile?

I connect with another raspberry pi, with small screen. For some reason I get the full blown site, even though the raspberry shows only a tiny bit from the site. I especially miss the buttons on the right.

Thanks in advance and kind regards,
Hans

**Comment by hans-martijn** [comment]
As you can see below, I have a tiny little screen. Every bunk on my boat is going to get such a little screen, but navigating becomes a little difficult, because when playing, the navigation buttons on the low left disappear. The bottom bar also takes a lot of screen real estate.

Btw: it automagically went to the mobile site with any browser but chromium...

![Screenshot](https://user-images.githubusercontent.com/59956528/80865454-e8a8b480-8c89-11ea-84e9-cb183863d7ab.png)

**Comment by jaedb** [comment]
Looking at your screenshot, the responsive interface is already at it's smallest limit. So elements don't compact down any further than what you're seeing.
Are your screens a high-pixel density? Is it possible your browser window is larger than the screen (ie it's been resized beyond the screen)?

**Comment by hans-martijn** [comment]
It's a 240x320 pixel screen, so that is at it's limit. I ordered some bigger screens (but not much bigger), to check whether that looks better. It actually looks good, but the bottom bar is a bit high and you lose some navigation when actually playing songs.

It looks impressive though on those tiny screens :-)

**Comment by jaedb** [comment]
Looking at Iris at 240 x 320 px I can see how difficult it is to use.
The approach to resolve would be to create an even smaller responsive breakpoint. I'll put it in the backlog until I can make the time (it will be quite fiddly) to address it properly.
