### ISSUE TITLE
[Feature Request] Soundcloud support

### ISSUE THREAD

**Issue by LickABrick** [jaedb/Iris#533]
**Describe the solution you'd like**
Being able to search music through soundcloud would be great as not all music is available on spotify.

Not sure if this has been asked/answered before.

**Comment by jaedb** [comment]
You can install the [Mopidy-Soundcloud](https://mopidy.com/ext/soundcloud/) extension to add SoundCloud support. Is this what you are after?

**Comment by LickABrick** [comment]
> You can install the [Mopidy-Soundcloud](https://mopidy.com/ext/soundcloud/) extension to add SoundCloud support. Is this what you are after?

Thanks, didn't know this worked out of the box with Iris (should've tried before asking..).
Love Iris btw, have been using it for the past 6 months and it works great.
