### ISSUE TITLE
Volume bar of Snapcast group is not updated correctly

### ISSUE THREAD

**Issue by jojo141185** [jaedb/Iris#534]
**Describe the bug**
The volume bar of the Snapcast group and its client is not in sync. Group volume bar is also not updated when it is changed via another program, e.g. Snapcast Android App or Homeassistant.
The page must be manually reloaded to update the group volume bar. 

**To Reproduce**
1. On Iris Web-Interface open Settings -> Services -> Snapcast
2. Add one client to group
3 a) Change Volume of this client in this group (vertical volume bar)
   b) Or open e.g. Snapcast Android App and change volume of the group. 
4. Volume bar of group (horizontal volume bar) isn't updated . 
5. Reload website (F5)
6. Volume bar of group is synced correctly.

**Comment by jaedb** [comment]
Snapcast doesn't technically support a group volume, so this is an Iris-only control. What I think could be done is to revisit how it is calculated. Right now it is only calculated when a client volume is changed in Iris.
A more resilient approach would be to have a group volume as a realtime representation of the average client volume, which would be updated when a client is updated outside of Iris. The challenge is when the number of clients change, the group volume would appear to change too (1 client at 50% volume, then another client connects at 100% would make the group volume change from 50% to 75%).

**Comment by jaedb** [comment]
Resolved in release `3.49.0`

**Comment by jojo141185** [comment]
Hello Jaedb,
Thanks for taking care of that bug so fast. 
Unfortunately, after updating to version 3.49.0 I still have the problem that the volume of the snapcast group does not automatically synchronize with the clients. Only after manual refreshing the web interface (F5) in browser the web interface in browser the view is updated. In contrast, the mute function works perfectly.
For better explanation I have recorded the phenomenon in the following video/gif:
![Iris 2020-05-22_edt](https://user-images.githubusercontent.com/6240522/82672477-b2cf6e00-9c40-11ea-9b28-5529d6dace45.gif)

**Comment by jaedb** [comment]
The version number indicates what version you have installed, but if your browser has cached an old version's javascript you won't be seeing the latest and greatest.

So, please try [clearing your browser cache](https://www.refreshyourcache.com/) and then re-trying. You can also do a forced refresh which should achieve the same thing but without affecting your settings.

Let me know if this does the trick or not.

**Comment by jojo141185** [comment]
Thanks James, for your answer. I have successfully deleted the browser cache. After redoing the settings and giving access to all my accounts, unfortunately the same behaviour appears as before.
Can you reproduce this problem on your computer? If not, I will try a complete reinstallation of iris.

**Comment by jaedb** [comment]
I am unable to replicate, but I've been using the Snapcast Android application as my benchmark for triggering Snapcast events. It looks like you're using some kind of HASS extension, and I wonder if that may be playing a part.

There are a few ways to verify this:
* open an incognito browser window with Iris and manipulate the volumes there to observe whether the two windows stay in-sync; and/or
* use the Snapcast Android app to observe whether Iris is receiving the volume changes.

It would also be useful to check whether any errors were being encountered in the browser. Initiate the Iris Test Mode (_Settings > Debug > Test mode_) and open your Developer Console to see if any errors appear.

**Comment by jojo141185** [comment]
Hello, James, 
I've completely reinstalled my small server in the last days (hardware change) - including mopidy and iris.The problem is still there. An identical behaviour is shown with the Snapcast Android app as well as with a second incognito window in Firefox. 
The volume control of the Snapcast group in the other window is not synchronized. Only by updating the Iris web interface (Ctrl + F5) the volume of the group will be synchronized. Volume bar of snapcast clients keep in sync. 
The volume control of the Snapcast clients is synchronized perfectly.
![Iris 2020-06-11](https://user-images.githubusercontent.com/6240522/84409404-ad48c080-ac0d-11ea-83de-1b11568f2b59.gif)

**Comment by jojo141185** [comment]
Updated to latest Snapcast Android Client v0.20.0.0. 
No improvement - same behavior!

**Comment by jaedb** [comment]
@jojo141185 thanks again for the screen capture, very helpful.
I notice you're using... Mandriva? Have you tried accessing Iris from another OS? Is the issue present there as well? Do you notice any errors in your developer console (F12)?

**Comment by jojo141185** [comment]
@jaedb No, the client I used to record the screen capture runs on Ubuntu 20.04 with Firefox 77.0.1 (64-bit). 
Currently Iris + Mopidy are running in a docker container on Ubuntu Server 18.04. Before the reinstallation I had both running in python venv. 
The behaviour is the same on all clients (Windows, Ubuntu, Android, ...) with different browsers (Firefox, Edge, Chrome, ...).
On Firefox I can catch the following css errors - but only on the first (re-)loading [ctrl +F5]: 

```
19:27:15.232
GEThttp://mopidy.server.leo.lan/iris/assets/app-icon_512.png
[HTTP/1.1 200 OK 116ms]
19:27:15.321
Unbekannte Eigenschaft 'appearance'.  Deklaration ignoriert. app.min.css:2:14
19:27:15.322
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. app.min.css:85:234324
19:27:15.327 Name einer Medienfunktion erwartet, aber '-o-min-device-pixel-ratio' gefunden. app.min.css:85:536687
19:27:15.327 Name einer Medienfunktion erwartet, aber 'min-device-pixel-ratio' gefunden. app.min.css:85:536735
19:27:15.327 Name einer Medienfunktion erwartet, aber '-o-min-device-pixel-ratio' gefunden. app.min.css:85:536998
19:27:15.327 Name einer Medienfunktion erwartet, aber 'min-device-pixel-ratio' gefunden. app.min.css:85:537046
19:27:15.327 Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:538536
19:27:15.327 Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:538713
19:27:15.328 Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:546956
19:27:15.328 Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:547294
19:27:15.329
Fehler beim Verarbeiten des Wertes für 'animation-delay'.  Deklaration ignoriert. app.min.css:85:560659
19:27:15.329
Fehler beim Verarbeiten des Wertes für 'animation-delay'.  Deklaration ignoriert. app.min.css:85:561084
19:27:15.330
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. app.min.css:85:735779
19:27:15.331 Unbekannte Pseudoklasse oder Pseudoelement '-ms-thumb'.  Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:737162
19:27:15.331
Fehler beim Verarbeiten des Wertes für '-webkit-appearance'.  Deklaration ignoriert. app.min.css:85:738399
19:27:15.331 Name einer Medienfunktion erwartet, aber '-o-min-device-pixel-ratio' gefunden. app.min.css:85:746853
19:27:15.331 Name einer Medienfunktion erwartet, aber 'min-device-pixel-ratio' gefunden. app.min.css:85:746924
19:27:15.331 Name einer Medienfunktion erwartet, aber '-o-min-device-pixel-ratio' gefunden. app.min.css:85:748055
19:27:15.331 Name einer Medienfunktion erwartet, aber 'min-device-pixel-ratio' gefunden. app.min.css:85:748126
19:27:15.332 Name einer Medienfunktion erwartet, aber '-o-min-device-pixel-ratio' gefunden. app.min.css:85:748738
19:27:15.332 Name einer Medienfunktion erwartet, aber 'min-device-pixel-ratio' gefunden. app.min.css:85:748809
19:27:15.332 Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:758323
19:27:15.332 Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:759085
19:27:15.333 Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:759846
19:27:15.333 Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:760618
19:27:15.333 Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:761361
19:27:15.333
Fehler beim Verarbeiten des Wertes für 'animation-delay'.  Deklaration ignoriert. app.min.css:85:766635
19:27:15.334
Fehler beim Verarbeiten des Wertes für 'animation-delay'.  Deklaration ignoriert. app.min.css:85:769498
19:27:15.334 Name einer Medienfunktion erwartet, aber '-o-min-device-pixel-ratio' gefunden. app.min.css:85:770102
19:27:15.334 Name einer Medienfunktion erwartet, aber 'min-device-pixel-ratio' gefunden. app.min.css:85:770173
19:27:15.334
Unbekannte Eigenschaft 'pointer'.  Deklaration ignoriert. app.min.css:85:776799
19:27:15.335
Fehler beim Verarbeiten des Wertes für 'white-space'.  Deklaration ignoriert. app.min.css:85:783486
19:27:15.336 Regelsatz wegen ungültigem Selektor ignoriert. app.min.css:85:800456
19:27:15.336
Fehler beim Verarbeiten des Wertes für 'justify-items'.  Deklaration ignoriert. app.min.css:85:807946
19:27:15.336
Fehler beim Verarbeiten des Wertes für 'animation-delay'.  Deklaration ignoriert. app.min.css:85:809027
19:27:15.576
GETws://mopidy.server.leo.lan/mopidy/ws/
[HTTP/1.1 101 Switching Protocols 18ms]
```
I don't think these errors are connected to the problem.

**Comment by jaedb** [comment]
I'll be honest, I have no clue why this isn't working for you. I've tried Mac, Windows and Mandriva with the mainstream browsers and all appear to be working as expected.

The errors you mention in the console output above all refer to CSS issues (and browser support prefixes) so shouldn't be involved.

The fact that the client volume updates shows that the Snapcast websocket is working properly, which would be my first port of call. So clearly the volume changes are being broadcast and received correctly. The next step is the volume change triggering a state change in the Iris app, which also clearly works.

The group volume is simply an average of the client volumes, calculated on render of the `SnapcastGroup` component. So the issue should be very easily replicated, but it is not.

Is the issue across all of your Snapcast groups? Or one group in particular?

**Comment by jojo141185** [comment]
Updated to version 3.51.0 yesterday. The problem is fixed now :)
@jaedb Thanks James, you for your continued support and your great work here. Iris is a masterpiece!
