### ISSUE TITLE
Adding Radio Section Under My Music for Internet Streams

### ISSUE THREAD

**Issue by Estefanop** [jaedb/Iris#535]
hi,

is there a way to have radio streams separated from the rest of music? currently i have it set in a playlist called radio streams. 

would be nice to have sections since it is a completely different format of listening

**Comment by jaedb** [comment]
It sounds like your request is a duplicate of #221, does this sound like what you are after?

**Comment by Estefanop** [comment]
Yeah they did a better job at explaining it than I did. I see that it was raised a couple years ago. Any plans on radio for Iris?

**Comment by jaedb** [comment]
At the moment there hasn't been enough support to justify the development time, hence it being requested so long ago with no implementation so far. This is project that I work on in my spare time so I need to focus on features that give as much benefit to as many users as possible - a very tricky balance.

If a large number of users wanted this feature then it would certainly warrant some extra attention. The reality is there are so many ways this could be implemented I would need to spend time scoping out the best approach before even touching the code.

**Comment by Estefanop** [comment]
Yeah i hear you, im not sure why streaming radio isnt more popular... I built one of these mopidy radios just to tune in to my fav radio stations from around the world, everything seems to have a live stream now.

Thanks for the reply
