### ISSUE TITLE
Queue page not working

### ISSUE THREAD

**Issue by kobbejager** [jaedb/Iris#536]
**Describe the bug**
After booting the system, the queye/"Now Playing" page , which is also the landing page, works ok. After a while, when I try to reopen this page, it shows the page for a second, and then turns completely black: no queue, no navigation panel, no music controls. Other pages continue to work.

The browser console outputs three times "TypeError: e is null", as shown below

Problems started to appear after updating Iris to 3.48.0 (using pip on Raspbian). I've updated Raspbian and Mopidy at the same time. 

**To Reproduce**
1. Open the [url]/iris or [url]/iris/queue in a web browser

**Expected behavior**
It should show the user interface.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/4146403/81058841-9062f400-8ecf-11ea-9023-9a743d443db8.png)

**Environment details:**
 - OS: Raspbian (server)
 - Browser: Firefox and Chrome (linux, windows and android)
 - Iris version: 3.48.0

**Comment by jaedb** [comment]
Can you please enable debug mode to get more information? You can enable this under _Settings > Debug > Test mode_. Once done please copy the full console output into this issue for diagnosis.

**Comment by jaedb** [comment]
@kobbejager I believe this issue is related to the (now released) fixes in `3.49.0`. If this problem persists, please feel free to re-open.

**Comment by kobbejager** [comment]
Ok, I'll give it a try.
I encountered the issue only three times and I didn't have a chance to switch test mode on while having the issue...

**Comment by kobbejager** [comment]
It's still there, apparently. The "Now Playing" page shows up for a brief second, and then turns black. Don't know if this has something to do with it, but it's playing a TuneIn radio station.
Below is the console output on that page with debug mode enabled.

```
The above error occurred in the <Track> component:
    in Track (created by TrackList)
    in div (created by TrackList)
    in TrackList (created by ConnectFunction)
    in ConnectFunction (created by Queue)
    in section (created by Queue)
    in div (created by Queue)
    in div (created by Queue)
    in Queue (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in main (created by App)
    in div (created by App)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. 2 react-dom.development.js:19527
    React 11
    unstable_runWithPriority scheduler.development.js:653
    React 5
    unstable_runWithPriority scheduler.development.js:653
    React 4
    Redux 4
    SnapcastMiddleware middleware.js:650
    GoogleMiddleware middleware.js:135
    GeniusMiddleware middleware.js:53
    LastfmMiddleware middleware.js:55
    SpotifyMiddleware middleware.js:488
    PusherMiddleware middleware.js:813
    MopidyMiddleware middleware.js:2495
    UIMiddleware middleware.js:256
    CoreMiddleware middleware.js:501
    localstorageMiddleware middleware.js:11
    Redux 2
    MopidyMiddleware middleware.js:2241
TypeError: string is null
2 helpers.js:413:2
    titleCase helpers.js:413
    render Track.js:244
    React 10
    performSyncWorkOnRoot self-hosted:891
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority scheduler.development.js:653
    React 4
    Redux 3
    handleChangeWrapper self-hosted:844
    dispatch Redux
    SnapcastMiddleware middleware.js:650
    GoogleMiddleware middleware.js:135
    GeniusMiddleware middleware.js:53
    LastfmMiddleware middleware.js:55
    SpotifyMiddleware middleware.js:488
    PusherMiddleware middleware.js:813
    MopidyMiddleware middleware.js:2495
    UIMiddleware middleware.js:256
    CoreMiddleware middleware.js:501
    localstorageMiddleware middleware.js:11
    Redux 2
    MopidyMiddleware middleware.js:2241
TypeError: string is null
```
