### ISSUE TITLE
Reverse proxy redirect loop

### ISSUE THREAD

**Issue by PureTryOut** [jaedb/Iris#542]
Using the nginx config as described in the wiki under "Advanced", I get a redirect loop and I can never reach Iris.

I'm using the Docker container version 3.48.0, but for some reason `pip list | grep iris` inside the container shows 3.47.0 installed.

**Environment details:**
 - OS: any OS
 - Browser: every browser
 - Iris version: 3.48.0

**Additional context**
```
192.168.1.1 - bart [14/May/2020:09:50:35 +0000] "GET /iris/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.1.1 - bart [14/May/2020:09:50:35 +0000] "GET /iris/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.1.1 - bart [14/May/2020:09:50:35 +0000] "GET /iris/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.1.1 - bart [14/May/2020:09:50:35 +0000] "GET /iris/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.1.1 - bart [14/May/2020:09:50:35 +0000] "GET /iris/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.1.1 - bart [14/May/2020:09:50:35 +0000] "GET /iris/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
192.168.1.1 - bart [14/May/2020:09:50:35 +0000] "GET /iris/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "-"
```

**Comment by PureTryOut** [comment]
Seems the configuration in the wiki is wrong. Where it lists the url of `proxy_pass` as `http://127.0.0.1:6680/`, it should actually be without the leading slash `/` at the end.

Nothing to see here :see_no_evil:

**Comment by jaedb** [comment]
@PureTryOut thanks for working through this and sharing your findings! I've updated the wiki now so other users don't experience the same issue :-)
