### ISSUE TITLE
Empty Pages: Tracks, Add to playlist - needs reopen

### ISSUE THREAD

**Issue by LimitlessGreen** [jaedb/Iris#543]
I hate to do doubles, but specially @jaedb you need to reopen this: #520 
It could also be in relation to #536

**Comment by juliusvaart** [comment]
@LimitlessGreen I've got it working again. Don't exactly know what worked, but here are the steps I took. Working in Chrome, Firefox & Safari.

1. pip uninstall iris - reboot - pip install iris
2. apt upgrade all and upgrade all mopidy extensions
3. whitelist api.spotify.com *.spotify.com in my Adblocker and PrivacyBadger
4. create new login credentials for mopidy-spotify and replace in mopidy.conf
5. logout from spotify in Iris and log back in again

**Comment by jaedb** [comment]
@LimitlessGreen can you please upgrade to `3.49.0` and confirm whether the problem is still present? The issue was closed, but the release containing the fix was only published two days ago.

**Comment by LimitlessGreen** [comment]
@jaedb I did a quick upgrade to `3.49.0` - pip version. Sadly, the symptoms are completely the same.

@juliusvaart I did nothing of this `Did you tried turning it off and on?` magic yet, maybe in a couple days.

**Comment by jaedb** [comment]
@LimitlessGreen in some cases you may need to do a hard browser refresh (shift + F5, command + shift + r, depending on your browser) to make sure you're seeing the latest code.
Can you please give this a crack to be sure?

**Comment by LimitlessGreen** [comment]
Yes, I already did a hard refresh, but nothing changed. 
Btw, don't forget to read the EDIT part :)

**Comment by LimitlessGreen** [comment]
I got confused and tried an other Browser. (Chromium)
And it just works all fine there. Looks like its a problem with (my) Firefox.

**Comment by jaedb** [comment]
Last thing to try is type this in your browser developer console: `localStorage.clear()`. This will reset all your browser-stored config. If things work after doing this, then we know there is a setting that was causing this problem.

**Comment by LimitlessGreen** [comment]
Thanks for the hint with the `localStorage`. Now it works also in Firefox.

**Comment by LimitlessGreen** [comment]
I think it's time to close it. And thank you again @jaedb .
