### ISSUE TITLE
ARM64 version of the Docker image

### ISSUE THREAD

**Issue by PureTryOut** [jaedb/Iris#545]
**Is your feature request related to a problem? Please describe.**
I'm slowly switching over from a x86_64 server to an aarch64 (arm64) one. It however seems the `jaedb/iris` Docker image I've been using is only available for x86_64.

**Describe the solution you'd like**
Please make the Docker image available for aarch64 (arm64) as well.

**Additional context**
Mopidy, it's various backends and plugins, and Iris are all architecture agnostic. Only Mopidy-Spotify isn't, but there are binaries for libspotify available for arm64 so that shouldn't be a problem.

**Comment by kingosticks** [comment]
As far as we know, there is no arm64 version of libspotify. All the ones we know about are available at https://mopidy.github.io/libspotify-archive. Have you found one elsewhere?

**Comment by PureTryOut** [comment]
Oh, darn, I misremembered then I guess, I was pretty sure there was one available.

Never mind then, Mopidy without Spotify isn't useful to me anyway, and I don't think you guys want the Docker image shipped without it either.

**Comment by kingosticks** [comment]
The rising popularity of arm64 is yet another nail in libspotify's coffin, no doubt about that. We will need an alternative at some point but sadly we don't have anything yet.

**Comment by PureTryOut** [comment]
I wonder if an armv7 image would be usable combined with 32-bit execution mode of some aarch64 cpu's actually.
