### ISSUE TITLE
[navigation] Random albums selection 

### ISSUE THREAD

**Issue by arthurlutz** [jaedb/Iris#546]
**Is your feature request related to a problem? Please describe.**

First off, congrats for Iris, it's really nice and shiny. It's a great frontend for mopidy. 

I recently fell in love with some of the UX provided by Lollypop a  gnome music player https://wiki.gnome.org/Apps/Lollypop (source https://gitlab.gnome.org/World/lollypop) it has some nice ways to explore a large collection.

**Describe the solution you'd like**

 This issue is to ask if you would be willing to look into a "Random albums" which would be next to Artists, Albums on the left. 

![Screenshot from 2020-05-25 00-03-47](https://user-images.githubusercontent.com/108437/82765998-95a2c700-9e1b-11ea-8efd-be2741629960.png)

This would present a selection of let's say 20 albums. In my case browsing through thousands of albums is a bit daunting.

**Comment by Alexdc-12** [comment]
this would be good, im looking for a similar feature much like deezers "flow" where i can say i dunno what i want to listen to just add some random tracks.

**Comment by jaedb** [comment]
@arthurlutz I'm thinking one way could be to piggy-back the _Now Playing > Add to Queue_ popup and have a button much like Google's old "I'm feeling lucky" to randomly pick tracks or albums and add those to the queue. Do you think this would achieve what you're after?

If anyone else has interest in this type of functionality, please speak up!

**Comment by Alexdc-12** [comment]
Yes exactly that! Sometimes i dont know what i want to listen to. 
Qmusic in my qnap has a similar feature it creates a playlist with 100 random tracks

**Comment by orontee** [comment]
It would be nice to have, at least optionally, this feature to clear the playlist before the chosen album is enqueued: In case one don't like the selection, he just keep on clicking the "I'm feeling lucky" button.

**Comment by jaedb** [comment]
Beta version of this has been released in `3.51`. Please have a play with it and provide feedback.

**Comment by orontee** [comment]
Great! I just updated and it's works like I expected. The `Remove` link is a good idea. 

What do you think of a second "Add random album" button?

Thanks for working on this.

**Comment by Alexdc-12** [comment]
I may be being thick but i cant see the option? I updated iris and restarted mopidy

**Comment by orontee** [comment]
@Alexdc-12 Now Playing > Add > Add random

**Comment by Alexdc-12** [comment]
Looks good to me, thanks!

**Comment by arthurlutz** [comment]
Finally got round to testing it, it works great, thanks @jaedb for a great feature.  :tada: :headphones:
