### ISSUE TITLE
Can't get Mopidy to start on raspbian

### ISSUE THREAD

**Issue by xxxjajoxxx** [jaedb/Iris#548]
I trying to start mopidy on raspbian as spotify alarm clock and when I type sudo mopidy it starting to run and stops on this

- sudo mopidy
INFO     2020-05-27 11:17:56,314 [1868:MainThread] mopidy.__main__
  Starting Mopidy 3.0.2
INFO     2020-05-27 11:17:56,401 [1868:MainThread] mopidy.config
  Loading config from builtin defaults
INFO     2020-05-27 11:17:56,415 [1868:MainThread] mopidy.config
  Loading config from file:///root/.config/mopidy/mopidy.conf
INFO     2020-05-27 11:17:56,419 [1868:MainThread] mopidy.config
  Loading config from command line options
INFO     2020-05-27 11:17:57,017 [1868:MainThread] mopidy.__main__
  Enabled extensions: stream, http, m3u, mpd, file, softwaremixer
INFO     2020-05-27 11:17:57,018 [1868:MainThread] mopidy.__main__
  Disabled extensions: spotify
WARNING  2020-05-27 11:17:57,019 [1868:MainThread] mopidy.__main__
  Found spotify configuration errors. The extension has been automatically disabled:
WARNING  2020-05-27 11:17:57,020 [1868:MainThread] mopidy.__main__
    spotify/username must be set.
WARNING  2020-05-27 11:17:57,021 [1868:MainThread] mopidy.__main__
    spotify/password must be set.
WARNING  2020-05-27 11:17:57,022 [1868:MainThread] mopidy.__main__
    spotify/client_id must be set.
WARNING  2020-05-27 11:17:57,022 [1868:MainThread] mopidy.__main__
    spotify/client_secret must be set.
WARNING  2020-05-27 11:17:57,023 [1868:MainThread] mopidy.__main__
  Please fix the extension configuration errors or disable the extensions to silence these messages.
INFO     2020-05-27 11:17:57,536 [1868:MainThread] mopidy.commands
  Starting Mopidy mixer: SoftwareMixer
INFO     2020-05-27 11:17:57,547 [1868:MainThread] mopidy.commands
  Starting Mopidy audio
INFO     2020-05-27 11:17:57,560 [1868:MainThread] mopidy.commands
  Starting Mopidy backends: FileBackend, M3UBackend, StreamBackend
INFO     2020-05-27 11:17:57,638 [1868:Audio-2] mopidy.audio.actor
  Audio output set to "autoaudiosink"
INFO     2020-05-27 11:17:57,676 [1868:MainThread] mopidy.commands
  Starting Mopidy core
INFO     2020-05-27 11:17:57,752 [1868:MainThread] mopidy.commands
  Starting Mopidy frontends: HttpFrontend, MpdFrontend
INFO     2020-05-27 11:17:57,758 [1868:HttpFrontend-8] mopidy.http.actor
  HTTP server running at [::ffff:127.0.0.1]:6680
INFO     2020-05-27 11:17:57,772 [1868:MainThread] mopidy_mpd.actor
  MPD server running at [::ffff:127.0.0.1]:6600
INFO     2020-05-27 11:17:57,787 [1868:MainThread] mopidy.commands
  Starting GLib mainloop

I tried to run mopidy with pimusicbox but I cannot instal there proper python to run mopidy alarm clock and on raspbian I cant even start mopidy

**Comment by kingosticks** [comment]
`sudo mopidy` is not a normal way to start Mopidy. The two supported ways to run Mopidy, and the difference that makes to the config file location, are thoroughly documented [here](https://docs.mopidy.com/en/latest/running/).

Since your problem has nothing to do with Iris it would be better suited to the Mopidy user forum at https://discourse.mopidy.com/
