### ISSUE TITLE
Theme selection "Auto" on new login is very dark.

### ISSUE THREAD

**Issue by onixx** [jaedb/Iris#549]
**Describe the bug**
When logging in to 3.49, the auto theme selection seems broken on Firefox.

**To Reproduce**
Login in private mode and proceed with new client

Screenshot
![image](https://user-images.githubusercontent.com/17165815/83142691-d837fe00-a0be-11ea-80e6-d8480680f355.png)

After login, go to settings. Auto is selected.
![image](https://user-images.githubusercontent.com/17165815/83142872-16cdb880-a0bf-11ea-8738-c4b9e0e23877.png)

Select dark and the colors come back normal and readable:
![image](https://user-images.githubusercontent.com/17165815/83142931-2ea53c80-a0bf-11ea-9446-f69032bad53b.png)

**Comment by jaedb** [comment]
I am unable to replicate this on Windows 10 + Firefox 76. What OS are you using, and have you performed a forced refresh or cleared your browser cache?

**Comment by onixx** [comment]
Here is Windows 10 + Firefox 76.0.1. Did a clear cache and same issue. Also tried with Edge (which I never used before), same issue.  Tried on a few other different machines with Firefox and same issue. My installation was originally 3.46 which was fine. The issue started right after my upgrade to 3.49 using sudo python3 -m pip install --upgrade Mopidy-Iris.  

The installation is inside a VM and I had made a snapshot before upgrade. I went back to 3.46 using my snapshot and its fine, no color issues.

Anything else you would like me to try

**Comment by jaedb** [comment]
I've finally managed to replicate this, but only with a rather old Microsoft Edge 44. This seemed to be due to the browser not supporting `prefers-color-scheme` which is how the auto-detection of colour theme works. Upgrading to the latest Edge (83) and it is working as expected.
So it _seems_ to be a browser issue, but I'm unable to replicate in the latest Firefox + Windows 10 (I have the same setup as yourself) so I'm a but stumped.
Perhaps the issue is to do with the VM? Can you tell me more about this?

**Comment by onixx** [comment]
I believe I found the issue. See: https://codepen.io/kleinfreund/pen/NmpKZM

My browser returns no (false) on the link above. according to https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme  : Indicates that the user has made no preference known to the system. This keyword value evaluates to false in the boolean context.

Is no-preference (false) handled as dark ?

**Comment by jaedb** [comment]
Yep you've hit the nail on the head. There isn't currently any proper handling of `prefers-color-scheme = false`.
