### ISSUE TITLE
This is just a question.. can i ask it here or somewhere else?

### ISSUE THREAD

**Issue by Hugo0485** [jaedb/Iris#553]
I installed mopidy with iris on my raspberry and i would like to play music from my file share or from an FTP. is this an option that i can install and if yes how can i do this. i searched for a long time before asking.

Thank you!

**Comment by jaedb** [comment]
@Hugo0485 this is a question for Mopidy itself (Iris is just the front-end). So if you have further questions I suggest the Mopidy [forum](https://discourse.mopidy.com/) or [chat](https://mopidy.zulipchat.com/) to get more thorough support.

To help get you started though, you will need to mount the network share on your RPI and add its path to the list for `Mopidy-File` to read from, see [docs](https://docs.mopidy.com/en/latest/ext/file/). I suggest you research "mounting FTP to raspberrypi" first to understand how this would work, the rest is just standard Mopidy configuration to suit your environment.

**Comment by jaedb** [comment]
Closing this issue as the question has been answered. If you have further questions that relate to Iris, please feel free to open another issue.
