### ISSUE TITLE
Improved Snapcast integration with per-client volume controls

### ISSUE THREAD

**Issue by djmattyg007** [jaedb/Iris#561]
**Describe the solution you'd like**
For my snapcast server I currently have two streams: one for mopidy, and one for a bluetooth audio receiver connected to the server. I then have one instance of snapclient running for each stream on each machine that plays back audio. This means music playback "just works" regardless of if it's coming from someone's phone via bluetooth or if it's coming from mopidy. We don't have to worry about manually switching clients between streams depending on how we're listening to music.

While Iris does allow volume levels to be controlled within its interface, it only lets you control volume levels for each group as a whole. For my use case, it would be better if I could select a single group and then have volume controls for each client within that group.

**Describe alternatives you've considered**
As far as I'm aware the only alternative I have right now is to use a different client to do this (like the official Snapcast Android app).

**Additional context**
![Screenshot at 2020-07-12 13-42-59](https://user-images.githubusercontent.com/489338/87238524-adbfbb80-c446-11ea-99cc-d60daf55267d.png)

Ideally this would show the same group names that show up in the official Snapcast app.

**Comment by jaedb** [comment]
The _Outputs_ panel (in your screenshot) originally showed all connected clients, but it became quite unwieldy and had limited practical use as most users wanted to change the volume of a room (aka Group), not a specific client.

Perhaps the way to accommodate your use case would be to have a checkbox for each element (Group or Client) so you could define what is shown in this _Outputs_ panel. This would require a fair bit of restructuring so I'm hesitant to commit time to this as it is quite a niche feature.

In the meantime, you can actually control all client volumes in _Settings > Snapcast > Group X_.

PS. I have opened another issue to add support for Snapcast Group Names (this didn't exist when Iris first supported Snapcast). See #563

**Comment by emiham** [comment]
Just commenting here to say that there's at least one more user who really wants this niche feature.

**Comment by sprnza** [comment]
I came here with exactly same need: to have an ability to control volume per client without necessity to go to Settings. So  I've stumbled upon this:
> most users wanted to change the volume of a room (aka Group),
Offtopic, but it's really new to me, could you please elaborate?
Never thought Group is a Room. Just curious: what's a point to organize clients like this? In what scenario you will have several clients in one room? In order to have several audio speakers playing simultaneously? But why? Ceiling speakers? No stereo be available.
