### ISSUE TITLE
Song menu available on playback controls bar

### ISSUE THREAD

**Issue by karrirasinmaki** [jaedb/Iris#566]
**Is your feature request related to a problem? Please describe.**
When there's a great song playing, and I'd like to add it to the playlist, for example, I need to go to "Now playing" view, find the song, and access the song menu from there to add it to the playlist. So far I haven't found a way to add a song to a playlist easier way.

**Describe the solution you'd like**
Would be great to have the song menu accessible from the playback controls bar, right next to the song visible on the bottom left.

**Describe alternatives you've considered**
Alternatively, would be great to access the song menu from the big album art shown on "Now playing" page.

**Additional context**
Screenshot of the song menu:
![Screenshot from 2020-07-27 12-37-17](https://user-images.githubusercontent.com/4706908/88527462-f6aa6f00-d005-11ea-904a-b437ff407b27.png)

This is how the playback controls bar could look like after the implementation:
![Screenshot from 2020-07-27 12-41-20](https://user-images.githubusercontent.com/4706908/88527885-8a7c3b00-d006-11ea-819a-598a3a1c5f49.png)
![Screenshot from 2020-07-27 12-41-41](https://user-images.githubusercontent.com/4706908/88527895-8e0fc200-d006-11ea-8a55-dc9613b32515.png)

**Comment by jaedb** [comment]
Nice work on the mockups and PR.

This is a particularly tricky part of the UI - it is quite limited in space given its alignment with the sidebar column. I'm wary that adding the context button (...) means there is even less space to display the track and artist text. My preference would be that the whole _CurrentTrack_ element became right-clickable to trigger the context menu. This would mean we don't need to add the context button and crunch this space any further.

**Comment by karrirasinmaki** [comment]
Thank you.

In PR, I implemented the feature by replacing the CurrentTrack element with the Track component. Meaning, it comes with the right-click context menu as well, and it's possible to hide (...) and Spotify (music source) icons.

With the context and music source icons, indeed, the space is very tight especially on screens smaller than 330px or 980px of width. For bigger screen sizes, the seeking bar could maybe give some space for new elements?

Anyway, I'd be happy with either or, visible context menu button or with right-click only.
