### ISSUE TITLE
[Feature Request] Spotify Playlist sorting

### ISSUE THREAD

**Issue by LickABrick** [jaedb/Iris#568]
**Is your feature request related to a problem? Please describe.**
Currently when opening a spotify playlist the newest song is at the bottom of the page. With longs playlists it will take a long time to get to the bottom.

**Describe the solution you'd like**
A way to sort playlists on e.g. date added/alphabetically

Sorry if this has been answered already, I tried to search through other issues and didn't see anything like this.

**Comment by jaedb** [comment]
This would only work if the interface had loaded the entire playlist and all of its tracks - which would potentially become an expensive process, especially for playlists with a lot of tracks.
I like the idea and would personally find it useful (I would rather see most-recently-added tracks at the top) so I'll contemplate how this might be achieved, and how long it will take.

**Comment by LickABrick** [comment]
> I like the idea and would personally find it useful (I would rather see most-recently-added tracks at the top) so I'll contemplate how this might be achieved, and how long it will take.

This would be all I/my friends need 95% of the time, thanks for taking this in consideration!

**Comment by karrirasinmaki** [comment]
I tried to start solving this problem on my fork and got the basics of it working. PR made #583.

**Comment by jaedb** [comment]
I had a quick crack at a display-level sorting but it affects quite a few behaviours that are dependent on the order of the tracks (play, delete, reorder, etc). I think the best approach is to add a sort dropdown approach like you had started working on, and use the track order in the playlist itself as the source-of-truth. The sort for display doesn't affect the asset (playlist) itself.

This is also only achievable now that `getPlaylist` fetches the entire playlist and all of it's tracks (cross-source).

**Comment by LickABrick** [comment]
@jaedb is it by design that when you sort a playlist and press the green 'Play' button it does still play in the 'As loaded' order instead of the order you sorted in?

Thanks for adding fulfilling the FR btw 👍
