### ISSUE TITLE
Help with Mopidy Config "default_app" setting

### ISSUE THREAD

**Issue by ncsufan8628** [jaedb/Iris#569]
Hello, 

Attempting to configure Iris to be the default app for mopidy.  When loading myip:6680, I understand this Mopidy setting will load Iris versus the standard mopidy Web Client list.

Here is my relevant config information.  I have tried both iris and mopidy-iris

> [http]
> enabled = true
> hostname = ::
> port = 6680
> zeroconf = Mopidy HTTP server on $hostname
> allowed_origins =
> csrf_protection = true
> default_app = iris

When loading this config, journalctl -xe spits out the following errors:

> Jul 28 10:15:38 AudioSVR mopidy[1529]: WARNING  Found http configuration errors, the extension has been automatically disabled:
> Jul 28 10:15:38 AudioSVR mopidy[1529]: WARNING    http/default_app unknown config key.
> Jul 28 10:15:38 AudioSVR mopidy[1529]: WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.

**Comment by LickABrick** [comment]
What version of mopidy and iris are you on? This option is supported as of Mopidy v3

**Comment by ncsufan8628** [comment]
You are right, I had not realized that v3 was a manual upgrade.  Upgraded and Iris working as expected now.
