### ISSUE TITLE
[Feature request] RFC integration for real radio (not spotify radio ;) )

### ISSUE THREAD

**Issue by sqrtroot** [jaedb/Iris#572]
I really like the interface of Iris. One thing I would like to see is some way to switch to radio channels easily. Having to search them every time gets convoluted (need to disable Spotify source, and then search). I like the way moped has a radio tab in its sidebar. 
It would be nice to have something like the following flow:

- search
  search the radio station, this would still involve deselecting other sources.
- add to radio sources
  when the search result is from TuneIn or RadioNet provide an extra setting in the dropdown. `Add to radiostations`. Which then adds it to the list in the sidebar.

## Alternative
Same flow for saving radiostations, but not add them to a list in the sidebar but in a seperate view (like how the current playlist, album etc. views are)

## Extra options
maybe a config option that allows default radiostations for all users.

I would like to hear what you think about this idea, and if you need help implementing it.

**Comment by jaedb** [comment]
Have a look at #221 - does this sound like the same thing you're requesting?

**Comment by sqrtroot** [comment]
Ah I didn't know about the trick with m8u playlists. It indeed sounds similar. I like your proposal of pinned playlists, because it would provide this functionality and even more (favourite playlists pinned). Hmu if you need/want help implementing this

**Comment by sqrtroot** [comment]
I'll close this issue in favour of #221
