### ISSUE TITLE
Custom Artist/Album library URI doesn't save

### ISSUE THREAD

**Issue by mcarlton00** [jaedb/Iris#574]
**Describe the bug**
Title.  After editing the textbox, clicking to a different page (ie: Browse) and coming back to the settings page shows that it doesn't reflect your changes

**To Reproduce**
1. Go to Settings -> Advanced
2. Change contents of Artist/Album URI textboxes
3. Has no effect, reverts after changing page

**Expected behavior**
An indication that the changes are saved or for them to have an effect on the contents of the Artists/Albums pages

**Environment details:**
 - OS: Linux
 - Browser: Firefox
 - Iris version: 3.50.0

**Comment by jaedb** [comment]
Confirmed, fixed in https://github.com/jaedb/Iris/commit/8824d7a5d6de30d09499df00b3adb50a6f8169e5
