### ISSUE TITLE
Group tracks by disk number and allow to play a given disk

### ISSUE THREAD

**Issue by orontee** [jaedb/Iris#586]
**Is your feature request related to a problem? Please describe.**

It's currently difficult to play a single disk in an album with multiple disks. One must know which track belong to which disk and select tracks by hand and play them.

There are good reason to play a single disk in an album:
* Albums can have a huge number of tracks (see https://musicbrainz.org/release/51a830b2-bdeb-49e9-8274-7e83e9aa57ec with more than 100 tracks)
* Each disk has its coherence that the whole album doesn't have (see https://musicbrainz.org/release/ff222cbc-bdb3-42d8-bf84-6b4a8e7f4c0f)

**Describe the solution you'd like**

The solution I imagine is made of the following changes:
- In the "album view", when there's more than one disk in the displayed album, tracks could be grouped by disk number, with a header for each disk number. That header could display the disk name when available.
- A menu button could be added alongside each disk number header that offers the expected actions (play disk, play next and enqueue)
- In the tracks section of the search page, for each track that belongs to an album with multiple disks, add the disk number right to the album name and make it clickable for users to be redirected to the right header of the album page.

**Comment by jaedb** [comment]
A MVP solution to this that I've been working on is the simple ability to allow sorting by track (which would incorporate disc order). This would provide some transparency of track's intended play order, without needing to develop unique views.

This will be coming out in the next release (or feel free to check out the `develop` branch).

**Comment by orontee** [comment]
James Barnsley <notifications@github.com> writes:

> A MVP solution to this that I've been working on is the simple 
> ability to allow sorting by track (which would incorporate disc 
> order). This would provide some transparency of track's intended 
> play order, without needing to develop unique views.

Looks promising.
 
> This will be coming out in the next release (or feel free to 
> check out the develop branch). 

I'll test this.

Thanks a lot.
-- 
Matthias

**Comment by orontee** [comment]
Visibility of track numbers in Album view is great improvement. Thanks a lot. 

Two remarks:
* I still don't know how to play a single disc in a multi-disc album
* In the tracks tab of the artist view, track numbers are hidden but the "sort by track" header is visible. Not clear to kind of sort is applied when "sort by track" is effective; Does it mean sort by album, disc and track? Won't it be clearer to display the track numbers prefixed by the album name and disc number if multiple discs?

**Comment by jaedb** [comment]
When viewing a multi-disc album, the track numbers are displayed on the far right. To play just a single disc's worth of tracks, you would need to select the tracks (using the track number to identify the end of one disc and the beginning of the next) and then play from there. That's the current solution at least.

You raise a point on the _Artist > Tracks_ view though. Sorting by track number isn't particularly useful as this would span all of the artist's tracks.

**Comment by orontee** [comment]
> When viewing a multi-disc album, the track numbers are displayed on the far right. To play just a single disc's worth of tracks, you would need to select the tracks (using the track number to identify the end of one disc and the beginning of the next) and then play from there. That's the current solution at least.

Ok, I wasn't aware of the "selection" feature. Thanks a lot!
