### ISSUE TITLE
iris won't connect to 2nd server instance

### ISSUE THREAD

**Issue by gwm** [jaedb/Iris#596]
this is a lovely looking mopidy client!

I have two mopidy instances running on the same IP address. I can connect to the first one fine:

name: borg1
ip address: 1.2.3.4
port: 6680

But iris will not connect to the second instance:

name: borg2
ip address: 1.2.3.4
port: 6681

it just gets stuck in "connecting" phase. 

Is it making assumptions about port numbers somewhere? or something more intractable?

FTR, each mopidy sends output to a separate fifo which are then both streamed from a single snapserver instance. However, I'm pretty sure this is a client side issue.

**Comment by gwm** [comment]
I should point out that if I directly edit the URL in the web browser bar to point to the other port number then it _does_ connect ok. The issue is that I can't switch between instances inside the Iris settings page.

**Comment by jaedb** [comment]
I suspect you need to allow cross-origin requests to both of your Mopidy instances. Check out the [Mopidy-HTTP](https://docs.mopidy.com/en/latest/ext/http/#confval-http-allowed_origins) docs about how to configure this.
I personally run Iris + Mopidy within a closed and controlled network, so I set `csrf_protection = false` to allow all origins.

**Comment by gwm** [comment]
oh sweet! yes that works great:

`allowed_origins = 1.2.3.4:6680,12.3.4:6681`

in both of the config files fixes the issue!

many thanks!

G

**Comment by kingosticks** [comment]
@jaedb, out of interest if you don't mind me asking, are you doing your own blocking with a proxy in front of Mopidy?

**Comment by gwm** [comment]
no proxy. just two mopidy instances running on the server/nas host.

**Comment by jaedb** [comment]
@kingosticks yeah I have a central local proxy that reverse proxies hostnames for the network. As a developer I have a few local services running so this is a lot easier than remembering IP addresses and ports.
