### ISSUE TITLE
Unicode / Non-ascii playlist names create unloadable playlists

### ISSUE THREAD

**Issue by 2e0byo** [jaedb/Iris#601]
**Description**
Iris allows one to create a playlist with a name it can't open, such as 'songs!' or 'don't work'.

**To reproduce**

Create a playlist with the name '!'.  Then open it: the url is encoded correctly as `iris/playlist/m3u%3A%21.m3u8` and iris throws the error 'Could not find anything with URI m3u:!.m3u8'.

The resulting playlist (if edited elsewhere, for example by just copying another file into it) can be loaded with the MusicBox webclient; so I _think_ the problem is in iris.

**Environment Details**
- OS: ArchLinux/debian
- Browser: Chromium
- Version: 3.52.4

I intend to dig into the code and try to fix this, but won't be able to look for at least a week.  Pointers for where to go appreciated.

Other than that Iris is great, thanks!

**Comment by jaedb** [comment]
Related to #674

**Comment by jaedb** [comment]
Resolved in 3.56.0

**Comment by 2e0byo** [comment]
Unfortunately the fix in 3.56.1 only solves some broken names.  `!` is now a valid playlist name, but `Mémoires` isn't.

In the short term would it be worth just adding a constraint to the playlist creation dialogue to enforce ascii?
