### ISSUE TITLE
Mediakey Integration

### ISSUE THREAD

**Issue by HTOgit** [jaedb/Iris#602]
Hi,

there are these Keyboard shortcuts, but is it possible to use also the Mediakeys provided by KDE or GNOME?

**Comment by jaedb** [comment]
At this stage, it is beyond the scope of this project. I want to avoid having environment-specific behavior - as I am the sole maintainer of this project so keeping functionality platform agnostic is essential.

You could install MPC and use a keybinding to trigger a mpc command (ie `mpc next`). I do something similar with a [Flirc](https://flirc.tv/) IR receiver.
