### ISSUE TITLE
Unable to delete first item in playlist

### ISSUE THREAD

**Issue by 2e0byo** [jaedb/Iris#603]
**Describe the bug**
All items in a mopidy playlist can be deleted except the first.

**To Reproduce**
1. Go to any mopidy playlist.
2. Select all tracks.
3. right click; 'remove'

**Expected behavior**
All tracks deleted.

** Actual behavior**
All tracks except first deleted.  (Attempting to delete first track in any playlist by itself results in nothing happening.)

**Environment details:**
 - OS: Archlinux/debian
 - Browser chrome, qutebrowser
 - Iris version 3.52.2/3.52.4

**Comment by MatthewFlamm** [comment]
I see this too. A (not satisfying) workaround is to reorder the playlist first and then to delete it.  

However, this also has a bug in that you cannot reorder the first song of playlist to another position.  But you can reorder the second song in the playlist to be the first.  Then you can delete the original song.  Let me know if this reordering bug should be a separate issue.  It might be related?

**Comment by 2e0byo** [comment]
I can confirm the inability to move the first item in a playlist.  However, when I reorder and delete the track is indeed deleted---is it possibleb @MatthewFlamm  that you had already queued the playlist and were just playing the old queue?  And what happens if you refresh and then load the playlist?  I find that:

- on deleting an entry the count for the playlist is unaltered---i.e. it shows n. tracks not n-1. tracks in both the playlist itself and the playlists view
- on reloading, the count is corrected
- the deleted track is indeed deleted, both as far as Iris is concerned (if I queue the playlist straight after deleting, it will queue the n-1 tracks left), and from the .m3u8

(does it delete from the .m3u8 for you?)

Sorry for delay confirming.

**Comment by MatthewFlamm** [comment]
@2e0byo I must not have refreshed properly the first time.  It works exactly as you describe.  I had removed the song from the playlist using the workaround, removed all songs from now playing and then played the playlist again.  Previously, it had played the deleted song first, but I can't reproduce now, if I additionally clear my cache before retrying.

I still cannot reorder the first track to another position.

**Comment by jaedb** [comment]
I have tracked down the cause to being the [use of Lodash `compact`](https://github.com/jaedb/Iris/blame/ddf257aaeb7360c00d2df761d2a1d44140fad392/src/js/util/arrays.js#L28). When an selected track's index is `0` (ie the first track in a list) it is treated as falsy and removed from the array, preventing it's deletion.

The fix is pretty straightforward, but I will need to check if there are implications elsewhere in the app.
