### ISSUE TITLE
Menu items wrapping on some devices

### ISSUE THREAD

**Issue by tomaspapan** [jaedb/Iris#604]
**Describe the bug**
Search and Browse menu items are having their last letter on second line.

**To Reproduce**
1. Open Iris with safari on ipad pro

**Expected behavior**
Search and Browse menu items are display on the same line

**Screenshots**
[link](https://i.imgur.com/3lCdNIY)

**Environment details:**
 - iOS 13
 - safari
 - Iris version 3.52.4

**Comment by hanerd** [comment]
Also happening on iOS 14beta8

**Comment by sebastiaanspeck** [comment]
Same for Safari on MacOS:
<img width="1680" alt="Schermafbeelding 2020-10-27 om 22 59 30" src="https://user-images.githubusercontent.com/12570668/97366842-54ba4d00-18a8-11eb-8277-b22836d017b7.png">

**Comment by giedriusb86** [comment]
Just noticed that setting css property `line-break` to auto or removing altogether from `.sidebar__menu__item` might help. But it's not necessarily a right thing to do:

```
.sidebar__menu__item {
	line-break: anywhere
}
```

**Comment by jaedb** [comment]
@sebastiaanspeck thanks for the screenshot! The weirdest bit is that it doesn't have anything to do with the length of the text (ie "Search"). Safari and Edge are two of the more 'entertaining' browsers to code for; this will probably require a browser-specific fix.
