### ISSUE TITLE
Using Spotify, I can stream with two different devices

### ISSUE THREAD

**Issue by busybox11** [jaedb/Iris#606]
**Describe the bug**
I'm currently streaming music on my phone.
I just installed Mopidy and Iris with Spotify, tried playing music, and now I have two different devices playing different music.

Why is this a thing? I think it's because Spotify Connect isn't a thing here but I don't really know.

**To Reproduce**
1. Stream music on a Spotify-Connect enabled device
2. Start a music on Iris with Spotify

**Expected behavior**
It should switch to the newly-created device, here Iris, if it has Spotify Connect integration (which does not seem to be the case)

**Environment details:**
 - OS: ArchLinux and Android
 - Browser Chrome
 - Iris version 3.52.4

**Comment by busybox11** [comment]
Wrong copy-paste, sorry.

**Comment by kingosticks** [comment]
Mopidy-Spotify has no support for Spotify Connect. The underlying Spotify library predates that feature and Spotify abandoned their software instead of supporting it.

**Comment by busybox11** [comment]
Why not switching to the newer APIs then?

**Comment by jaedb** [comment]
@busybox11 as Spotify Connect isn't available on Mopidy, it is not something that Iris can do anything about at this point (Iris is just the _interface_).

**Comment by busybox11** [comment]
Okay, I see. Does this still counts on my stats?
Like, if I listen to some kind of music, will it get registered by spotify and added to my daily mixes, just like the app.

**Comment by jaedb** [comment]
That is a question only Spotify can answer. But as music is playing, so long as it's using the same Spotify account, I would expect it to all be attributed as played tracks.
