### ISSUE TITLE
Output Controls missing on Mobile

### ISSUE THREAD

**Issue by hanerd** [jaedb/Iris#608]
**Describe the bug**
The output control (speaker icon) appears to be missing on mobile view

**To Reproduce**
1. Go to '/iris' on mobile-slim (?)
2. Click on the up carat
3. Look for speaker icon
4. Don't find speaker icon

**Expected behavior**
I would expect the speaker icon to be available to provide playback controls from a mobile device the same way it is from desktop

**Screenshots**
![IMG_1EADDB2B2339-1](https://user-images.githubusercontent.com/49296333/93269002-cc5a6f80-f773-11ea-8807-270e97593d03.jpeg)

**Environment details:**
 - OS: iOS 14 beta 8
 - Browser Chrome
 - Iris version 3.52.4

**Additional context**
This is totally outside of the scope of the awesome project you've created here, but I have custom javascript that I'm injecting via nginx using a mutation observer in order to override the `<p>` content of `.output-control__items--no-results` with `<embed>`.   I have a whole-home audio system that's REST controlled so I've built a custom page that gives me speaker controls.  Everything works fine on desktop, but mobile seems to be missing the output controls button.

I'm not 100% sure if this is a bug or a deliberate viewport breakpoint decision--sorry if it's intentional, I just couldn't find _where_ it was happening.

**Comment by jaedb** [comment]
Have you ensured that you have setup the _Snapcast_ configuration on your mobile device? The output controls section is hidden when there are no controls (ie when Snapcast isn't connected).

This is how they appear on a mobile device, with playbar expanded:

![image](https://user-images.githubusercontent.com/1711444/93586388-587ec800-f9fc-11ea-99a1-af457e0eb06d.png)

**Comment by hanerd** [comment]
ah shoot, that was it.  So sorry for the false bug--brain just wasn't working.
