### ISSUE TITLE
Added by not showing user name

### ISSUE THREAD

**Issue by sgraca** [jaedb/Iris#61]
Hi James,

After upgrading to the latest release I noticed that in the queue the name of the user who added the track is no longer displayed. The session id is displayed instead.

![screenshot_2017-02-19-09-19-28](https://cloud.githubusercontent.com/assets/1324598/23106476/6845127c-f6ee-11e6-9da2-d83a27a34d56.png)
![screenshot_2017-02-19-09-19-54](https://cloud.githubusercontent.com/assets/1324598/23106478/69d2286e-f6ee-11e6-88fa-ec253ff9f6e2.png)

Thanks,
Sebastian

**Comment by jaedb** [comment]
This is actually the username (`connection_id` is the guid in grey text)

 Try setting your username (_Settings_ > _Username_) and then adding tracks. Please note this will only apply to newly added tracks (not tracks added prior to updating your username).

**Comment by sgraca** [comment]
Thanks, that's clear now.
