### ISSUE TITLE
problem adding link/URI from SoundCloud music

### ISSUE THREAD

**Issue by lealoureiro** [jaedb/Iris#610]
Hello,

I'm trying to add a link/URI from a SoundCloud song nothing happens. 

Link:
`sc:https://soundcloud.com/sanderkleinenberg/sets/sander-kleinenberg-620292245`

The same works in **musicbox** Front end.

Iris Version that I'm using: 3.52.4

Thanks in advance.

**Comment by partofthething** [comment]
What browser are you using? In recent firefox they're blocking CORS more heavily, as shown in #609. Do you see anything in your browser's developer console?

**Comment by lealoureiro** [comment]
I'm using Brave (Chromium Based).

I can't see anything special developer console.

**Comment by jaedb** [comment]
@partofthething this is unrelated to #609. Rather it sounds similar to #594.
