### ISSUE TITLE
Snapcast: Add WebSocket streaming support

### ISSUE THREAD

**Issue by tgurr** [jaedb/Iris#611]
The latest Snapcast 0.21.0 introduced:

* Server: Support for WebSocket streaming clients

Which is also available via the Snapweb web client that is now also shipped with 0.21.0.

![Screenshot_20200917_224014](https://user-images.githubusercontent.com/414984/93525912-f90ab480-f936-11ea-8e21-2c583a283afd.png)

Note the `Play` button in the top right corner.

It would be great to have this feature available in Iris as well, so it can act as a snapcast client e.g. streaming from Mopidy via Snapcast without having to setup Icecast.

Contrary to the Snapweb web client it should probably remove itself as device when playback is stopped to not end up having multiple disconnected devices piling up over time when using Iris with multiple endpoints / different browsers / sessions.

![Screenshot_20200917_223948](https://user-images.githubusercontent.com/414984/93525896-f1e3a680-f936-11ea-9ace-cdb362d7ba4d.png)
![Screenshot_20200917_224059](https://user-images.githubusercontent.com/414984/93525901-f4de9700-f936-11ea-8e26-dc81701d6b22.png)

**Comment by jaedb** [comment]
This would be awesome, and something I would elect to support over Icecast (which is relatively buggy anyway). This would be a significant block of work; the browser would ultimately behave like a Snapclient.

**Comment by jaedb** [comment]
Released in 3.53
