### ISSUE TITLE
Snapcast: Discrepancy between muting in Iris vs. muting in Snapweb web client

### ISSUE THREAD

**Issue by tgurr** [jaedb/Iris#612]
**Describe the bug**
There seems to be a discrepancy between muting in Iris vs. muting in Snapweb web client

**To Reproduce**
Muting a Snapcast client in Iris
![Screenshot_20200917_224751](https://user-images.githubusercontent.com/414984/93526537-e17ffb80-f937-11ea-85d8-3ec051feb18f.png)
results in:
![Screenshot_20200917_224804](https://user-images.githubusercontent.com/414984/93526545-e3e25580-f937-11ea-8f8a-d2d9e6de41b7.png)

Muting a Snapcast client in Snapweb web client
![Screenshot_20200917_224909](https://user-images.githubusercontent.com/414984/93526666-0aa08c00-f938-11ea-8e98-b9a995fe906c.png)
results in:
![Screenshot_20200917_224859](https://user-images.githubusercontent.com/414984/93526655-08d6c880-f938-11ea-87e1-12067dc7d082.png)

**Expected behavior**
Having the same behaviour when muting no matter if using Iris or Snapcast client in Snapweb.

**Environment details:**
 - OS: Linux
 - Browser: Chromium
 - Iris version: 3.52.4

**Comment by rio-** [comment]
I posted a [related issue for snapweb](https://github.com/badaix/snapweb/issues/6).

**Comment by jaedb** [comment]
@tgurr can you confirm this occurs when using Snapdroid + Iris? If not, then the issue is likely to be related to [the issue](https://github.com/badaix/snapweb/issues/6) @rio- pointed out.
