### ISSUE TITLE
when using file browsing, media files are not seen if there is a folder

### ISSUE THREAD

**Issue by LiranSX** [jaedb/Iris#617]
i'm using Browse->Files ([File] is enabled) most of the time, and when you are entering a folder with songs you can see the song files, select and play all and it is fine, but if this folder contains a sub-folder , you cannot see the song files - only the folder/folders.

To reproduce:
click "Browse"->"Files" -> enter a folder which contains only music files -> all ok
click "Browse"->"Files" -> enter a folder which contains both music files and folder -> you can only see the folder.

this happens from any browser - firefox, internet explorer and phone browser. the issue is only happening with iris - when using an MPD client from my phone you can see all files and folders in such a folder which contains media files and sub folders.

**Comment by danielstaleiny** [comment]
Can confirm, I can see files only if there is no folder next to files.
