### ISSUE TITLE
Remember scroll position on navigate

### ISSUE THREAD

**Issue by tperich** [jaedb/Iris#618]
First of all, this is a really great project, and I love it.

**Is your feature request related to a problem? Please describe.**
It would be really nice if the app remembered scroll positions, especially when entering and then exiting playlists.

**Describe the solution you'd like**
We can implement this through DOM's scrollY and store it in state.

**Describe alternatives you've considered**
Maybe a hook?

**Additional context**
I'd be willing to write the code myself, just wanted to get other thoughts on implementing this.

**Comment by jaedb** [comment]
This - while not great with lazy-loading - already exists. Check out the restorer here: https://github.com/jaedb/Iris/blob/master/src/js/App.js#L189-L195.

I am currently overhauling the loading and remote fetching processes which will indirectly make it easier to restore scroll position on lazy-loaded lists/grids. Please note this _won't_ change navigating into a playlists, just using the browser's _Back_ and _Forwards_ navigation buttons.

Is this in line with what you're suggesting?

**Comment by atrizdawiz** [comment]
I would like this feature also. I'm attaching a gif of current behavior. The expected behavior is that going back centers on the album I just clicked on.
![please-remember](https://user-images.githubusercontent.com/42801244/99431890-b56b0180-290b-11eb-8656-6088fc1a13da.gif)

**Comment by jaedb** [comment]
Resolved in [3.57.0](https://github.com/jaedb/Iris/releases/tag/3.57.0)

**Comment by tperich** [comment]
@jaedb You are awesome!
