### ISSUE TITLE
Permissoin Denied /iris/mopidy_iris/system.sh

### ISSUE THREAD

**Issue by diabl0w** [jaedb/Iris#624]
**Describe the bug**
I am having some issue which I believe is caused by the fact that Iris isn't executing /iris/mopidy_iris/system.sh properly. I noticed this when trying to run a local scan from the webui, which would never complete. I then looked at the logs and saw:

> ERROR    2020-10-25 01:42:15,229 [6:Thread-14] mopidy_iris.system
  Password-less access to file:///iris/mopidy_iris/system.sh was refused. Check your /etc/sudoers file.

which makes sense that it is the issue, because I see that it contains the script that executes the proper local scan command based on whether it is a docker container or not

I can confirm that the file permissions are correct:
> -rwxrwxrwx 1 mopidy audio  1191 Jun 10 19:48 system.sh

/etc/sudoers contains:

> mopidy ALL=NOPASSWD: /iris/mopidy_iris/system.sh

and /IS_CONTAINER contains:

> 1

So every time my library changes I have to log in to the docker container and run the command manually, which is obviously not an acceptable workflow, but what I am doing for now

**Expected behavior**
system.sh executes properly

**Environment details:**
 - OS: Raspbian (docker)
 - Browser any
 - Iris version 3.49

**Comment by diabl0w** [comment]
I found the two issues, first there is no "sudo" installed in the docker image, so a sudoers file is pretty useless without that. Second, giving sudo permissions to run /iris/mopidy_iris/system.sh is pointless if the commands inside that file also use "sudo". The commands inside such as "sudo python" will still fail because the sudoers file is giving permission to run system.sh passwordlessly, it is not giving sudo permission to run python, etc. These must be defined individually. After addressing these problems, the issue is fixed. But obviously docker doesn't retain these changes after restart so we need a fix in the build.

**Comment by jaedb** [comment]
I feel like there is something else at play here. Are you running the supported [Iris Docker image](https://hub.docker.com/repository/docker/jaedb/iris)?

This Dockerfile should handle everything required to achieve the `system.sh` workarounds (except restarting; that isn't viable from within a Docker container).

You will also see that when running in Docker the [system.py](https://github.com/jaedb/Iris/blob/master/mopidy_iris/system.sh#L30-L31) scan doesn't use `sudo`:
```
if $IS_CONTAINER; then
	SCAN=$(mopidy --config /config/mopidy.conf local scan)
else
	SCAN=$(sudo mopidyctl local scan)
fi
```
