### ISSUE TITLE
Tunein "Now Playing" song info does not update

### ISSUE THREAD

**Issue by tekdru** [jaedb/Iris#627]
When I play a TuneIn station or add a station to the play queue, the station initially plays fine with the accurate song info.  I notice that after the actual audio changes to a new song, the song information that is displayed in "Now Playing" remains the same as what was originally playing at the time that the station was added to the "Now Playing" queue and never changes or updates to the current song info.

I see that the song info is updated properly if I switch to the Musicbox webclient but its not updated in the IRIS or Muse webclients

![Screen Shot 2020-10-29 at 1 59 41 PM](https://user-images.githubusercontent.com/7363668/97613634-4aef3180-19ef-11eb-925b-f85ae297910c.png)
![Screen Shot 2020-10-29 at 1 59 27 PM](https://user-images.githubusercontent.com/7363668/97613644-4fb3e580-19ef-11eb-86c3-9cb0efa860cd.png)
![Screen Shot 2020-10-29 at 2 00 02 PM](https://user-images.githubusercontent.com/7363668/97613651-52163f80-19ef-11eb-998e-099c202ea946.png)

**Comment by jaedb** [comment]
If any other mopidy frontend/client is not reflecting the update, I would suspect the issue lies with your server, rather than a specific frontend.

To ascertain this, please:
1. Enable _Settings > Debug > Test Mode_
2. Open your browser console
3. Replicate the issue (playing a Tunein track)
4. Copy and paste the console log into a codeblock on this issue.

**Comment by tekdru** [comment]
The Musicbox webclient does show the update correctly.

Theses are the screenshots of the Debug page

![Screen Shot 2020-11-03 at 8 39 01 PM](https://user-images.githubusercontent.com/7363668/98059511-5094af00-1e15-11eb-90ed-2c2494d64729.png)
![Screen Shot 2020-11-03 at 8 39 23 PM](https://user-images.githubusercontent.com/7363668/98059512-512d4580-1e15-11eb-9578-e75efd573ea9.png)
![Screen Shot 2020-11-03 at 8 39 38 PM](https://user-images.githubusercontent.com/7363668/98059513-512d4580-1e15-11eb-9620-5b85194f669e.png)

To clarify, where instructing me to copy the console log from the browser's console log?  

Let me know if this is what you are looking for:

`VM122 app.min.js:16 [react-ga] ReactGA.initialize must be called first or GoogleAnalytics should be loaded manually
s @ VM122 app.min.js:16
B @ VM122 app.min.js:16
H @ VM122 app.min.js:16
K @ VM122 app.min.js:16
$ @ VM122 app.min.js:16
o @ VM122 app.min.js:48
onClick @ VM122 app.min.js:1
c @ VM122 app.min.js:78
d @ VM122 app.min.js:78
(anonymous) @ VM122 app.min.js:78
b @ VM122 app.min.js:78
it @ VM122 app.min.js:78
ot @ VM122 app.min.js:78
ct @ VM122 app.min.js:78
dt @ VM122 app.min.js:78
L @ VM122 app.min.js:78
z @ VM122 app.min.js:78
$t @ VM122 app.min.js:78
Jt @ VM122 app.min.js:78
t.unstable_runWithPriority @ VM122 app.min.js:86
Yo @ VM122 app.min.js:78
I @ VM122 app.min.js:78
Qt @ VM122 app.min.js:78
Navigated to http://192.168.50.124:6680/iris/settings/debug
Navigated to http://192.168.50.124:6680/iris/settings/debug
VM150 app.min.js:16 [react-ga] ReactGA.initialize must be called first or GoogleAnalytics should be loaded manually
s @ VM150 app.min.js:16
B @ VM150 app.min.js:16
H @ VM150 app.min.js:16
K @ VM150 app.min.js:16
$ @ VM150 app.min.js:16
o @ VM150 app.min.js:48
onClick @ VM150 app.min.js:24
onClick @ VM150 app.min.js:1
c @ VM150 app.min.js:78
d @ VM150 app.min.js:78
(anonymous) @ VM150 app.min.js:78
b @ VM150 app.min.js:78
it @ VM150 app.min.js:78
ot @ VM150 app.min.js:78
ct @ VM150 app.min.js:78
dt @ VM150 app.min.js:78
L @ VM150 app.min.js:78
z @ VM150 app.min.js:78
$t @ VM150 app.min.js:78
Jt @ VM150 app.min.js:78
t.unstable_runWithPriority @ VM150 app.min.js:86
Yo @ VM150 app.min.js:78
I @ VM150 app.min.js:78
Qt @ VM150 app.min.js:78
Navigated to http://192.168.50.124:6680/iris/queue`

Thanks

.

**Comment by kingosticks** [comment]
Does Iris use the stream_title_changed event? https://docs.mopidy.com/en/latest/api/core/#mopidy.core.CoreListener.stream_title_changed

**Comment by jaedb** [comment]
@kingosticks no we use `trackPlaybackStarted` (see [mopidy/middleware.js](https://github.com/jaedb/Iris/blob/master/src/js/services/mopidy/middleware.js#L137-L148)) to listen to track changes. Is `streamTitleChanged` the better source of truth for this purpose? What is the difference between the two events?

**Comment by kingosticks** [comment]
Whenever Mopidy starts playing a new track it emits track_playback_started event. Tracks can emit new/more metadata as they are playing and normally we don't care. But we do expose when the 'title' *changes* because in the case of a streaming internet radio it happens all the time as the currently playing song within the stream changes and it's nice to reflect that in clients. We expose the updated title tag we get from the Track through our stream_title_changed event. You'll only get stream_title_changed events when the metadata (specifically the title) changes. So you would normally want to handle both events.

**Comment by jaedb** [comment]
@kingosticks what is a reliable way of manually triggering this `stream_title_changed` event?
