### ISSUE TITLE
country and locale settings not saved

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#63]
From time to time my browser cache gets somehow deleted and I lose authentication information for Spotify. I have to go to "Settings" and relogin. Whenever I do it, I have to enter my country and locale code again. This didn't happen in past. I am using 2.12.1 from PIP.

**Comment by jaedb** [comment]
Please provide more information about your environment. Had you restarted your Mopidy server? Upgraded Iris? What steps can I perform to replicate the issue? Can you replicate the issue?

Please read the [wiki](https://github.com/jaedb/Iris/wiki/Logging-an-issue) for guidelines on creating issues.

**Comment by vojtapolasek** [comment]
Hm, I think I solved this problem by setting locale and country in for Iris in Mopidy configuration.
