### ISSUE TITLE
3.53.1 missing from GitHub releases

### ISSUE THREAD

**Issue by tgurr** [jaedb/Iris#630]
**Describe the bug**
While 3.53.1 is available via PyPI, it's missing a release on GitHub.

**Comment by jaedb** [comment]
Please refrain from creating issues for this - it is not a bug!

I am aware the release is not yet tagged in this repository. It will come, please be patient.

**Comment by tgurr** [comment]
Apart from being a very happy user myself - really can't say it often enough - together with snapcast it's a wonderful solution, so thanks for all your work on it, I'm also packaging Iris for a distributionand it's really confusing if a new version is up only on PyPI but not yet tagged in VCS which raises the question if there are differences between the GitHub release and the one on PyPI, or how the release process is done. If you say it makes sense to rather rely on the PyPI tarball instead I'll look into switching our package source download to that instead of the GitHub release tarball.

**Comment by jaedb** [comment]
I'm really glad to hear you're getting some good value out of Iris. It can be quite hard to see how much people are using Iris and where it can be better. It is definitely a pet project, but there are a lot of my personal hours behind it.

I would recommend using PyPi as a source of truth for distribution versions. GitHub is source control but PyPi (and to some degree, Docker Hub) is the distribution channel. This would also alleviate your dependency on me manually tagging each version.

What project are you packaging Iris for distribution with?

**Comment by tgurr** [comment]
Litte background info on my usecase and why Iris makes me so happy: When renovating I put a speaker in the ceiling of our kitchen and our bathroom, wired them to the basement where they're each connected to a Raspberry with a HifiBerry unit. They just run the Snapclient and connect to a small NAS where Snapserver/Mopidy/Iris runs on. Additionally since the latest version of Snapcast where stream mixing is now possible I also use a loopback alsa device for OpenHAB which e.g. triggers the door bell running through the same setup. So even if/when listening to music with Iris now you don't miss the bell and you don't have to remember to switch back the snapcast streams afterwards anymore. So right now I'm really happy that things came together and work the way I initially had in my mind back then.

I'm packaging Iris for Exherbo Linux since I started using Iris:
https://git.exherbo.org/media.git/log/?qt=grep&q=mopidy-iris

And I switched back to PyPI with the bump to 3.53.1:
https://git.exherbo.org/media.git/commit/?id=583b92622ef6681f2886601b69311d9e6075e7c5

There are also a few other Distributions packaging Iris:
https://repology.org/project/mopidy-iris/versions
[![Packaging status](https://repology.org/badge/vertical-allrepos/mopidy-iris.svg)](https://repology.org/project/mopidy-iris/versions)

(They also seem to rely on the GitHub tarball as far as I can see.)
