### ISSUE TITLE
Play/add to queue all (Spotify) tracks

### ISSUE THREAD

**Issue by kazik56** [jaedb/Iris#634]
**Is your feature request related to a problem? Please describe.**
I always used the feature that went missing recently - play all. Whenever I opened "Tracks" tab, I could add all of them with just one click.

**Describe the solution you'd like**
Bring back the button for playing all (Spotify) songs.

**Describe alternatives you've considered**
I tried through "Browse" tab and navigated into Spotify. Whereas it provides "Play all" it does for only most recent (20) tracks. Also, clicking through so many folders just to play most recent 20 tracks feels a little pointless.

**Comment by jaedb** [comment]
This is semi-intentional (hah, yes it sounds like a cop-out). Now _Library > My Tracks_ includes Mopidy tracks, this for most users will be an enormous list of URIs. How did you handle this, before the recent change? Did you add every single track from your Spotify library?

**Comment by kazik56** [comment]
I use Iris mainly for it's Spotify integration. I used "Tracks" to play liked songs from the Spotify. 

I often played just a few of the most recent ones. However, sometimes I had a will to add all of them (I have almost 1200 liked tracks) just to have something playing in the background (usually with shuffling turned on to hear some "older" songs too). I cannot imagine adding all of them manually, one by one.

I can understand if this is semi-intentional - you're the mind behind all of it, so you probably had a reason to do so. Do you have any future plans with regards to this feature?
