### ISSUE TITLE
Queue history broken on v3.54.0 and v3.53.1

### ISSUE THREAD

**Issue by RoggerFabri** [jaedb/Iris#637]
**Describe the bug**
The queue history is not working any more after updating to 3.54.0. URL: **server**:**port**/iris/queue/history.

**To Reproduce**
1. Go to 'Now playing'
2. Click on 'History'
3. See error

```
app.min.js?v=1604908814:78 TypeError: Cannot read property 'map' of undefined
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at Function.mapToProps (app.min.js?v=1604908814:116)
    at r (app.min.js?v=1604908814:1)
    at Function.r.mapToProps (app.min.js?v=1604908814:1)
    at r (app.min.js?v=1604908814:1)
    at app.min.js?v=1604908814:1
ec @ app.min.js?v=1604908814:78
app.min.js?v=1604908814:78 Uncaught TypeError: Cannot read property 'map' of undefined
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at Function.mapToProps (app.min.js?v=1604908814:116)
    at r (app.min.js?v=1604908814:1)
    at Function.r.mapToProps (app.min.js?v=1604908814:1)
    at r (app.min.js?v=1604908814:1)
    at app.min.js?v=1604908814:1
```

**Expected behavior**
History list should show up.

**Environment details:**
 - OS: raspbian buster
 - Browser: chrome/firefox/edge
 - Iris version: 3.54.0

**Comment by jaedb** [comment]
Can you enable Test Mode (_Settings > Debug > Test Mode_) and then reproduce the error? Then paste the console log please.

**Comment by RoggerFabri** [comment]
`app.min.js?v=1604908814:78 TypeError: Cannot read property 'map' of undefined
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at Function.mapToProps (app.min.js?v=1604908814:116)
    at r (app.min.js?v=1604908814:1)
    at Function.r.mapToProps (app.min.js?v=1604908814:1)
    at r (app.min.js?v=1604908814:1)
    at app.min.js?v=1604908814:1
ec @ app.min.js?v=1604908814:78
app.min.js?v=1604908814:78 Uncaught TypeError: Cannot read property 'map' of undefined
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at app.min.js?v=1604908814:16
    at Function.mapToProps (app.min.js?v=1604908814:116)
    at r (app.min.js?v=1604908814:1)
    at Function.r.mapToProps (app.min.js?v=1604908814:1)
    at r (app.min.js?v=1604908814:1)
    at app.min.js?v=1604908814:1`

This is everything I get on the console log. The screen is completely black, I can't see anything else.

**Comment by RoggerFabri** [comment]
Worth to mention that I also tested on **v3.53.1** and the same happens.

**Comment by jaedb** [comment]
@RoggerFabri Hmm that doesn't look like the test mode output (it references `app.min.js`, test mode should be using `app.js`).

Can you try using a browser in incognito mode, or resetting cache (_Settings > Reset cache_)?

Also do you mean _3.54.1_?

**Comment by 01tot10** [comment]
I'm also affected by this bug, since a couple of version iterations! I updated just now to `3.54.1` and the problem to persists.
`http://SERVER:PORT/iris/queue/history` is showing nothing at the moment.

I'm not comfortable with the Iris debugging tools, but if you can provide me some instructions I'm happy to provide some logs.

I don't know if this is the log you are after, but after enabling Test mode in (Settings > Debug > Test Mode), the Firefox console shows the following error at the history page:

[console-export-2020-11-14_12-2-57.txt](https://github.com/jaedb/Iris/files/5540465/console-export-2020-11-14_12-2-57.txt)

**Comment by RoggerFabri** [comment]
@jaedb apologies, I forgot to enable Test Mode. I meant v.3.53.1, it was not a typo. I tested on the versions:

- v.3.53.1
- v.3.54.0
- v.3.54.1

All of them I have the same issue, tested on Incognito, other browsers and even other machine. Please see my log attached:

[192.168.0.100-1605382071836.log](https://github.com/jaedb/Iris/files/5541344/192.168.0.100-1605382071836.log)
