### ISSUE TITLE
Local Media Library not shown in GUI

### ISSUE THREAD

**Issue by diabl0w** [jaedb/Iris#646]
**Describe the bug**
After fixing the docker image via https://github.com/jaedb/Iris/pull/645, the local library is indeed properly updated (see log below), and /var/lib/mopidy/local/library.db is properly populated with music. **Howeve**r, this music is not shown in iris when browsing artists/albums/tracks. They are only visible via Browse -> Local Media

**To Reproduce**
1.  in mopidy.conf:
```
[local]
media_dir = /var/lib/mopidy/media
```
2. put your media in said directory (or bind mount the volume in docker)
3. run a local scan to add the media to the library
4. nothing seen in gui

**Expected behavior**
Tracks/albums/artists with artwork from local library should be visible.

**Console log**
```
  Finding files in file:///var/lib/mopidy/media ...
INFO     2020-11-14 05:42:02,649 [36:MainThread] mopidy_local.commands
  Found 10 files in file:///var/lib/mopidy/media
DEBUG    2020-11-14 05:42:02,650 [36:MainThread] mopidy_local.storage
  Using SQLite database schema v6
INFO     2020-11-14 05:42:02,651 [36:MainThread] mopidy_local.commands
  Checking 4 tracks from library
INFO     2020-11-14 05:42:02,654 [36:MainThread] mopidy_local.commands
  Removing 0 missing tracks
DEBUG    2020-11-14 05:42:02,654 [36:MainThread] mopidy_local.commands
  Skipped file:///var/lib/mopidy/media/config/mopidy.conf: File extension on excluded list
DEBUG    2020-11-14 05:42:02,654 [36:MainThread] mopidy_local.commands
  Skipped file:///var/lib/mopidy/media/Music/Brian%20Eno/banner.jpg: File extension on excluded list
DEBUG    2020-11-14 05:42:02,655 [36:MainThread] mopidy_local.commands
  Skipped file:///var/lib/mopidy/media/Music/Brian%20Eno/fanart.jpg: File extension on excluded list
DEBUG    2020-11-14 05:42:02,655 [36:MainThread] mopidy_local.commands
  Skipped file:///var/lib/mopidy/media/Music/Brian%20Eno/artist.nfo: File extension on excluded list
DEBUG    2020-11-14 05:42:02,655 [36:MainThread] mopidy_local.commands
  Skipped file:///var/lib/mopidy/media/Music/Brian%20Eno/logo.png: File extension on excluded list
DEBUG    2020-11-14 05:42:02,655 [36:MainThread] mopidy_local.commands
  Skipped file:///var/lib/mopidy/media/Music/Brian%20Eno/folder.jpg: File extension on excluded list
DEBUG    2020-11-14 05:42:02,655 [36:MainThread] mopidy_local.commands
  Included file:///var/lib/mopidy/media/Music/Brian%20Eno/Ambient%201-%20Music%20for%20Airports%20%281978%29/02%20-%202%2B1.flac: File extension not on excluded list
DEBUG    2020-11-14 05:42:02,655 [36:MainThread] mopidy_local.commands
  Included file:///var/lib/mopidy/media/Music/Brian%20Eno/Ambient%201-%20Music%20for%20Airports%20%281978%29/04%20-%202%2B2.flac: File extension not on excluded list
DEBUG    2020-11-14 05:42:02,656 [36:MainThread] mopidy_local.commands
  Included file:///var/lib/mopidy/media/Music/Brian%20Eno/Ambient%201-%20Music%20for%20Airports%20%281978%29/03%20-%201%2B2.flac: File extension not on excluded list
DEBUG    2020-11-14 05:42:02,656 [36:MainThread] mopidy_local.commands
  Included file:///var/lib/mopidy/media/Music/Brian%20Eno/Ambient%201-%20Music%20for%20Airports%20%281978%29/01%20-%201%2B1.flac: File extension not on excluded list
INFO     2020-11-14 05:42:02,656 [36:MainThread] mopidy_local.commands
  Found 0 tracks which need to be updated
INFO     2020-11-14 05:42:02,656 [36:MainThread] mopidy_local.commands
  Scanning...
INFO     2020-11-14 05:42:02,656 [36:MainThread] mopidy_local.commands
  Scanned 0 of 0 files in 0.000s.
INFO     2020-11-14 05:42:02,656 [36:MainThread] mopidy_local.commands
  Done scanning
INFO     2020-11-14 05:42:02,664 [36:MainThread] mopidy_local.storage
  Cleaning up image directory
INFO     2020-11-14 05:42:02,768 [6:Thread-11] mopidy_iris.system
  Completed in 1 seconds
```

**Environment details:**
 -  docker
 -  master

**Comment by jaedb** [comment]
Yes, you will need to hit the _Refresh_ button on the top right in order to re-sync the Iris index. 

Essentially Iris has an in-browser database to store data so it can perform well when running Mopidy on low powered devices or with huge libraries.

**Comment by diabl0w** [comment]
> Yes, you will need to hit the _Refresh_ button on the top right in order to re-sync the Iris index.
> 
> Essentially Iris has an in-browser database to store data so it can perform well when running Mopidy on low powered devices or with huge libraries.

whoops, I apologize for missing that. Can you also tell me what should be providing the artist/album art? Is that on the iris side or local extension side? I am not getting any art

**Comment by jaedb** [comment]
Yeah this is the next step to improve the massive overhaul to move to a browser-based database. To avoid hitting API rate limits by fetching all artwork on refresh, this is fetched after you click in to the artist or album itself (you can also right-click and select _Refresh_ on each item).

For Mopidy albums, artwork will show immediately provided you have it added to your local library.
