### ISSUE TITLE
[Wiki] Wrong compile commands

### ISSUE THREAD

**Issue by karrirasinmaki** [jaedb/Iris#647]
On Wiki page Advanced -> Development there are wrong deploy commands that no longer exist.
https://github.com/jaedb/Iris/wiki/Advanced#development

I believe new commands should be:
- ~``npm run dev``~ -> ``npm run build:dev`` (or ``npm run watch:dev``)
- ~``npm run prod``~ -> ``npm run build:prod`` (or ``npm run watch:prod``)

**Comment by jaedb** [comment]
Good spotting, fixed
