### ISSUE TITLE
"Reset Cache" and "Reset Storage" raises an error

### ISSUE THREAD

**Issue by LiranSX** [jaedb/Iris#649]
using version 3.54.1 on raspberry pi 3
going to "Settings" -> "Reset Cache" / "Reset Storage" raises the following error:
"Service Worker Not Supported"

**Comment by jaedb** [comment]
Please recreate this issue following the provided issue template.

**Comment by jaedb** [comment]
_Reset Cache_ resets the `fetch` cache used when using a service worker, so this isn't an error, it is a valid warning.

I haven't been able to replicate the _Reset Storage_ message though. This works completely separate to the service worker, so I can't see how this could cross over.
