### ISSUE TITLE
Can't play any tracks at all

### ISSUE THREAD

**Issue by el97** [jaedb/Iris#652]
**Describe the bug**
Hi! I recently upgraded my setup with a Raspberry Pi 4. After a clean install of the latest Pi OS I jumped on to install mopidy and Iris. Everything worked smoothly including installing needed backends such as mopidy-spotify. My problem starts when I want to play a track. There is no sound and I get errors that says "Mopidy: Request timed out" and in the load queue I get "mopidy_playback.getTimePosition". 
I'm not sure if I should submit a issue here or on the mopidy repo but I decided to try here first.

**To Reproduce**
1. Try to play a track in Iris with a Pi 4

**Expected behavior**
I expect that it should play a track but clearly it's not.

**Console log**
[mopidy.log](https://github.com/jaedb/Iris/files/5555050/mopidy.log)

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Environment details:**
 - OS: Win 10 (and latest version of Raspberry Pi OS)
 - Browser Firefox 82.0.3
 - Iris version 3.54.1

**Additional context**
[Add any other context about the problem]

**Comment by jaedb** [comment]
It sounds like a Mopidy issue, but I'll do my best to help. I have observed this error from time-to-time and it has typically been due to the backend not being authorized.

What track URI are you trying to play (right click on the track and _Copy URI_)? What do you see in your Mopidy log?

**Comment by el97** [comment]
The thing is that it happens to every track i try with. The hole service hangs and I can't see anything in the logs if I don't do this command `pkill -SIGUSR1 mopidy` that I found on the troubleshooting page from the mopidy [docs](https://docs.mopidy.com/en/latest/troubleshooting/#debugging-deadlocks).

**Comment by jaedb** [comment]
I really think you are best to post this on the [Mopidy Discourse forum](https://discourse.mopidy.com/) or the Mopidy repository.

**Comment by el97** [comment]
Will do!

**Comment by el97** [comment]
I finally managed to fix the issue after some help from someone at the mopidy github. I will post the solution if anyone else stumbles across this. On earlier versions of raspberry pis, the same sound card is used. On the 4th, there are two different ones. Therefore you have to write `output = alsasink device = hw: 0.0` to use HDMI as audio output. You can read more about it [here](https://discourse.mopidy.com/t/no-audio-from-mopidy-was-previously-working/4112).
