### ISSUE TITLE
Connect Icecast2 to Iris

### ISSUE THREAD

**Issue by dpradonline** [jaedb/Iris#654]
Icecast does not appear in Iris as service I am able to connect. 

I have been troubleshooting for the past two hours and read something about it not being compatible with python3.

Any ideas, or should Icecast be able to connect to Iris no problem? 

I believe my Icecast is working correctly. I can see "Mountpoint /mopidy" when viewing the statistics and am able to browse to local files able to stream them successfully in Iris. 

There is no button in Iris to connect to Icecast like there is for Spotify, Lastfm, Genius, and Snapcast.

**Comment by midasf** [comment]
I've never seen a button to connect, in the modipy.conf i've just set my output to icecast as following:
`output = lamemp3enc ! shout2send async=false mount=foo ip=192.168.2.8 port=8000 password=bar
`

**Comment by jaedb** [comment]
@dpradonline Unfortunately Icecast is no longer supported in the Iris project. The recommended streaming solution is [Snapcast](https://github.com/badaix/snapcast), which is supported in Iris to achieve browser-based audio streaming.

**Comment by kingosticks** [comment]
@jaedb it's probably worth removing the info about icecast integration from the readme.
