### ISSUE TITLE
info on snapcast support

### ISSUE THREAD

**Issue by gwm** [jaedb/Iris#656]
I have two instances of Mopidy running on a server both streaming to snapcast. I also have a DLNA renderer running on the same server and also streaming to snapcast. Therefore I have three snapcast streams that my various clients can connect to. All these streams are handled by a single snapserver instance.

I would like to make use of the snapcast support in Iris but perhaps I don't understand how it works. Whatever options I configure I cannot get iris to show anything other than "Disconnected". 

Should this work? What does the "streaming enabled" check box configure for? I am also assuming that the "port" should be the control port for snapserver.

Thanks for any enlightenment!

G

**Comment by jaedb** [comment]
I would recommend reading up on the Snapcast docs, as I definitely found it difficult to understand to start with.

Ultimately Snapcast _server_ manages the audio streams and broadcasts audio to Snapcast _clients_. Iris integrates with Snapcast in two ways:
- Controller
  - To manage Snapcast _clients_ and their volumes, names, etc
  - Add Snapcast _server_ details to _Iris > Settings > Snapcast > Host/Port_ and _enable_
- Streaming
  - Uses beta version of websocket audio streaming
  - Must have controller setup (as above)
  - _Enable streaming_ essentially makes Iris (running in your web browser) a Snapcast _client_

If you are unable to connect to the Snapcast _server_ from Iris then neither of the above will function. I would recommend double-checking your details and ensuring that your Snapcast _server_ is available to your browser.

**Comment by jaedb** [comment]
I'll close this issue now. For further questions, please refer to the [Mopidy Discourse channel](https://discourse.mopidy.com/search?q=iris).
