### ISSUE TITLE
Media buttons

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#658]
**Is your feature request related to a problem? Please describe.**
Manipulating Iris play state from anywhere in my OS. 

**Describe the solution you'd like**
Iris to listen to media keys (like headphone volume / skip controls) and act accordingly. Use the Media Session API, with examples here: https://googlechrome.github.io/samples/media-session/video.html

**Comment by jaedb** [comment]
Released for Chrome on Windows. Doesn't work on Chrome for Android though.

The [demo](https://googlechrome.github.io/samples/media-session/audio.html) works on mobile, so it's not a compatibility issue, just an implementation issue.

**Comment by jaedb** [comment]
Works on Chrome + Android now, needed longer silence clip. Still to do is setting duration/progress for controls.

Displaying on Garmin watch music widget but interactions are ignored.

**Comment by kingosticks** [comment]
> Displaying on Garmin watch music widget but interactions are ignored.

How does that work? With one of the 3rd party apps?

**Comment by jaedb** [comment]
@kingosticks This is the beautiful part; it doesn't require any additional software.

Because Android sees the MediaSession and provides media controls as part of it's notification bar (just like Spotify), Garmin is able to access this and relay that metadata/controls onto it's built-in widget.

**Comment by kingosticks** [comment]
This is very cool. So checking that I understand correctly. With the Iris page running (not even in focus?) on my Android phone, my Garmin watch will see that via it's Bluetooth connection to my phone, and allow me to control music on my Mopidy server running elsewhere?

**Comment by kingosticks** [comment]
Next question: can we make this more general for all web clients to use or is it a bunch of work to integrate?

I think I actually looked at this really recently (with no idea that it would allow for control from a watch!) but something make me think it wouldn't work for Mopidy webclients. Perhaps I wrongly assumed it only work alongside the Web Audio APIs?

**Comment by jaedb** [comment]
It is a pretty exciting tech opportunity. And yep, you bet:

On desktop:
<img width="458" alt="Screen Shot 2020-12-11 at 10 52 27 AM" src="https://user-images.githubusercontent.com/1711444/101834301-0edaef00-3b9f-11eb-947d-2ea37282014f.png">

On mobile:
<img width="300" src="https://user-images.githubusercontent.com/1711444/101834648-801aa200-3b9f-11eb-8b33-0dc748dc240d.jpg" />

On watch:
<img width="400" src="https://user-images.githubusercontent.com/1711444/101835068-1d75d600-3ba0-11eb-8cc9-7b7df53bc7f4.jpg" />

Because each web client will use a different tech stack (Iris uses React) I don't think there would be a one-size-fits-all option. But it is achievable using vanilla javascript, so it wouldn't be too difficult to have a tutorial for webclient developers to achieve it on a per-webclient basis.

95% of the logic required to achieve this for Iris is in [`MediaSession.js`](https://github.com/jaedb/Iris/blob/master/src/js/components/MediaSession.js).

The watch application of this does require an active connection between watch and phone (just like much like most of the watch functionality). And I've only experimented with Garmin Vivoactive. And it only works with Chrome. So definitely an experimental-level tech.

**Comment by kingosticks** [comment]
I just tried it with Mopidy Mobile on Android which has a similar hook into Android's media system. Sadly it was a mixed bag on my Garmin Fenix 5+. I could see the track details and the pause/play status but I couldn't actually control it from the watch. I appreciate this isn't quite the same as the browser's MediaSession API so I'll give that a try next. I've had various problems with my watch so it could well be an issue specific to the Fenix software. Great job on integrating this.

**Comment by jaedb** [comment]
That's right - it isn't _quite_ working on the Garmin device for me either, but the fact that it's displaying the now playing information gives me hope that it is achievable. I only recently got a Garmin watch which is what fuelled this project for me 😄

**Comment by jaedb** [comment]
Unfortunately it seems that Garmin + Chrome music controls are [broken at the moment](https://forums.garmin.com/apps-software/mobile-apps-web/f/garmin-connect-mobile-andriod/236850/music-control-is-not-working-on-latest-chrome-85).

I'll close this issue as the feature is now implemented, at least for browsers and devices that support it. Hopefully it can be expanded when support is wider.

**Comment by jaedb** [comment]
@kingosticks I received an update to my Vivoactive 3, now on 7.70 that has now made full music controls functional 🎉

**Comment by OzymandiasTheGreat** [comment]
Hello, could you reopen this issue and make a few tweaks to make the notification compatible with Firefox (linux/android, not sure about other systems)?

What you'd need to do is replace the silence.mp3 with very quiet white noise or a simple ding.
Firefox currently ignores audio files with only silence. I have tested and verified that using a short clip of white noise makes the notification compatible with Firefox on the aforementioned platforms.

**Comment by jaedb** [comment]
@OzymandiasTheGreat have you checked to see the impact of this on other browsers and devices? In principle it should have no issue, but browsers like to do things differently, sometimes just for the sake of being different...

**Comment by OzymandiasTheGreat** [comment]
Honestly, I haven't. But loading white noise on chrome seems overkill anyway, you could do a quick user agent check and load white noise on firefox and silence otherwise.
I mean white noise out of nowhere is a bit annoying, but it's the only way to make it work on firefox due to its stricter checks.
