### ISSUE TITLE
Release radar playlist

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#66]
would it be possible to access the Release radar playlist creatd automatically by Spotify?
thanks.

**Comment by jaedb** [comment]
The Spotify HTTP API does not currently provide the ability to request this. There may be a way to work around, but not that I'm currently aware of.

Have a look at what _is_ possible on the [Spotify HTTP API docs](https://developer.spotify.com/web-api/endpoint-reference/)

**Comment by jaedb** [comment]
This also applies to #64

**Comment by jaedb** [comment]
The only way to show this playlist is for you to _Add to library_. This means you'll then be able to see these custom playlists appear in _My Music_ > _Playlists_. The trick will be finding the playlist in the first place, which you may need to do from https://open.spotify.com/browse/discover
