### ISSUE TITLE
mopidy-dleyna: no track lengths in search results

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#660]
Iris is not displaying track lengths for search results of the mopidy-dleyna backend (same issue is with mopidy-youtube but I did not checked if this is not mopidy-youtube side issue).

I added debug log at the end of the search method of the mopidy-dleyna LibraryProvider which prints out mopidy.SearchResult and this is what it logged:
`SearchResult(tracks=[Track(album=Album(name=dbus.String('WWW.EMKASTUDIO.EU', variant_level=1)), artists=[Artist(name=dbus.String('Chantal Prym'))], bitrate=dbus.Int32(320, variant_level=1), date=dbus.String('2013-01-01', variant_level=1), genre=dbus.String('Rock', variant_level=1), length=367000, name=dbus.String('Chantal', variant_level=1), track_no=dbus.Int32(5, variant_level=1), uri='dleyna://uuid%3a55076f6e-6b79-4d65-6459-6038e0060e53/3024312438493530363939'), Track(album=Album(name=dbus.String('Polish Independent Music Compilation Vo.1', variant_level=1)), artists=[Artist(name=dbus.String('13. Chantal Prym'))], bitrate=dbus.Int32(128, variant_level=1), genre=dbus.String('Unknown', variant_level=1), length=221000, name=dbus.String('Chantal', variant_level=1), track_no=dbus.Int32(13, variant_level=1), uri='dleyna://uuid%3a55076f6e-6b79-4d65-6459-6038e0060e53/302431243849323539303833'), Track(album=Album(name=dbus.String('WWW.EMKASTUDIO.EU', variant_level=1)), artists=[Artist(name=dbus.String('Chantal Prym'))], bitrate=dbus.Int32(192, variant_level=1), date=dbus.String('2013-01-01', variant_level=1), genre=dbus.String('Rock', variant_level=1), length=342000, name=dbus.String('Co znajde tam', variant_level=1), track_no=dbus.Int32(6, variant_level=1), uri='dleyna://uuid%3a55076f6e-6b79-4d65-6459-6038e0060e53/3024312438493530393535'), Track(album=Album(name=dbus.String('WWW.EMKASTUDIO.EU', variant_level=1)), artists=[Artist(name=dbus.String('Chantal Prym'))], bitrate=dbus.Int32(192, variant_level=1), date=dbus.String('2013-01-01', variant_level=1), genre=dbus.String('Rock', variant_level=1), length=81000, name=dbus.String('Intro', variant_level=1), track_no=dbus.Int32(1, variant_level=1), uri='dleyna://uuid%3a55076f6e-6b79-4d65-6459-6038e0060e53/3024312438493531323131'), Track(album=Album(name=dbus.String('WWW.EMKASTUDIO.EU', variant_level=1)), artists=[Artist(name=dbus.String('Chantal Prym'))], bitrate=dbus.Int32(320, variant_level=1), date=dbus.String('2013-01-01', variant_level=1), genre=dbus.String('Classic Rock', variant_level=1), length=251000, name=dbus.String('Rockendroll', variant_level=1), track_no=dbus.Int32(3, variant_level=1), uri='dleyna://uuid%3a55076f6e-6b79-4d65-6459-6038e0060e53/3024312438493531343637'), Track(album=Album(name=dbus.String('WWW.EMKASTUDIO.EU', variant_level=1)), artists=[Artist(name=dbus.String('Chantal Prym'))], bitrate=dbus.Int32(256, variant_level=1), date=dbus.String('2013-01-01', variant_level=1), genre=dbus.String('Rock', variant_level=1), length=217000, name=dbus.String('Szept', variant_level=1), track_no=dbus.Int32(4, variant_level=1), uri='dleyna://uuid%3a55076f6e-6b79-4d65-6459-6038e0060e53/3024312438493531373233'), Track(album=Album(name=dbus.String('WWW.EMKASTUDIO.EU', variant_level=1)), artists=[Artist(name=dbus.String('Chantal Prym'))], bitrate=dbus.Int32(192, variant_level=1), date=dbus.String('2013-01-01', variant_level=1), genre=dbus.String('Rock', variant_level=1), length=235000, name=dbus.String('Wojna', variant_level=1), track_no=dbus.Int32(2, variant_level=1), uri='dleyna://uuid%3a55076f6e-6b79-4d65-6459-6038e0060e53/3024312438493531393739')]`
All tracks have length attribute defined properly as milliseconds, but in iris frontend there is no track lengths displayed.

**To Reproduce**
1. install mopidy-dleyna backend
2.setup some dlna server with audio tracks
3. search for something

**Expected behavior**
Iris should display track lengths in the search results

**Screenshots**
![iris_dleyna_length](https://user-images.githubusercontent.com/2772080/100394334-15188980-303d-11eb-80e3-6e1570c540dd.png)

**Environment details:**
 - OS: client: linux mint 20.0, server: armbian buster
 - Browser firefox
 - Iris version 3.54.2

**Comment by tha23rd** [comment]
I'd like to add that this is happening for a custom extension I have created as well. Tracks are being listed but their duration is not.

Another thing I noticed (and perhaps this warrants a new issue) is that images are not being shown for albums/artists that appear as search results. I do see in the logs that images are being retrieved for albums, but they are not being displayed on the UI.
