### ISSUE TITLE
Selecting 'Playlists' from the left navigation menu brings up an empty black page

### ISSUE THREAD

**Issue by robcee** [jaedb/Iris#662]
**Describe the bug**
Clicking on the Playlists list in the left-hand navigation area produces a blank screen.

**To Reproduce**
1. Enable Test Mode (_Settings > Debug > Test Mode_). This provides more verbose error logs.
2. Click Playlists in left-hand navigation mode.

**Expected behavior**
A list of playlists should appear and options around creating and editing them.

**Console log**
```
Uncaught TypeError: _state$spotify$me is null
    mapStateToProps LibraryPlaylists.js:355
    Redux 6
    React 3
    ConnectFunction Redux
    React 6
    sentryWrapped helpers.js:71
    React 7
    unstable_runWithPriority scheduler.development.js:653
    React 6
    sentryWrapped helpers.js:71
    node_modules app.js:2379
    instrumentDOM instrument.js:338
    React 15
    unstable_runWithPriority scheduler.development.js:653
    React 7
    Redux 9
    SnapcastMiddleware middleware.js:643
    GoogleMiddleware middleware.js:162
    GeniusMiddleware middleware.js:53
    LastfmMiddleware middleware.js:55
    SpotifyMiddleware middleware.js:203
    PusherMiddleware middleware.js:886
    MopidyMiddleware middleware.js:1948
    UIMiddleware middleware.js:238
    CoreMiddleware middleware.js:765
    Redux 3
    js index.js:266
    Webpack 7
LibraryPlaylists.js:355:35
The above error occurred in the <ConnectFunction> component:
    in ConnectFunction (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in main (created by App)
    in div (created by App)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
    in PersistGate
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. instrument.js:110
Uncaught TypeError: _state$spotify$me is null
    mapStateToProps LibraryPlaylists.js:355
    Redux 6
    React 3
    ConnectFunction Redux
    React 6
    sentryWrapped helpers.js:71
    React 7
    unstable_runWithPriority scheduler.development.js:653
    React 6
    sentryWrapped helpers.js:71
    node_modules app.js:2379
    instrumentDOM instrument.js:338
    React 15
    unstable_runWithPriority scheduler.development.js:653
    React 7
    Redux 9
    SnapcastMiddleware middleware.js:643
    GoogleMiddleware middleware.js:162
    GeniusMiddleware middleware.js:53
    LastfmMiddleware middleware.js:55
    SpotifyMiddleware middleware.js:203
    PusherMiddleware middleware.js:886
    MopidyMiddleware middleware.js:1948
    UIMiddleware middleware.js:238
    CoreMiddleware middleware.js:765
    Redux 3
    js index.js:266
    Webpack 7
LibraryPlaylists.js:355:35
```

**Screenshots**
A blank screen. An app div with no contents. Here's a picture of the HTML Inspector.

![Screenshot 2020-11-29 095347](https://user-images.githubusercontent.com/27976/100543871-e7903380-3228-11eb-89bc-bb0ad98ff11f.png)

**Environment details:**
 - OS: Windows 10 Professional 64 bit 20H2
 - Firefox latest release version (83.0)
 - Iris version 3.54.2

**Additional context**
This has been happening for awhile. I had two created playlists but they never seemed to work properly. Investigating the /var/lib/mopidy/m3u directory, I found both of the playlists and deleted them to try to fix the issue with no luck. Not sure if I should add something back in there to help.

Also, the removed playlists still show up in the list at left, but aren't clickable / they navigate to the same black screen as the top level playlist button.

![Screenshot 2020-11-29 095855](https://user-images.githubusercontent.com/27976/100544035-861c9480-3229-11eb-9f64-449463652544.png)

**Comment by robcee** [comment]
Another point, I only have File, Local, Podcasts and TuneIn enabled as plugins in my mopidy configuration.

the error suggests a missing null check around the Spotify module.

`Uncaught TypeError: _state$spotify$me is null`

**Comment by jaedb** [comment]
@robcee can you please try using your browser's Incognito Mode? This should work, indicating that the issue is with the data stored in your browser. You will need to clear _all_ Iris-related data to reset `state.spotify.me` to `undefined`, fixing this issue.

Please confirm whether this has solved the issue for you.

**Comment by robcee** [comment]
> Please confirm whether this has solved the issue for you.

yes, fixed! I still have two persistent pinned playlists that don't exist, but I am able to navigate to Playlists and create new ones. Thank you!

Do we have a button in Settings somewhere that can wipe all localstorage/indexeddb? Closing this to get it off your plate.
