### ISSUE TITLE
snapcast control not working

### ISSUE THREAD

**Issue by gwm** [jaedb/Iris#666]
**Describe the bug**
Unable to get Iris to connect to the control port of my snapcast server instance

**To Reproduce**
In settings I configure the snapcast service with the IP address of the server (both actual NIC interface OR 127.0.0.1), put the default control port of 1705 and click the Enable checkbox.

snapcast shows as "Disconnected" and I've not managed to persuade it to ever connect. 

I should point out that Mopidy, Iris and snapcast are all working perfectly otherwise and are all running on the same server.

**Expected behavior**
I would expect Iris to connect to my snapcast server instance running on the same host as Mopidy/Iris and provide a view of the clients and streams, similar to the Android snapcast app.

**Console log**

Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
g_CS[e] is null background.js:1
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_toggleReaderMode” browser.xhtml
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xhtml
debuggee 'resource://devtools/shared/base-loader.js:289' would run builtin-modules.js:196:11
Exception { name: "NS_ERROR_NOT_AVAILABLE", message: "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannelInternal.remoteAddress]", result: 2147746065, filename: "resource://devtools/server/actors/network-monitor/network-observer.js", lineNumber: 1162, columnNumber: 0, data: null, stack: "_onResponseHeader@resource://devtools/server/actors/network-monitor/network-observer.js:1162:5\n_dispatchActivity@resource://devtools/server/actors/network-monitor/network-observer.js:629:14\nNetworkObserver.prototype.observeActivity<@resource://devtools/server/actors/network-monitor/network-observer.js:738:12\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:103:22\n", location: XPCWrappedNative_NoHelper }
ThreadSafeDevToolsUtils.js:82:13
TypeError: undefined has no properties
    _getWaitTiming resource://devtools/server/actors/network-monitor/network-observer.js:1261
    _setupHarTimings resource://devtools/server/actors/network-monitor/network-observer.js:1486
    _onTransactionClose resource://devtools/server/actors/network-monitor/network-observer.js:1209
    _dispatchActivity resource://devtools/server/actors/network-monitor/network-observer.js:632
    observeActivity resource://devtools/server/actors/network-monitor/network-observer.js:738
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
ThreadSafeDevToolsUtils.js:82:13
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Exception { name: "NS_ERROR_FAILURE", message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITraceableChannel.setNewListener]", result: 2147500037, filename: "resource://devtools/server/actors/network-monitor/network-observer.js", lineNumber: 1085, columnNumber: 0, data: null, stack: "_setupResponseListener@resource://devtools/server/actors/network-monitor/network-observer.js:1085:38\n_createNetworkEvent@resource://devtools/server/actors/network-monitor/network-observer.js:911:12\n_httpStopRequest@resource://devtools/server/actors/network-monitor/network-observer.js:409:14\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:103:22\n", location: XPCWrappedNative_NoHelper }
ThreadSafeDevToolsUtils.js:82:13
    reportException resource://devtools/shared/ThreadSafeDevToolsUtils.js:82
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:109
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified

**Screenshots**
I don't think its necessary to include a screenshot - snapcast is disconnected

**Environment details:**
 - OS: server: debian buster, client: ubuntu 20.04
 - Browser firefox
 - Iris version 3.55.1

**Additional context**
I believe I understand how this _should_ work based on the reply to #656

**Comment by jaedb** [comment]
What is the LAN IP address of your server? Is the browser you're using on this server itself? Bearing in mind that `127.0.0.1` is a local loopback address, essentially equivalent to `localhost`.

**Comment by gwm** [comment]
the IP address is 192.168.1.81. I've tried both this and 127.0.0.1 

The browser is _not_ on the server, I'm browsing from my laptop on the same subnet.

Snapcast is running on the same server as mopidy. It is using the default ports (1704 and 1705). These settings work fine on the android snapcast client app on my phone but I'd really like to be able to control snapcast from the same fantastic web interface that Iris provides.

let me know if I can help with any further info.

G

**Comment by jaedb** [comment]
I'm at a loss as to why this isn't working for you. You should definitely be using `192.168.1.81` rather than `127.0.0.1`.

Are you able to try from a different device or browser? The fact that the Snapdroid app works suggests to me that the issue lies with the browser or device. Do you have any other network elements that control or manipulate TCP traffic (firewalls, proxies, etc)?

**Comment by gwm** [comment]
the socket seems open. I can connect to it every which way using telnet, e.g.

telnet 192.168.1.81 1705
telnet 127.0.0.1 1705
telnet localhost 1705

these all work connect as expected.

Could it be because I am using the version of snapserver that comes in the debian repo rather than the most recent?

g@borg:~$ dpkg -l snapserver
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  snapserver     0.15.0-1     amd64        Snapcast server

**Comment by jaedb** [comment]
Yep that would do it. You need to be running at least 0.21.0 (see [release notes](https://github.com/badaix/snapcast/releases/tag/v0.21.0)) for streaming over websockets.

Upgrade to the latest and you should be up and running.
