### ISSUE TITLE
Wrong label for listeners count in album view

### ISSUE THREAD

**Issue by orontee** [jaedb/Iris#667]
**Describe the bug**
When I am visiting a album view, I see two numbers with same label "plays".

**To Reproduce**
1. Visit an album view

**Expected behavior**
I expect to read the number of "plays" then the number of "listeners".

**Screenshots**
![image](https://user-images.githubusercontent.com/2065954/101277839-8b448b00-37b7-11eb-8a83-bf9068e7615e.png)

**Environment details:**
 - OS: any
 - Browser: any
 - Iris version 3.55.1

**Comment by orontee** [comment]
Thanks!

**Comment by jaedb** [comment]
Closing, will be released in next version.
