### ISSUE TITLE
Spotify authorized and connected - but on playback : "Mopidy failed to add some tracks"

### ISSUE THREAD

**Issue by 0x0lli** [jaedb/Iris#671]
**Describe the bug**

Am using the phoniebox-script that installs Iris along.
Iris is fully connected to my spotify account, authorized and appears to work - but doesnt let me play back files.
They are looped 
I can search through my spotify account and it is integrated perfectly but on hitting play it shows me:
"Mopidy: failed to add some tracks"

**To Reproduce**
installed RpiOS 20201202, installed "phoniebox script with spotify intergration" (that installs Iris)

updated via:
"sudo python3 -m pip install --upgrade Mopidy-Iris"
(because update button in iris-setting resulted in loop)

next installation I used RpiOS 20200820, updated Iris from version 3.43 (?) via:
"sudo pip3 install --upgrade --force-reinstall Mopidy-Iris"

still: no reaction to "local scan" (looping endlessly)

**Expected behavior**
playback any file, either local or streamed from spotify,
output response for malfunctioning buttons (update/run local scan)

**Console log**
"systemctl status mpd.socket":
-- The job identifier is 460.
Dec 19 16:34:18 pi3A-phoniebox mpd[21621]: exception: bind to '127.0.0.1:6600' failed (continuing anyway, because binding to '[::1]:6600' succeeded): Failed to bind socket: Address already in use
Dec 19 16:34:18 pi3A-phoniebox mpd[21621]: exception: Failed to set group 0: Operation not permitted
Dec 19 16:34:18 pi3A-phoniebox systemd[21610]: mpd.service: Main process exited, code=exited, status=1/FAILURE

**Screenshots**
https://i.imgur.com/hGz65iK.png

**Environment details:**
OS: Raspberry Pi OS 20201202-full]
Chrome: Browser on AMD CPU 
 - Iris version [e.g. 3.54.0]

**Additional context**
I thought about the pulseaudio driver within the latest raspian rls would interfere with the scripts based on "older" alsa mixer but using the old image without update-/-grading didnt change a thing

What info can I provide to bugfix rthis ?

**Comment by jaedb** [comment]
I think the biggest issue is highlighted in your logs:
```
Failed to bind socket: Address already in use
```
Clearly something is consuming that port. Perhaps you're running MPD on the port that Mopidy is trying to use? You will need Mopidy-Spotify to add Spotify tracks to Mopidy. I suggest reading up on the documentation for [Mopidy](https://docs.mopidy.com/en/latest/).

I am also not familiar with the _phoniebox-script_ inner workings, so I would suggest your first port of call is the author of phoniebox. 

I imagine it feels like I'm fobbing you off to other people to answer your questions. Iris is just the frontend for Mopidy, so issues with the server side is not something that I'm well placed to help with.
