### ISSUE TITLE
snapcast not up to date, control works but playback doesnt work for the machine in use

### ISSUE THREAD

**Issue by 0x0lli** [jaedb/Iris#672]
My client show me the used version is snapcast v0.10.
I can see the full information and change some settings but the playback doesnt work on the machine used,
although I clearly use the options for iris, it sets colume for another speraker in the network.
rather strange

I would love to update snapcast to v0.22 in order to check whether it works.
I cannot seem to find the folder in which it is installed as configuration is not where it is found when installing snapscast-client/server with regular raspian

any help ?

**Comment by jaedb** [comment]
That is something you need to look at the [Snapcast docs](https://github.com/badaix/snapcast/blob/master/doc/install.md) for. 

This repository is for **issues**, not questions. As you will have noticed when creating this issue, if you have a question you need to consult the Mopidy Discourse forum:

> STOP! QUESTIONS DON'T BELONG IN THE REPOSITORY ISSUE TRACKER.
> Please instead use the [Mopidy Discourse](https://discourse.mopidy.com/) forum.
