### ISSUE TITLE
Wrong track order in album view when sorted by track number and album has multiple discs

### ISSUE THREAD

**Issue by orontee** [jaedb/Iris#673]
**Describe the bug**
Tracks aren't sorted as expected in album view when the album has multiple discs and sorting by track number is selected.

**To Reproduce**
1. Visit the album view for an album with multiple discs: For example, disc 1 has 17 tracks, disc 2 has 18 tracks
2. Observe the track ordering 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 12, 2, 13, 3, 14, 5, etc.

**Expected behavior**
For the same example, I am expecting 1, 2, 3, ..., 17, 1, 2, 3, ...

**Screenshots**
![image](https://user-images.githubusercontent.com/2065954/102694308-6c66df80-4220-11eb-9742-740b30eb665b.png)

**Environment details:**
 - OS: Debian
 - Browser: Firefox
 - Iris version: 3.55.4

**Comment by TrollDecker** [comment]
Heyo, Also experiencing the same problem on Firefox for Android (85.1.1) and Chromium (86.0.4240.197) on Raspberry Pi OS:

![Screenshot_20210207_222822_org mozilla firefox](https://user-images.githubusercontent.com/4513715/107161364-2e6e7800-6994-11eb-993a-f16b139873ff.jpg)

Oddly if you add the album to the Playlist with the Play button, they are sent to the playlist in the correct order. 

Server is a Pi Zero W running
* Raspberry Pi OS
* Python 3.7.3
* Mopidy 3.1.1
* Iris 3.55.4
