### ISSUE TITLE
After setup proxy can't connect to mpd

### ISSUE THREAD

**Issue by Morta1985** [jaedb/Iris#679]
The mpd work with a local gui but not with iris. When i hit https://www.mopidy.listen then the UI from Iris comes but unable to connect to the mpd. Here my config:

`<VirtualHost *:80>
        # Leave empty (or "*") to listen to all domains
        ServerName www.mopidy.listen

        # Redirect non-https requests to https
        RewriteRule ^(.*)$ http://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
        # Leave empty (or "*") to listen to all domains
        ServerName www.mopidy.listen

        # Optional: set this to wherever Iris is installed (depends on your setup)
        DocumentRoot /usr/lib/python3.9/site-packages/mopidy_iris/static/
        <Directory /usr/lib/python3.9/site-packages/mopidy_iris/static>
                RewriteEngine on

                # rewite all requests at /iris/ (but NOT ./ws) to accommodate the
                # ./mopidy/{extension} URL format
                RewriteCond %{REQUEST_URI} !^/ws/
                RewriteRule ^iris/(.*)$ /$1 [L]
        </Directory>

        RewriteEngine on
        ProxyRequests off
        ProxyPreserveHost on

        # Mopidy websocket
        ProxyPass /mopidy/ws/ ws://127.0.0.1:6680/mopidy/ws/
        ProxyPassReverse /mopidy/ws/ ws://127.0.0.1:6680/mopidy/ws/

        # Local-Images
        ProxyPass /images/ ws://127.0.0.1:6680/images/
        ProxyPassReverse /images/ ws://127.0.0.1:6680/images/

        # Iris websocket (Pusher)
        ProxyPass /iris/ws/ ws://127.0.0.1:6680/iris/ws/
        ProxyPassReverse /iris/ws/ ws://127.0.0.1:6680/iris/ws/

        # Iris HTTP endpoint
        ProxyPass /iris/http/ http://127.0.0.1:6680/iris/http/
        ProxyPassReverse /iris/http/ http://127.0.0.1:6680/iris/http/
</VirtualHost >

`
Why isn't working?

**Comment by JialuZhang** [comment]
@Morta1985 

I suggest you add "RewriteEngine on" in `<VirtualHost :80>. Otherwise, the setting "RewriteRule ^(.*)$ http://%{HTTP_HOST}$1 [R=301,L]" will be a silent misconfiguration, and adding it to your system will not change any system behavior.

Here is the related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```

Hope it helps!

**Comment by jaedb** [comment]
@Morta1985 I trust that @JialuZhang's fix worked for you. I shall close this issue now, but please re-open if the issue persists.
