### ISSUE TITLE
Search by URI goes directly to asset

### ISSUE THREAD

**Issue by k0nG** [jaedb/Iris#68]
Hi,

Great work on Iris, its great. We're using it in our studio.

Are you currently able to paste a spotify playlist/album/track URI into the interface to display it so it can be played or added to playlists.  Much like you can in the spotify app when you paste a URI into the search field.

I can't see anywhere on the spotify API that you can just send an URI and get back the info. It looks like you might need to parse the URI and extract the ids you need. For instance with this URI `spotify:user:bbc_playlister:playlist:6ToRtiBeKUf0py8gZO6gQj`. We can detect `playlist` and `user` and extract their values and request from API with this endpoint: `https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}` ?

Does that seem like a viable method?

Thanks

**Comment by jaedb** [comment]
We actually already have the URL for the playlist, so shouldn't need to reconstruct it. See [HTTP API /playlist endpoint](https://developer.spotify.com/web-api/get-playlist/).

The difference is how we would present this in the UI, which is where the effort is. I shouldn't be tricky, but I'm considering introducing a context menu (much like the Spotify native application).

In the meantime you can right-click on playlist/artist/album items (eg grid view) to expose a context menu and copy URIs in that manner.

**Comment by k0nG** [comment]
Hey @jaedb that sounds great.

I think you may have misunderstood my original request, maybe I didn't make sense. The use case i'm looking to solve is:
- User is sent spotify URI by friend
- User copies spotify URI to clipboard
- User can paste URI into Iris to view the playlist/track/artist 
- User can play playlist/track/artist

Your context menu idea makes sense to allow users to get the URI and share with another user. But it would be great if someone receiving the URI could then play it via Iris.

**Comment by jaedb** [comment]
Ah, I see. I have updated the title to reflect this.

**Comment by jaedb** [comment]
Resolved in 2.13.1

**Comment by k0nG** [comment]
@jaedb Just updated our Iris. All working great. Thanks for getting this in so quickly.
