### ISSUE TITLE
mopidy-dleyna and album search result

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#681]
When I get albums in search results for mopidy dleyna backend the album is desribed only by the artist name (I suppose) and I cannot display album content by clicking on it.

1. install mopidy-dleyna baclend
2. setup dlna server accessible by mopidy
3. search for artist from mopidy-dleyna backend that should have some albums on your dlna server
4. see that in search result the album is described by the artist name
5. click on the album to display its content
6. empty page is displayed

**Expected behavior**
It is expected to display album name in the search results instead of only artist name. After Clicking on the album its content should be displayed.

**Console log**
No errors in console log

**Screenshots**
Search results in Iris:
![Screenshot_2021-01-05 Szukaj metallica](https://user-images.githubusercontent.com/2772080/103649904-82cea400-4f5f-11eb-8850-74ebbb9b771a.png)
Attempt to display album content in Iris:
![Screenshot_2021-01-05 Album](https://user-images.githubusercontent.com/2772080/103649939-924ded00-4f5f-11eb-853e-8d01a2e1bb39.png)

For reference, this is what it looks like in musicbox webclient:
![Screenshot_2021-01-05 Search Mopidy on guitarix local](https://user-images.githubusercontent.com/2772080/103649975-a1349f80-4f5f-11eb-98d7-ffe1f1a1fe74.png)
![Screenshot_2021-01-05 Albums Mopidy on guitarix local](https://user-images.githubusercontent.com/2772080/103649982-a265cc80-4f5f-11eb-933d-ef4c14fed0d4.png)

**Environment details:**
    OS: client: linux mint 20.0, server armbian buster
    Browser firefox
    Iris version 3.54.2

**Additional context**
Browsing mopidy dleyna albums trough Browse feature works as expected.

**Comment by jaedb** [comment]
My DLNA server does not support searching (go figure) so I am somewhat limited in being able to test this. Has the latest version of Iris, which refactors all of the URI encoding, resolved this issue for you?

**Comment by lostmyshape** [comment]
Hi Jaedb -- I can confirm this bug report and it is NOT limited to dleyna.  A search with any source that results in more than the display limit for iether Artist and Album will produce a "All Artists" or "All Albums" button.  Clicking on the button results in an empty page with spinning circle.  I'm new to Mopidy and Iris but it looks like maybe the URI is the problem?  For example clicking "All Artists" goes to: "http://xxx.xxx.x.xxx:6680/iris/uri/iris%3Asearch%3Aartists%3Athe" (I used "the" as the search term to get a lot of results).

Environment details:
OS: client: MacOS 10.15..7, server armbian buster
Browser Chrome
Iris version 3.56.1
