### ISSUE TITLE
Integration with Jamendo

### ISSUE THREAD

**Issue by cedricbousmanne** [jaedb/Iris#682]
I was wondering if you had any plan to integrate Iris with Jamendo at some point? I'd love to be able to listen to Jamedo music straight from Iris. 

Thanks for your time

API doc : https://developer.jamendo.com/v3.0/docs

**Comment by jaedb** [comment]
Unfortunately there doesn't appear to be a Mopidy implementation of this provider, so even if Iris were to integrate with it, the Mopidy server wouldn't be able to play it.
