### ISSUE TITLE
Dragging tracks to playlist not escaping chars escaped by right-clicking

### ISSUE THREAD

**Issue by 2e0byo** [jaedb/Iris#684]
**Describe the bug**
Tracks dragged and dropped in a playlist with (at least) apostrophes do not have the apostrophes escaped.
If I select a bunch of tracks containing (at least) apostrophes and use dragging to add them to a playlist, the resulting entries do not have the apostrophe escaped (urlified) and consequently fail.  If I se

**To Reproduce**
1. Select a bunch of tracks containing apostrophes.
2. Drag and drop them to a playlist.
3. Select the same nuch again.
4. Right-click and add them to a playlist.
5. Compare the two playlists.

**Expected behavior**
Playlists should be identical.  In fact, urlifying happens with right-clicking but not with dragging.  (Confirm by examining the .m3u8 files).

**Environment details:**
 - OS: Debian
 - Browser: any (tested various chrome-based).
 - Iris version: 3.52.2

**Comment by 2e0byo** [comment]
Confirmed with Iris 3.55.4

**Comment by jaedb** [comment]
When you say tracks that contain apostrophes, what exactly do you mean? Does the track URI contain the apostrophe or the track name? Do you have any publicly-accessible examples? Or at least some example URIs?

**Comment by 2e0byo** [comment]
Sorry that was unhelpfully vague.  

For a track, stored in the local music dir under `/Non-Album/Joe Dassin/'L’Été indien.opus`, the .m3u8 contains this if I right-click and add:

    local:track:Non-Album/Joe%20Dassin/L%E2%80%99%C3%89t%C3%A9%20indien.opus

but this if I drag and add:

    local:track:Non-Album/Joe%20Dassin/L’Été%20indien.opus

I.e. only spaces are urlified.  The second of course doesn't play.

Not sure if this is limited to `local:` urIs as I use the exclusively and have no means of testing anything else.
