### ISSUE TITLE
Iris not connected to mopidy

### ISSUE THREAD

**Issue by Xenosender** [jaedb/Iris#688]
Hello everyone
I am trying to setup iris on my raspberry pi (raspberry os)

I installed mopidy via apt (mopidy-3.1.1-1) and started it as a service (status is ok)
I installed mopidy-iris via pip3 (3.55.4)

I can reach iris, but the server status stays on "connecting" and nothing happens (so I cannot play anything).
In settings/advanced, "connection" stays on "not connected", and Version is '0.0.0 installed'

This behaviour stays if I uninstall Mopidy and reinstall mopidy-3.1.1 via pip3

Did I miss something in the configuration ? Is there a problem between the current versions of mopidy and mopidy-iris ?

**Comment by jaedb** [comment]
Please post **questions** to the [Discourse forum](https://discourse.mopidy.com/), tagged with _Iris_ if it is specific to Iris.

I would suggest reviewing your Mopidy configuration, as well as the IP addresses and ports configured in Iris. The Iris configuration under _Settings > Servers_ is _relative to your browser_.
