### ISSUE TITLE
Mopidy-Spotify extension is not running - you will not be able to play any Spotify tracks

### ISSUE THREAD

**Issue by WorldWideWebDev** [jaedb/Iris#689]
**Describe the bug**
[you cannot play anything, you are logged in but the screen reports you will not be able to play spotify tracks]
**To Reproduce**
1. log in
2. play'...'
3. play'....'

**Expected behavior**
[A clear and concise description of what you expected to happen]
I guess some music would be in order??
**Console log**
[Copy and paste your browser console log]

**Screenshots**
[if i only knew how to add a screenshot.]

**Environment details:**
 - OS: [mc]
 - Browser [safari]
 - Iris version [e.g. 3.54.0]

**Additional context**
[Add any other context about the problem]

**Comment by WorldWideWebDev** [comment]
You log in, but it says Read Only?

**Comment by jaedb** [comment]
I will refer you to the [Mopidy-Spotify documentation](https://github.com/mopidy/mopidy-spotify#configuration) - this should have all you need to get the extension running. If the extension is not running, even if you Authenticate in Iris, you will not be able to play any Spotify content.
If all else fails, please use the [Discourse forum](https://discourse.mopidy.com/) to post your question.
