### ISSUE TITLE
Add to playlist not working 

### ISSUE THREAD

**Issue by deadcyclo** [jaedb/Iris#69]
Browser: Firefox 47
Installed from pip

Header
```
Accept	
*/*
Accept-Encoding	gzip, deflate, br
Accept-Language	en-US,en;q=0.5
Authorization Bearer REDACTED
Connection	keep-alive
Content-Length	11
Content-Type	application/x-www-form-urlencoded; charset=UTF-8
Host	api.spotify.com
Referer	http://localhost:6680/iris/
User-Agent	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
origin	http://localhost:6680
```

Post parameters
`{"uris":[]}	`

Response
```
{
  "error" : {
    "status" : 400,
    "message" : "No tracks specified."
  }
}
```

**Comment by jaedb** [comment]
Please provide more information, especially the steps one can take to replicate this issue.

Please also read [Logging an issue](https://github.com/jaedb/Iris/wiki/Logging-an-issue) before logging issues.

**Comment by deadcyclo** [comment]
I can no longer reproduce this after updating firefox, so I assume it was a firefox bug. I'll go ahead and close this issue.
