### ISSUE TITLE
Global shared configuration

### ISSUE THREAD

**Issue by majuscule** [jaedb/Iris#691]
If I understand the iris model correctly, it treats each connection as a new user, therefore allowing them to set individual settings/connect to their own accounts, etc. I can see how this is helpful for some "advanced" cases, but I want any device to be able to connect and easily play music from global filesystems/connections without having to start from scratch. Am I missing this functionality somewhere?

**Describe the solution you'd like**
For a multiple new devices to be able to connect and immediately play & control music without a setup flow.

Thanks!

**Comment by majuscule** [comment]
As an aside, I also can't figure out why I need to connect to services (such as spotify) through the web UI, when my underlying mopidy connection is already configured to connect, and works with other mpd clients. I'm wondering if this is related to the above and I'm missing something obvious :-)

**Comment by majuscule** [comment]
Apologies, I'm reading more carefully now and see that this is mostly addressed from https://github.com/jaedb/Iris/wiki/Spotify-Authorization. It would be great if this could be pre/auto-shared for each new connecting user though.

**Comment by jaedb** [comment]
This had been covered in a previous issue (#322) and I have purposely avoided auto-sharing any authentication as this would provide full write access of the Spotify account to an unknown user (anyone who has access to your LAN for example).
