### ISSUE TITLE
Mobile view has no bottom padding

### ISSUE THREAD

**Issue by JamsheedMistri** [jaedb/Iris#700]
**Describe the bug**
On newer iPhones that don't have a home button, the bottom of the screen is curved and the home "bar" is at the bottom of the screen. Both of these inhibit viewing and interacting with the bottom status bar. While it's still possible, it's not optimal, and the UI could really use some padding at the bottom on mobile devices to avoid the curves & home bar.

**Screenshots**
![IMG_6340](https://user-images.githubusercontent.com/13024750/108482397-4a083700-724e-11eb-8df5-cc6658f6416d.PNG)

**Environment details:**
 - OS: iOS
 - Browser: Safari
 - Iris version: 3.55.2

**Comment by jaedb** [comment]
The latest versions of android push up the viewport, making sure it doesn't overlap the app content.

![Screenshot_20230219_185133_Chrome.jpg](https://user-images.githubusercontent.com/1711444/219931546-de0845ed-9af9-41a5-8fb6-20491d750cd9.jpg)


Also further to this there are no longer swipe gestures; they would be quite fiddly with android gestures as well.

So I shall close this issue. Please feel free to open a new one for any further issues.
