### ISSUE TITLE
Add a full screen display for Now Playing

### ISSUE THREAD

**Issue by Estefanop** [jaedb/Iris#702]
It would be great if an option could be added to have the album art shown on a full screen and track info superimposed. Similar to the way the [pirate radio](https://shop.pimoroni.com/products/pirate-audio-mini-speaker) displays on the small screen. 

Right now I use a small display and use the "Now Playing" tab zoomed to like 300% which is a nice solution but not the best looking. When you zoom in the sidebar disappears and the album art gets centered and the info is displayed to the right. Id like to see the art work take priority over the other details so it can be used as a display.

**Comment by jaedb** [comment]
You are in luck. _Kiosk Mode_ is already a feature in Iris, which I believe is exactly what you are after. Hover the currently-playing artwork and click the 'expand' icon:
![image](https://user-images.githubusercontent.com/1711444/110429335-9d63fb80-810f-11eb-8d04-9fa4233bb110.png)

Or you can use the hotkey `3` to trigger this.
