### ISSUE TITLE
No sound when streaming from iOS [snapcast]

### ISSUE THREAD

**Issue by Leitftw** [jaedb/Iris#709]
There is no sound when I stream music on IOS [Mopidy-Iris snapcast]
PC and Android are works well , there are no errors in the mopidy server log

[audio]
output = audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo

ubuntu 20.04 LTS
IOS 14.4 iphone 7 plus
browser: safari

**Comment by badaix** [comment]
[Snapweb](https://github.com/badaix/snapweb) was having the same issue. There were several reasons, like not using the `webkitAudioContext` and that the audio context was not created as a direct result of user interaction (i.e. in some "onClick" listener), but indirect through WebSocket read events. There was also a problem with the audiocontext timestamp for the sync playback.
I also don't have an iOS device, but was able to reproduce and fix the playback issue with Epiphany, a webkit based browser. As I heard from the community playback is now possible in snapweb, but with [stutters](https://github.com/badaix/snapweb/issues/18#issuecomment-759075863). I think that the timestamps provided by iOS webkit are not precise enough to enable synchronized playback, so playback should be smooth if the sync code is disabled. But I gave up trying to fix iOS problems without having an iOS device and without help from the community.

**Comment by jaedb** [comment]
Closing; it is not something that Iris handles (Iris uses Snapweb as it's Snapcast client).

**Comment by bendschs** [comment]
in snacast webapp for IOS it's working though.
