### ISSUE TITLE
Broken uri encoding in mopidy calls in 3.56

### ISSUE THREAD

**Issue by 2e0byo** [jaedb/Iris#711]
**Describe the bug**
3.56 breaks URI encoding for unicode tracks.

**To Reproduce**
1. Enable Test Mode (_Settings > Debug > Test Mode_). This provides more verbose error logs.
2. Select a track with unicode chars in the uri.
3. Add to queue.
4. Track is not added.
5. Select 'play'.
6. Iris notices it failed to enqueue the track.

**Expected behavior**
Track is enqueued.

**Console log**
from `MOPIDY_ENQUEUE_URIS`

With 3.55.4 the uri is:
`"local:track:Non-Album/St%C3%A9phane%20Golmann/Actualit%C3%A9s.m4a"`

With 3.56.1 the uri is:
`"local:track:Non-Album/Stéphane%20Golmann/Actualités.m4a"`

**Environment details:**
 - OS: Linux (various)
 - Browser: Qutebrowser
 - Iris version: 3.56.1/3.55.4

**Additional context**

Apologies to take so long to test 3.56 after it closed #601.  #601 is only partially resolved; I've commented over there.

Really sorry not to offer anything more constructive than a bug report!  I'm drowning in other code atm.  Will have a look at this if I get a chance.

**Comment by orontee** [comment]
Same problem here.

With mpc the following works well:
```
matthias@carbon:~ 
↳ mpc add local:track:Serge%20Gainsbourg/L%27Homme%20%C3%80%20T%C3%AAte%20De%20Chou%20%5BInt%C3%A9grale%2020%C3%A8me%20Anniversaire%5D/04%20Transit%20%C3%A0%20Marilou.flac
```

On iris side I see the following message in `/mopidy/ws/`
```
{"method":"core.tracklist.add","params":{"uris":["local:track:Serge%20Gainsbourg/L%27Homme%20Ã%20TÃªte%20De%20Chou%20%5BIntÃ©grale%2020Ã¨me%20Anniversaire%5D/04%20Transit%20Ã %20Marilou.flac"],"at_position":0},"jsonrpc":"2.0","id":14}
```
and the response is:
```
{"jsonrpc": "2.0", "id": 13, "result": null}
```
