### ISSUE TITLE
Searching spotify on iOS devices fails with error

### ISSUE THREAD

**Issue by leemel** [jaedb/Iris#715]
**Describe the bug**
Searching Spotify on mobile iOS devices fails in error (see screen shot)
This is both on iPad and iPhone

**To Reproduce**
Have spotify enabled
try to search for something

**Expected behavior**
search to return items like it does on the desktop

**Console log**
see screenshot (more info can be given if needed)

**Screenshots**
![Screen Shot 2021-03-16 at 7 22 34 PM](https://user-images.githubusercontent.com/2242095/111392442-f80bd300-868c-11eb-8933-cfaec3d06522.png)

![Screen Shot 2021-03-16 at 7 15 35 PM](https://user-images.githubusercontent.com/2242095/111391971-0a394180-868c-11eb-8456-e02198e125c1.png)

**Environment details:**
 - OS:  iOS
 - Browser: safari
 - Iris version  3.56.1

**Additional context**
[Add any other context about the problem]

**Comment by leemel** [comment]
User error.  Didn't realize each device using iris had to log into spotify individually

**Comment by jaedb** [comment]
If your Mopidy server is logged in to Spotify, Iris will use that user to authenticate with Spotify. So strictly speaking, you shouldn't need to log in each Iris user.
