### ISSUE TITLE
Browse files is broken in 3.57.0

### ISSUE THREAD

**Issue by bluepuma77** [jaedb/Iris#718]
**Describe the bug**
Browse files is broken in 3.57.0. The first level of folders is shown, but nothing beneath.
```
Not found
Oops, that link could not be found
```

**To Reproduce**
1. Click on browse
2. Click on Files
2. Click on a folder
3. "Not found. Oops, that link could not be found"

**Expected behavior**
Show files and folder beneath root

**Environment details:**
Fresh install

Raspberry Pi OS Lite
Release date: January 11th 2021
Kernel version: 5.4

Mopidy 3.1.1

Iris  3.57.0

**Additional context**

First level works
`http://music.local:6680/iris/library/browse/Files/file%3A%2F%2F%2Fhome%2Fpi%2Fmusic`
Second level does not work
`http://music.local:6680/iris/directory/file%3A%2F%2F%2Fhome%2Fpi%2Fmusic%2FWeezer`

Somehow the path structure changes. If you keep the path "iris/library" and add path manually it works.

**Comment by PeterWurmsdobler** [comment]
Hello, I have experienced similar issues, filed on https://discourse.mopidy.com/t/problem-scanning-local-flac-files/4823
Regards, peter.

**Comment by bluepuma77** [comment]
It seems the bug was introduced recently, it still works fine in mopidy-iris 3.56.1.

```
# list available version
pip3 install mopidy-iris==

# install previous version
sudo pip3 install --upgrade mopidy-iris==3.56.1

# restart mopidy
sudo service mopidy restart
```

**Comment by jaedb** [comment]
@bluepuma77 Your observation of the path changing is curious, and definitely shouldn't work this way. Did you try a force-refresh to ensure your browser cache isn't using the previous Iris version?

**Comment by pjones1063** [comment]
I had the same issue.  (also reported in 719).

This fixed it for me:
sudo pip3 install --upgrade mopidy-iris==3.56.1

**Comment by jaedb** [comment]
I have been unable to replicate this locally so I will need some assistance to debug this:
1. Enable _Test Mode_ (under _Settings_ > _Debug_)
2. Open your browser's developer console
3. Reproduce the issue (ie navigate to _Files_ and then a subfolder)
4. Copy and paste the developer console output into this issue.
