### ISSUE TITLE
Mopidy : Failed to add some tracks  Rpi 0 W

### ISSUE THREAD

**Issue by djbd21** [jaedb/Iris#720]
So I've been working at this project for awhile now. I'm completely new to both raspberry pi and mopidy. I read everything [here](https://learn.pimoroni.com/tutorial/sandyj/streaming-spotify-to-your-pi) and I think it works pretty well, minus the playback of tracks. Both mopidy and Iris have full access to my premium spotify account. Only thing that I could see it being is that I don't have audio hooked up yet. Would that create an issue with how mopidy "adds" tracks?   

Like I said I am very new to this so please break it down for me haha.
Thanks in advance!!

**Comment by jaedb** [comment]
Support queries and general questions don't belong in this repository's issue tracker. Please instead use the [Mopidy Discourse](https://discourse.mopidy.com/) forum. There are a lot more people monitoring this and will be better able to help (especially as your issue is not directly Iris related).
