### ISSUE TITLE
Bring up context menu when Track item is Tapped/Clicked exactly as it does when right-clicked

### ISSUE THREAD

**Issue by rpelletierrefocus** [jaedb/Iris#721]
I would like to add the context menu to the track item when touched/clicked similar to #226 

**Describe the solution you'd like**
When the track item is clicked or touched the context menu comes up, exactly like it does when the item is right-clicked.

I would love to figure out how to do this myself, if someone would not mind pointing me in the right direction. I have some programming skill, but I would need a little help finding where to look for this project.

I appreciate it.

**Comment by jaedb** [comment]
Personally this doesn't feel like an intuitive interaction, so I wouldn't look to implement this into Iris. But it's a great learning opportunity, for sure. All you'd need to do is change the logic of the `onTouchStart` event on the `Track` element, and call `openContextMenu` instead.

For questions like this in the future please instead refer to the [Mopidy Discourse](https://discourse.mopidy.com/) forum.

**Comment by rpelletierrefocus** [comment]
You were correct, this did not make any sense. Instead I decided to just use css to make the ellipsis that brings up the context menu into a button that is more prominent. This accomplishes more or less exactly what I want without the unnecessary coding. I appreciate the help.
![Image 219](https://user-images.githubusercontent.com/47399964/112895297-ee319900-90aa-11eb-84a1-e9d51bd1edc0.png)
