### ISSUE TITLE
Add To Queue does not automatically play if the queue is empty. 

### ISSUE THREAD

**Issue by rpelletierrefocus** [jaedb/Iris#725]
**Is your feature request related to a problem? Please describe.**
Right now, if someone chooses Add to queue and there are currently no tracks in the queue, it will not automatically play. You have to actually then click play. It would be nice if there was a settings for this.

**Describe the solution you'd like**
Ideally, there would be a setting in mopidy.conf if you would like to autoplay tracks in the queue.

**Describe alternatives you've considered**
I would absolutely be happy to do this on my own, I just need a little assistance regarding where to look. I have a dev environment setup and looked around for a couple of hours, but could not quite find a way to go about it. 

I was thinking in the enqueueURIs function (or whatever is is really called), it could look to see if the queue length = 0. If true then it would add to queue and then play the queue. 

This may be totally off base, I am just learning both mopidy and Iris, which is why I am asking for assistance. 

Thanks again for any assistance. I hope this particular feature request belongs here, my last one understandably did not. I am happy to move this to discourse with my apologies if not.

**Comment by jaedb** [comment]
Thinking about the action "Add to queue" doesn't imply that anything will be played, just that these items will be _added_. For this reason I don't think that "Add to queue" should start autoplaying if the queue is empty.

However in the interests of learning, by all means! The best place to start looking would indeed be `enueueURIs` and perform a state lookup (eg `store.getState().core.queue`) to see if it was currently empty. All the best 👍
