### ISSUE TITLE
Control/seed songs via spotify radio - via Websockets in Node App - How to generate Spotify Auth Token?

### ISSUE THREAD

**Issue by ned-kelly** [jaedb/Iris#730]
Hi There,

So I'm trying to "seed" radio tracks in a node app when Mopidy "stops" playing automatically so that that music never stops...

Basically all works fine & as expected when I've authenticated via the front-end previously... however if I leave the app for a few days (so my Spotify JTW tokens expire), I'm seeing the following in my logs:

```
ERROR    2021-04-06 03:08:42,270 [40:HttpServer] mopidy_iris.core
  IrisFrontend: access_token missing or invalid
```

Question - How can I re-auth to Spotify via a websockets request from my node app directly to Iris (Without opening the front-end Iris UI in chrome)?

Here's how I'm currently communicating with iris which works fine once i'm already authenticated...

```javascript

const SPOTIFY_SEED_TRACKS = (process.env.SPOTIFY_SEED_TRACKS !== undefined) ? process.env.SPOTIFY_SEED_TRACKS.split(',').map(Function.prototype.call, String.prototype.trim) : ['spotify:track:5UqCQaDshqbIk3pkhy4Pjg'];
const SPOTIFY_SEED_GENRES = (process.env.SPOTIFY_SEED_GENRES !== undefined) ? process.env.SPOTIFY_SEED_GENRES.split(',').map(Function.prototype.call, String.prototype.trim) : [];
const SPOTIFY_SEED_ARTISTS = (process.env.SPOTIFY_SEED_ARTISTS !== undefined) ? process.env.SPOTIFY_SEED_ARTISTS.split(',').map(Function.prototype.call, String.prototype.trim) : [];


const WebSocket = require('ws');
const ws = new WebSocket(`ws://${MPD_HOST}:${MPD_HTTP_PORT}/iris/ws/`, {
    perMessageDeflate: false,
});

ws.on('open', function open() {
    ws.send(JSON.stringify({
        "jsonrpc":"2.0",
        "id":161726943236543,
        "method":"change_radio",
        "params":{
            "reset":false,
            "seed_artists": SPOTIFY_SEED_ARTISTS,
            "seed_genres": SPOTIFY_SEED_GENRES,
            "seed_tracks": SPOTIFY_SEED_TRACKS
        }
    }));

});

```

Any help would be greatly appreciated!

**Comment by ned-kelly** [comment]
Answering this for anyone else wanting to auto seed...

Turns out you need to make a GET request every few hours to `/iris/http/refresh_spotify_token` to keep updating the spotify token - since there's no service worker installed when running only serverside...

**Comment by jaedb** [comment]
Please bear in mind that this is an _internal_ API endpoint. While it can be used outside of Iris itself, it's behaviour may change in future releases, potentially breaking external implementations.
