### ISSUE TITLE
Search results "Show all" buttons create broken link

### ISSUE THREAD

**Issue by ericroussille** [jaedb/Iris#731]
**Describe the bug**
When I click "All Artists" "All Albums" "All Playlists" buttons, the search is launched but it does not return any result

**Console log**
This is the Console log when I search for "James", I see the result (firsts artists, albums and playlists). Then , I click on "All Artists" => no trace on Console log. 

Searching for all matching "james" app.js:6809:46
<unavailable> 4 app.js:6809:46
Mopidy websocket:outgoingMessage <unavailable> app.js:6809:46
<unavailable> 3 app.js:6809:46
XHRGEThttps://api.spotify.com/v1/search?q=james&type=album,artist,playlist,track&country=FR&limit=50&offset=0
[HTTP/2 200 OK 0ms]

<unavailable> app.js:6809:46
Mopidy websocket:incomingMessage <unavailable> app.js:6809:46
<unavailable> app.js:6809:46
Mopidy websocket:outgoingMessage <unavailable> app.js:6809:46
Mopidy websocket:incomingMessage <unavailable> app.js:6809:46
<unavailable> app.js:6809:46
Mopidy websocket:outgoingMessage <unavailable> app.js:6809:46
<unavailable> 8 app.js:6809:46
Mopidy websocket:incomingMessage <unavailable> app.js:6809:46
<unavailable> app.js:6809:46
Mopidy websocket:outgoingMessage <unavailable> app.js:6809:46
<unavailable> 2 app.js:6809:46
Mopidy websocket:incomingMessage <unavailable> app.js:6809:46
<unavailable> 19 app.js:6809:46
Mopidy websocket:outgoingMessage <unavailable> app.js:6809:46
Mopidy websocket:incomingMessage <unavailable> app.js:6809:46
<unavailable> 24 app.js:6809:46

**Screenshots**
![image](https://user-images.githubusercontent.com/82306701/114295793-b4e42a80-9aa7-11eb-8c51-5b8af53da318.png)

![image](https://user-images.githubusercontent.com/82306701/114295804-cc231800-9aa7-11eb-8deb-9799f276c57e.png)

**Environment details:**
 - Window 10 (same behaviour on Android)
 - Firefox, Edge
 - Iris version [e.g. 3.57.5]

**Comment by lostmyshape** [comment]
I think this is the same issue as #681.
