### ISSUE TITLE
"now playing" gets out of sync

### ISSUE THREAD

**Issue by gwm** [jaedb/Iris#732]
**Describe the bug**
the "Now Playing" page of Iris shows the previously playing song title

**To Reproduce**
I believe this happens when the Iris page is not focussed on the desktop. Switch back to browser window and see that the song title is incorrect, tho artist always seems to be correct

**Expected behavior**
correct song title

**Console log**
[Copy and paste your browser console log]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![Screenshot from 2021-04-12 17-10-35](https://user-images.githubusercontent.com/2979135/114427307-dda51680-9bb2-11eb-91ba-02f50b61f328.png)

**Environment details:**
Ubuntu 20.10
firefox
iris 3.57.3

**Additional context**
[Add any other context about the problem]

**Comment by jaedb** [comment]
Please enable _Test Mode_ (under _Settings > Debug_) and open the developer console in your browser. This should provide the information required to replicate this issue.

**Comment by gwm** [comment]
In this case, Pixies, Gouge Away was displayed correctly but while working on a different workspace, the track changed to Beach Boys, Good Vibrations but Iris showed it as Beach Boys, Gouge Away!

I can't see anything in the console log that looks like this but here it is:

Test mode enabled, using un-minified code debug:134:11
Download the React DevTools for a better development experience: https://fb.me/react-devtools react-dom.development.js:24994
redux-persist/stateReconciler: rehydrated keys 'outputs, queue, queue_metadata, current_track, pinned, current_track_uri, seeds_resolved, radio, current_tracklist, stream_title, next_track_uri, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'language, theme, smooth_scrolling_enabled, hotkeys_enabled, playback_controls_touch_enabled, allow_reporting, wide_scrollbar_enabled, slim_mode, suppressed_broadcasts, grid_glow_enabled, window_title, uri_schemes_search_enabled, initial_setup_complete, library_albums_sort_reverse, library_albums_sort, album_tracks_sort_reverse, album_tracks_sort, show_lyrics, library_playlists_view, library_artists_sort_reverse, library_artists_sort, debug_info, log_actions, log_mopidy, log_pusher, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'host, port, ssl, current_server, servers, mute, volume, progress, play_state, uri_schemes, library_albums_uri, library_artists_uri, library_tracks_uri, connecting, restart_running, upgrade_running, consume, random, repeat, time_position, queue_history, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'country, locale, enabled, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'username, version, config, connecting, commands, pinned, upgrading, connection_id, _persist, client_id' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'authorization_url, authorizing, authorization, authorization_code, access_token, me, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'authorization_url, authorizing, authorization, me, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'enabled, connected, host, port, ssl, streams, groups, clients, server, commands, connecting, _persist' autoMergeLevel1.js:35:43
Restoring "local:track:Pixies/Doolittle%2025/1-15%20Gouge%20Away.flac" from database instrument.js:109
Restoring "local:track:Beach%20Boys%2C%20The/I%20Love%20You/01%20Good%20Vibrations.mp3" from database instrument.js:109

Let me know if I can turn on other debugging switches or other logs that might help.

G

**Comment by gwm** [comment]
it took a few tracks to happen again. Here is another example. Iris "now playing" is showing the correct band "Bandit Queen" but listing the track as "Last Resort" which was the previous playing track.

```
Test mode enabled, using un-minified code debug:134:11
Download the React DevTools for a better development experience: https://fb.me/react-devtools react-dom.development.js:24994
redux-persist/stateReconciler: rehydrated keys 'outputs, queue, queue_metadata, current_track, pinned, current_track_uri, seeds_resolved, radio, current_tracklist, stream_title, next_track_uri, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'language, theme, smooth_scrolling_enabled, hotkeys_enabled, playback_controls_touch_enabled, allow_reporting, wide_scrollbar_enabled, slim_mode, suppressed_broadcasts, grid_glow_enabled, window_title, uri_schemes_search_enabled, initial_setup_complete, library_albums_sort_reverse, library_albums_sort, album_tracks_sort_reverse, album_tracks_sort, show_lyrics, library_playlists_view, library_artists_sort_reverse, library_artists_sort, debug_info, log_actions, log_mopidy, log_pusher, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'host, port, ssl, current_server, servers, mute, volume, progress, play_state, uri_schemes, library_albums_uri, library_artists_uri, library_tracks_uri, connecting, restart_running, upgrade_running, consume, random, repeat, time_position, queue_history, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'country, locale, enabled, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'username, version, config, connecting, commands, pinned, upgrading, connection_id, _persist, client_id' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'authorization_url, authorizing, authorization, authorization_code, access_token, me, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'authorization_url, authorizing, authorization, me, _persist' autoMergeLevel1.js:35:43
redux-persist/stateReconciler: rehydrated keys 'enabled, connected, host, port, ssl, streams, groups, clients, server, commands, connecting, _persist' autoMergeLevel1.js:35:43
Restoring "local:track:Beach%20Boys%2C%20The/I%20Love%20You/01%20Good%20Vibrations.mp3" from database instrument.js:109
Restoring "local:track:Dreadzone/Eye%20On%20The%20Horizon/06%20Gangster.flac" from database instrument.js:109
"local:track:Green%20Day/Dookie/08%20She.m4a" already in index instrument.js:109
"local:track:Green%20Day/Dookie/08%20She.m4a" already in index instrument.js:109
"local:track:Various/Teenage_Dirtbags/2-04%20Papa%20Roach%20-%20Last%20Resort.flac" already in index instrument.js:109
"local:track:Various/Teenage_Dirtbags/2-04%20Papa%20Roach%20-%20Last%20Resort.flac" already in index instrument.js:109
"local:track:Bandit_Queen/Pervert/03%20Dirt%20and%20Soul%20%28Speed%20mix%29.flac" already in index instrument.js:109
"local:track:Bandit_Queen/Pervert/03%20Dirt%20and%20Soul%20%28Speed%20mix%29.flac" already in index instrument.js:109
Restoring "m3u:random100.m3u8" from database instrument.js:109
"local:track:Fatboy%20Slim/You%27ve%20Come%20A%20Long%20Way%2C%20Baby/04%20Gangster%20Tripping.flac" already in index instrument.js:109
```

**Comment by gwm** [comment]
ok. this seems to be a reasonable reproducer:

1. start playing tracks on Iris (firefox) check that track name is showing correctly
2. switch to another workspace and use another firefox window
3. allow Iris to advance to next track while you have the other firefox window focussed
4. switch back to the workspace with your firefox instance running Iris.
For me this makes Iris show the previous track name (altho artist will be correct) in the Now playing area, including the bottom bar if you are on a different section of Iris such as Settings.

G

**Comment by jaedb** [comment]
Nice, thanks for that extra info. It sounds like a rendering issue. Is the artist/track/artwork panel in the play bar (bottom left) affected too?

**Comment by gwm** [comment]
yes, the bottom panel also shows the incorrect info.

**Comment by gwm** [comment]
just a quick note to say that I saw exactly this behaviour on the mobile page yesterday when using my android phone (android 10, chrome).

**Comment by gwm** [comment]
could it be related to the fact that I use "consume" mode by default?

**Comment by gwm** [comment]
it got weirder... I turned off "consume" mode and used it like that for a while. This evening I cued up a bunch of albums. When I went back to Iris _much_ later, it was showing the wrong track title in the bottom panel and in the kiosk mode but this time the title wasn't from the previous song. It was from 4 albums back! 

Iris had not been running for all this time, the albums were cued up and laptop was then turned off. It was when I turned laptop back on and went back to Iris that I noticed. From the attached screencap you can see that the artist is Blondie but the the track title is from a Pixies album which is way back in the playback history.

![Screenshot from 2021-06-16 19-46-43](https://user-images.githubusercontent.com/2979135/122276240-8128e500-cedc-11eb-8b41-56346f88c89e.png)

**Comment by J-tt** [comment]
I'm getting the same issue, but the bottom left now playing is usually correct, it seems to just be the Now Playing/queue page that has the incorrect song.

![image](https://user-images.githubusercontent.com/10516525/160532497-a455286f-0b55-4dd5-a2a2-6e9bde661af8.png)

**Comment by gwm** [comment]
that's great news. Iris is the best interface to my music but this little bug keeps putting me off using it.

Let me know if I can help.

G

**Comment by jaedb** [comment]
This seems related to `stream_title` in that if Mopidy reports a stream title, we favour that over the track title. I've been able to replicate this where the `stream_title` has not been updated to match that of the track.

The fix is to always favour `current_track.name`, but fallback to `stream_title`. Unfortunately this may impact integrations which do not correctly provide `current_track.name`.

**Comment by gwm** [comment]
Yes! have just upgraded to 3.64.1 and this is fixed! You rock!
