### ISSUE TITLE
Remember Consume Mode choice when Iris is restarted

### ISSUE THREAD

**Issue by ericroussille** [jaedb/Iris#745]
Hello,

It would be nice to remember the last choice of the Consume Mode when you restart Iris. Every time, I start Iris, I set Consume Mode on to avoid to play again a song when I add a new song in the list.

Thanks for this great work.

**Comment by kingosticks** [comment]
Is this something different to Mopidy's consume mode? For which  you can use https://docs.mopidy.com/en/latest/config/#confval-core-restore_state

**Comment by ericroussille** [comment]
Thank you. I did not know this option of Mopidy. Consume mode is restored after restart.
