### ISSUE TITLE
Docs Update: nginx.conf for Snapserver

### ISSUE THREAD

**Issue by Sieboldianus** [jaedb/Iris#747]
**Describe the bug**

I have a system nginx reverse proxy, and used the [nginx-conf example](https://github.com/jaedb/Iris/wiki/Advanced#nginx) from the wiki

When I open `https://iris.local.my.tld/`, everything works except the Snapserver connection. When I try to enter the IP, I get:
```
WebSocket connection to 'wss://192.168.40.17:1780/jsonrpc' failed: Error in connection establishment: net::ERR_CONNECTION_RESET
```

As you can see, it tries to connect via `wss`, which is obvisioully wrong for IP-based. If I use the domain name `https://iris.local.my.tld/`, it doesn't work either.
I assume it is because the sample nginx conf only forwards to port 6680, not 1780.

To work around this, I created the following separate nginx conf:
```
server {
        listen 80;

        # Set to "_" to listen to all domains
        server_name  snapserver.local.mytld.com

        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl;

        # Set to "_" to listen to all domains
        server_name  snapserver.local.mytld.com;

        # Update the following to reflect your certificate and key location
        ssl on;
        ssl_certificate    /etc/nginx/ssl/wildcard.local.mytld.com.fullchain;
        ssl_certificate_key /etc/nginx/ssl/wildcard.local.mytld.com.key;
        ssl_prefer_server_ciphers on;

        proxy_http_version 1.1;
        proxy_read_timeout 600s;

        location / {
                proxy_pass http://127.0.0.1:1780;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;
        }
}
```

I did not test this, but it should be possible to combine this with the iris.conf, e.g. simply add a subdirectory:
```
        location /snapserver {
                proxy_pass http://127.0.0.1:1780;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;
        }
```

Afterwards, I added `snapserver.local.mytld.com` and port `443` in iris server settings and the connection worked.

Took me a while to figure out. Perhaps this could be added to the documentation?

**Comment by diabl0w** [comment]
even without using snapcast, I am getting websocket errors and nothing works via nginx:

```

  Uncaught exception GET /iris/ws/ (192.168.111.1)


HTTPServerRequest(protocol='http', host='*my.domain.net*', method='GET', uri='/iris/ws/', version='HTTP/1.1', remote_ip='192.168.111.1')


Traceback (most recent call last):


  File "/usr/local/lib/python3.7/dist-packages/tornado/websocket.py", line 954, in _accept_connection


    open_result = handler.open(*handler.open_args, **handler.open_kwargs)


  File "/usr/local/lib/python3.7/dist-packages/mopidy_iris/handlers.py", line 48, in open


    iris.add_connection(connection=self, client=client)


  File "/usr/local/lib/python3.7/dist-packages/mopidy_iris/core.py", line 287, in add_connection


    "params": {"connection": client},


  File "/usr/local/lib/python3.7/dist-packages/mopidy_iris/core.py", line 238, in broadcast


    connection["connection"].write_message(json_encode(message))


  File "/usr/local/lib/python3.7/dist-packages/tornado/websocket.py", line 337, in write_message


    raise WebSocketClosedError()


tornado.websocket.WebSocketClosedError
```

**Comment by Sieboldianus** [comment]
I am not sure if this works if your snapserver is listening on the same host on the same port. Is this your setup?

**Comment by diabl0w** [comment]
> I am not sure if this works if your snapserver is listening on the same host on the same port. Then nginx and snapserver would both listen on port 1780, which I think is not possible. Is this your setup?

yeah they're not on the same host... otherwise you would have to change one of the ports. 

just curious, so you have iris (127.0.0.1:6680) and snapserver (127.0.0.1:1780) both at location "/"?

**Comment by Sieboldianus** [comment]
I run the Iris Docker stack, which includes Snapserver, according to the [docker-compose.example.yml](https://github.com/jaedb/Iris/blob/master/docker-compose.example.yml). This is also what the [Wiki describes](https://github.com/jaedb/Iris/wiki/Getting-started#to-install-using-docker) for the Docker installation.

The sample [nginx conf](https://github.com/jaedb/Iris/wiki/Advanced#nginx) for this stack does not include port forwarding for 1780, which would be fine - but the Iris frontend, when accessed through SSL, leads to Snapclient/Snapserver connection getting requests with `wss://...:1780` instead of  `ws://...:1780` (this was apparantly a fix of another issue). But 1780, if not going through nginx ssl, is only available directly on port 1780.

To fix this, I had to create a different domain, _pointing to the same server_, only that nginx is forwarding `443` requests to 1780, through SSL. Would be great if someone could confirm this works elsewhere, too.

**Comment by diabl0w** [comment]
Ohhhh okay, you have them served at two different domains. that makes more sense. and yeah it looks like that is the way to do it. but it should save whatever you changed it to once changing it the first time unless your talking about access from new users.

**Comment by Sieboldianus** [comment]
> Ohhhh okay, you have them served at two different domains. that makes more sense. and yeah it looks like that is the way to do it. but it should save whatever you changed it to once changing it the first time unless your talking about access from new users.

Exactly, I was wondering how to set/modify _default_ configs for new users, because the default address for snapserver does not work.

**Comment by diabl0w** [comment]
> > Ohhhh okay, you have them served at two different domains. that makes more sense. and yeah it looks like that is the way to do it. but it should save whatever you changed it to once changing it the first time unless your talking about access from new users.
> 
> Exactly, I was wondering how to set/modify _default_ configs for new users, because the default address for snapserver does not work in this kind of setup.

yeah so it looks like you would use:
```
domain.net/iris/?snapcast={"enabled":true,"host":"my-host.com","port":"443"}
```

**Comment by Sieboldianus** [comment]
Thanks. But, there is no way to hardcode these settings in `mopidy.conf` or `snapserver.conf` on the server?

**Comment by diabl0w** [comment]
> Thanks. But, just to confirm, there is no way currently to hardcode these settings in `mopidy.conf` or `snapserver.conf` on the server?

definitely not in snapserver.conf, not sure about mopidy.conf. I don't think an "[iris]" section even exists for mopidy config

**Comment by Sieboldianus** [comment]
Apparently, [`[iris]-Section` exists], but it only includes 5 possible config values, e.g. not the snapserver-address. I will test this and report, perhaps there is a way to include other Iris default configs in the `[Iris]` section of `mopidy.conf`.

**Comment by diabl0w** [comment]
> Apparently, [`[iris]-Section` exists](https://github.com/jaedb/Iris/wiki/Getting-started#configuration), but it only includes 5 possible config values, e.g. not the snapserver-address. I will test this and report, perhaps there is a way to include other Iris default configs in the `[Iris]` section of `mopidy.conf`.

looks like you're right... sounds like it would be a good festure/pull request then to be able to include that

**Comment by jaedb** [comment]
Is the thinking here to _replace_ the in-browser settings with settings in `mopidy.conf`? Or to have defaults populated in `mopidy.conf`, but the user can overwrite those within the Iris UI?

**Comment by Sieboldianus** [comment]
Yes, basically populate the frontend values with defualt values defined in `mopidy.conf`. If This would be possible,
I could turn on Snapserver by default, and add the Service URL (snapserver.local.mytld.com), so users don't have to ask me what it is.

Obvisoully, I did not succeed creating a PR for this. It works _somehow_, but needs manual intervention on my side. So this is not critical, but would be a nice improvement. Many thanks for this otherwise awesome software!

**Comment by jaedb** [comment]
You can now set _default_ Snapcast configuration in `mopidy.conf`. Clients can _restore defaults_ to apply these, but they're not applied initially. For this, the [URL-based preconfiguration](https://github.com/jaedb/Iris/wiki/Advanced#preconfiguration) approach is more suited. This approach does need a bit more reviewing which is in the pipeline.

**Comment by Sieboldianus** [comment]
Wow, thanks so much jaedb! I will try it as soon as possible.

**Comment by Sieboldianus** [comment]
Tested (build local image using the `Dockerfile`):

- Defaults are read from mopidy.conf correcly
- my iris section:
```
[iris]
snapcast_enabled = true
snapcast_host = snapserver.local.mytld.com
snapcast_port = 443
```
- since this build, I do see brief disconnects from iris to the snapserver every ~10 seconds:

<details><summary>log</summary>
snapserver_1  | 2021-10-02 04-51-26.023 [Info] (PipeStream) Stream: Mopidy, connect to pipe: /tmp/snapfifo, fd: 15, pipe size: 65536
snapserver_1  | 2021-10-02 04-51-26.070 [Notice] (ControlServer) ControlServer::NewConnection: 172.17.2.1
snapserver_1  | 2021-10-02 04-51-26.070 [Error] (ControlServer) Removing 2 inactive session(s), active sessions: 1
snapserver_1  | 2021-10-02 04-51-26.123 [Info] (PipeStream) Stream: Mopidy, connect to pipe: /tmp/snapfifo, fd: 16, pipe size: 65536
snapserver_1  | 2021-10-02 04-51-26.223 [Info] (PipeStream) Stream: Mopidy, connect to pipe: /tmp/snapfifo, fd: 16, pipe size: 65536
</details>

This might not be connected to this particular update. Will look into this..
