### ISSUE TITLE
Add tap-and-hold support to TrackList

### ISSUE THREAD

**Issue by sgraca** [jaedb/Iris#75]
Hi,

After upgrading to 2.13.0 (and later 2.13.1) I noticed that it's no longer possible to remove multiple items from the queue on mobile. If I select multiple items then, the menu which is displayed on the bottom of the screen does not have remove option. Available options are: play, next, queue, playlist and start radio.
If I hold an item a little bit longer a context popup appears with remove option, but then it acts weird. Although single item is selected it removes multiple items. And it appears random. Sometimes clicking one item on queue which has 10 items leaves only two or three items in the queue.
I managed to reproduce such behaviour in a desktop browser. This happens when for some reason when I right click a song in the queue it is not highlighted but the menu appears. Clicking remove then has this strange effect.

Thanks,
Sebastian

**Comment by jaedb** [comment]
I have been unable to replicate this issue. Is anyone else experiencing this?

@sgraca have you tried using [test mode](https://github.com/jaedb/Iris/wiki/Developing-and-debugging) to gain further insight into the issue?

**Comment by sgraca** [comment]
Strange, currently I can see context menu toggle (three dots) when selecting items in the queue. Previously I saw standard blue bar at the bottom of the screen. Maybe the browser was still using cached version.
However I'm still able to reproduce removal of multiple items (but as it's possible to remove items from the queue, it's not a big deal). If you're still interested I attached debug log for this action.
How to reproduce:
* in the developer tools change to mobile device
* add some tracks to queue
* go to queue and press and hold a track until context menu appears
* click remove
[raspberry-1488832388072.txt](https://github.com/jaedb/Iris/files/822444/raspberry-1488832388072.txt)

**Comment by jaedb** [comment]
@sgraca Thanks for that extra info. Are you experiencing this issue on a true touch device? 

There is no accurate way to emulate another device or browser and it's behavior, especially regarding touch behavior. For accurate testing use a dedicated testing service like [BrowserStack](https://www.browserstack.com/) where actual devices are used.

**Comment by sgraca** [comment]
@jaedb Yes, that's what happens on my mobile phone. It's easily reproducible in Chrome Dev tools after switching to a mobile device profile. Just like described (touch and hold a song in the middle of the queue).

**Comment by jaedb** [comment]
I think I've got my head around the issue here. Ultimately it's constrained to tap and hold behavior on track items, so I've updated the issue title to reflect this.

At this stage tap and hold is not strictly supported, so further consideration is required on how we can accommodate this.
