### ISSUE TITLE
WS: Handle missing Spotify-Mopidy config

### ISSUE THREAD

**Issue by davewuvswaffles** [jaedb/Iris#76]
New installs on Raspberry Pi's running Raspbian Lite seem to be running into the following errors constantly, whether or not I've updated the entire system or not.

```
ERROR     Uncaught exception in /iris/ws

Traceback (most recent call last)

     File "/usr/lib/python2.7/dist-packages/tornado/websocket.py", line 316, in wrapper return callback(*args, **kwargs)

     FIle "/usr/lib/python2.7/dist-packages/mopidy_iris/handlers.py", line 87, in on_message response = getattr(mem.iris, message['method'])(data)

     File "/usr/local/python2.7/dist-packages/mopidy_iris/core.py", line 186, in get_config "spotify_username": self.config['spotify']['username'],

     File "/usr/lib/python2.7/dist-packages/mopidy/config/__init__.py", line 284, in __getitem__ item = self.data.__getitem__(key)

KeyError: u'spotify'

```

**Comment by jaedb** [comment]
This looks to be due to not having Spotify configuration vales in your mopidy.conf.

Please try adding these (see Mopidy-Spotify docs for details) and then restart Mopidy.

**Comment by davewuvswaffles** [comment]
Double checked my mopidy.conf and that requisite info was there.

On a hunch, I double checked the status of my Mopidy-spotify installation through Pip and it looks like it failed without warning when I installed it as a dependency upon installing Mopidy-Iris.

Installing Mopidy-spotify again through apt solved the issue.  Thanks, jaedb.  The updates are looking great.

**Comment by jaedb** [comment]
Original issue not related to missing Spotify-Iris configuration values.

Testing has confirmed that even when configuration missing, Iris operates fine (but can't play Spotify content as the extension is disabled when required config values are missing).
