### ISSUE TITLE
Add support for additional PIP packages to Docker image

### ISSUE THREAD

**Issue by BasVanBoven** [jaedb/Iris#763]
**Is your feature request related to a problem? Please describe.**
The extension-based architecture Mopidy provides is not necessarily a good fit to an one-size-fits-all Docker image. However, there are setups where running Mopidy/Iris inside a Docker is the preferred and/or only solution.

**Describe the solution you'd like**
I would like to add the following four lines to docker/entrypoint.sh, in order to enable users to optionally add a small number of pip packages suited to their desired Mopidy setup (in my case, Mopidy-Scrobbler) through an environment variable, without building an entirely new Docker image.

if  [ ${PIP_PACKAGES:+x} ]; then
    echo "-- INSTALLING PIP PACKAGES $PIP_PACKAGES --"
    python3 -m pip install --no-cache $PIP_PACKAGES
fi

**Describe alternatives you've considered**
Currently, I am running a modified Docker image, but this requires additional maintenance and I doubt I am the only one running into this problem.

**Additional context**
If deemed acceptable, I can contribute the required PR and edit the Wiki to reflect this option. Please discuss! :)

**Comment by jaedb** [comment]
PR merged and will be included in next release - thanks for the contribution!
