### ISSUE TITLE
docker install can not see media

### ISSUE THREAD

**Issue by zsamiatt** [jaedb/Iris#768]
**Describe the bug**
I installed your docker files (latest). Everything looking good (snapserver, mopidy, iris) but the Iris can not see the media library.  I hope you can help me. Thank you,

My docker runing on Synology NAS.
I try:
add full right
add /var/lib/mopidy/local
Mopidy config file or local setup

Did not help.

version: "3"
services:
  snapserver:
    image: jaedb/snapserver
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - /volume1/docker/snapserver/TMP:/tmp
      - /volume1/docker/snapserver/snapserver.conf:/etc/snapserver.conf
  mopidy:
    image: jaedb/iris

    build:
      context: .
    depends_on:
      - snapserver
    ports:
      - 6600:6600
      - 6680:6680
    volumes:
      # Uncomment these lines to use a host-managed development build
      #- ./mopidy_iris:/iris/mopidy_iris
      #- ./IRIS_VERSION:/iris/IRIS_VERSION
      - /volume1/docker/mopidy/data:/var/lib/mopidy/iris
      - /volume1/docker/mopidy/mopidy.conf:/config/mopidy.conf
      - /volume1/music:/var/lib/mopidy/media
      #- /volume1/music:/var/lib/mopidy/local
      - /volume1/docker/snapserver/TMP:/tmp

**Console log**

  Failed looking up file:///var/lib/mopidy/media: gst-resource-error-quark: Could not open file "/var/lib/mopidy/media" for reading. (5)

ERROR    2021-09-24 16:31:32,771 [8:Core-10] mopidy.core.library

  FileBackend backend caused an exception.

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/Mopidy-3.1.1-py3.7.egg/mopidy/core/library.py", line 17, in _backend_error_handling
      

d

  File "/usr/local/lib/python3.7/dist-packages/Mopidy-3.1.1-py3.7.egg/mopidy/core/library.py", line 114, in _browse

    result = backend.library.browse(uri).get()

  File "/usr/local/lib/python3.7/dist-packages/pykka-3.0.1-py3.7.egg/pykka/_threading.py", line 55, in get

    raise exc_value

  File "/usr/local/lib/python3.7/dist-packages/pykka-3.0.1-py3.7.egg/pykka/_actor.py", line 186, in _actor_loop

    response = self._handle_receive(envelope.message)

  File "/usr/local/lib/python3.7/dist-packages/pykka-3.0.1-py3.7.egg/pykka/_actor.py", line 286, in _handle_receive

    return callee(*message.args, **message.kwargs)

  File "/usr/local/lib/python3.7/dist-packages/Mopidy-3.1.1-py3.7.egg/mopidy/file/library.py", line 58, in browse

    for dir_entry in local_path.iterdir():

  File "/usr/lib/python3.7/pathlib.py", line 1083, in iterdir

    for name in self._accessor.listdir(self):

PermissionError: [Errno 13] Permission denied: '/var/lib/mopidy/media'

INFO     2021-09-24 16:31:41,777 [8:Thread-16] mopidy_iris.system

  Running system action 'local_scan'

INFO     2021-09-24 16:31:43,650 [50:MainThread] mopidy.__main__

  Starting Mopidy 3.1.1

INFO     2021-09-24 16:31:43,738 [50:MainThread] mopidy.config

  Loading config from builtin defaults

INFO     2021-09-24 16:31:43,744 [50:MainThread] mopidy.config

  Loading config from file:///config/mopidy.conf

INFO     2021-09-24 16:31:43,745 [50:MainThread] mopidy.config

  Loading config from command line options

INFO     2021-09-24 16:31:43,753 [50:MainThread] mopidy.internal.path

  Creating dir file:///root/.cache/mopidy

INFO     2021-09-24 16:31:43,753 [50:MainThread] mopidy.internal.path

  Creating dir file:///root/.config/mopidy

INFO     2021-09-24 16:31:43,760 [50:MainThread] mopidy.ext

  Disabled extension ytmusic: ytmusicapi<0.15.0,>=0.14.0 required, but found ytmusicapi 0.16.0 at /usr/local/lib/python3.7/dist-packages

INFO     2021-09-24 16:31:44,641 [50:MainThread] mopidy.__main__

  Enabled extensions: dleyna, file, musicbox_webclient, http, mpd, stream, tunein, youtube, iris, m3u, softwaremixer, podcast

INFO     2021-09-24 16:31:44,641 [50:MainThread] mopidy.__main__

  Disabled extensions: ytmusic, soundcloud, local, spotify, tidal, jellyfin

WARNING  2021-09-24 16:31:44,641 [50:MainThread] mopidy.__main__

  Found jellyfin configuration errors. The extension has been automatically disabled:

WARNING  2021-09-24 16:31:44,641 [50:MainThread] mopidy.__main__

    jellyfin/hostname must be set.

WARNING  2021-09-24 16:31:44,642 [50:MainThread] mopidy.__main__

    jellyfin/username must be set.

WARNING  2021-09-24 16:31:44,642 [50:MainThread] mopidy.__main__

  Found local configuration errors. The extension has been automatically disabled:

WARNING  2021-09-24 16:31:44,642 [50:MainThread] mopidy.__main__

    local/media_dir must be set.

WARNING  2021-09-24 16:31:44,642 [50:MainThread] mopidy.__main__

  Found soundcloud configuration errors. The extension has been automatically disabled:

WARNING  2021-09-24 16:31:44,642 [50:MainThread] mopidy.__main__

    soundcloud/auth_token must be set.

WARNING  2021-09-24 16:31:44,642 [50:MainThread] mopidy.__main__

  Found spotify configuration errors. The extension has been automatically disabled:

WARNING  2021-09-24 16:31:44,642 [50:MainThread] mopidy.__main__

    spotify/username must be set.

WARNING  2021-09-24 16:31:44,642 [50:MainThread] mopidy.__main__

    spotify/password must be set.

WARNING  2021-09-24 16:31:44,642 [50:MainThread] mopidy.__main__

    spotify/client_id must be set.

WARNING  2021-09-24 16:31:44,643 [50:MainThread] mopidy.__main__

    spotify/client_secret must be set.

WARNING  2021-09-24 16:31:44,643 [50:MainThread] mopidy.__main__

  Found tidal configuration errors. The extension has been automatically disabled:

WARNING  2021-09-24 16:31:44,643 [50:MainThread] mopidy.__main__

    tidal/username must be set.

WARNING  2021-09-24 16:31:44,643 [50:MainThread] mopidy.__main__

    tidal/password must be set.

WARNING  2021-09-24 16:31:44,643 [50:MainThread] mopidy.__main__

  Please fix the extension configuration errors or disable the extensions to silence these messages.

ERROR    2021-09-24 16:31:44,643 [50:MainThread] mopidy.__main__

  Unable to run command provided by disabled extension local

INFO     2021-09-24 16:31:44,747 [8:Thread-16] mopidy_iris.system

  Completed in 2 seconds

WARNING  2021-09-24 16:31:47,753 [8:FileBackend-7] mopidy.file.library

  Failed looking up file:///var/lib/mopidy: gst-resource-error-quark: "/var/lib/mopidy" is a directory. (5)

WARNING  2021-09-24 16:31:47,887 [8:FileBackend-7] mopidy.file.library

  Failed looking up file:///var/lib/mopidy/pulse.cookie: gst-stream-error-quark: Stream contains no data. (4)

WARNING  2021-09-24 16:31:48,568 [8:FileBackend-7] mopidy.file.library

  Failed looking up file:///var/lib/mopidy/media: gst-resource-error-quark: Could not open file "/var/lib/mopidy/media" for reading. (5)

ERROR    2021-09-24 16:31:48,583 [8:Core-10] mopidy.core.library

  FileBackend backend caused an exception.

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/Mopidy-3.1.1-py3.7.egg/mopidy/core/library.py", line 17, in _backend_error_handling
      

d

  File "/usr/local/lib/python3.7/dist-packages/Mopidy-3.1.1-py3.7.egg/mopidy/core/library.py", line 114, in _browse

    result = backend.library.browse(uri).get()

  File "/usr/local/lib/python3.7/dist-packages/pykka-3.0.1-py3.7.egg/pykka/_threading.py", line 55, in get

    raise exc_value

  File "/usr/local/lib/python3.7/dist-packages/pykka-3.0.1-py3.7.egg/pykka/_actor.py", line 186, in _actor_loop

    response = self._handle_receive(envelope.message)

  File "/usr/local/lib/python3.7/dist-packages/pykka-3.0.1-py3.7.egg/pykka/_actor.py", line 286, in _handle_receive

    return callee(*message.args, **message.kwargs)

  File "/usr/local/lib/python3.7/dist-packages/Mopidy-3.1.1-py3.7.egg/mopidy/file/library.py", line 58, in browse

    for dir_entry in local_path.iterdir():

  File "/usr/lib/python3.7/pathlib.py", line 1083, in iterdir

    for name in self._accessor.listdir(self):

PermissionError: [Errno 13] Permission denied: '/var/lib/mopidy/media'

**Comment by zsamiatt** [comment]
I find the problem. The mopidy docker can not use environment. The default rights only see in docker folder. Any idea how can add correct right to docker?

**Comment by jaedb** [comment]
What is your docker _host_ setup? Are you running on Mac? Windows? Linux? The permissions provided and the user that you're running `docker-compose` as could be the culprit here.

Also, this error: `local/media_dir must be set.` is a hint. Have you changed this in your `mopidy.conf` file?

**Comment by zsamiatt** [comment]
I have synology NAS and the NAS runing the docker. 
I try:
add full right in environment
add /var/lib/mopidy/local volumes
Mopidy config, file or local setup

I think default no permission connect to folder, but the docker can not use environment right.

**Comment by zsamiatt** [comment]
I solved. I added full rights to media folder and Iris see music. So, the issue not in mopdy config. A problem that default docker user can not see outside the docker folder.

**Comment by jpbaril** [comment]
@zsamiatt How did you do that? I'm also on a Synology NAS and can't get it to access my local music directory.
Thank you.

**Comment by zsamiatt** [comment]
Enable telnet on synology. Telnet to synology and add full right to your media folder.
