### ISSUE TITLE
Add and use Last.FM statistics

### ISSUE THREAD

**Issue by sjoukebakker** [jaedb/Iris#769]
**Is your feature request related to a problem? Please describe.**
I'm a very satisfied user of Mopidy + Local + Iris since my Spotify Unlimited account ended. But I always liked the daily mixes that spotify provided. Or a list of songs/albums that haven't been played for a while.

**Describe the solution you'd like**
Would it be possible to get the playcounts of the tracks/albums in Mopidy-Local from Last.Fm for the authorized last.fm user, and optionally display them in the album list?
And with this data available it would be cool to generate a dashboard with, for example, a list of albums that haven't been played for a few months (but a lot in the past). Recently played artists. Or the 20 most played tracks in 2019.
Generating playlists of songs often played together would also be cool, but I can imagine that this would be a lot harder to do.

**Comment by jaedb** [comment]
Supportive information, like play counts or popularity, is totally doable. However the effort required to create a dashboard based on this data is difficult to justify, at least as part of the Iris project.

I think you'll find that Spotify's daily mixes and their recommendation engine in general is a very polished part of their product. Not to mention it being a paid service.

To me, the solution to this is a separate application that procures data from your various music sources, collates tracks into playlist, and then makes them available for Iris/Mopidy to consume. It could even just save tracks into an `m3u` file on your Mopidy server, which Iris would be able to read.

Ultimately, while I think this is a neat idea, it is beyond the scope of the Iris project.
