### ISSUE TITLE
Enable skip to next/previous track on mobile device

### ISSUE THREAD

**Issue by bluepuma77** [jaedb/Iris#786]
**Is your feature request related to a problem? Please describe.**
On mobile device (iPhone) I can not skip to the next or previous track.

**Describe the solution you'd like**
Enable buttons on mobile devices to skip a track forward and back, like on desktop.

**Describe alternatives you've considered**
Use console or a different client.

**Additional context**
Desktop has the back and forward buttons next to play/pause.
<img width="134" alt="Mopidy-Iris" src="https://user-images.githubusercontent.com/5221187/140498813-02f7e2eb-f9f1-4efe-9e69-c5d5cf132be2.png">

On mobile device those buttons are not shown
![IMG_9333(1)](https://user-images.githubusercontent.com/5221187/140498862-a059b44a-fc95-436c-9075-32d7426afa1b.PNG) ![IMG_9334(1)](https://user-images.githubusercontent.com/5221187/140498870-10f3de0a-7493-476d-9cc8-da5adf0cd430.PNG)

![IMG_9335(1)](https://user-images.githubusercontent.com/5221187/140498883-d925710a-4ead-49c1-be29-a22a2152da05.PNG)

![IMG_9336(1)](https://user-images.githubusercontent.com/5221187/140498899-e077088f-41e8-4fa3-9e59-ad65d89bafb8.PNG)

**Comment by jaedb** [comment]
In the interim, the intended way to change track on mobile devices is to swipe left or right on the track.

**Comment by bluepuma77** [comment]
Wow, amazing stuff, I didn't know :-)
