### ISSUE TITLE
Spotify API's album type renamed to `album_type`, filters no longer work

### ISSUE THREAD

**Issue by grimpy** [jaedb/Iris#788]
### Iris version

3.60.1

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

When browsing to an artist it's discography you see singles/albums mixed there is a filter to select album/single

When selecting album it still shows all including the singles when selecting single it does not show anything (no the singles either)

Example artist:
http://localhost:6680/iris/artist/c3BvdGlmeTphcnRpc3Q6NUhBNWFMWTNqSlY3ZWltWFdrUkJCcA==

![image](https://user-images.githubusercontent.com/143869/142415126-33c2edd4-a0e6-4be6-9004-6dc9a483258e.png)
one of these two is a single

When manually doing the api calls to spotify: things get filtered correctly when using the include_groups query param

**Comment by jaedb** [comment]
It looks like Spotify have changed their API to use `album_type` to contain the single vs compilation vs album. Iris applies filtering based on `type`, which in the case of Spotify, is always `album` hence this filter doesn't work. Good spotting!
