### ISSUE TITLE
"Could not get Snapcast server" popup

### ISSUE THREAD

**Issue by HigherSY** [jaedb/Iris#790]
### Iris version

3.59.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [X] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

"Could not get Snapcast server" pops up even when Snapcast wasn't enabled.

![Screenshot_20211220-095656_Chrome](https://user-images.githubusercontent.com/21186824/146701262-85771d9d-668b-41b7-b092-913db9791d35.png)

**Comment by HigherSY** [comment]
By the way, I'm willing to contribute a Chinese translation, is that ok?

**Comment by jaedb** [comment]
Where do you manage your `mopidy.conf` file (which can be responsible for enabling/disabling Snapcast)? The comment https://github.com/jaedb/Iris/issues/791#issuecomment-999419750  might be related to your situation.

And for translations, please do! Please make sure you follow the [contribution guidelines](https://github.com/jaedb/Iris/wiki/Contributing#translations).

**Comment by HigherSY** [comment]
It worked!
But that's strange, shouldn't it be disabled by default?

**Comment by bluepuma77** [comment]
I just re-installed my Raspberry Pi  and mopidy and suddenly see error messages in the logs
```
Dec 23 20:47:24 soundboxmopidy[598]: INFO     [HttpServer] mopidy_iris.core Updating Snapcast stream metadata: http://localhost:1780/jsonrpc
Dec 23 20:47:24 soundboxmopidy[598]: ERROR    [HttpServer] mopidy_iris.core [Errno 111] Connection refused
```
which seems confusing as the GUI states in Settings: "Snapcast disabled"

Now I set `snapcast_enabled = false` in `/etc/mopidy/mopidy.conf` and it seems ok.

**Comment by Paul-Vdp** [comment]
I can testify that no amount of disabling via the GUI nor via the mopidy.conf file makes the error go away

**Comment by antiguru** [comment]
After e787a339f273fc54900b4fd5c498222165758acb I'm getting the following error. I don't have the spotify plugin configured.
```
Feb 06 09:45:28 musicpi mopidy[616]: Traceback (most recent call last):
Feb 06 09:45:28 musicpi mopidy[616]:   File "/usr/lib/python3/dist-packages/mopidy/listener.py", line 44, in on_event
Feb 06 09:45:28 musicpi mopidy[616]:     getattr(self, event)(**kwargs)
Feb 06 09:45:28 musicpi mopidy[616]:   File "/var/lib/mopidy/.local/lib/python3.9/site-packages/mopidy_iris/frontend.py", line 26, in track_playback_ended
Feb 06 09:45:28 musicpi mopidy[616]:     if iris.ioloop and iris.config["spotify"]["enabled"]:
Feb 06 09:45:28 musicpi mopidy[616]:   File "/usr/lib/python3/dist-packages/mopidy/config/__init__.py", line 312, in __getitem__
Feb 06 09:45:28 musicpi mopidy[616]:     item = self._data.__getitem__(key)
Feb 06 09:45:28 musicpi mopidy[616]: KeyError: 'spotify'
```
