### ISSUE TITLE
With Snapcast disabled Iris still tries to update 

### ISSUE THREAD

**Issue by martijncalker** [jaedb/Iris#791]
### Iris version

3.60.1

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

Hi there! 

I'm not very familiar with Mopidy and Iris, so excuse me if I'm getting it wrong. 

I've installed Mopidy and Iris on my Raspberry Pi Zero 2 W, which runs pretty smooth. I noticed my logs are filling up with the `Updating Snapcast stream metadata` error: it fails to update due to a refused connection. As far as I know, I'm not running a Snapcast server. 

I've tried to search this repo and tried to modify the iris configuration (changed `snapcast_enabled` to false), which now looks like the configuration given below. This however does not resolve the error messages. I can't find any related code where this variable (`snapcast_enabled`) is checked. Am I correct that I can't disable this? 

```
[iris]
enabled = true
country = NZ
locale = en_NZ
snapcast_enabled = false
snapcast_host = localhost
snapcast_port = 1780
snapcast_ssl = false
snapcast_stream = Default
```

### Logs

```shell
Dec 21 21:10:01 raspberrypi mopidy[21981]: INFO     [HttpServer] mopidy_iris.core Updating Snapcast stream metadata: http://localhost:1780/jsonrpc
Dec 21 21:10:01 raspberrypi mopidy[21981]: ERROR    [HttpServer] mopidy_iris.core [Errno 111] Connection refused
Dec 21 21:12:45 raspberrypi mopidy[21981]: INFO     [HttpServer] mopidy_iris.core Updating Snapcast stream metadata: http://localhost:1780/jsonrpc
Dec 21 21:12:45 raspberrypi mopidy[21981]: ERROR    [HttpServer] mopidy_iris.core [Errno 111] Connection refused
Dec 21 21:16:02 raspberrypi mopidy[21981]: INFO     [HttpServer] mopidy_iris.core Updating Snapcast stream metadata: http://localhost:1780/jsonrpc
Dec 21 21:16:02 raspberrypi mopidy[21981]: ERROR    [HttpServer] mopidy_iris.core [Errno 111] Connection refused
Dec 21 21:19:24 raspberrypi mopidy[21981]: INFO     [HttpServer] mopidy_iris.core Updating Snapcast stream metadata: http://localhost:1780/jsonrpc
Dec 21 21:19:24 raspberrypi mopidy[21981]: ERROR    [HttpServer] mopidy_iris.core [Errno 111] Connection refused
Dec 21 21:23:11 raspberrypi mopidy[21981]: INFO     [HttpServer] mopidy_iris.core Updating Snapcast stream metadata: http://localhost:1780/jsonrpc
Dec 21 21:23:11 raspberrypi mopidy[21981]: ERROR    [HttpServer] mopidy_iris.core [Errno 111] Connection refused
Dec 21 21:26:40 raspberrypi mopidy[21981]: INFO     [HttpServer] mopidy_iris.core Updating Snapcast stream metadata: http://localhost:1780/jsonrpc
Dec 21 21:26:40 raspberrypi mopidy[21981]: ERROR    [HttpServer] mopidy_iris.core [Errno 111] Connection refused
```

**Comment by martijncalker** [comment]
Hm, seems like that configuration isn't picked up when modifying the `/usr/share/mopidy/conf.d/mopidy.conf`, but it is picked up when I configured exactly the same in `/etc/mopidy/mopidy.conf`. Probably my bad here.

**Comment by kingosticks** [comment]
Doesn't /usr/share/mopidy/conf.d/mopidy.conf have a comment right at the top saying don't modify this file?
