### ISSUE TITLE
Lyrics not complete

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [jaedb/Iris#794]
### Iris version

3.60.1

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

Whenever I go the track info of a song to view the lyrics, half of the lyrics are missing.
When clicking on the album cover in the bottom-left and view the lyrics there, they move far too slowly (probably because its only using half).

**Comment by jaedb** [comment]
This sounds like it could be a browser bug.

Have you tried any other non-Chromium browsers on the same machine (eg Firefox)? 

What version of Chrome are you using?

**Comment by LevitatingBusinessMan** [comment]
@jaedb I am using Chromium, but it seems to happen with Firefox as well. With short songs the complete lyrics seem to show up, suggesting it gets truncated somewhere.

**Comment by jaedb** [comment]
Lyrics auto-scroll based on the size of the lyrics. I suspect the `<div>` containing the lyrics results is not correctly reporting its height (in pixels), and so the auto-scroll is not able to function correctly.

As per my previous question, what _version_ of Chrome are you using?

The other thought is whether the play progress is showing accurately. When you're about half way through the track, does the playback bar correctly show as being 50% also?

**Comment by jaedb** [comment]
Closing issue; no response from issue author.

**Comment by LevitatingBusinessMan** [comment]
I am sorry I've stopped using iris since Mopidy stopped working with spotify.

The version of Chromium I was on was the most recent one (at the time (ArchLinux user), once I have set up my Mopidy server again I will continue investigating this myself.

**Comment by Dzordzu** [comment]
@LevitatingBusinessMan mopidy-spotify is back again, but (until merge) you need to use [this repository with a special branch](https://github.com/kingosticks/mopidy-spotify/tree/gstspotifysrc-hack)

**Comment by LevitatingBusinessMan** [comment]
> @LevitatingBusinessMan mopidy-spotify is back again, but (until merge) you need to use [this repository with a special branch](https://github.com/kingosticks/mopidy-spotify/tree/gstspotifysrc-hack)

Hey @Dzordzu, thanks I 've been following the progress :)

I recently moved house so I still have a lot of networking to set up before I need to run Mopidy again.

**Comment by Dzordzu** [comment]
To be sure: issue still exists

**Comment by LevitatingBusinessMan** [comment]
> To be sure: issue still exists

You've experienced this bug as well?

**Comment by Dzordzu** [comment]
Yep. It's quite a random behavior. It can happen regardless of the browser. Latest firefox and chromium have been tested. If i manage to stumble across this issue (it may take a while, I'm not reading lyrics very often ;) ) I will take some screenshots, try to look at the console and stylings
