### ISSUE TITLE
docker image fails to build - Unable to locate package libspotify-dev

### ISSUE THREAD

**Issue by footy42** [jaedb/Iris#797]
### Iris version

3.60.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [x] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [x] Other

### What happened?

docker image fails to build.

```
E: Unable to locate package libspotify-dev
ERROR: Service 'mopidy' failed to build: The command '/bin/sh -c wget -q -O - https://apt.mopidy.com/mopidy.gpg   | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn apt-key add -   && wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list   && apt-get update   && apt-get install -y libspotify-dev   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by jojo141185** [comment]
We have no problems building docker images for multiple architectures on [our fork](https://github.com/seppi91/Iris/actions) . However, the dockerfile has been slightly modified.

**Comment by jaedb** [comment]
I too have had no problems building this:
```
Step 4/19 : RUN wget -q -O - https://apt.mopidy.com/mopidy.gpg   | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn apt-key add -   && wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list   && apt-get update   && apt-get install -y libspotify-dev   && rm -rf /var/lib/apt/lists/*
 ---> Running in 4ee5eab0f647
OK
```
...
```
The following additional packages will be installed:
  libspotify12
The following NEW packages will be installed:
  libspotify-dev libspotify12
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 1610 kB of archives.
After this operation, 4312 kB of additional disk space will be used.
Get:1 https://apt.mopidy.com buster/non-free amd64 libspotify12 amd64 12.1.51-1 [1145 kB]
Get:2 https://apt.mopidy.com buster/non-free amd64 libspotify-dev amd64 12.1.51-1 [464 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1610 kB in 4s (430 kB/s)
Selecting previously unselected package libspotify12.
(Reading database ... 29102 files and directories currently installed.)
Preparing to unpack .../libspotify12_12.1.51-1_amd64.deb ...
Unpacking libspotify12 (12.1.51-1) ...
Selecting previously unselected package libspotify-dev.
Preparing to unpack .../libspotify-dev_12.1.51-1_amd64.deb ...
Unpacking libspotify-dev (12.1.51-1) ...
Setting up libspotify12 (12.1.51-1) ...
Setting up libspotify-dev (12.1.51-1) ...
```

@footy42 how are you running your build? Perhaps you had network connectivity issues during the build? Have you tried again since? Make sure you use the `--no-cache` flag to pull everything from remote.

**Comment by jaedb** [comment]
Hmm nope scratch that. I can build successfully, however cannot play any Spotify tracks (via `Mopidy-Spotify`) due to it missing:
```
INFO     2022-01-29 09:18:56,031 [7:IrisFrontend-9] mopidy_iris.core,
  Disabled extension spotify: Dependency The 'pyspotify>=2.0.5' distribution was not found and is required by the application not found
```
This has been resolved by using `apt` to install `Mopidy-Spotify`, so it can handle any system dependencies.

**Comment by jojo141185** [comment]
@jaedb I also came to the same conclusion. that was one of the reasons why we had to make adjustments to the Dockerfile.
There seems to be a problem with mopidy-spotify's pip package related to the python version in debian buster. Based on debian 11 bullseye (slim) image it seems to work.

**Comment by kingosticks** [comment]
As per Mopidy-Spotify docs, when from pip (source) you must manually install the non-python dependencies and since libspotify is non-free (and therefore unavailable in Debian repos) you must install it from apt.mopidy.com. So since you are doing that, you might as well just install mopidy-spotify itself from apt.mopidy.com and let it take care of all dependencies for you.

I'm unaware of any problem with Mopidy-Spotify's pip package that would make it incompatible with Buster. We still support Buster. If you could file a bug report with specifics that would be helpful.

**Comment by jaedb** [comment]
@kingosticks totally; now building the image with `apt install mopidy-spotify` resolves the issue 🎉
