### ISSUE TITLE
EXTINF in m3u playlist

### ISSUE THREAD

**Issue by jaedb** [jaedb/Iris#8]
_From @mczerski on October 16, 2016 20:24_

when I create playlist like this:
# EXTINF:1,MultiRoom

rtsp://osmc.local:5004/test

and then open the playlist in spotmop, the name of the track is the uri not the name from the EXTINF directive. In moped ui this playlist is displayed correctly.

_Copied from original issue: jaedb/spotmop#154_

**Comment by jaedb** [comment]
_From @mczerski on October 24, 2016 11:55_

ok, I thought that parsing m3u playlist is done by mopidy core. it would suffice to just show the url but this is also sometimes fail. sometimes the url is showed and sometimes there is nothing showed.

**Comment by jaedb** [comment]
@mczerski, can you please send me the relevant part of your m3u playlist? I'm just trying to isolate whether the issue is Iris not showing the info, or Mopidy not providing it.

**Comment by mczerski** [comment]
`#EXTINF:1,MultiRoom
rtsp://livingroom-osmc.local:5004/test`

**Comment by jaedb** [comment]
The issue is that when requesting the current track info from Mopidy (eg `playback.current_tl_track`), it returns the rendered track information. I believe Mopidy gets this from the backend provider related to the URI.

However, when requesting the track information from a playlist, it doesn't perform a backend lookup. It just reads the `m3u` file and respects whatever values are set there (eg your `MultiRoom` string). This is why you are experiencing a discrepancy.

With this in mind, I believe the issue is related to Mopidy (or more specifically, the m3u backend) as that is what is providing us the variation in titles.

Moped must be reading the playlist track information and not using the `playback.current_tl_track` functionality. Iris does use this.

**Comment by Yadro** [comment]
It seems this issue related to iris..

I can demonstrate it:
_Radio_M.m3u_
```
#EXTM3U

#EXTINF:1,Ambient - UK2
http://uk2.internet-radio.com:31491/

#EXTINF:2,Echo Msk - Sample title
http://ice912.echo.msk.ru:9120/24.aac
```
And this is request and response about this playlist
![image](https://user-images.githubusercontent.com/3994873/47621131-46dc6080-db04-11e8-81fc-41e67f6563b0.png)

![image](https://user-images.githubusercontent.com/3994873/47621145-8dca5600-db04-11e8-9b32-b51b146e2a75.png)

As you can see Iris receive this information. But it render another.
It would be greate to show information from m3u in playlist. (I'm not talking about current playing track)
