### ISSUE TITLE
Iris & snapcast - no web browser sound

### ISSUE THREAD

**Issue by chlowden** [jaedb/Iris#805]
Hello
I am struggling to understand why on my iphone 6s, I cannot hear the snapcast delivery. I have tried Firefox, Edge, Chrome & Safari but all are the same. I cannot find anything in the OS to manage the sound. The Iris pages work fine. I don't have any sound issues on any other websites.

On my android phone, everything works fine. 
Any thoughts are most welcome.
Thank you

**Comment by jaedb** [comment]
It looks like you've filed an invalid bug report ticket. Please follow the [steps provided](https://github.com/jaedb/Iris/issues/new/choose).
