### ISSUE TITLE
Suggestion: separate various album types

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#81]
While viewing all albums of some artists on regular Spotify, I can see if the album is a regular album, a signle, an antology or whatever. I don't know if this is somehow indicated in Iris, but my screenreader can't tell. Could you please for example for example separate those albums into categories and precede every category by a heading? Or something similar even more clever?
Thanks.

**Comment by jaedb** [comment]
Related to #33

**Comment by vojtapolasek** [comment]
Hi, I am sorry, do I understand it right that this is going to be fixed in future? Or is it fixed? I canẗ see any change so far and I am a bit confused about that commit which closed this issue.

**Comment by jaedb** [comment]
In the album view, at the top the title structure is now `{source} {type}`. This is based on the `album_type` property of the album (currently only provided by Spotify). So, a Spotify _Single_ will show as _Spotify Single_.

The album type is not available for any other source types at this time, so this will only affect Spotify albums.

**Comment by vojtapolasek** [comment]
I can't see it in the latest 2.13.3 version of Iris. For example, I open
this artist (spotify:artist:0I8nAaq5bLnTm3aEvr8rIB) and I go through
list of his albums. All I can see with my screenreader is album name
which can be clicked and artist name represented as link. There isn't
anything else. When I open some album
(spotify:album:6TPAZBSnM7edgaRFg4u3X0) I can see:
text "Spotify album"
heading with album name
Artist's name, date, number of tracks / playing time
The there are buttons "Play", "Add to library", and a button with no
description which opens a context menu.
Then there follows a list of songs.
Am I missing anything?
