### ISSUE TITLE
Custom local artist library URI ignored when force-refreshing artist library

### ISSUE THREAD

**Issue by sulph68** [jaedb/Iris#810]
Hi

I am trying to get the Artist library to pickup from the ID3 tag of artist using the Advanced URI.
The URI i am using is
local:directory?type=artist

however, it doesn't seem to pick up correctly and continues to only refresh based on albumartist tag.
Is there something special that needs to be done? how would i debug this?

Thanks lots

**Comment by sulph68** [comment]
After some digging, i found and fixed the bug some what. it seems that the "refresh" icons does not pick up the advanced URI settings defined. As i only needed the artists to be found, i removed a few of the role=albumartist uris. This allowed it to pick up the artist names as is. This is a rough patch however. a more complete fix is to have the refresh button pick up the advanced URI settings as defined within the settings panel.

**Comment by jaedb** [comment]
@sulph68 Please make sure any of your future tickets use the provided issue templates.

**Comment by 0n3man** [comment]
[sulph68](https://github.com/sulph68) can you provide details on what you did as a work around as I have this same issue and I'm trying to get the artist to show in the interface.  Thanks

**Comment by sulph68** [comment]
hi @on3man,

It seems that Iris uses the ID3 tag "album artist", as the filter for the artist. it just wasn't possible for me to go change all my tags. So YMMV.

What i did was that i made edits in the app.js file as well as the app.min.js. the former really just to test but the latter is the one that is usually loaded.

In both cases, the general steps are to look for 
1) the _library_artists_uri_ and change that to _local:directory?type=artist_ (line 180471)
2) look for the artists filter and change that to only _type=artist_ (line 177855)

in the app.min.js case, it was more tricky to edit but it works.
Once this is done, clear all the caches for the page and do a reload. You should then see all your artists listed as you prefer.

Hope that works for you too!

**Comment by 0n3man** [comment]
thanks

**Comment by 0n3man** [comment]
FYI - I only needed to change item 1 in both of the files mentioned.

**Comment by sulph68** [comment]
sounds great! hope a fix will get rolled in officially soon though! ;-)
