### ISSUE TITLE
Iris does not open on firefox >=96

### ISSUE THREAD

**Issue by grimpy** [jaedb/Iris#811]
### Iris version

3.61.1

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Other

### What happened?

Iris does not load, I see a short flash of the UI and then the screen turns black.
I tried this on a fresh firefox session

### Logs

```shell
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
iris
Service worker registered iris:120:13
[react-ga] ReactGA.initialize must be called first or GoogleAnalytics should be loaded manually 2 app.min.js:24:72823
TypeError: history.push is not a function
    fb http://localhost:6680/iris/app.min.js?v=1637477794:128
    is http://localhost:6680/iris/app.min.js?v=1637477794:95
    bc http://localhost:6680/iris/app.min.js?v=1637477794:95
    unstable_runWithPriority http://localhost:6680/iris/app.min.js?v=1637477794:103
    Hi http://localhost:6680/iris/app.min.js?v=1637477794:95
    hc http://localhost:6680/iris/app.min.js?v=1637477794:95
    mc http://localhost:6680/iris/app.min.js?v=1637477794:95
    z http://localhost:6680/iris/app.min.js?v=1637477794:103
    onmessage http://localhost:6680/iris/app.min.js?v=1637477794:103
app.min.js:128:249569
Uncaught TypeError: history.push is not a function
    fb http://localhost:6680/iris/app.min.js?v=1637477794:128
    is http://localhost:6680/iris/app.min.js?v=1637477794:95
    bc http://localhost:6680/iris/app.min.js?v=1637477794:95
    unstable_runWithPriority http://localhost:6680/iris/app.min.js?v=1637477794:103
    Hi http://localhost:6680/iris/app.min.js?v=1637477794:95
    hc http://localhost:6680/iris/app.min.js?v=1637477794:95
    mc http://localhost:6680/iris/app.min.js?v=1637477794:95
    z http://localhost:6680/iris/app.min.js?v=1637477794:103
    onmessage http://localhost:6680/iris/app.min.js?v=1637477794:103
app.min.js:128:635133
Some cookies are misusing the recommended “SameSite“ attribute 2
```

**Comment by grimpy** [comment]
I'm not sure anymore if it's a firefox issue or some other change i just tried it with version 95 and 94 and it seems to have the same behaviour

**Comment by jaedb** [comment]
Have you tried clearing your browser cache to rule data persistence out of the issue? Also, are you inserting any [preconfiguration](https://github.com/jaedb/Iris/wiki/Advanced#preconfiguration) arguments into the URL?

**Comment by jaedb** [comment]
Also, can you please enable [debug mode](https://github.com/jaedb/Iris/wiki/Advanced#debugging) to get more useful error logs?

**Comment by jaedb** [comment]
Sure is, just use `.../iris/?test_mode=1` to enable Test (Debug) mode.

**Comment by grimpy** [comment]
Hmmm, I just tried this when using this option I get redirected to the initial setup page (http://localhost:6680/iris/initial-setup ) and everything works afterwards.

This made me try clearing browser cache again and directly navigate to http://localhost:6680/iris/initial-setup  which showed a flash of the page and then turned black, with same error logs as before. I'm not sure how I can reproduce this with debug/test mode enabled though.

**Comment by jaedb** [comment]
You can _append_ the `test_mode=1` to any URL to apply Debug mode immediately. Remember to add a ? or & depending on it's position amongst the other url parameters.
So try the url that has the error and add `&test_mode=1` on the end of it.

**Comment by grimpy** [comment]
Yes that's what I did so when I use the test_mode argument I can't reproduce the bug and it redirects to the initial-setup page (as it supposed to I guess)

**Comment by jaedb** [comment]
I believe this is a Service Worker caching issue (note: this is a bit different to the standard browser cache). By using `localhost` your browser will install the Iris service worker. This is the same for users who have non-`localhost` setup but are using SSL. This is great for mobile devices and offline availability, however it requires a bit of effort to force reloading of the latest code.

Switching on `test_mode` will use the non-minified JS bundle, so is using a new file that has not yet been cached by the Service Worker.

Do you think that sounds plausible? And are you up and running now?

**Comment by grimpy** [comment]
I don't think that's the problem cause I tried in a clean empty Firefox
profile I don't think those share any caching...

I am up an running as mentioned in my previous comment by skipping the
initial setup
