### ISSUE TITLE
Latest Release 3.62.0 Not Pushed to Dockerhub

### ISSUE THREAD

**Issue by DecWebb** [jaedb/Iris#817]
### Iris version

3.62.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [X] Other

### Browser(s) affected

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Other

### What happened?

The latest release of 3.62.0 is not available on dockerhub.
https://hub.docker.com/r/jaedb/iris/tags
last update was 4 months ago

I also dont think its available on ghcr.io either
I tried pulling ghcr.io/jaedb/iris:3.62.0 the response was:
Head "https://ghcr.io/v2/jaedb/iris/manifests/3.62.0": denied

I am not experienced with building and pushing docker images, so not sure how to fix this issue.

Looking in the github actions, this could be the issue:
https://github.com/jaedb/Iris/runs/5476550657#step:13:100

### Logs

```shell
time="2022-03-09T07:32:34Z" level=warning msg="No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load"
```

**Comment by jaedb** [comment]
This looks to be an issue with the GitHub action... despite it succeeding, the images are indeed not published.

**Comment by jaedb** [comment]
Resolved now
