### ISSUE TITLE
snapcast works, but shows as "disconnected" and can't be controlled

### ISSUE THREAD

**Issue by jennussbaum** [jaedb/Iris#821]
The Iris interface shows Snapcast as "disconnected", and I am unable to control Snap through Iris. Disabling and re-enabling it has no effect. However, Iris does play through snapserver: playing music sends audio to the snapserver, and the audio plays on the connected snapclients. Furthermore, Snapweb, the built-in snapserver controller, works fine through port 1780 on the same box: I see all the connected snapclients and can individually adjust their sound while audio is playing through Iris. 
If, in Iris, I go to Debug, enter Test Mode, enable the debug overlay, and send the default `{"method":"Server.GetStatus"}` message to Snapcast, the request enters the load queue, does nothing for some number of seconds, and eventually pops up a "Could not debug Request timed out" alert.
I'm using snapserver v0.26.0 and Iris 3.62.0 on Debian (running on the same machine). Everything had been working fine until recently, and I'm not aware of any changes that might have affected this situation. I have restarted snapserver, Mopidy, and eventually the machine itself. I looked at the old Issues and didn't see anything related to this. Thank you for any suggestions.

**Comment by jaedb** [comment]
You have not submitted an issue using the required templates, so are missing crucial information. I would suggest you verify your host and port configurations are correct and restart all servers.

In any case, this seems more like a **question** so should really be directed to the [Mopidy Discourse](https://discourse.mopidy.com/) forum.
