### ISSUE TITLE
Snapcast source selection in app cut off

### ISSUE THREAD

**Issue by psistorm** [jaedb/Iris#827]
### Iris version

3.62.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [X] Android
- [ ] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

I'm using Iris with multiple snapcast destinations and multiple sources. The topmost destination (in the fold up menu) in the mobile view is only capable of showing 2 sources (of at least 4 at the moment), the rest of the sources is cut off. I can't scroll them or similar. It makes switching sources quite a bit complicated especially regarding the WAF :)

Couldn't test it with different devices than Android. Probably also happening for others.

![70f992aa-d160-4490-9ba6-578a49e98d43](https://user-images.githubusercontent.com/401902/162565278-88a21123-0b47-43fb-99f7-2c3981688109.jpg)

**Comment by jaedb** [comment]
Will be included in the next release
