### ISSUE TITLE
UX consideration, delete from queue using mouseover and the 'delete'-button

### ISSUE THREAD

**Issue by Skeen** [jaedb/Iris#832]
### Problem to solve

Hi,

I was cleaning up my playlist queue at: `/iris/queue`.

I found an entity I wanted to remove, and found myself mousing over the entity before pressing the `delete` button on the keyboard, upon which nothing happened.

I did not consider what I was doing, it was just what my mind came up with on autopilot.

I am not a UX designer, and I do not know if the feature is worth implementing, I just thought I'd shared what happened and open a ticket for discussion.

### Proposed solution

Support deleting items by mousing over and clicking the 'delete' button.

**Comment by jaedb** [comment]
Removing items from the play queue already supports the `Delete` keyboard shortcut. However you first need to _click_ to select the item(s) you wish to delete. This selection UX is in place for all track lists (but naturally you cannot delete in all circumstances, ie someone else's playlist).

**Comment by Skeen** [comment]
Hi @jaedb.

Sounds good, we can close the issue then, I just wanted to let you know of my experience.
