### ISSUE TITLE
Rebuild Docker image on Dockerhub to get it to use Mopidy 3.3.0

### ISSUE THREAD

**Issue by PureTryOut** [jaedb/Iris#839]
### Problem to solve

Mopidy 3.3.0 has been out for a while but the Docker image on Dockerhub still uses Mopidy 3.2.0.

```
Disabled extension mpd: Mopidy>=3.3.0 required, but found Mopidy 3.2.0 at /usr/lib/python3/dist-packages
```

### Proposed solution

Rebuild the image so it pulls in Mopidy 3.3.0 from the Mopidy repos.

**Comment by kingosticks** [comment]
Note that Mopidy v3.3.0 was released but is not yet available from APT. I can ask for that to be addressed.

**Comment by jaedb** [comment]
@kingosticks please advise when this is ready and I can rebuild the Docker image to include Mopidy 3.3. Cheers!

**Comment by kingosticks** [comment]
I think it should be available now. Let us know if not.
