### ISSUE TITLE
Plaied songs disappear from queue

### ISSUE THREAD

**Issue by vojtapolasek** [jaedb/Iris#84]
I have recently upgraded to the latest version 2.13.3. I found out that radios for artists work, that's great. But now when I  add some songs to the queue, they disapper after being plaied once. This didn't happen in previous version. Is this wanted? Is this somehow configurable? Thanks.

**Comment by jaedb** [comment]
Please read the [Mopidy documentation](https://docs.mopidy.com/en/latest/api/core/?highlight=consume%20mode#mopidy.core.TracklistController.get_consume), and again, please refrain from posting issues without reading [guidelines for lodging issues](https://github.com/jaedb/Iris/wiki/Logging-an-issue).

**Comment by vojtapolasek** [comment]
I looked in the source code of core.py and I think I can see the problem.
In start_radio function, you wrote:
self.core.tracklist.set_consume( True )
But in stop_radio function you don't set this to False.
