### ISSUE TITLE
Playback control keeps "playing" after queue is done

### ISSUE THREAD

**Issue by PureTryOut** [jaedb/Iris#840]
### Iris version

3.62.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [X] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

When the queue of tracks to play is done, playback control (the slider at the bottom of the page and play/pause/stop button) doesn't seem to get the message and keeps "playing" forever. The current position keeps going up and when a song is for example 3:35 long, it doesn't mind going to for example 4:01 without ever realizing it should've finished.

![Screenshot_20220517_144448](https://user-images.githubusercontent.com/1565836/168813774-9b0d35b7-2f76-4be9-8f7b-edd44c8e520a.jpg)

**Comment by jaedb** [comment]
Are you using Mopidy with Snapcast?

**Comment by PureTryOut** [comment]
I am now but wasn't at the time of reporting the issue. It still happens though.

**Comment by WallyDW** [comment]
I had same issue when using a filesink, but the tcpclientsink solves it.

**Comment by jaedb** [comment]
This appears to be an issue with fifo outputs, and is wholly related to Mopidy (ie nothing to do with the Iris frontend). The best course of action is responding on the Mopidy repo, and potentially this related issue: https://github.com/mopidy/mopidy/issues/1566
