### ISSUE TITLE
config params  snapcast_enabled and  snapcast_host not working

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#848]
### Iris version

3.63.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

setting snapcast_enabled and  snapcast_host in the mopidy config is not working, in the iris interface in settings->services->snapcast enabled is still unchecked and host is localhsot

**Comment by jaedb** [comment]
This is deprecated in favour of the new _Share Configuration_ feature. This allows you to set client-side configuration values and push them to the common Mopidy server for anyone else to import at their leisure.

I have now removed the _Restore defaults_ values from the UI to avoid confusion.

**Comment by mczerski** [comment]
:( configuring iris from web browser is tedious and ability to set config values in mopidy.conf is much less time consuming. I have 5 players running iris, configurig 5 of them for three clients is 5x3=15 instead of once in common mopidy.conf. :( once again

**Comment by curiousercreative** [comment]
FYI, [this wiki](https://github.com/jaedb/Iris/wiki/Getting-started#configuration) still documents the old and unsupported snapcast configuration

**Comment by daredoes** [comment]
@jaedb I was thinking on this. Could we add a button to the initial setup modal for a new client that includes an "Import Server Settings" button?
