### ISSUE TITLE
Current playtime and bar is related to playlist, not song

### ISSUE THREAD

**Issue by WallyDW** [jaedb/Iris#849]
### Iris version

3.63.0

### Operating system(s) affected

- [X] Windows
- [ ] MacOS
- [ ] iOS
- [X] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [X] Chrome
- [X] Edge
- [X] Other

### What happened?

The current playtime seems to count for an entire playlist an not the current song.

Add 3 songs to a playlist
Set repeat to on (Not required, but shows an extra side of the bug)
If you can order the songs by duration with the shortest first and the longest last (Not required but shows the bug better)
jump to the second and start playing

The Now playing will now show the current playtime, a bar and the length of the song.
When the current playtime reach the value of the length of the song, the song will change, but the bar and counter will not be reset.
When the last song is reached, then the counter and bar will be reset if repeat is not on.
If repeat is on then the counter and bar will continue until it reach the start song (song 2) again and then they will be reset.

Either the song length should be changed to playlist length or the counter and bar should relate to the current song.

An extra set of  features could be to provide both solutions with a switch and maybe also add a view that shows remaining playtime of the current song and a view for remaining playtime of the playlist.

### Logs

```shell
No relatable output
```

**Comment by jaedb** [comment]
I have been trying to replicate this issue but have had no luck. Are you able to take a screen recording of this in action?

**Comment by WallyDW** [comment]
Sadly not.
I had too many issues with Mopidy (not Iris) and have switched to a MPD setup instead.

**Comment by jaedb** [comment]
Closing this issue; it cannot be replicated and no further information has been provided to aid in discovery.
