### ISSUE TITLE
Use resource URLs relative to the current path

### ISSUE THREAD

**Issue by sabvente** [jaedb/Iris#85]
When using nginx reverse proxy to use Iris on port 80 with the following rewrite rule, the resource urls are broken, because they are relative to the document root.
`rewrite /(.*) /iris/$1 break;`

I suggest to use URLs relative to the current path to make reverse proxying easier.
e.g. instead of:
`/iris/app.min.js`
use:
`app.min.js`

**Comment by jaedb** [comment]
You might find your rewrite rules are not working because they clash with the rules in [`mopidy_iris/static/.htaccess`](https://github.com/jaedb/Iris/blob/master/mopidy_iris/static/.htaccess).

The `/iris` component of the URL is necessary for making Iris work with both Apache and Tornado web servers.

Can you please provide more information about your setup and your proxy rules?

**Comment by sabvente** [comment]
I'm running nginx on port 80. Mopidy is configured to use port 6680. My current nginx server block file:
```nginx
server {
        root /var/www/html;
        server_name localhost;

        location / {
                proxy_pass http://localhost:6680;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                rewrite /mopidy/(.*) /mopidy/$1 break;
                rewrite /(.*) /iris/$1 break;
                proxy_redirect off;
        }
}
```
Using this, the `http://localhost:80/index.html` works fine, but the css/js/asset files couldn't be loaded. The browser tries to request them from `http://localhost:80/iris/app.min.js` instead of `http://localhost:80/app.min.js` so the result is 404.


In the meantime, I managed to get it working by adding the following rule:
```nginx
rewrite /iris/(.*) /iris/$1 break;
```
Now Iris running nicely on `http://localhost:80`. From my perspective, the issue is resolved. I don't know if anyone has similiar problem, so it's up to you to close this @jaedb.

**Comment by jaedb** [comment]
@sabvente As mentioned, it looks like your setup wasn't retaining `/iris` as the root directory. Glad to hear you managed to get it working.
