### ISSUE TITLE
Dragging sources priority bugs left nav bar

### ISSUE THREAD

**Issue by Nightenom** [jaedb/Iris#850]
### Iris version

3.63 to 3.64.0

### Operating system(s) affected

- [X] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [ ] Linux
- [ ] Other

### Browser(s) affected

- [x] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

Dragging/sorting `sources priority` in settings permanently changes the left nav bar to quick song actions.
Reproducibility 100%, reloading the page fixes it.

**Comment by WallyDW** [comment]
Add firefox to this too

**Comment by jaedb** [comment]
Due to a conflict between `react-dnd` and `react-sortable`. Can be resolved by upgrading `SourcesPriority` component to use `react-dnd`.

**Comment by jaedb** [comment]
Removing sources priority entirely; this is a buggy logic and I would rather have fewer features working really well then loads of features that don't. `Commands` component upgraded to `react-dnd` in ae3b831aa4a58d05fcb4a6b1b8b8dcfc0ba872dd
