### ISSUE TITLE
Issue launching with Docker Compose

### ISSUE THREAD

**Issue by joecaraccio** [jaedb/Iris#852]
### Iris version

Master

### Operating system(s) affected

- [X] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [ ] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Other

### What happened?

When following the simple steps with Docker Compose on windows. I get:

ERROR: for iris_snapserver_1  Cannot start service snapserver: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/a7d214e34bed6e55247598ee674c11c2005f64202ba71ba07be7321d6c9c8880" to rootfs at "/etc/snapserver.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

I am running Docker_compose from a Ubuntu WSL$ window on linux. Wondering if I shouldn't be doing that

**Comment by jaedb** [comment]
It is hard to say without seeing the `docker-compose.yml` file you are using, but it seems all the information you need is in that error log: `not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`. My guess is that `/etc/snapserver.conf` does not exist.

**Comment by jaedb** [comment]
Stale. Closing.
