### ISSUE TITLE
Hiding discover section in web ui

### ISSUE THREAD

**Issue by Platypuschan** [jaedb/Iris#856]
### Problem to solve

Since i´m not using Spotify and miss-clicking in the web-ui gives me errors all the time, i just wanted to know: is there a way  to hide the discover section in the sidebar?
![image](https://user-images.githubusercontent.com/8338806/182658737-7ee465b1-8187-4892-97ec-1c6cf81d2c1f.png)

### Proposed solution

Just a small Checkbox in the Spotify options would be fine.

**Comment by jotak** [comment]
I'm suggesting a patch, cf #859 
I'm in the same situation as you @Platypuschan , not using spotify, hence seeing errors systematically in these menus.

I'm just wondering if it's correct to assume that a missing spotify token makes these discover entries unneeded, or if there should be a distinction between "no spotify token" and "spotify plugin not installed" ?
cc @jaedb

**Comment by chiefy** [comment]
I'd really love it if there was an option to completely disable Spotify integrations.
