### ISSUE TITLE
Some keyboard shortcuts not working

### ISSUE THREAD

**Issue by andy-lang** [jaedb/Iris#862]
### Iris version

3.64.1

### Operating system(s) affected

- [X] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [ ] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

I noted the [Keyboard Shortcuts](https://github.com/jaedb/Iris/wiki/Features#keyboard-shortcuts) section of the wiki, but have found that only some of the keyboard shortcuts work or have expected outcomes. I have tested on both Firefox and Chrome.

- `space` or `p` = toggle play/pause ✅
- `s` = Stop ✅
  - this one had some odd behaviour, I ran the step and worked fine, but on resuming the song I had queued kept playing but disappeared from the queue. I would have expected the song to stay on the queue until it finished (similar to play/pause)
- `,` = previous track ✅
- `.` = next track ✅
- `b` = Seek backwards 30 seconds ❌ - did not appear to work at all
- `f` = Seek forwards 30 seconds ✅
- `=` or `+` = Volume up to 5% ✅ and ❌
  - `=` worked, `+` did not
- `-` = Volume down by 5% ✅
- `0` = Mute ✅
- `enter` = Play currently selected tracks ✅
- `delete` = Remove currently selected tracks ✅
- `1` = Now playing ❌
- `2` = Search (input field will be auto-selected) ❌
- `3` = Kiosk mode ❌

**Comment by jaedb** [comment]
Nice work, thanks for highlighting this! I've removed the outdated wiki references and updated the in-app hotkeys docs. Next release will restore the `1`, `2` and `3` hotkeys.
