### ISSUE TITLE
Experiencing WebSocketClosedException with Iris behind nginx reverse proxy

### ISSUE THREAD

**Issue by scottashipp** [jaedb/Iris#868]
### Iris version

3.64.1 1659230018

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [X] Chrome
- [ ] Edge
- [X] Other

### What happened?

Hi everyone, thanks for reading. Really appreciate the help. So I have Iris up and running on my local network and it is working perfectly using a URL that includes its port e.g. 192.168.XXX.XXX:6680 or hostname:6680. To simplify things for my friends, I thought it would be nice if they could access Iris from their browser when on the network, and not have to remember to add :6680 (e.g. they can just visit http://hostname) so I added an nginx reverse proxy which listens on port 80 and forwards to Iris on port 6680.

This nginx configuration is similar to the one in the wiki but without SSL. It is also nearly identical to the many that are posted in other issues here, e.g. https://github.com/jaedb/Iris/issues/493

The problem I experience, though, is that when visiting just http://hostname I can see in Web Dev tools that most or all JS calls are erroring out, and I get the following trace in the Mopidy logs (see logs section).

I suspected Mopidy's CSRF but I have set `csrf_enabled = false` in mopidy.conf.

The issue seems related to websockets + nginx but I cannot figure out why that would be if there are plenty of other Iris users with nginx (or another) reverse proxy, and who have not configured a specific proxy setting for the websocket port? Maybe my logic is wrong. If so, is there a way to find out what websocket port Iris is using so I can configure that? And if that is required now, the wiki would probably need updated to incorporate it?

Thanks so much for the help

### Logs

```shell
ERROR    [HttpServer] tornado.application Uncaught exception GET /iris/ws/ (127.0.0.1)
 HTTPServerRequest(protocol='http', host='127.0.0.1:6680', method='GET', uri='/iris/ws/', version='HTTP/1.0', remote_ip='127.0.0.1')
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 867, in write_message
     fut = self._write_frame(True, opcode, message, flags=flags)
   File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 846, in _write_frame
     return self.stream.write(frame)
   File "/usr/lib/python3/dist-packages/tornado/iostream.py", line 570, in write
     self._check_closed()
   File "/usr/lib/python3/dist-packages/tornado/iostream.py", line 1112, in _check_closed
     raise StreamClosedError(real_error=self.error)
 tornado.iostream.StreamClosedError: Stream is closed
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 546, in _run_callback
     result = callback(*args, **kwargs)
   File "/usr/local/lib/python3.8/dist-packages/mopidy_iris/handlers.py", line 48, in open
     iris.add_connection(connection=self, client=client)
   File "/usr/local/lib/python3.8/dist-packages/mopidy_iris/core.py", line 282, in add_connection
     self.broadcast(
   File "/usr/local/lib/python3.8/dist-packages/mopidy_iris/core.py", line 236, in broadcast
     connection["connection"].write_message(json_encode(message))
   File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 262, in write_message
     return self.ws_connection.write_message(message, binary=binary)
   File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 869, in write_message
     raise WebSocketClosedError()
 tornado.websocket.WebSocketClosedError
```

**Comment by scottashipp** [comment]
Hmmm ... ok the following has resolved the issue for me:

```
server {
  listen       80;
  server_name  _;

  proxy_http_version 1.1;
  proxy_read_timeout 600s;
  
  location = / {
  	return 301 /iris/;
  }

  location / {
      proxy_pass http://127.0.0.1:6680/;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
  }

}
```

**Comment by lblabr** [comment]
i have:

server {
        listen 8091;
        # Set to "_" to listen to all domains
        server_name  _;

        access_log /var/log/nginx/access_8091.log;
        error_log /var/log/nginx/error_8091.log debug;

        proxy_http_version 1.1;
        proxy_read_timeout 600s;

        location = / {
                return 301 /iris/;
        }

        location / {
                proxy_pass http://127.0.0.1:6680/;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;
        }
}

**Comment by kingosticks** [comment]
> I suspected Mopidy's CSRF but I have set csrf_enabled = false in mopidy.conf.

Unlike the OP, you must not have done this. But I suggest you don't disable that security feature because

> This config should only be disabled if you understand the security implications and require the HTTP server’s old behaviour.

Instead, configure Mopidy to allow requests coming from your nginx server using [http/allowed_origins](https://docs.mopidy.com/en/latest/ext/http/#confval-http-allowed_origins). e.g.
```
allowed_origins = 10.100.10.181:8091
```
