### ISSUE TITLE
Album art in Browse overlaid with loading/spinning animation.

### ISSUE THREAD

**Issue by 01tot10** [jaedb/Iris#882]
### Iris version

3.66.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [X] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

When browsing albums provided by a backend, the album arts are overlaid with loading/spinning animation even though the artworks seem to be loaded correctly. The behavior seems to be the same for different backends (tested with Mopidy-Local and Mopidy-Bandcamp), as well as different platforms / browsers (tested with Firefox/Linux and Chrome/Android). I have the feeling, although haven't confirmed this, that this wasn't the case some versions back. 

Here's an example using Browse -> Bandcamp -> Wishlist:
![Screenshot from 2023-01-21 19-57-17](https://user-images.githubusercontent.com/35490779/213880590-6a47963b-c20b-4ab4-a25a-d89077b42fda.png)

And here for Browse -> Mopidy-Local -> Albums:
![Screenshot from 2023-01-21 19-57-44](https://user-images.githubusercontent.com/35490779/213880601-e10ca868-101f-4750-91ce-2f14550c7722.png)

**Comment by 9acca9** [comment]
The same for me, please if you find a solution, share it.
Thanks!

**Comment by 01tot10** [comment]
Thanks a lot for taking the time to look into this! I upgraded my installation to `3.66.1`, but for some reason the ever rotating spinners are still there. I tried upgrading both via pip and manually via cloning the repo and following the instructions, but the end result is the same for both. Could there be something wrong with the patch, or am I maybe doing something wrong?

**Comment by 9acca9** [comment]
"I upgraded my installation to 3.66.1, but for some reason the ever rotating spinners are still there.", yep, the same for me.

**Comment by 01tot10** [comment]
Hey @jaedb! I can't re-open this issue due to not having privileges, but it seems like the previous attempt didn't fix the ever-rotating spinner. Just wanted to give a bump to this issue and see if you are aware of this!

Thanks a lot for your efforts!
