### ISSUE TITLE
Typo in sponsorship message

### ISSUE THREAD

**Issue by 2e0byo** [jaedb/Iris#884]
### Iris version

3.66.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [ ] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Other

### What happened?

There is a typo in the (english) funding message displayed when new instances open: s/ejoying/enjoying.

I'd submit a trivial PR but `grep -iR "full time"` finds nothing, so guessing it's loaded from elsewhere.

**Comment by jaedb** [comment]
I'm really not sure where you're seeing this. Can you please provide a screenshot?

**Comment by 2e0byo** [comment]
Sure, couldn't find the button earlier:

![2023-01-26-21:55:00-screenshot](https://user-images.githubusercontent.com/22841038/215186603-1ad53b33-2f89-4ed0-a463-6a3d11cb58b3.png)

**Comment by jaedb** [comment]
Thanks, fixed.
