### ISSUE TITLE
Can't upgrade via web interface

### ISSUE THREAD

**Issue by formfarbefabs** [jaedb/Iris#888]
### Iris version

3.63.0

### Operating system(s) affected

- [ ] Windows
- [X] MacOS
- [ ] iOS
- [ ] Android
- [ ] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Other

### What happened?

I want to upgrade to 3.66.1 via web interface, but there's only the upgrading spinner shown. Nothing happens, waiting for 1h ... What can i do?
![grafik](https://user-images.githubusercontent.com/125191839/218309506-afc1aceb-6501-4453-ab1c-3ffe365180d6.png)
![grafik](https://user-images.githubusercontent.com/125191839/218309518-e1a83681-6831-489f-9a18-f33aedde3b38.png)

**Comment by jaedb** [comment]
Can you please post the output of your Mopidy server log?

**Comment by formfarbefabs** [comment]
SD card crashed...

**Comment by formfarbefabs** [comment]
... can't get the log
