### ISSUE TITLE
Artist "Top Tracks" includes compilations

### ISSUE THREAD

**Issue by 9acca9** [jaedb/Iris#889]
### Iris version

3.66.1

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

When i make a Search, let's say "Marilyn Manson" i get this:

![Captura desde 2023-02-20 21-45-07](https://user-images.githubusercontent.com/25393371/220220391-01d28bb9-2bf7-45b6-b3e1-d21d327f053b.png)

I cant see the images but the names of the artist and the albums names are FINE!.
But, when i select the artist i see this in his albums:
![Captura desde 2023-02-20 21-45-18](https://user-images.githubusercontent.com/25393371/220220468-a7735861-d4bd-4f0d-a02d-3156267d8013.png)

Yep... that are not his albums, just compilations.
And this in his tracks:

![Captura desde 2023-02-20 21-44-57](https://user-images.githubusercontent.com/25393371/220220522-7badff3b-9283-446e-a840-0384c03d4093.png)

yep, those are his songs but are taking from incorrect albums. (if you look, those are compilation).

The wrong albums are compilations, and the songs are from there.

But, it is strange, because, as you see in the first image, when i make a search i get the correct albums in the "search section".

And of course that happens with all, not just with Marilyn Manson.
Well, if you need something tell me.
Thanks for all your work!

**Comment by jaedb** [comment]
What is the source provider you're using?

**Comment by 9acca9** [comment]
Im using the only extension i know is workign for Qobuz right now:
https://github.com/vitiko98/mopidy-qobuz

Thanks for looking.

**Comment by jaedb** [comment]
None of the Mopidy backends provide a "top tracks" endpoint or collection. Only the Spotify HTTP Api provides this.

As a result, "Top Tracks" for an artist from a Mopidy backend simply plucks the top 10 tracks from their tracks. In your case, this list of tracks includes all tracks from their compilations, which are going to be tracks from other artists.

Does this sound plausible? If so, this is an issue with Qobuz and you would be best to raise the issue on the [Mopidy-Qobuz](https://github.com/taschenb/mopidy-qobuz) repository.

**Comment by jaedb** [comment]
Please feel free to re-open this issue if it is indeed with Iris rather than the Qoobuz backend.
