### ISSUE TITLE
Iris page failed to load

### ISSUE THREAD

**Issue by mczerski** [jaedb/Iris#891]
### Iris version

3.64.1

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [X] Android
- [ ] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

Page failed to load. I dont know what caused that. Page loads fine when using incognito mode. I dont know how to debug it.
![Screenshot_20230326-152550](https://user-images.githubusercontent.com/2772080/227779010-cbb39964-8c8d-462b-95cd-3ba32927bdf8.png)

**Comment by jaedb** [comment]
Please follow the instructions on the Iris wiki on [debugging](https://github.com/jaedb/Iris/wiki/Advanced#debugging). In short, the first part is to enable [_test mode_](https://github.com/jaedb/Iris/wiki/Advanced#test-mode) so you can get more meaningful logs in your developer toolbar. This requires you to view from desktop, not from a mobile device.

Based on the screenshot, that suggests your browser is unable to load the Iris core files (app.js and app.css). What is your installation method (ie Docker, or `pip`), and have you made any changes/updates lately? What about loading the same URL on a different device?

**Comment by mczerski** [comment]
Dev tools od not an option, this happens only on Android. Opening Iris on the same device in incognito mode works. Also works on desktop. Iris is installed from the pip on nano pi arm sbc (armbian os). No changes and no updates lately. I tried removing cookies but i dont know if successfully because nothing changed. Yesterday i realised that Iris is working again and greets me with setup page (so cookies were deleted after all). Very wierd ...
