### ISSUE TITLE
gapless?

### ISSUE THREAD

**Issue by 9acca9** [jaedb/Iris#896]
### Problem to solve

Those disc that need to be playing without a single second of pause (between the songs) because with the pause between the songs is not the same.

### Proposed solution

Then with gapless they are played like a continue big song.

**Comment by jaedb** [comment]
As an audio-based issue, this is related to Mopidy server (not the user interface, Iris). Please open a ticket on the Mopidy repository.

Please note that some backends may be able to resolve this, and others may not. If you're using the new Spotify backend then I think this is something the team is already working on.
