### ISSUE TITLE
Cannot hear any music, only quiet static

### ISSUE THREAD

**Issue by ItsNiceCraft** [jaedb/Iris#898]
### Iris version

3.66.1

### Operating system(s) affected

- [X] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [ ] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [ ] Chrome
- [X] Edge
- [ ] Other

### What happened?

After scanning my media library and trying to play a song, nothing plays and only a quiet static sound is to be heard. I have tried multiple tracks, verified that they contain music by playing them locally, switched earphones and speakers and browsers. The browsers didn't seem to recognize that any sound was played, there was no indicator on the tab that it is playing music. However, after reloading the page, the static was gone until I clicked somewhere (the track was still "playing").

**Comment by PureTryOut** [comment]
Iris itself doesn't play the music, Mopidy does in the background. And that needs to be configured to output to something you can listen too, be that some online service or your PC's audio system. Thus Iris will never show an indicator on the tab that is playing music as it never will play music.

Not a bug with Iris.
