### ISSUE TITLE
Add instruction on how to update Iris

### ISSUE THREAD

**Issue by sarukuku** [jaedb/Iris#90]
I suggest that we add a section to the Readme that tells you how to update / upgrade Iris after you've installed it and new features / bug fixes have been released.

**Comment by jaedb** [comment]
Thanks for your suggestion. This has now been added to the Wiki: [Installation and upgrading](https://github.com/jaedb/Iris/wiki/Installation-and-upgrading)

**Comment by sarukuku** [comment]
Thanks!
