### ISSUE TITLE
Search "sort" breaks search persistently

### ISSUE THREAD

**Issue by curiousercreative** [jaedb/Iris#900]
### Iris version

3.66.1

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

1. On a "fresh" load of Iris (use an incognito window or the like to have fresh app state)
1. Perform a search ("HAIM" for example)
    AR/ER: search results load for all of the configured backends, yay!
1. Click the search sort and select "Name" from the dropdown.
1. Replace search term "HAIM" with "Beatles" and submit search
    AR: app crashes with error logged `w.filter is not a function`
1. Refresh browser window
    AR: app cannot load
1. manually navigate away from the search result by manipulating the address bar
    ER/AR: app loads
1. Navigate back to search and submit a new search
    AR: app crashes

**Comment by jaedb** [comment]
@curiousercreative is this still happening for you? I have been unable to replicate this issue.

**Comment by curiousercreative** [comment]
@jaedb I haven't noticed this lately and following my own repro steps I wasn't able to repro.
