### ISSUE TITLE
docker entrypoint should install request PIP_PACKAGES

### ISSUE THREAD

**Issue by curiousercreative** [jaedb/Iris#904]
### Iris version

3.67.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Other

### What happened?

When starting the mopidy iris container, env $PIP_PACKAGES are not installed with error "ERROR: Invalid requirement: 'package_name1 package_name2'

[This](https://github.com/jaedb/Iris/commit/dcbfce4f8b7ad0e9510fa2583aaee474ea149dcf#diff-4f5cabe26761257a4d685a6edc7a43e0fe0f78762f50eeb48530f2bd3b3ee7caR11) appears to be the cause of the regression. To workaround, I've simply run `docker compose exec -it mopidy python3 -m pip install --no-cache Mopidy-Subidy Mopidy-Bandcamp` (without quotes for the packages) after creating and running the container. After that, I restart it and everything's fine until the container is removed.

**Comment by joepaolicelli** [comment]
Also running in to this, it seems the added quotes cause pip to think the list of packages [here](https://github.com/jaedb/Iris/blob/master/docker-compose.example.yml#L16) is all one package, which causes the failure.
