### ISSUE TITLE
PayPal Donation link not working

### ISSUE THREAD

**Issue by curiousercreative** [jaedb/Iris#911]
### Iris version

master

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [ ] Android
- [ ] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Other

### What happened?

When clicking on the PayPal donate button on the repo readme, I'm presented with a PayPal error page "This organization can't accept donations right now."

**Comment by jaedb** [comment]
This is because PayPal no longer accept donations for not-for-profit accounts like mine. To accept this I have to have a paid PayPal account and be a registered charity.

For users who wish to support Iris, please see [GitHub Sponsors](https://github.com/sponsors/jaedb).
