### ISSUE TITLE
[solved, pls read comment] Iris (supposedly) starting but not reachable.

### ISSUE THREAD

**Issue by Cornflix244** [jaedb/Iris#934]
I have Mopidy and Iris installed on a Raspi zero W.
Iris is starting when starting the Mopidy service.
I can't reach it under http://localhost:6680/iris/ or http://hostname:6680/iris/ where I tried any possible IP as hostname.
I attached screenshots of my config output and the journalctl output.
![Screenshot_20231116_213317](https://github.com/jaedb/Iris/assets/70451196/af72889a-f186-43a6-a606-6bd969d451c2)
![Screenshot_20231116_213522](https://github.com/jaedb/Iris/assets/70451196/00745869-3abb-40e8-b897-f352a8d84247)

**Comment by Cornflix244** [comment]
Sooooooooooo...

I am sorry that I opened this issue ._.

The mistake was in my config. I didn't know that I had to specify my IP for the hostname. Maybe write that into the getting started guide.

**Comment by evelinwillow** [comment]
i love you
