### ISSUE TITLE
Can the frontend spotify login be avoided ?

### ISSUE THREAD

**Issue by crazyiop** [jaedb/Iris#95]
As my spotify username/password are already in the [spotify] section of mopidy's config file, why are they needed a second time in the frontend to have a full access to spotify ?

Can this be avoided and only rely on the login in the config file, even if it means expanding the mopidy-spotify capabilities ?

**Comment by jaedb** [comment]
**Short answer:** no.

**Long answer**
Spotify has different levels (and methods) of authentication. Each has different functions and limitations. I recommend reading the [Spotify Web API Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/).

Ultimately the `[spotify]` section of `mopidy.conf` uses the [_Client Credentials Flow_](https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow), which _"cannot be used to access or manage a user’s private data"_. This flow can therefore only provide the base-level functionality of browsing and playing music.

Private data includes the editing and creation of playlists, following or unfollowing playlists/artists/users and accessing the user's music library. 

To manage this private data and get the most out of _Iris_ we need to use the [_Authorization Code Flow_](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow).

**Comment by Informatic** [comment]
This is slightly related - right now `access_token` obtained in one session does not seem to be propagated to any other client. This requires every user to login to the same Spotify account on every device, which is kind of tedious... Copying and pasting contents of `localStorage['spotify']` from one browser session to another seems to work, so why don't we just pass it back and forth with Mopidy instance?

**Comment by jaedb** [comment]
Sharing a Spotify user's authorization credentials to all client connections is insecure, and as such is not supported by Iris. Think of the implications of having everyone else with user-level access of your Spotify account. This would allow anyone to alter your library and access information they shouldn't.

If you wanted to share authorization without giving another user your login credentials, you can instead use _Settings_ > _Share Authentication_. This allows you (as the authorized user) to share your authorization to specific individual clients, rather than to all clients.

**Comment by Informatic** [comment]
Why not just proxy everything via python to properly secure it then, to not reveal the authentication token?

**Comment by crazyiop** [comment]
That won't solve the security issues raised by @jaedb that I now get. The issues is not the token being "public", it is other people having full access to your spotify account and mess with it. Think of people used to have their own account on the spotify app, they may forgot/not realised they are not using theirs with Iris, and add a bunch of new album/playlist to someone else's library, even unintentionnaly. (that just happens here :)

Now that I get it, I'm actually glad my SO and I can have different spotify account connected on each device, each one having acces to it's own playlist and so on, to be played on the same player.

**Comment by Informatic** [comment]
Also, a way to share/store access_token by default sill would be a nice feature, as the only "destructive" options I can see are saved albums/tracks/playlists modifications, and in my case i really only use spotify account solely with mopidy.

@crazyiop not really, you can just allow only for GET requests, and most of functionality stays intact, without allowing really anything destructive.

**Comment by crazyiop** [comment]
Well in that case you won't be able to manage you're own library either, wich in your case is even worse as you only use your spotify account with mopidy... 

I still think you're point is valid, but with peoples having contradictory preference and use-case, I think the current state is the best compromise as most people would want the hability to manage the library.

**Comment by Informatic** [comment]
Also, another tiny question (I don't feel like making multiple issues related to general "security" here)

https://github.com/jaedb/Iris/blob/46c8288713a4860f6b39966c457bb11167a6a903/src/js/services/spotify/actions.js#L98
Is there any issue with issuing AJAX requests, or passing windows messages back and forth between https:// and http://? We really should have https forced over here. Maybe i'm paranoid, but i really trust people on my local network more than anyone behind my firewall.

**Comment by jaedb** [comment]
@Informatic this off-application reference is necessary to complete the authentication process. The URL starts with `//` instead of specifying the protocol. This means the request will inherit whatever protocol you're currently using.

If you choose to use HTTPS + WSS you need to configure a proxy. This is beyond the scope of _Iris_. See [Advanced](https://github.com/jaedb/Iris/wiki/Advanced) to get started.

**Comment by Informatic** [comment]
I understand how this works, really. My issue here is that it falls back to http:// on pretty much every instance of mopidy. Having mopidy on http:// in local network imo is not as big issue, as throwing access tokens around the internet.

**Comment by jaedb** [comment]
@Informatic Ah, yes I see what you're saying. Please open another issue for this and it can be looked at.

**Comment by jaedb** [comment]
Resolved as at 7717c95e7b3910f21bb30044647b819c854cd8e1
