### ISSUE TITLE
Failed to add some urls

### ISSUE THREAD

**Issue by philoukid** [jaedb/Iris#96]
It's my first project on raspberry pi 3b
Everything went fine but when I want to play a song I got a error message saying
"failed to add some urls"
On my spotify account, i see that NZ is set as my country but i'm from Canada.
Can this be the problem? I don't think I something wrong in the config.
My spotify account as been created with facebook. Is that can be the problem?
I love the frontend. Is the best I've found to use Spotify on my pi... Hope I can hear a song!
thanks

**Comment by jaedb** [comment]
Please provide more information - refer to [Logging an issue](https://github.com/jaedb/Iris/wiki/Logging-an-issue).

**Comment by nohumanbee** [comment]
Hi jaedb, 
I'm seeing a similar issue as Philoukid.
I'm using  Jessie Lite on a Raspberry Pi Zero W, with a fresh install using the Pimoroni installer script at https://get.pimoroni.com/spotipy.

I'm able to connect to Spotify via my premium account with my content visible in the UI; Playlists, Daily Recommend, etc. However, trying to play any content (Artist, Radio, Playlist, or even manually adding URL's from Spotifys Desktop App) results in the same error message "failed to add some url(s)"

I'm planning tonight to try looking at Pimoroni script to see if its a package version issue.

**Comment by nohumanbee** [comment]
Got it. Not a Iris issue more a interaction between Pimoroni script and Modidy. 

@philoukid hey take a look at - [http://forums.pimoroni.com/t/streaming-spotify-to-your-pi-failed-to-load-uri-s/4361/7](http://forums.pimoroni.com/t/streaming-spotify-to-your-pi-failed-to-load-uri-s/4361/7 ), looks like the Spotify section of the /etc/mopidy/mopidy.conf can become commented out. That is the cause of this error.

If like me you used FB log on you can set up a Device User Account within Spotify in the Set Device Password section for a username/pwd for Mopidy and Iris.

Cheers

**Comment by jaedb** [comment]
Thanks for investigating this @nohumanbee
