### ISSUE TITLE
Snapcast in gui not allowed

### ISSUE THREAD

**Issue by boris19** [jaedb/Iris#960]
### Content

hello, i am trying to set iris so that snapcast is always enabled and host is set to ip address and not localhost. i made a setting in mopidy.conf but it didn't help. if I change the country setting, it changes in spotify. can you please help me where the error could be?

**Comment by jaedb** [comment]
Hi @boris19, as a question this really belongs on the documented Discourse forum.

In essence, that isn't what the mopidy.conf options are for. You will need to export/share configuration and/or import it from the server.
