### ISSUE TITLE
Documentation clarification on Iris upgrade inside docker container

### ISSUE THREAD

**Issue by alanmilinovic** [jaedb/Iris#969]
### Problem to solve

There is no description how to perform an upgrade in the documentation when using installation via Docker.

### Proposed solution

Can you please elaborate how is the upgrade for Iris running inside docker possible? Ideally it could be added to the documentation for the future reference. I can do container pull, but not sure if that is the right way.

**Comment by alanmilinovic** [comment]
Any hint please? Is it a standard pull command sufficient or not?

**Comment by jaedb** [comment]
Can you try re-pulling the image from DockerHub? Assuming you haven't manually specified a version, recreating your stack should get the `:latest` [tag](https://hub.docker.com/r/jaedb/iris/tags) from DockerHub.

**Comment by alanmilinovic** [comment]
Yes I can do it. The question is only if it is the right way.

**Comment by jaedb** [comment]
This is the way. 

It is designed to work like any other docker image: to get an updated version you need to pull from the docker repository. The only time this won't work is if you've set an explicit version tag for your stack.

**Comment by alanmilinovic** [comment]
Ok, thanks, great!
