### ISSUE TITLE
[Request] Use local artwork

### ISSUE THREAD

**Issue by kabellrics** [jaedb/Iris#971]
Hello, I don't know if it's a Mopidy issue or an Iris issue, but it could be a good idea to let the users the possibility of picking local image files for the artist, album or even playlist artwork, or at least use the same file structure as Kodi.
Sorry for my english, it's not my native language.

**Comment by jaedb** [comment]
Thanks for reaching out! For general queries, please direct your question to the [Discourse website for Mopidy](https://discourse.mopidy.com).

Your question relates to the back-end platform, and it looks like there is a conversation thread you could dig into as a starting point. Please see: https://discourse.mopidy.com/t/prefer-local-covert-art-in-current-directory/5373
