### ISSUE TITLE
[Feature request] Detect default port from URL

### ISSUE THREAD

**Issue by FilipLigaarden** [jaedb/Iris#98]
Currently, if you change the port of mopidy web ui, you have to manually input the port in the configuration menu.
Is it possible to add an easy way to set default port?

**Comment by jaedb** [comment]
Related to #70 

Before we can get any information about the Mopidy server, we need to connect to the websocket (running on your defined port). We need to know the port before we can connect, so it's a chicken-and-egg situation.

It may be possible to detect the current port in use by the browser (eg http://myserver.local:**1234**/iris) and then use that as the default, however this will need to be tested to ensure it doesn't interfere with out-of-the-box functionality.

**Comment by Hugomm** [comment]
Is it possible to read the new port on mopidy.conf before connecting to the websocket?

**Comment by jaedb** [comment]
@Hugomm as above:
> Before we can get any information about the Mopidy server, we need to connect to the websocket (running on your defined port). We need to know the port before we can connect, so it's a chicken-and-egg situation.
