### ISSUE TITLE
Deselect the songs when added to queue

### ISSUE THREAD

**Issue by FilipLigaarden** [jaedb/Iris#99]
When selecting songs and adding the to queue you have to manually deselect them to prevent them from being added again when selecting other songs from the same playlist.
This can become confusing and hard to remember to do at times.
Again, great work, just some small QOL changes would perfect this extension.

**Comment by jaedb** [comment]
I guess this functionality is quite subjective. 

The approach with tracks in Iris has been to use UX that the vast majority of users will be familiar with: Windows Explorer and Mac Finder. In both of these, the selected items remain selected until you click or navigate elsewhere.

That being said, it does raise an issue when you navigate away from a playlist/queue/etc and then return, if the tracklist hasn't changed (eg loaded from cache) then the selected states remain. This doesn't align with the overall intended UX, so I'm addressing this as we speak.
